README.md, src/activities/Elsa.Activities.Primitives/Activities/Join.cs, src/activities/Elsa.Activities.Primitives/ActivityDescriptors.cs, src/activities/Elsa.Activities.Primitives/Drivers/ForkDriver.cs, src/activities/Elsa.Activities.Primitives/Drivers/JoinDriver.cs, src/activities/Elsa.Activities.Primitives/Extensions/ServiceCollectionExtensions.cs, src/core/Elsa.Abstractions/Extensions/ServiceCollectionExtensions.cs, src/core/Elsa.Abstractions/Extensions/WorkflowExtensions.cs, src/core/Elsa.Abstractions/IWorkflowEventHandler.cs, src/core/Elsa.Abstractions/Models/WorkflowExecutionContext.cs, src/core/Elsa.Abstractions/WorkflowEventHandlerBase.cs, src/core/Elsa.Core/Handlers/ActivityDriver.cs, src/core/Elsa.Core/Results/HaltResult.cs, src/core/Elsa.Core/Results/TriggerEndpointsResult.cs, src/core/Elsa.Core/WorkflowInvoker.cs, src/web/modules/Elsa.Web.Activities.Primitives/Drivers/JoinDisplay.cs, src/web/modules/Elsa.Web.Activities.Primitives/Elsa.Web.Activities.Primitives.csproj, src/web/modules/Elsa.Web.Activities.Primitives/Startup.cs, src/web/modules/Elsa.Web.Activities.Primitives/ViewModels/JoinViewModel.cs, src/web/modules/Elsa.Web.Activities.Primitives/Views/Join.Card.cshtml, src/web/modules/Elsa.Web.Activities.Primitives/Views/Join.Design.cshtml, src/web/modules/Elsa.Web.Activities.Primitives/Views/Join.Edit.cshtml, src/web/modules/Elsa.Web.Activities.Primitives/Views/_ViewImports.cshtml
=> Added Join activity

Elsa.sln, src/activities/Elsa.Activities.Cron/Activities/CronTrigger.cs, src/activities/Elsa.Activities.Cron/ActivityDescriptors.cs, src/activities/Elsa.Activities.Cron/Drivers/CronTriggerDriver.cs, src/activities/Elsa.Activities.Cron/Elsa.Activities.Cron.csproj, src/activities/Elsa.Activities.Cron/Extensions/ServiceCollectionExtensions.cs, src/activities/Elsa.Activities.Cron/HostedServices/CronHostedService.cs, src/activities/Elsa.Activities.Cron/Options/CronOptions.cs, src/activities/Elsa.Activities.Email/Drivers/SendEmailDriver.cs, src/core/Elsa.Core/Serialization/Tokenizers/WorkflowTokenizer.cs, src/core/Elsa.Runtime.Hosting/Elsa.Runtime.Hosting.csproj, src/core/Elsa.Runtime.Hosting/Extensions/ProgramExtensions.cs, src/core/Elsa.Runtime.Hosting/TypeConverters/PeriodTypeConverter.cs, src/core/Elsa.Runtime/Extensions/ServiceCollectionExtensions.cs, src/core/Elsa.Runtime/WorkflowHost.cs, src/samples/SampleDashboard.Web/SampleDashboard.Web.csproj, src/samples/SampleHost.Web/Program.cs, src/samples/SampleHost.Web/SampleHost.Web.csproj, src/samples/SampleHost.Web/Startup.cs, src/samples/SampleHost.Web/appsettings.json, src/web/modules/Elsa.Web.Activities.Cron/Display/CronTriggerDisplay.cs, src/web/modules/Elsa.Web.Activities.Cron/Elsa.Web.Activities.Cron.csproj, src/web/modules/Elsa.Web.Activities.Cron/Manifest.cs, src/web/modules/Elsa.Web.Activities.Cron/Startup.cs, src/web/modules/Elsa.Web.Activities.Cron/ViewModels/CronTriggerViewModel.cs, src/web/modules/Elsa.Web.Activities.Cron/Views/CronTrigger.Card.cshtml, src/web/modules/Elsa.Web.Activities.Cron/Views/CronTrigger.Design.cshtml, src/web/modules/Elsa.Web.Activities.Cron/Views/CronTrigger.Edit.cshtml, src/web/modules/Elsa.Web.Activities.Cron/Views/_ViewImports.cshtml
=> Implemented Cron activity

src/core/Elsa.Abstractions/Models/WorkflowDefinition.cs, src/core/Elsa.Abstractions/Services/IWorkflowBuilder.cs, src/core/Elsa.Abstractions/Services/IWorkflowHost.cs, src/core/Elsa.Core/Services/WorkflowBuilders/WorkflowBuilder.cs, src/core/Elsa.Core/Services/WorkflowHost.cs, src/samples/Sample05/RecurringWorkflow.cs
=> Implemented singleton workflows

samples/Sample10/Program.cs, samples/Sample12/Program.cs, src/activities/Elsa.Activities.Http/RequestHandlers/Handlers/SignalRequestHandler.cs, src/core/Elsa.Abstractions/Models/VersionOptions.cs, src/core/Elsa.Abstractions/Models/WorkflowDefinition.cs, src/core/Elsa.Abstractions/Models/WorkflowInstance.cs, src/core/Elsa.Abstractions/Persistence/IWorkflowDefinitionStore.cs, src/core/Elsa.Abstractions/Services/IWorkflowRegistry.cs, src/core/Elsa.Abstractions/Services/Models/Workflow.cs, src/core/Elsa.Core/Persistence/Memory/MemoryWorkflowDefinitionStore.cs, src/core/Elsa.Core/Services/WorkflowBuilders/WorkflowBuilder.cs, src/core/Elsa.Core/Services/WorkflowFactory.cs, src/core/Elsa.Core/Services/WorkflowInvoker.cs, src/core/Elsa.Core/Services/WorkflowRegistry.cs, src/persistence/Elsa.Persistence.YesSql/Documents/WorkflowDefinitionDocument.cs, src/persistence/Elsa.Persistence.YesSql/Documents/WorkflowInstanceDocument.cs, src/persistence/Elsa.Persistence.YesSql/Indexes/WorkflowDefinitionIndex.cs, src/persistence/Elsa.Persistence.YesSql/Indexes/WorkflowInstanceIndex.cs, src/persistence/Elsa.Persistence.YesSql/Services/YesSqlWorkflowDefinitionStore.cs, src/persistence/Elsa.Persistence.YesSql/StartupTasks/StoreInitializationTask.cs
=> Implemented versioning

Samples.sln, samples/Sample13/ActivityOutputWorkflow.cs, samples/Sample13/Program.cs, samples/Sample13/Sample13.csproj, samples/Sample13/ScriptEngineConfigurator.cs, src/activities/Elsa.Activities.Console/Activities/ReadLine.cs, src/activities/Elsa.Activities.Console/Elsa.Activities.Console.csproj, src/core/Elsa.Abstractions/Services/ActivityBase.cs, src/core/Elsa.Abstractions/Services/Models/IActivity.cs, src/core/Elsa.Core/Elsa.Core.csproj, src/core/Elsa.Core/Scripting/CommonScriptEngineConfigurator.cs
=> Implemented activity outputs

Elsa.sln, src/persistence/Elsa.Persistence.DocumentDb/DocumentDbStorage.cs, src/persistence/Elsa.Persistence.DocumentDb/DocumentDbStorageOptions.cs, src/persistence/Elsa.Persistence.DocumentDb/Documents/WorkflowDefinitionVersionDocument.cs, src/persistence/Elsa.Persistence.DocumentDb/Documents/WorkflowInstanceDocument.cs, src/persistence/Elsa.Persistence.DocumentDb/Elsa.Persistence.DocumentDb.csproj, src/persistence/Elsa.Persistence.DocumentDb/Extensions/ServiceCollectionExtensions.cs, src/persistence/Elsa.Persistence.DocumentDb/Extensions/WorkflowDefinitionDocumentExtensions.cs, src/persistence/Elsa.Persistence.DocumentDb/Helpers/ClientHelper.cs, src/persistence/Elsa.Persistence.DocumentDb/Helpers/QueryHelper.cs, src/persistence/Elsa.Persistence.DocumentDb/Helpers/TimeHelper.cs, src/persistence/Elsa.Persistence.DocumentDb/Mapping/DocumentProfile.cs, src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowDefinitionStore.cs, src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowInstanceStore.cs
Document Db Persistence layer implementation
=> Added in DocumentDb Persistence layer

src/activities/Elsa.Activities.Email/Extensions/ServiceCollectionExtensions.cs, src/activities/Elsa.Activities.Email/Options/SmtpCredentials.cs, src/activities/Elsa.Activities.Email/Options/SmtpOptions.cs, src/core/Elsa.Abstractions/Services/IActivityBuilder.cs, src/core/Elsa.Core/WorkflowBuilders/ActivityBuilder.cs, src/dashboard/Elsa.Dashboard/Extensions/DashboardServiceCollectionExtensions.cs, src/persistence/Elsa.Persistence.MongoDb/Extensions/ServiceCollectionExtensions.cs, src/persistence/Elsa.Persistence.MongoDb/Services/MongoWorkflowDefinitionStore.cs, src/samples/Sample01/Program.cs, src/samples/Sample02/Program.cs, src/samples/Sample03/Program.cs, src/samples/Sample04/Program.cs, src/samples/Sample05/Program.cs, src/samples/Sample06/Startup.cs, src/samples/Sample07/Startup.cs, src/samples/Sample08/Startup.cs, src/samples/Sample09/Program.cs, src/samples/Sample10/Program.cs, src/samples/Sample11/Program.cs, src/samples/Sample12/Program.cs, src/samples/Sample13/Program.cs
=> Extend SMTP options

src/core/Elsa.Abstractions/Services/ActivityBase.cs, src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/_Layout.cshtml, src/dashboard/Elsa.WorkflowDesigner/ActivityDescriber.cs
=> Add support for custom title and description

src/core/Elsa.Core/Extensions/WorkflowDefinitionExtensions.cs, src/persistence/Elsa.Persistence.DocumentDb/Extensions/WorkflowDefinitionDocumentExtensions.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Extensions/WorkflowDefinitionExtensions.cs, src/persistence/Elsa.Persistence.YesSql/Elsa.Persistence.YesSql.csproj, src/persistence/Elsa.Persistence.YesSql/Extensions/WorkflowDefinitionExtensions.cs
=> Fix version query issue

src/persistence/Elsa.Persistence.YesSql/StartupTasks/InitializeStoreTask.cs
=> Add CreatedAt column

src/activities/Elsa.Activities.Reflection/Activities/ExecuteFunction.cs, src/activities/Elsa.Activities.Reflection/Activities/SplitObject.cs, src/activities/Elsa.Activities.Reflection/Elsa.Activities.Reflection.csproj, src/activities/Elsa.Activities.Reflection/Extensions/ServiceCollectionExtensions.cs
=> Elsa.Activities.Reflection

src/activities/Elsa.Activities.MassTransit/Activities/ReceiveMassTransitMessage.cs, src/activities/Elsa.Activities.MassTransit/Constants.cs, src/activities/Elsa.Activities.MassTransit/Consumers/WorkflowConsumer.cs, src/activities/Elsa.Activities.MassTransit/Extensions/ServiceCollectionExtensions.cs, src/activities/Elsa.Activities.MassTransit/Options/RabbitMqOptions.cs, src/samples/Sample08/Sample08.http, src/samples/Sample08/Workflows/CreateOrderWorkflow.cs, src/samples/Sample08/appsettings.json
This fixes issue #134 and a few others.
I have a TODO comment in there where I think behaviour has changed. Can you look at the ReceiveMassTransitMessage class. Im not too sure if OnCanExecute can be validated in the current state. Maybe the message type needs to be inserted at another input key?
=> MassTransit Fixes

src/samples/Sample08/Workflows/CreateOrderWorkflow.cs, src/samples/Sample08/Workflows/HandleOrderWorkflow.cs
Something I missed on the last pull request
=> Fix response message workflow instance correlation

src/core/Elsa.Abstractions/Models/Variables.cs, src/core/Elsa.Abstractions/Models/WorkflowExecutionScope.cs
Fixes a bug found by the registration sample
=> Feature variables v2.01 with bugfix 

src/scripting/Elsa.Scripting.JavaScript/Services/JavaScriptExpressionEvaluator.cs
Expression was returning the JValue of the property and was unable to convert to a string.
This was occurring in Sample08 in the `SendEmail` activity. The expression `order.customer.email` was returning a `JValue` from the `JavaScriptExpressionEvaluator`, which then throws in the `WorkflowExpressionEvaluatorExtensions.EvaluateAsync` method trying to cast the `JValue` to a `string`.
=> Fix issue with property expressions throwing invalid cast exceptions

src/activities/Elsa.Activities.Email/Activities/SendEmail.cs, src/activities/Elsa.Activities.Email/Elsa.Activities.Email.csproj, src/activities/Elsa.Activities.Email/Extensions/ServiceCollectionExtensions.cs, src/activities/Elsa.Activities.Email/Options/SmtpCredentials.cs, src/activities/Elsa.Activities.Email/Options/SmtpDeliveryMethod.cs, src/activities/Elsa.Activities.Email/Options/SmtpEncryptionMethod.cs, src/activities/Elsa.Activities.Email/Options/SmtpOptions.cs, src/activities/Elsa.Activities.Email/Services/ISmtpService.cs, src/activities/Elsa.Activities.Email/Services/SmtpService.cs, src/samples/Sample18/Program.cs, src/scripting/Elsa.Scripting.Liquid/Handlers/CommonLiquidContextHandler.cs
=> Replace SmtpClient from System.Net.Mail with MailKit's

src/activities/Elsa.Activities.ControlFlow/Activities/ActivityBuilderExtensions.cs, src/samples/Sample21/Workflows/CartTrackingWorkflow.cs
Just makes the code a little more readable 🙂
=> Control flow extension methods

src/activities/Elsa.Activities.Startup/Activities/Startup.cs, src/activities/Elsa.Activities.Startup/Elsa.Activities.Startup.csproj, src/activities/Elsa.Activities.Startup/Extensions/ServiceCollectionExtensions.cs, src/activities/Elsa.Activities.Startup/HostedServices/StartupHostedService.cs
Hey dude...
Had some troubles with me fork... Had to delete a lot.
Here's the Startup Activity #203 
Greetings
=> Feature: Startup Activities

src/activities/Elsa.Activities.Timers/HostedServices/TimersHostedService.cs, src/activities/Elsa.Activities.Timers/Options/TimersOptions.cs, src/dashboard/Elsa.Dashboard.Web/Startup.cs, src/dashboard/Elsa.Dashboard.Web/appsettings.json, src/samples/Sample05/Program.cs, src/samples/Sample08/Startup.cs, src/samples/Sample18/Program.cs, src/samples/Sample21/Startup.cs
Duration is semantically more correct in the context of were it's used.
=> Use Duration instead of Period

src/core/Elsa.Core/Elsa.Core.csproj, src/core/Elsa.Core/Serialization/Formatters/YamlTokenFormatter.cs
=> Fixed yaml serialisation and updated to YamlDotNet

src/core/Elsa.Abstractions/Services/Extensions/WorkflowExtensions.cs
When the following workflow is executed, the Join activity throws a stack overflow when trying to build a list its ancestor activity ids. 
``` csharp
builder.StartWith<Start>()
.Then<WriteLine>(x => x.TextExpression = new LiteralExpression("Start"), name: "Start")
.Then<Fork>(x => { x.Branches = new[] {"Branch1", "Branch2"}; },
fork =>
{
// First one loops back to start above
fork.When("Branch1")
.Then<Signaled>(x => x.Signal = new LiteralExpression("Test"))
.Then("Start");
// Second straight to join below
fork.When("Branch2")
.Then("Join");
})
// When executed and finding all activity ancestor paths, causes stack overflow
.Then<Join>(x => x.Mode = Join.JoinMode.WaitAny)
.WithName("Join");
```
There was a check in `WorkflowExtensions.GetInboundActivityPathInternal` for infinite loops, but …
=> Fixed stackoverflow when finding Join activity ancestors

src/core/Elsa.Abstractions/Models/BlockingActivity.cs, src/core/Elsa.Abstractions/Persistence/IWorkflowInstanceStore.cs, src/core/Elsa.Core/Persistence/Memory/MemoryWorkflowInstanceStore.cs, src/providers/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowInstanceStore.cs, src/providers/Elsa.Persistence.EntityFrameworkCore/Entities/BlockingActivityEntity.cs, src/providers/Elsa.Persistence.EntityFrameworkCore/Services/EntityFrameworkCoreWorkflowInstanceStore.cs, src/providers/Elsa.Persistence.MongoDb/Services/MongoWorkflowInstanceStore.cs, src/providers/Elsa.Persistence.YesSql/Indexes/WorkflowInstanceIndex.cs, src/providers/Elsa.Persistence.YesSql/Services/YesSqlWorkflowInstanceStore.cs, src/providers/Elsa.Persistence.YesSql/StartupTasks/InitializeStoreTask.cs
Pull request related to Query UserTask issue which contains files, definitions and implementations required to query user tasks by specified "Tag".
=> Query UserTask issue

src/utils/Elsa.AutoMapper.Extensions/ServiceCollectionExtensions.cs
=> Fix duplicate Automapper profile registration when using AddElsa Fand AddElsaDasboard

src/core/Elsa.Abstractions/Models/WorkflowInstance.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Entities/ActivityDefinitionEntity.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Mapping/EntitiesProfile.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/MySql/20200402200706_Update01.Designer.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/MySql/20200402200706_Update01.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/PostgreSql/20200402200555_Update01.Designer.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/PostgreSql/20200402200555_Update01.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/PostgreSql/PostgreSqlContextModelSnapshot.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/SqlServer/20200402200549_Update01.Designer.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/SqlServer/20200402200549_Update01.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/SqlServer/SqlServerContextModelSnapshot.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/Sqlite/20200402200519_Update01.Designer.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/Sqlite/20200402200519_Update01.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/Sqlite/SqliteContextModelSnapshot.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/README.md
=> Fix missing mapping issues

src/activities/Elsa.Activities.Http/RequestHandlers/Handlers/TriggerRequestHandler.cs
The `TriggerRequestHandler.HandleRequestAsync` checks for the existence of the `X-Correlation-Id` header. If present, it will filter the workflows to resume by the correlation id(s) provided in the header(s). If the header is not present, no additional filtering will occur; i.e. all matching workflow instances will be included whether they have a correlation ID. This addresses issue #262.
=> TriggerRequestHandler workflows to resume filtered by X-Correlation-ID header(s)

src/activities/Elsa.Activities.Http/Activities/SendHttpRequest.cs
Looks like SendHTTPRequest hasn't been used with POST yet. Fixing ContentType so it will convert correctly.
=> Updating ContentType in SendHTTPRequest to match WriteHTTPRequest (#322)

src/activities/Elsa.Activities.Http/Activities/SendHttpRequest.cs, src/activities/Elsa.Activities.Http/Activities/WriteHttpResponse.cs
=> Fix inaccurate parsing of HTTP headers

src/activities/Elsa.Activities.ControlFlow/Activities/ForEach.cs, src/activities/Elsa.Activities.ControlFlow/Activities/While.cs, src/core/Elsa.Abstractions/Models/WorkflowInstance.cs, src/core/Elsa.Abstractions/Services/Models/Workflow.cs, src/core/Elsa.Abstractions/Services/Models/WorkflowExecutionContext.cs, src/persistence/Elsa.Persistence.MongoDb/Extensions/ServiceCollectionExtensions.cs
Too many issues, zero benefits.
=> Remove multiple execution scopes

src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/MySql/20201027194413_Update02.Designer.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/MySql/20201027194413_Update02.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/MySql/MySqlContextModelSnapshot.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/PostgreSql/20201027192219_Update02.Designer.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/PostgreSql/20201027192219_Update02.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/SqlServer/20201027192116_Update02.Designer.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/SqlServer/20201027192116_Update02.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/SqlServer/SqlServerContextModelSnapshot.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/Sqlite/20201027192013_Update02.Designer.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/Sqlite/20201027192013_Update02.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/Migrations/Sqlite/SqliteContextModelSnapshot.cs, src/samples/Sample23/Migrations/Sqlite/20201027194619_Create.Designer.cs, src/samples/Sample23/Migrations/Sqlite/20201027194619_Create.cs, src/samples/Sample23/Migrations/Sqlite/ElsaContextModelSnapshot.cs
=> Update EF migrations

src/core/Elsa.Core/WorkflowBuilders/ActivityBuilder.cs
=> Propagate activity definition properties

src/core/Elsa.Core/Elsa.Core.csproj, src/core/Elsa.Core/Results/GoBackResult.cs
=> Add GoBackResult

src/activities/Elsa.Activities.ControlFlow/Activities/While.cs
=> Expose outcomes to While activity designer

src/scripting/Elsa.Scripting.JavaScript/Handlers/CommonJavaScriptEngineHandler.cs, src/scripting/Elsa.Scripting.Liquid/Handlers/CommonLiquidContextHandler.cs
branch for elsa 1.4.x updates.
Resolve #484
=> Make available TransientState to JS and Liquid script contexts

src/core/Elsa.Abstractions/Elsa.Abstractions.csproj, src/core/Elsa.Core/Elsa.Core.csproj, src/core/Elsa.Core/ElsaOptions.cs, src/core/Elsa.Core/Extensions/AutoMapperServiceCollectionExtensions.cs
=> Using AutoMapper.Extensions.Microsoft.DependencyInjection, instead of own implementation

src/core/Elsa.Abstractions/Extensions/JObjectExtensions.cs, src/core/Elsa.Abstractions/Services/Activity.cs, src/core/Elsa.Core/Activities/ControlFlow/Join/Join.cs, src/core/Elsa.Core/ElsaOptions.cs, src/core/Elsa.Core/Persistence/InMemory/InMemoryStore.cs, src/core/Elsa.Core/Persistence/InMemory/InMemoryWorkflowDefinitionStore.cs, src/core/Elsa.Core/Persistence/InMemory/InMemoryWorkflowExecutionLogStore.cs, src/core/Elsa.Core/Persistence/InMemory/InMemoryWorkflowInstanceStore.cs, src/samples/aspnet/Elsa.Samples.ForkJoinTimerAndSignalHttp/Workflows/DemoWorkflow.cs
=> Fix memory stores + Join activity

src/activities/Elsa.Activities.ControlFlow/Activities/Join.cs, src/core/Elsa.Abstractions/Services/IWorkflowEventHandler.cs, src/core/Elsa.Abstractions/Services/WorkflowEventHandlerBase.cs, src/core/Elsa.Core/Services/WorkflowInvoker.cs
I've put to IWorkflowEventHandler a new event.
=> executing activity event.

src/clients/Elsa.Client/Models/BulkDeleteWorkflowInstancesRequest.cs, src/clients/Elsa.Client/Models/BulkRetryWorkflowInstancesRequest.cs, src/clients/Elsa.Client/Services/IWorkflowInstancesApi.cs, src/core/Elsa.Core/Consumers/RunWorkflowDefinitionConsumer.cs, src/core/Elsa.Core/Persistence/Specifications/WorkflowInstances/WorkflowInstanceIdsSpecification.cs, src/dashboards/blazor/ElsaDashboard.Application/Icons/BulkActionIcon.razor, src/dashboards/blazor/ElsaDashboard.Application/Pages/WorkflowInstances/List.razor, src/dashboards/blazor/ElsaDashboard.Application/Pages/WorkflowInstances/List.razor.cs, src/dashboards/blazor/ElsaDashboard.Application/Shared/ButtonDropdown.razor, src/dashboards/blazor/ElsaDashboard.Application/Shared/ButtonDropdown.razor.cs, src/dashboards/blazor/ElsaDashboard.Backend/Rpc/WorkflowInstanceService.cs, src/dashboards/blazor/ElsaDashboard.Shared/Rpc/WorkflowInstance/Extensions/WorkflowInstanceServiceExtensions.cs, src/dashboards/blazor/ElsaDashboard.Shared/Rpc/WorkflowInstance/Models/DeleteWorkflowRequest.cs, src/dashboards/blazor/ElsaDashboard.Shared/Rpc/WorkflowInstance/Models/RetryWorkflowRequest.cs, src/dashboards/blazor/ElsaDashboard.Shared/Rpc/WorkflowInstance/Services/IWorkflowInstanceService.cs, src/samples/dashboard/ElsaDashboard.Samples.Monolith/ElsaDashboard.Samples.Monolith.csproj, src/samples/dashboard/ElsaDashboard.Samples.Monolith/Startup.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/BulkDelete.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/BulkRetry.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/Models.cs
This PR adds a Bulk Actions button to the Workflow Instances list view in the Blazor dashboard. Actions include:
- Delete
- Retry
=> Workflow Instance Bulk Actions on Blazor Dashboard

src/clients/Elsa.Client/Extensions/ServiceCollectionExtensions.cs, src/dashboards/blazor/ElsaDashboard.Abstractions/ElsaDashboard.Abstractions.csproj, src/dashboards/blazor/ElsaDashboard.Abstractions/Events/DisplayingWorkflowInstanceListView.cs, src/dashboards/blazor/ElsaDashboard.Abstractions/Events/DisplayingWorkflowInstanceRecord.cs, src/dashboards/blazor/ElsaDashboard.Application/Pages/WorkflowInstances/List.razor, src/dashboards/blazor/ElsaDashboard.Application/Pages/WorkflowInstances/List.razor.cs, src/dashboards/blazor/ElsaDashboard.Application/Shared/ButtonDropdown.razor, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkStore.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkWorkflowInstanceStore.cs
This PR enables the host application to extend the following:
* Workflow Instance context menu
* Workflow Instance list view bulk actions
=> Add Blazor Dashboard Workflow Instance List View extensibility

Elsa.sln, src/samples/console/Elsa.Samples.UserTaskConsole/Elsa.Samples.UserTaskConsole.csproj, src/samples/console/Elsa.Samples.UserTaskConsole/Program.cs, src/samples/console/Elsa.Samples.UserTaskConsole/UserTaskWorkflow.cs
=> troubleshoot usertask demo

Elsa.sln, src/core/Elsa.Core/Activities/ControlFlow/Break/Break.cs, src/core/Elsa.Core/Activities/ControlFlow/Break/BreakBuilderExtensions.cs, src/core/Elsa.Core/Activities/ControlFlow/For/For.cs, src/core/Elsa.Core/Activities/ControlFlow/ForEach/ForEach.cs, src/core/Elsa.Core/Activities/ControlFlow/While/While.cs, src/core/Elsa.Core/ElsaOptions.cs, src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs, src/samples/worker/Elsa.Samples.BreakLoop/Elsa.Samples.BreakLoop.csproj, src/samples/worker/Elsa.Samples.BreakLoop/Program.cs, src/samples/worker/Elsa.Samples.BreakLoop/Properties/launchSettings.json, src/samples/worker/Elsa.Samples.BreakLoop/Workflows/BreakoutWorkflow.cs, src/samples/worker/Elsa.Samples.BreakLoop/appsettings.json
The **Break** activity allows for breaking out of a looping construct such as `For`, `ForEach` and `While`, and is semantically the same as the C# `break` statement.
=> Add Break activity

src/core/Elsa.Abstractions/Services/Models/Workflow.cs, src/persistence/Elsa.Persistence.EntityFrameworkCore/CustomSchema/CustomSchemaOptionsExtensionInfo.cs
376
Self-referential loop in CustomSchemaOptionsExtensionInfo
https://github.com/elsa-workflows/elsa-core/issues/376
331
"Input" is the property of workflowinstance,but it is empty in database
https://github.com/elsa-workflows/elsa-core/issues/331
=> 2 bug fixes: (376 + 331)

src/clients/Elsa.Client/Models/ActivityScope.cs, src/clients/Elsa.Client/Models/SimpleStack.cs, src/clients/Elsa.Client/Models/WorkflowInstance.cs, src/core/Elsa.Abstractions/Models/ActivityScope.cs, src/core/Elsa.Abstractions/Models/WorkflowInstance.cs, src/core/Elsa.Abstractions/Services/CompositeActivity.cs, src/core/Elsa.Abstractions/Services/Models/ActivityExecutionContext.cs, src/core/Elsa.Abstractions/Services/Models/WorkflowExecutionContext.cs, src/core/Elsa.Core/Activities/ControlFlow/Break/Break.cs, src/core/Elsa.Core/Activities/ControlFlow/Finish/Finish.cs, src/core/Elsa.Core/Activities/ControlFlow/For/For.cs, src/core/Elsa.Core/Activities/ControlFlow/For/ForScope.cs, src/core/Elsa.Core/Activities/ControlFlow/ForEach/ForEach.cs, src/core/Elsa.Core/Activities/ControlFlow/ForEach/ForEachScope.cs, src/core/Elsa.Core/Activities/ControlFlow/IfElse/IfElse.cs, src/core/Elsa.Core/Activities/ControlFlow/Join/Join.cs, src/core/Elsa.Core/Activities/ControlFlow/Switch/Switch.cs, src/core/Elsa.Core/Activities/ControlFlow/While/While.cs, src/core/Elsa.Core/Handlers/RescheduleBranchingActivitiesAndContainers.cs, src/samples/console/Elsa.Samples.ForEachLoopConsole/ForEachLoopWorkflow.cs, src/samples/console/Elsa.Samples.ProgrammaticCompositeActivitiesConsole/Activities/CountdownActivity.cs
=> Add support for scoped variables

src/clients/Elsa.Client/Extensions/ServiceCollectionExtensions.cs, src/clients/Elsa.Client/Models/ActivityDefinitionPropertyValue.cs, src/core/Elsa.Core/Activities/ControlFlow/Break/Break.cs, src/core/Elsa.Core/Activities/ControlFlow/If/If.cs, src/core/Elsa.Core/Activities/ControlFlow/Switch/SwitchBuilderExtensions.cs, src/core/Elsa.Core/Activities/ControlFlow/Switch/SwitchCaseBuilder.cs, src/core/Elsa.Core/Consumers/RunWorkflowInstanceConsumer.cs, src/core/Elsa.Core/Expressions/ExpressionEvaluator.cs, src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs, src/core/Elsa.Core/Serialization/DefaultContentSerializer.cs, src/dashboards/blazor/ElsaDashboard.Shared/Surrogates/WorkflowBlueprintSurrogate.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/ElsaContextModelSnapshot.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Sqlite/Migrations/ElsaContextModelSnapshot.cs, src/persistence/Elsa.Persistence.YesSql/Stores/YesSqlWorkflowDefinitionStore.cs, src/samples/console/Elsa.Samples.DeclarativeCompositeActivitiesConsole/Program.cs, src/samples/console/Elsa.Samples.ForEachLoopConsole/ForEachLoopWorkflow.cs, src/samples/console/Elsa.Samples.Serialization/Program.cs, src/samples/console/Elsa.Samples.SwitchConsole/GrayscaleWorkflow.cs, src/samples/console/Elsa.Samples.UserTaskConsole/Program.cs, src/samples/persistence/Elsa.Samples.Persistence.EntityFramework/Program.cs, src/server/Elsa.Server.Api/Endpoints/Activities/List.cs, src/server/Elsa.Server.Api/Swagger/Examples/WorkflowDefinitionExample.cs, test/component/Elsa.ComponentTests/Helpers/JsonContent.cs
This PR simplifies constructing Switch activities by allowing each case to be configured with the activities to be executed inline, instead of having to do so separately.
=> Refactor Switch builder API

README.md, appveyor.yml
This PR simplifies, de-duplicates and removes redundant parts of the YML file.  The aim is to make it easier to maintain moving forward.
There's also a small change on the README to fix the URL to the AppVeyor project.
=> Resolves #664 - simplify AppVeyor YML

src/designer/elsa-workflows-studio/src/utils/utils.ts
I use this function a lot in my projects when not using [MomentJS](https://momentjs.com/). I think it could come in handy in the upcoming tasks to display when an activity or workflow was executed.
Edit: I found it a long time ago on the internet but lost the reference so I'm not able to give someone kudos 😞
=> Time since option

src/core/Elsa.Abstractions/Services/Models/Workflow.cs
Update Workflow.cs
merge input and instance variables  instead of overwriting
=> merge workflow input and instance variables  instead of overwriting

.github/stale.yml
I've renamed these three priority labels, and the config needs updating in-line with those changes.
=> Update Stale-bot config (label changes)

src/designer/elsa-workflows-studio/package-lock.json, src/designer/elsa-workflows-studio/package.json, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx, src/designer/elsa-workflows-studio/src/utils/jsplumb-helper.ts, src/designer/elsa-workflows-studio/tailwind.css, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Save.cs
This PR adds the following improvements to the designer:
* Delete connections on click
* Change connections by drag & drop activity onto another outcome
* Manually created connections are now persisted
=> Designer connection management

src/designer/elsa-workflows-studio/src/components/editors/workflow-editor/elsa-activity-editor-modal/elsa-activity-editor-modal.tsx, src/designer/elsa-workflows-studio/src/components/editors/workflow-editor/elsa-workflow-editor/elsa-workflow-editor.tsx, src/designer/elsa-workflows-studio/src/components/editors/workflow-editor/elsa-workflow-settings-modal/elsa-workflow-settings-modal.tsx, src/designer/elsa-workflows-studio/src/models/view.ts, src/designer/elsa-workflows-studio/src/plugins/send-email-plugin.tsx, src/designer/elsa-workflows-studio/src/utils/forms.tsx
This PR updates the activity editor with the following tabs:
- Properties (activity-specific properties)
- Common (common properties for all activities, such as Name, Display Name and Description)
- Behavior (control things like persisting workflow instance and workflow context)
=> Activity editor tabs

src/activities/Elsa.Activities.Http/Extensions/StreamExtensions.cs, src/designer/elsa-workflows-studio/src/components.d.ts, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx, src/designer/elsa-workflows-studio/src/components/editors/workflow-editor/elsa-workflow-editor-notifications/elsa-workflow-editor-notifications.tsx, src/designer/elsa-workflows-studio/src/components/editors/workflow-editor/elsa-workflow-editor/elsa-workflow-editor.tsx, src/designer/elsa-workflows-studio/src/components/editors/workflow-editor/elsa-workflow-publish-button/elsa-workflow-publish-button.tsx, src/designer/elsa-workflows-studio/src/models/events.ts, src/designer/elsa-workflows-studio/src/services/elsa-client.ts, src/designer/elsa-workflows-studio/src/utils/download.ts, src/designer/elsa-workflows-studio/src/utils/jsplumb-helper.ts, src/samples/dashboard/ElsaDashboard.Samples.Monolith/Startup.cs, src/samples/dashboard/ElsaDashboard.Samples.Server/ElsaDashboard.Samples.Server.csproj, src/samples/server/Elsa.Samples.Server.Host/Startup.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Export.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Import.cs
This PR adds an implementation for importing & exporting workflow JSON files.
=> Designer Import/Export

src/activities/Elsa.Activities.Telnyx/Activities/GatherUsingAudio.cs, src/clients/Elsa.Client/Models/ActivityPropertyDescriptor.cs, src/core/Elsa.Abstractions/Attributes/ActivityPropertyAttribute.cs, src/core/Elsa.Abstractions/Metadata/ActivityPropertyDescriptor.cs, src/core/Elsa.Core/Metadata/TypedActivityTypeDescriber.cs, src/dashboards/blazor/ElsaDashboard.Shared/Surrogates/ActivityPropertyDescriptorSurrogate.cs, src/designer/elsa-workflows-studio/src/components/editors/properties/elsa-text-property/elsa-text-property.tsx, src/designer/elsa-workflows-studio/src/models/domain.ts, src/samples/dashboard/ElsaDashboard.Samples.Monolith/Pages/_Host.cshtml, src/samples/dashboard/ElsaDashboard.Samples.Server/Pages/_Host.cshtml
This PR adds support for providing default activity property values that are used when initializing the activity editor UI.
=> Add support for setting default activity property values

src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree-activity/elsa-designer-tree-activity.tsx
Double click to open activity.
My first pull request here, I believe this resolves https://github.com/elsa-workflows/elsa-core/issues/670.
=> Double click to edit activity in designer

src/activities/Elsa.Activities.Http/Activities/HttpEndpoint/HttpEndpoint.cs, src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequest.cs
This should fix https://github.com/elsa-workflows/elsa-core/issues/824.
=> Fix for "complex" content type in HTTP Endpoint and HTTP Send request

src/activities/Elsa.Activities.MassTransit/Activities/ReceiveMassTransitMessage/ReceiveMassTransitMessage.cs, src/activities/Elsa.Activities.MassTransit/Bookmarks/MessageReceivedBookmark.cs, src/activities/Elsa.Activities.MassTransit/Consumers/WorkflowConsumer.cs, src/activities/Elsa.Activities.MassTransit/Extensions/ServiceCollectionExtensions.cs, src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Controllers/TriggerMessageController.cs, src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Elsa.Samples.MassTransitRabbitMq.csproj, src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Messages/FirstMessage.cs, src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Messages/SecondMessage.cs, src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Program.cs, src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Startup.cs, src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Workflows/TestWorkflow.cs
Implemented functionality to trigger workflows through mass transit. If you have any feedback let me know. 
To test the functionality I added a small example.
=> Implemented functionality to trigger workflows through mass transit

src/activities/Elsa.Activities.ControlFlow/Activities/ForEach.cs, src/activities/Elsa.Activities.ControlFlow/Activities/IfElse.cs, src/activities/Elsa.Activities.ControlFlow/Activities/While.cs, src/activities/Elsa.Activities.Timers/Activities/CronEvent.cs, src/activities/Elsa.Activities.Timers/Activities/TimerEvent.cs, src/activities/Elsa.Activities.Workflows/Activities/Finish.cs, src/activities/Elsa.Activities.Workflows/Activities/TriggerWorkflow.cs
[https://github.com/elsa-workflows/elsa-core/issues/868](url)
=> Issue #868 - Switched LiteralExpression & JavaScriptExpression to base type WorkflowExpression in activities

src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/DbContextOptionsBuilderExtensions.cs, src/samples/persistence/Elsa.Samples.Persistence.EntityFramework/Program.cs
Fixes problem described in #913.
Adding DbContextOptionsBuilderExtensions and a using statement in main sample program.
=> Fixing SQL Server persistence

src/activities/Elsa.Activities.Http/Activities/HttpEndpoint/HttpEndpointBuilderExtensions.cs, src/activities/Elsa.Activities.Http/Middleware/HttpRequestMiddleware.cs, src/core/Elsa.Abstractions/Builders/IWorkflowBuilder.cs, src/core/Elsa.Core/Builders/CompositeActivityBuilder.cs, src/core/Elsa.Core/Builders/WorkflowBuilder.cs, src/core/Elsa.Core/Persistence/Specifications/WorkflowExecutionLogRecords/ActivityIdSpecification.cs, src/designer/elsa-workflows-studio/src/components.d.ts, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/models.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-blueprint-viewer/elsa-workflow-blueprint-viewer-screen/elsa-workflow-blueprint-viewer-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-journal/elsa-workflow-instance-journal.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-viewer-screen/elsa-workflow-instance-viewer-screen.tsx, src/designer/elsa-workflows-studio/src/models/domain.ts, src/designer/elsa-workflows-studio/src/services/elsa-client.ts, src/designer/elsa-workflows-studio/src/utils/utils.ts, src/persistence/Elsa.Persistence.YesSql/Indexes/WorkflowExecutionLogRecordIndex.cs, src/persistence/Elsa.Persistence.YesSql/Migrations.cs, src/samples/server/Elsa.Samples.Server.Host/Workflows/HelloWorld.cs, src/samples/server/Elsa.Samples.Server.Host/Workflows/HelloWorld.v2.cs, src/server/Elsa.Server.Api/Endpoints/ActivityStats/Get.cs, src/server/Elsa.Server.Api/Endpoints/ActivityStats/Models.cs
This PR adds a feature that enables the user to inspect an activity's performance.
=> Activity Stats

src/activities/Elsa.Activities.Http/Endpoints/Signals/DispatchEndpoint.cs, src/activities/Elsa.Activities.Http/Endpoints/Signals/TriggerEndpoint.cs, src/activities/Elsa.Activities.MassTransit/Consumers/WorkflowConsumer.cs, src/activities/Elsa.Activities.Rebus/Consumers/MessageConsumer.cs, src/core/Elsa.Abstractions/Services/IWorkflowLaunchpad.cs, src/core/Elsa.Core/Activities/Signaling/Services/ISignaler.cs, src/core/Elsa.Core/Activities/Signaling/Services/Signaler.cs, src/core/Elsa.Core/Services/WorkflowLaunchpad.cs, src/samples/server/Elsa.Samples.Server.Host/Elsa.Samples.Server.Host.csproj, src/samples/server/Elsa.Samples.Server.Host/Models/SampleInputModel.cs, src/samples/server/Elsa.Samples.Server.Host/Startup.cs, src/server/Elsa.Server.Api/ActionFilters/ElsaJsonFormatterAttribute.cs, src/server/Elsa.Server.Api/Endpoints/Signals/Dispatch.cs, src/server/Elsa.Server.Api/Endpoints/Signals/Execute.cs, src/server/Elsa.Server.Api/Endpoints/Signals/Models.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Dispatch.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Execute.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Models.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/Dispatch.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/Execute.cs, src/server/Elsa.Server.Api/Endpoints/Workflows/Dispatch.cs, src/server/Elsa.Server.Api/Endpoints/Workflows/Execute.cs, src/server/Elsa.Server.Api/ModelBinders/ElsaJsonBodyModelBinder.cs, src/server/Elsa.Server.Hangfire/Jobs/CorrelatedWorkflowDefinitionJob.cs, src/server/Elsa.Server.Orleans/Grains/CorrelatedWorkflowDefinitionGrain.cs
This PR adds more API endpoints that are related to executing workflows.
Closes #991
=> Execution api endpoints

src/core/Elsa.Abstractions/Models/SimpleException.cs, src/core/Elsa.Abstractions/Services/Models/ActivityExecutionContext.cs, src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs, src/core/Elsa.Core/Handlers/WriteWorkflowExecutionLog.cs, src/core/Elsa.Core/Mapping/ExceptionConverter.cs, src/core/Elsa.Core/Mapping/ExceptionProfile.cs, src/core/Elsa.Core/Services/WorkflowRunner.cs, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-journal/elsa-workflow-instance-journal.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-viewer-screen/elsa-workflow-instance-viewer-screen.tsx, src/designer/elsa-workflows-studio/src/utils/utils.ts, src/server/Elsa.Server.Api/Mapping/ActivityBlueprintConverter.cs, src/server/Elsa.Server.Api/Mapping/ConnectionConverter.cs
=> Journal UI improvements

src/designer/elsa-workflows-studio/src/utils/utils.ts
Fast and dirty fix for #1024.
Fixing 3 decimal places to time display.
=> Time display fixed to fixed 3 decimal places.

src/persistence/Elsa.Persistence.MongoDb/Serializers/JObjectSerializer.cs, src/persistence/Elsa.Persistence.MongoDb/Serializers/ObjectSerializer.cs, src/persistence/Elsa.Persistence.MongoDb/Services/DatabaseRegister.cs
=> BREAKING: Update MongoDB provider with support for object derivatives

src/locking/Elsa.DistributedLocking.AzureBlob/DistributedLockingOptionsExtensions.cs
=> Change extension method name to UseAzureBlobLockProvider

src/core/Elsa.Abstractions/Metadata/ActivityDescriptor.cs, src/core/Elsa.Abstractions/Metadata/ActivityInputDescriptor.cs
Solves first two items in #1165.
=> 2.0 to 2.1 code backward compatibility related to IActivityTypeProvider

src/activities/Elsa.Activities.Http/Middleware/HttpEndpointMiddleware.cs
having a fault in a workflow started through http endpoint returns 500
only in case the response has not alerady been started
=> http endpoint respond with 500 for faulted workflow

src/activities/Elsa.Activities.Temporal.Quartz/Startup.cs, src/activities/webhooks/Elsa.Webhooks.Persistence.EntityFramework.Core/EntityFrameworkWebhookStartupBase.cs, src/activities/webhooks/Elsa.Webhooks.Persistence.EntityFramework.MySql/Startup.cs, src/activities/webhooks/Elsa.Webhooks.Persistence.EntityFramework.PostgreSql/Startup.cs, src/activities/webhooks/Elsa.Webhooks.Persistence.EntityFramework.SqlServer/Startup.cs, src/activities/webhooks/Elsa.Webhooks.Persistence.EntityFramework.Sqlite/Startup.cs, src/activities/webhooks/Elsa.Webhooks.Persistence.MongoDb/Startup.cs, src/activities/webhooks/Elsa.Webhooks.Persistence.YesSql/Startups.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/EntityFrameworkCoreStartupBase.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.MySql/Startup.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Startup.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Startup.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Sqlite/Startup.cs, src/persistence/Elsa.Persistence.MongoDb/Startup.cs, src/persistence/Elsa.Persistence.YesSql/Startups.cs, src/samples/server/Elsa.Samples.Server.Host/README.md, src/samples/server/Elsa.Samples.Server.Host/appsettings.json, src/scripting/Elsa.Scripting.JavaScript/Startup.cs, src/server/Elsa.Server.Hangfire/Startup.cs
Colons are removed from any element name in the appsettings
=> Don#t use colon in appsettings #1223

Elsa.sln, src/core/Elsa.Abstractions/Services/ITenantAccessor.cs, src/core/Elsa.Core/Activities/Signaling/Services/Signaler.cs, src/core/Elsa.Core/ElsaOptionsBuilder.cs, src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs, src/core/Elsa.Core/Services/DefaultTenantAccessor.cs, src/samples/aspnet/Elsa.Samples.CustomTenantIdSource/CustomTenantAccessor.cs, src/samples/aspnet/Elsa.Samples.CustomTenantIdSource/Elsa.Samples.CustomTenantIdSource.csproj, src/samples/aspnet/Elsa.Samples.CustomTenantIdSource/Program.cs, src/samples/aspnet/Elsa.Samples.CustomTenantIdSource/Properties/launchSettings.json, src/samples/aspnet/Elsa.Samples.CustomTenantIdSource/Startup.cs, src/samples/aspnet/Elsa.Samples.CustomTenantIdSource/appsettings.Development.json, src/samples/aspnet/Elsa.Samples.CustomTenantIdSource/appsettings.json, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Import.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/List.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Save.cs, src/server/Elsa.Server.Api/Endpoints/Workflows/Dispatch.cs, src/server/Elsa.Server.Api/Endpoints/Workflows/Execute.cs, src/server/Elsa.Server.Api/Endpoints/Workflows/Trigger.cs
Mainly add the ability of tenantid customization for API projects, and add sample projects
=> Add ITenantAccessor interface to provide custom ability for acquiring tenantid

src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx
This resolves #1155. My humble apologies, I know it has Elsa 2.3 mark on it but I couldn't wait :)......
The start activity is now placed in the upper middle of visible area when workflow is loaded.
=> Center start activity when loading workflow

src/core/Elsa.Abstractions/Services/Workflows/IStartsWorkflow.cs, src/core/Elsa.Abstractions/Services/Workflows/IWorkflowFactory.cs, src/core/Elsa.Core/Activities/Workflows/RunWorkflow/RunWorkflow.cs, src/core/Elsa.Core/Services/Workflows/WorkflowFactory.cs, src/core/Elsa.Core/Services/Workflows/WorkflowLaunchpad.cs, src/core/Elsa.Core/Services/Workflows/WorkflowStarter.cs, test/unit/Elsa.UnitTests/Services/WorkflowExecutionContextForWorkflowBlueprintFactoryTests.cs
=> Added TenantId in IStartsWorkflow.StartWorkflowAsync and IWorkflowFactory.InstantiateAsync

src/designer/elsa-workflows-studio/src/components.d.ts, src/designer/elsa-workflows-studio/src/components/controls/elsa-control/elsa-control.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-activity-editor-modal/elsa-activity-editor-modal.tsx, src/designer/elsa-workflows-studio/src/index.html, src/designer/elsa-workflows-studio/src/models/events.ts
This PR adds the ability to customize what tabs are displayed in the activity editor, as well as adding custom tabs and reo=moving existing ones).
The following example demonstrates a plugin that removes the Properties tab and adds a custom tab for the WriteLine activity:
```javascript
// Plugin that completely customizes the activity editor for the WriteLine activity.
function CustomActivityEditorPlugin(elsaStudio) {
const {eventBus, getOrCreateProperty, htmlToElement} = elsaStudio;
// When the activity editor is about to be rendered.
eventBus.on('activity-editor-displaying', e => {
const {activityDescriptor, activityModel} = e;
// We only handle WriteLine activities.
if(activityDescriptor.type !== 'WriteLine')
return;
let tabs = [...e.tabs];
// Remove the 'Properties' tab:
tabs = …
```
=> Activity editor dialog extensibility

src/activities/Elsa.Activities.MassTransit/Consumers/WorkflowConsumer.cs
Test-Project Elsa.Samples.MassTransitRabbitMq works again. :)
=> Fix for missing input in MassTransit message-consuming (#1332)

src/core/Elsa.Core/Services/Messaging/ServiceBusFactory.cs
This solves #1373, IBus instances are properly disposed at shutdown.
=> Disposing IBus instances

src/designer/elsa-workflows-studio/package-lock.json, src/designer/elsa-workflows-studio/src/components.d.ts, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-dashboard/elsa-studio-dashboard.tsx, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-blueprint-view/readme.md, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-definitions-edit/readme.md, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-blueprint-viewer/elsa-workflow-blueprint-side-panel/elsa-workflow-blueprint-side-panel.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-blueprint-viewer/elsa-workflow-blueprint-side-panel/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-blueprint-viewer/elsa-workflow-blueprint-viewer-screen/elsa-workflow-blueprint-viewer-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-blueprint-viewer/elsa-workflow-blueprint-viewer-screen/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-properties-panel/elsa-workflow-properties-panel.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-properties-panel/localizations.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-properties-panel/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-publish-button/elsa-workflow-publish-button.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-journal/elsa-workflow-instance-journal.tsx
=> Side Panel Implementation

src/activities/Elsa.Activities.Temporal.Hangfire/Services/HangfireWorkflowDefinitionScheduler.cs, src/activities/Elsa.Activities.Temporal.Hangfire/Services/HangfireWorkflowInstanceScheduler.cs
This solves #1376 by using using block around IStorageConnection getter.
=> Properly Dispose IStorageConnection

Elsa.sln, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-definitions-edit/elsa-studio-workflow-definitions-edit.tsx, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-activity-editor-modal/elsa-activity-editor-modal.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx, src/designer/elsa-workflows-studio/src/components/shared/elsa-modal-dialog/elsa-modal-dialog.tsx, src/designer/elsa-workflows-studio/src/models/events.ts
Hi Sipke, this is the addressed fix to copy/paste activities, where Ctrl+C and Ctrl+P should not affect the Workflow Editor and other Workflow modal windows copy/paste functionality.
=> Fix to copy/paste activities.

src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-journal/elsa-workflow-instance-journal.tsx
=> Fixed scroll issue on the journal side panel.

src/designer/bindings/aspnet/Elsa.Designer.Components.Web/package-lock.json, src/designer/bindings/aspnet/Elsa.Designer.Components.Web/yarn.lock, src/designer/elsa-workflows-studio/package-lock.json, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/readme.md
Hi again, this is a follow up of PR #1462 to add automatically generated or edited files.
Let me know if you find anything wrong.
=> Sync auto-generated build files

src/persistence/Elsa.Persistence.MongoDb/Serializers/ObjectSerializer.cs
=> Add ReferenceLoopHandling In MongoDb Serializer

src/designer/elsa-workflows-studio/package.json, src/designer/elsa-workflows-studio/src/components/controls/elsa-pager/elsa-pager.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-list/elsa-workflow-instance-list-screen/elsa-workflow-instance-list-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-list/elsa-workflow-instance-list-screen/localizations.ts
This fixes #1504.
Added page size dropdown.
Added bunch of sanity checks on page nad page size in case user enters wrong numbers in url.
Fixed one off error in pager summary.
Fixed small bug in package.json for dev build.
=> Add page size control and some sanity checks, fix one off in pager

src/designer/elsa-workflows-studio/src/components.d.ts, src/designer/elsa-workflows-studio/src/components/controls/elsa-context-menu/readme.md, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-dashboard/readme.md, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-root/readme.md, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-blueprint-view/readme.md, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-definitions-edit/readme.md, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-instances-view/readme.md, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-registry/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-blueprint-viewer/elsa-workflow-blueprint-viewer-screen/elsa-workflow-blueprint-viewer-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-blueprint-viewer/elsa-workflow-blueprint-viewer-screen/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-properties-panel/elsa-workflow-properties-panel.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-properties-panel/localizations.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-journal/elsa-workflow-instance-journal.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-journal/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-viewer-screen/elsa-workflow-instance-viewer-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-viewer-screen/readme.md, src/designer/elsa-workflows-studio/src/components/screens/workflow-registry-list/elsa-workflow-registry-list-screen/readme.md, src/designer/elsa-workflows-studio/src/components/shared/elsa-confirm-dialog/readme.md, src/designer/elsa-workflows-studio/src/components/shared/elsa-flyout-panel/elsa-flyout-panel.tsx, src/designer/elsa-workflows-studio/src/components/shared/elsa-flyout-panel/readme.md, src/designer/elsa-workflows-studio/src/components/shared/elsa-tab-content/elsa-tab-content.tsx, src/designer/elsa-workflows-studio/src/components/shared/elsa-tab-content/readme.md, src/designer/elsa-workflows-studio/src/components/shared/elsa-tab-header/elsa-tab-header.tsx, src/designer/elsa-workflows-studio/src/components/shared/elsa-tab-header/readme.md, src/designer/elsa-workflows-studio/src/components/shared/elsa-toast-notification/readme.md, src/designer/elsa-workflows-studio/src/globals/tailwind.css, src/designer/elsa-workflows-studio/src/modules/elsa-webhooks/components/screens/webhook-definition-editor/elsa-webhook-definition-editor-notifications/readme.md, src/designer/elsa-workflows-studio/src/modules/elsa-webhooks/components/screens/webhook-definition-list/else-webhook-definitions-screen/readme.md
Added flyout panel to instances page. Refactored existing properties panel to share the same component.
closes #1431
=> Added flyout panel to instances page.

src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-activity-editor-modal/elsa-activity-editor-modal.tsx, src/designer/elsa-workflows-studio/src/components/shared/elsa-modal-dialog/elsa-modal-dialog.tsx
=> Added keyboard actions support for activity edit modal.

src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx
=> Fixed position issue.

src/designer/elsa-workflows-studio/src/components.d.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx, src/designer/elsa-workflows-studio/src/components/shared/elsa-flyout-panel/elsa-flyout-panel.tsx, src/designer/elsa-workflows-studio/src/components/shared/elsa-modal-dialog/elsa-modal-dialog.tsx, src/designer/elsa-workflows-studio/src/components/shared/elsa-tab-header/elsa-tab-header.tsx
=> Added legend/help. Added cursor pointer.

src/designer/elsa-workflows-studio/src/components.d.ts, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx, src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/models.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/localizations.ts
=> Added multi delete.

src/modules/workflowsettings/Elsa.WorkflowSettings/Elsa.WorkflowSettings.csproj, src/modules/workflowsettings/Elsa.WorkflowSettings/Extensions/WorkflowSettingsOptionsBuilderExtensions.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Extensions/WorkflowSettingsStoreExtensions.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Handlers/EvaluatingJavaScriptExpressionHandler.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Handlers/RenderingTypeScriptDefinitionsHandler.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Models/WorkflowSetting.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Persistence/Specification/WorkflowSettingsDefinitions/WorkflowSettingsBlueprintIdAndKeySpecification.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Persistence/Specification/WorkflowSettingsDefinitions/WorkflowSettingsBlueprintIdSpecification.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Providers/ConfigurationWorkflowSettingsProvider.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Providers/DatabaseWorkflowSettingsProvider.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Providers/IWorkflowSettingsProvider.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Providers/WorkflowSettingsProvider.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Services/IWorkflowSettingsManager.cs, src/modules/workflowsettings/Elsa.WorkflowSettings/Services/WorkflowSettingsManager.cs
Extended javascript vocabulary with workflow settings.
=> WorkflowSettings for JavaScript vocabulary

Nuget.Config, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Configuration/WorkflowDefinitionConfiguration.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/ElsaContext.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/Migrations/20211104093625_Update24.Designer.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/Migrations/20211104093625_Update24.cs
when data is bigger than 2000 chars the columns of database should be NCLOB
=> Fix for oracle persistence provider

src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequest.cs, src/activities/Elsa.Activities.Http/Parsers/Response/ExpandoObjectHttpResponseContentReader.cs, src/activities/Elsa.Activities.Http/Parsers/Response/FileHttpResponseContentReader.cs, src/activities/Elsa.Activities.Http/Parsers/Response/JTokenHttpResponseContentReader.cs, src/activities/Elsa.Activities.Http/Parsers/Response/JsonRawHttpResponseContentReader.cs, src/activities/Elsa.Activities.Http/Parsers/Response/PlainTextHttpResponseContentReader.cs, src/activities/Elsa.Activities.Http/Parsers/Response/TypedHttpResponseContentReader.cs, src/activities/Elsa.Activities.Http/Services/IHttpResponseContentReader.cs
=> Refactor IHttpResponseContentReader

src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-root/elsa-studio-root.tsx
=> Call to get config file is not done if the config param is empty.

src/activities/Elsa.Activities.RabbitMq/Activities/IRabbitMqActivity.cs, src/activities/Elsa.Activities.RabbitMq/Activities/RabbitMqMessageReceived/RabbitMqMessageReceived.cs, src/activities/Elsa.Activities.RabbitMq/Activities/RabbitMqMessageReceived/RabbitMqMessageReceivedBuilderExtensions.cs, src/activities/Elsa.Activities.RabbitMq/Activities/RabbitMqMessageReceived/RabbitMqMessageReceivedExtensions.cs, src/activities/Elsa.Activities.RabbitMq/Activities/SendRabbitMqMessage/SendRabbitMqMessage.cs, src/activities/Elsa.Activities.RabbitMq/Activities/SendRabbitMqMessage/SendRabbitMqMessageBuilderExtensions.cs, src/activities/Elsa.Activities.RabbitMq/Activities/SendRabbitMqMessage/SendRabbitMqMessageExtensions.cs, src/activities/Elsa.Activities.RabbitMq/Bookmarks/MessageReceivedBookmark.cs, src/activities/Elsa.Activities.RabbitMq/Configuration/RabbitMqBusConfiguration.cs, src/activities/Elsa.Activities.RabbitMq/Services/Client.cs, src/activities/Elsa.Activities.RabbitMq/Services/RabbitMqQueueStarter.cs, src/activities/Elsa.Activities.RabbitMq/Services/Worker.cs, src/samples/worker/Elsa.Samples.RabbitMqWorker/Workflows/ConsumerWorkflow.cs, src/samples/worker/Elsa.Samples.RabbitMqWorker/Workflows/ProducerWorkflow.cs, src/samples/worker/Elsa.Samples.RabbitMqWorker/Workflows/SendAndReceiveWorkflow.cs
- Added Exchange Name property to give ability to subscribe/publish to specific exchange. 
- Removed binding auto-delete to preserve binding in case of disconnect.  
- Added RabbitMQ connection string format to connection string property tooltip.
- Added more builder configurations (with/without headers and exchange name)
=> Improvements for RabbitMQ activity

src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-root/elsa-studio-root.tsx
Fixes http plugins that are registered according to documentation not working anymore described in #2653
=> reordered operations to make http plugins work again

src/scripting/Elsa.Scripting.JavaScript/Handlers/ConfigureJavaScriptEngine.cs, src/scripting/Elsa.Scripting.JavaScript/Handlers/RenderJavaScriptTypeDefinitions.cs
This adds the getTransientVariable JS declaration to access transient variables in the workflow designer.
=> Add getTransientVariable JS declaration

src/designer/elsa-workflows-studio/package-lock.json, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-journal/elsa-workflow-instance-journal.tsx, src/designer/elsa-workflows-studio/src/globals/tailwind.css, src/designer/elsa-workflows-studio/src/index.html
=> Fixed journal time display. Fixed minor visual issues.

src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-home/elsa-studio-home.tsx, src/designer/elsa-workflows-studio/src/components/shared/elsa-flyout-panel/elsa-flyout-panel.tsx
+  Changed version on home page.
Closes #2724
=> Fixed scroll overflow issue on journal tab.

src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-viewer-screen/elsa-workflow-instance-viewer-screen.tsx
=> Instance viewer layout will use the layout set in the designer.

src/persistence/Elsa.Persistence.MongoDb/Extensions/ServiceCollectionExtensions.cs, src/server/Elsa.Server.Api/Endpoints/Signals/Dispatch.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/BulkRetry.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/Cancel.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowRegistry/ListByProvider.cs
Fix #2517 
Validated with https://validator.swagger.io/
=> Fix swagger duplicate operationId

src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-list/elsa-workflow-instance-list-screen/elsa-workflow-instance-list-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-list/elsa-workflow-instance-list-screen/localizations.ts, src/designer/elsa-workflows-studio/src/services/elsa-client.ts, src/samples/server/Elsa.Samples.Server.Host/Startup.cs
=> Add BulkRetry + Retry UI

src/activities/Elsa.Activities.AzureServiceBus/Services/WorkerManager.cs
This PR fixes the race condition #2812  by adding a semaphore on RemoveWorkersAsync(Triggers)
=> Fix race condition for TriggerIndexingFinished/TriggersDeleted

src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/ElsaContext.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/Migrations/ElsaContextModelSnapshot.cs
Oracle NCLOB column can't be used in where clause. 
current implementation throws an error at the begining :ORA-00932: inconsistent datatypes: expected - got NCLOB
and you should manually change datatype in database side.this will fix  migration script to be NVARCHAR2(2000)
note :I didn't run migration script to generate migration classes
=> problem in Trigger table

src/designer/bindings/aspnet/Elsa.Designer.Components.Web/package.json
=> Docker build fix

src/clients/Elsa.Client/Models/SaveWorkflowDefinitionRequest.cs, src/clients/Elsa.Client/Models/WorkflowDefinition.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Models.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Save.Request.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Save.cs, src/server/Elsa.Server.Api/Swagger/Examples/WorkflowDefinitionSummaryModelExample.cs
- Added the changes described in #2738 
- Removed random whitespace
=> Add CustomAttributes to SaveWorkflowDefinitionRequest and WorkflowDefinitionSummaryModel

src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequest.cs
This is a fix for bug issue #2776
=> Bugfix: Adding also the content headers to ResponseModel.

src/activities/Elsa.Activities.UserTask/Contracts/IUserTaskService.cs, src/activities/Elsa.Activities.UserTask/Models/TriggerUserAction.cs, src/activities/Elsa.Activities.UserTask/Services/UserTaskService.cs
Hello everyone ;D
For the use case that I am trying to replicate with Elsa we need to create to-do mailboxes for the users.
As documented, it is possible to obtain the list of available actions that a specific workflow has or all the pending UserTasks through the IUserTaskService.
This will allow me to create a list for users with buttons to trigger the actions but we need to expose endpoints that allow us to trigger and continue the workflows.
I have added support to be able to execute/dispatch activities of type UserTask in several ways:
- From a specific UserTask in a workflow instance
- All UserTasks that are waiting for the same action in any workflow instance
- All UserTasks that are waiting for the same action in any workflow instance that has the specified CorrelationId
=> Execute/Dispatch UserTask activities

src/core/Elsa.Core/Builders/WorkflowDefinitionBuilder.cs, src/core/Elsa.Core/Models/Workflow.cs, src/core/Elsa.Persistence.Abstractions/Entities/WorkflowDefinition.cs, src/core/Elsa.Persistence.Abstractions/Extensions/WorkflowDefinitionExtensions.cs, src/core/Elsa.Runtime/HostedServices/PopulateWorkflowDefinitionStore.cs, src/core/Elsa.Runtime/WorkflowProviders/ClrWorkflowDefinitionProvider.cs, src/persistence/efcore/Elsa.Persistence.EntityFrameworkCore/Configuration/WorkflowDefinitionConfiguration.cs, src/persistence/efcore/Elsa.Persistence.EntityFrameworkCore/Handlers/WorkflowDefinitionSerializer.cs
Reverts elsa-workflows/elsa-core#2990
=> Revert "Provide tag support for workflows"

src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/Models.cs
=> Metadata included in WorkflowInstanceSummaryModel

src/api/Elsa.Api/ApiResults/DispatchWorkflowDefinitionResult.cs, src/api/Elsa.Api/ApiResults/ExecuteWorkflowDefinitionResult.cs, src/api/Elsa.Api/ControllerNames.cs, src/api/Elsa.Api/Endpoints/Labels/Delete.cs, src/api/Elsa.Api/Endpoints/Labels/Get.cs, src/api/Elsa.Api/Endpoints/WorkflowDefinitionLabels/Get.cs, src/api/Elsa.Api/Endpoints/WorkflowDefinitionLabels/Update.cs, src/api/Elsa.Api/Endpoints/WorkflowDefinitions/Execute.cs, src/api/Elsa.Api/Endpoints/WorkflowDefinitions/List.cs, src/api/Elsa.Api/Extensions/EndpointRouteBuilderExtensions.cs, src/api/Elsa.Api/Models/ListModel.cs, src/core/Elsa.Persistence.Abstractions/Entities/Label.cs, src/core/Elsa.Persistence.Abstractions/Implementations/NullLabelStore.cs, src/core/Elsa.Persistence.Abstractions/Implementations/NullWorkflowDefinitionLabelStore.cs, src/core/Elsa.Persistence.Abstractions/Implementations/NullWorkflowDefinitionStore.cs, src/core/Elsa.Persistence.Abstractions/Services/ILabelStore.cs, src/core/Elsa.Persistence.Abstractions/Services/IWorkflowDefinitionLabelStore.cs, src/core/Elsa.Persistence.Abstractions/Services/IWorkflowDefinitionStore.cs, src/persistence/efcore/Elsa.Persistence.EntityFrameworkCore.Sqlite/Migrations/20220518111933_Initial.Designer.cs, src/persistence/efcore/Elsa.Persistence.EntityFrameworkCore.Sqlite/Migrations/20220518111933_Initial.cs, src/persistence/efcore/Elsa.Persistence.EntityFrameworkCore.Sqlite/Migrations/ElsaDbContextModelSnapshot.cs, src/persistence/efcore/Elsa.Persistence.EntityFrameworkCore/Elsa.Persistence.EntityFrameworkCore.csproj, src/persistence/efcore/Elsa.Persistence.EntityFrameworkCore/Implementations/EFCoreLabelStore.cs, src/persistence/efcore/Elsa.Persistence.EntityFrameworkCore/Implementations/EFCoreWorkflowDefinitionLabelStore.cs, src/persistence/efcore/Elsa.Persistence.EntityFrameworkCore/Implementations/EFCoreWorkflowDefinitionStore.cs, src/persistence/memory/Elsa.Persistence.InMemory/Implementations/InMemoryLabelStore.cs, src/persistence/memory/Elsa.Persistence.InMemory/Implementations/InMemoryWorkflowDefinitionLabelStore.cs, src/persistence/memory/Elsa.Persistence.InMemory/Implementations/InMemoryWorkflowDefinitionStore.cs
This PR adds support for querying workflow definitions by labels.
Closes #2983
=> Query workflows by labels API

src/designer/elsa-workflows-designer/src/components.d.ts, src/designer/elsa-workflows-designer/src/components/designer/toolbox/toolbox-activities.scss, src/designer/elsa-workflows-designer/src/components/designer/toolbox/toolbox-activities.tsx, src/designer/elsa-workflows-designer/src/components/shared/tooltip/tooltip.scss, src/designer/elsa-workflows-designer/src/components/shared/tooltip/tooltip.tsx, src/designer/elsa-workflows-designer/src/models/api.ts
Added description tooltip on activity panel.
Related to https://github.com/elsa-workflows/elsa-core/issues/2876
=> activity description tooltip added

src/designer/elsa-workflows-designer/src/components.d.ts, src/designer/elsa-workflows-designer/src/components/shared/forms/info-list.tsx, src/designer/elsa-workflows-designer/src/utils/copy.ts, src/designer/elsa-workflows-designer/src/utils/index.ts
Added copy text tool to workflow defenition info
Related to https://github.com/elsa-workflows/elsa-core/issues/3012
=> Copy Text Tool

src/api/Elsa.Api/Endpoints/WorkflowDefinitions/BulkDelete.cs, src/api/Elsa.Api/Endpoints/WorkflowDefinitions/BulkPublish.cs, src/api/Elsa.Api/Endpoints/WorkflowDefinitions/BulkRetract.cs, src/api/Elsa.Api/Endpoints/WorkflowDefinitions/Retract.cs, src/api/Elsa.Api/Endpoints/WorkflowInstances/BulkCancel.cs, src/api/Elsa.Api/Endpoints/WorkflowInstances/BulkDelete.cs, src/api/Elsa.Api/Extensions/EndpointRouteBuilderExtensions.cs
This PR adds the following API endpoints:
- Bulk-delete workflow instances
- Bulk-cancel workflow instances
- Bulk-delete workflow definitions
- Bulk-publish workflow definitions
- Bulk-retract workflow definitions
Closes #3059
=> V3 Bulk Actions API Endpoints

src/designer/elsa-workflows-designer/src/components/modals/workflow-definition-browser/filter.tsx, src/designer/elsa-workflows-designer/src/components/modals/workflow-definition-browser/utils.ts, src/designer/elsa-workflows-designer/src/components/modals/workflow-definition-browser/workflow-definition-browser.tsx, src/designer/elsa-workflows-designer/src/services/api-client/workflow-definitions-api.ts
Related to https://github.com/elsa-workflows/elsa-core/issues/3013 and https://github.com/elsa-workflows/elsa-core/issues/3011
=> workflow definition pagination and bulk actions

src/designer/elsa-workflows-studio/src/components/controls/elsa-monaco/elsa-monaco.tsx
Attempting to fix code completion for Monaco editor #2907
=> Attempt fix #2907

src/designer/elsa-workflows-designer/src/components.d.ts, src/designer/elsa-workflows-designer/src/components/modals/workflow-definition-browser/filter.tsx, src/designer/elsa-workflows-designer/src/components/modals/workflow-definition-browser/workflow-definition-browser.tsx, src/designer/elsa-workflows-designer/src/modules/labels/label-picker.tsx, src/designer/elsa-workflows-designer/src/services/api-client/workflow-definitions-api.ts, src/designer/elsa-workflows-designer/src/utils/utils.ts
related to https://github.com/elsa-workflows/elsa-core/issues/2985
=> added label filter to workflow definition modal

src/designer/elsa-workflows-studio/src/utils/utils.ts
=> Liquid is liquid

src/designer/elsa-workflows-designer/src/components.d.ts, src/designer/elsa-workflows-designer/src/components/designer/workflow-definition-editor/toolbar.tsx, src/designer/elsa-workflows-designer/src/components/designer/workflow-definition-editor/workflow-definition-editor.scss, src/designer/elsa-workflows-designer/src/components/designer/workflow-definition-editor/workflow-definition-editor.tsx
related to https://github.com/elsa-workflows/elsa-core/issues/2892
=> added toolbar layouts

src/designer/elsa-workflows-designer/src/components/activities/flowchart/flowchart.tsx, src/designer/elsa-workflows-designer/src/components/designer/workflow-definition-editor/workflow-definition-editor.tsx
related to https://github.com/elsa-workflows/elsa-core/issues/2972
=> fixed incorrect positioning on zoom or graph move

src/designer/elsa-workflows-designer/src/components.d.ts, src/designer/elsa-workflows-designer/src/components/activities/container-activity-component.tsx, src/designer/elsa-workflows-designer/src/components/activities/flowchart/flowchart.tsx, src/designer/elsa-workflows-designer/src/components/designer/canvas/canvas.tsx, src/designer/elsa-workflows-designer/src/components/designer/workflow-definition-editor/toolbar.tsx, src/designer/elsa-workflows-designer/src/components/designer/workflow-definition-editor/workflow-definition-editor.scss, src/designer/elsa-workflows-designer/src/components/designer/workflow-definition-editor/workflow-definition-editor.tsx
related to https://github.com/elsa-workflows/elsa-core/issues/2952
=> added zoom-to-fit functionality

src/core/Elsa.Core/Persistence/Specifications/WorkflowDefinitions/WorkflowDefinitionSearchTermSpecification.cs, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-list/elsa-workflow-definitions-screen/elsa-workflow-definitions-list-screen.tsx, src/designer/elsa-workflows-studio/src/services/elsa-client.ts, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/List.cs
Follow up of #3128 with suggested edits.
=> Workflow Definitions Search

src/activities/Elsa.Activities.RabbitMq/Activities/RabbitMqMessageReceived/RabbitMqMessageReceived.cs, src/activities/Elsa.Activities.RabbitMq/Activities/SendRabbitMqMessage/SendRabbitMqMessage.cs
Add the posibility to define dyamic headers with JavaScript Syntax
=> [RabbitMQ] Add Javascript Syntax to Headers definition

src/core/Elsa.Core/Activities/ControlFlow/Join/Join.cs, test/integration/Elsa.Core.IntegrationTests/Workflows/ForkEagerJoinWorkflow.cs, test/integration/Elsa.Core.IntegrationTests/Workflows/ForkJoinWorkflowTests.cs
This was discussed in this issue: https://github.com/elsa-workflows/elsa-core/issues/3065
=> Add "EagerJoin" option to joins

src/scripting/Elsa.Scripting.JavaScript/Messages/ConfigureJavaScriptOptions.cs, src/scripting/Elsa.Scripting.JavaScript/Messages/EvaluatingJavaScriptExpression.cs, src/scripting/Elsa.Scripting.JavaScript/Services/JintJavaScriptEvaluator.cs
Adding notification to allow the jint options to be intercepted as part of the configuration Action
=> Jint options configuration

src/samples/server/Elsa.Samples.Server.Host/Endpoints/BrandModels/List.cs
Small fix to enable swagger generation in Server Sample
=> Fix Server Sample Swagger Gen

src/activities/Elsa.Activities.Http.OpenApi/HttpEndpointDocumentFilter.cs
=> Prepend HttpEndpoint's path with BasePath in swagger

src/designer/elsa-workflows-studio/package-lock.json, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-test-panel/elsa-workflow-test-panel.tsx, src/designer/elsa-workflows-studio/src/index.html, src/designer/elsa-workflows-studio/src/models/events.ts
Adding HubConnection events to elsa-studio
Resolves Issue: https://github.com/elsa-workflows/elsa-core/issues/2649
Simple events created for `eventBus`
```
HubConnectionCreated: 'hubconnection-created',
HubConnectionStarted: 'hubconnection-started',
HubConnectionConnected: 'hubconnection-connected',
HubConnectionFailed: 'hubconnection-failed',
HubConnectionClosed: 'hubconnection-closed'
```
Example Plugin (included in `index.html`)
```
function accessTokenFactory() {
return  (Math.random() + 1).toString(36).substring(7);
}
function CustomHubConnectionPlugin(elsaStudio) {
const eventBus = elsaStudio.eventBus;
eventBus.on('hubconnection-created', e => {
// e: HubConnectionBuilder
//example to modify the with url for Bearer token handling.
e.withUrl(e.url, { accessTokenFactory: …
```
=> PR: SignalR Hub Connection Events

src/core/Elsa.Core/Services/Workflows/WorkflowRunner.cs
Fixes #3031....
The changes in 3 catch handlers were needed to pass correct activity (current, not starting one) to `Fault` and Journal `AddEntry`.
The additional `if (workflowInstance.WorkflowStatus != WorkflowStatus.Faulted)` was needed to avoid leaving instance in running state (since similar if existed when instance is started from idle I used same for this case when starting from suspended).
=> Fixing faulted activity display in Journal as well as workflow that remain in running state after fault.

src/core/Elsa.Core/HostedServices/ScopedBackgroundService.cs, src/core/Elsa.Core/Metadata/TypedActivityTypeDescriber.cs, src/core/Elsa.Core/Runtime/StartupRunner.cs, src/core/Elsa.Core/Services/Workflows/WorkflowRunner.cs
Added the `CreateAsyncScope` instead of `CreateScope`.
=> #3257 Move to CreateAsyncScope

src/activities/Elsa.Activities.Rpa.Web/Activities/ClickElement.cs, src/activities/Elsa.Activities.Rpa.Web/Activities/NavigateToUrl.cs, src/activities/Elsa.Activities.Rpa.Web/Activities/OpenBrowser.cs, src/activities/Elsa.Activities.Rpa.Web/Activities/TypeText.cs, src/activities/Elsa.Activities.Rpa.Web/Activities/WebActivity.cs
#3300 fix
-) added possibility to scope browser instance
-) added support to javascript and liquid expressions in designer
=> RPA Activities Enhancements

src/core/Elsa.Core/Activities/StateMachine/State.cs
Alays Outcomes Transitions,CurrentState Not used on outcome, so Perform all activities at all times
After modification：
=> Fix StateMachine

src/activities/Elsa.Activities.Http/Scripting/JavaScript/HttpTypeDefinitionProvider.cs
#3308 
fix error when HttpEndpoint.TargetType not configured
=> fix error when TargetType not configured #3308

src/designer/elsa-workflows-studio/src/modules/elsa-webhooks/components/screens/webhook-definition-editor/elsa-webhook-definition-editor-screen/elsa-webhook-definition-editor-screen.tsx, src/designer/elsa-workflows-studio/src/modules/elsa-webhooks/components/screens/webhook-definition-list/else-webhook-definitions-screen/elsa-webhook-definitions-list-screen.tsx, src/designer/elsa-workflows-studio/src/modules/elsa-webhooks/services/elsa-client.ts, src/designer/elsa-workflows-studio/src/modules/elsa-workflows-settings/services/elsa-client.ts
createHttpClient is duplicated
=> reuse createHttpClient

test/unit/Elsa.UnitTests/Scripting/Liquid/LiquidParserTests.cs
=> fixed test on non windows machine

src/persistence/Elsa.Persistence.MongoDb/Extensions/ServiceCollectionExtensions.cs, src/persistence/Elsa.Persistence.MongoDb/Services/DatabaseInitializer.cs, src/persistence/Elsa.Persistence.MongoDb/Services/ElsaMongoDbContext.cs, src/persistence/Elsa.Persistence.MongoDb/Services/IElsaMongoDbContext.cs
=> Change dependence ElsaMongoDbContext to IElsaMongoDbContext

src/core/Elsa.Core/Activities/Workflows/RunWorkflow/RunWorkflow.cs, src/core/Elsa.Core/Providers/Workflows/DatabaseWorkflowProvider.cs
Pass tenantId to provider where already provided. See issue https://github.com/elsa-workflows/elsa-core/issues/3340 for details
=> elsa-core/issues/3340: pass tenantId to DatabaseWorkflowProvider

src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkStore.cs
=> Improve SQL character replacement by `ISqlGenerationHelper`

src/activities/Elsa.Activities.Http/Scripting/JavaScript/HttpEndpointTypeDefinitionRenderer.cs, src/activities/Elsa.Activities.Http/Scripting/JavaScript/HttpTypeDefinitionProvider.cs
#3309 changes , ` HttpEndpointTypeDefinitionRenderer.cs ` also to modify.
=> fix error when TargetType not configured #3308 #3309

src/core/Elsa.Core/Activities/StateMachine/State.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Extensions/RelationalEntityTypeExtensions.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkStore.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkWorkflowInstanceStore.cs
=> fix "relation "elsa.triggers" does not exist" when DeleteManyAsync  #3383

common.props, src/designer/elsa-workflows-studio/src/components.d.ts, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-home/elsa-studio-home.tsx, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-root/elsa-studio-root.tsx, src/designer/elsa-workflows-studio/src/data/dashboard.tsx, src/designer/elsa-workflows-studio/src/models/services.ts, src/designer/elsa-workflows-studio/src/services/elsa-client.ts, src/samples/server/Elsa.Samples.Server.Host/Endpoints/BrandModels/List.cs, src/server/Elsa.Server.Api/Endpoints/Version/Get.cs
=> Add version endpoint for consumption by dashboard

src/activities/Elsa.Activities.Email/Activities/SendEmail/SendEmail.cs
=> Expose Success outcome on SendEmail activity

src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Extensions/RelationalEntityTypeExtensions.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkStore.cs, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkWorkflowInstanceStore.cs
=> Fixes SQL quoted identifiers by `ISqlGenerationHelper` (#3430)

src/designer/elsa-workflows-designer/src/components/toolbar/new-button/new-button.tsx, src/designer/elsa-workflows-designer/src/modules/activity-definitions/plugin.tsx, src/designer/elsa-workflows-designer/src/modules/workflow-definitions/components/publish-button.tsx, src/designer/elsa-workflows-designer/src/modules/workflow-definitions/plugin.tsx, src/designer/elsa-workflows-designer/src/modules/workflow-definitions/services/api.ts, src/designer/elsa-workflows-designer/src/modules/workflow-definitions/services/manager.ts, src/designer/elsa-workflows-designer/src/utils/utils.ts, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Import/Endpoint.cs
Restore import/export functionality
=> Update import / export

src/activities/webhooks/Elsa.Webhooks.Persistence.YesSql/Elsa.Webhooks.Persistence.YesSql.csproj, src/core/Elsa.Core/Elsa.Core.csproj
Upgrading Elsa Workflow solution to use Automapper 12. 
This is to resolve issue raised: https://github.com/elsa-workflows/elsa-core/issues/3369
=> feat: 🎸 Automapper 12.0.0

src/designer/elsa-workflows-designer/src/components/shared/monaco-editor/monaco-editor.scss, src/designer/elsa-workflows-designer/src/components/shared/monaco-editor/monaco-editor.tsx
task https://github.com/elsa-workflows/elsa-core/issues/3188 Make scroll for elsa script block
=> V3 bugfix  

src/designer/elsa-workflows-studio/src/components/designers/x6-designer/x6-designer.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-test-panel/elsa-workflow-test-panel.tsx
Just minor improvements and fixes
=> Some minor improvements to x6 graph

src/designer/elsa-workflows-studio/src/components/editors/properties/elsa-dropdown-property/elsa-dropdown-property.tsx
Fix for #3525 by setting default value if set.
@jdevillard can you please test if any impact on cascading dropdown?
=> check default value for dropdown

src/locking/Elsa.DistributedLocking.AzureBlob/DistributedLockingOptionsExtensions.cs
For my scenario I need to use TokenCredential to support ManagedIdentityCredential in production and VisualStudioCredential/AzureCliCredential in developer environments.
For BlobClientOptions I also use GeoRedundantSecondaryUri, so that has also been optionally exposed on the extension.
=> Azure Blob TokenCredential and BlobClientOptions for AzureBlobLeaseDistributedLock

src/activities/webhooks/Elsa.Webhooks.Persistence.EntityFramework.Core/Elsa.Webhooks.Persistence.EntityFramework.Core.csproj, src/activities/webhooks/Elsa.Webhooks.Persistence.EntityFramework.MySql/Elsa.Webhooks.Persistence.EntityFramework.MySql.csproj, src/modules/workflowsettings/Elsa.WorkflowSettings.Persistence.EntityFramework.Core/Elsa.WorkflowSettings.Persistence.EntityFramework.Core.csproj, src/modules/workflowsettings/Elsa.WorkflowSettings.Persistence.EntityFramework.MySql/Elsa.WorkflowSettings.Persistence.EntityFramework.MySql.csproj, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.MySql/Elsa.Persistence.EntityFramework.MySql.csproj, src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/Elsa.Persistence.EntityFramework.Oracle.csproj
update Oracle and MySQL providers.
some cleanups on workflowsettings and webhooks persistence to use implicit dependency.
=> Ef7 provider

.github/workflows/ci.yml
Azure DevOps has better support for managing teams + multiple types of packages.
=> Connect to to Azure DevOps feed

src/bundles/Elsa.WorkflowServer.Web/Program.cs, src/modules/Elsa.ProtoActor/Extensions/ClusterExtensions.cs, src/modules/Elsa.ProtoActor/Extensions/PersistenceExtensions.cs, src/modules/Elsa.ProtoActor/Grains/BookmarkGrain.cs, src/modules/Elsa.ProtoActor/Grains/RunningWorkflowsGrain.cs, src/modules/Elsa.ProtoActor/Grains/WorkflowGrain.cs, src/modules/Elsa.ProtoActor/Handlers/UpdateRunningWorkflowsHandler.cs, src/modules/Elsa.ProtoActor/Implementations/ProtoActorWorkflowRuntime.cs, src/modules/Elsa.ProtoActor/Protos/Messages.proto, src/modules/Elsa.ProtoActor/Snapshots.cs
=> Implement ProtoActor snapshot + event cleanup

src/designer/elsa-workflows-designer/src/modules/workflow-definitions/components/toolbox.tsx
=> Apply scroll overflow to activity picker

src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx
Fix for #3621 by waiting for a resize event with width and height > 0 before rendering.
=> Fix #3621 by waiting for a resize event with width and height > 0

src/designer/elsa-workflows-designer/package.json, src/modules/Elsa.Expressions/Implementations/WellKnownTypeRegistry.cs, src/modules/Elsa.Http/Activities/WriteHttpResponse.cs, src/modules/Elsa.JavaScript/Implementations/JintJavaScriptEvaluator.cs, src/modules/Elsa.JavaScript/Providers/CommonFunctionsDefinitionProvider.cs, src/modules/Elsa.Telnyx/Activities/Dial.cs, src/modules/Elsa.Telnyx/Activities/SpeakText.cs, src/modules/Elsa.Telnyx/Providers/WebhookEventActivityProvider.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Post/Endpoint.cs, src/modules/Elsa.Workflows.Core/Activities/While.cs, src/modules/Elsa.Workflows.Designer/package-lock.json, src/modules/Elsa.Workflows.Designer/package.json, src/modules/Elsa.Workflows.Management/Extensions/ActivityDescriberExtensions.cs, src/modules/Elsa.Workflows.Management/Implementations/ActivityDescriber.cs, src/modules/Elsa.Workflows.Management/Services/IActivityDescriber.cs
This PR adds bits of javascript and fixes a few annoying issues.
=> Tweaks and fixes

src/designer/bindings/aspnet/Elsa.Designer.Components.Web/WorkflowDashboard.razor, src/designer/elsa-workflows-studio/src/components/designers/x6-designer/x6-designer.tsx
Fixes #3675 and adds new params to WorkflowDashboard Blazor component.
=> Added missing params to WorkflowDashboard component, limited model change handler

src/activities/Elsa.Activities.Kafka/Services/WorkerManager.cs
Elsa server crashes if a trigger of type KafkaMessageReceived is defined without a topic or connection string.
---
Only create a worker instance if the persisted trigger has defined a connection string and a topic.
=> Kafka: ELSA Startup Crash

src/activities/Elsa.Activities.Kafka/Extensions/ServiceCollectionExtensions.cs, src/activities/Elsa.Activities.Kafka/Services/DefaultKafkaTenantIdResolver.cs, src/activities/Elsa.Activities.Kafka/Services/IKafkaTenantIdResolver.cs, src/activities/Elsa.Activities.Kafka/Services/Worker.cs
(feat: #3671 ) Implemented default kafka tenant TenantIdResolver analog to feat: #3667
=> Feature: Kafka TenantIdResolver

src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx
WIP to enhance performance of Elsa 2 designer by reducing the number of required renders to be limited to updates in the workflow model (adding/removing/updating) activities only.
=> Designer Performance Enhancement

src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/Configurations.cs, src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs, src/modules/Elsa.Workflows.Core/Implementations/WorkflowStateSerializer.cs, src/modules/Elsa.Workflows.Core/Models/InputDescriptor.cs, src/modules/Elsa.Workflows.Core/Models/PropertyDescriptor.cs, src/modules/Elsa.Workflows.Core/Models/WorkflowExecutionContext.cs, src/modules/Elsa.Workflows.Core/State/WorkflowState.cs, src/modules/Elsa.Workflows.Management/Activities/SetWorkflowOutput.cs, src/modules/Elsa.Workflows.Management/Activities/WorkflowDefinitionActivity.cs, src/modules/Elsa.Workflows.Management/Extensions/ActivityExecutionContextExtensions.cs, src/modules/Elsa.Workflows.Management/Features/WorkflowManagementFeature.cs, src/modules/Elsa.Workflows.Management/Providers/WorkflowDefinitionActivityProvider.cs, src/modules/Elsa.Workflows.Management/Serialization/Converters/ActivityJsonConverter.cs, src/modules/Elsa.Workflows.Runtime/Activities/DispatchWorkflow.cs, src/modules/Elsa.Workflows.Runtime/Handlers/ResumeDispatchWorkflowActivityHandler.cs
This PR adds the ability for child workflows to produce output. This works for both child workflows invoked as activities as well as separate child workflow instances.
=> Workflow input/output

src/activities/Elsa.Activities.Kafka/Services/Client.cs
Kafka headers were not added to ConsumerConfig. Headers Implemented.
=> Adding Kafka headers to ConsumerConfig.

configureawait.props, src/bundles/Elsa.WorkflowServer.Web/Elsa.WorkflowServer.Web.csproj, src/common/Elsa.Api.Common/Elsa.Api.Common.csproj, src/modules/Elsa.AzureServiceBus/Elsa.AzureServiceBus.csproj, src/modules/Elsa.Elasticsearch/Elsa.Elasticsearch.csproj, src/modules/Elsa.Email/Elsa.Email.csproj, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Elsa.EntityFrameworkCore.PostgreSql.csproj, src/modules/Elsa.EntityFrameworkCore.SqlServer/Elsa.EntityFrameworkCore.SqlServer.csproj, src/modules/Elsa.EntityFrameworkCore.Sqlite/Elsa.EntityFrameworkCore.Sqlite.csproj, src/modules/Elsa.EntityFrameworkCore/Elsa.EntityFrameworkCore.csproj, src/modules/Elsa.Hangfire/Elsa.Hangfire.csproj, src/modules/Elsa.Http/Elsa.Http.csproj, src/modules/Elsa.Labels/Endpoints/Labels/Get/Endpoint.cs, src/modules/Elsa.Labels/Endpoints/Labels/Get/Mappers.cs, src/modules/Elsa.Labels/Endpoints/Labels/Post/Endpoint.cs, src/modules/Elsa.Labels/Endpoints/Labels/Post/Mappers.cs, src/modules/Elsa.Labels/Endpoints/Labels/Update/Mappers.cs, src/modules/Elsa.Labels/Endpoints/Labels/Update/Update.cs, src/modules/Elsa.MassTransit/Elsa.MassTransit.csproj, src/modules/Elsa.ProtoActor.Cluster.AzureContainerApps/Elsa.ProtoActor.Cluster.AzureContainerApps.csproj, src/modules/Elsa.ProtoActor/Elsa.ProtoActor.csproj, src/modules/Elsa.Quartz/Elsa.Quartz.csproj, src/modules/Elsa.Webhooks/Elsa.Webhooks.csproj, src/modules/Elsa.Workflows.Api/Mappers/WorkflowDefinitionMapper.cs, src/modules/Elsa.Workflows.Designer/Elsa.Workflows.Designer.csproj, src/samples/aspnet/Elsa.Samples.TelnyxIntegration/Elsa.Samples.TelnyxIntegration.csproj, test/Elsa.IntegrationTests/Elsa.IntegrationTests.csproj, test/Elsa.UnitTests/Elsa.UnitTests.csproj
This PR updates all third-party NuGet package references to their current latest version.
=> Update NuGet package references

src/designer/elsa-workflows-designer/src/modules/flowchart/default-activity-template.tsx, src/designer/elsa-workflows-designer/src/modules/switch/switch-port-provider.ts, src/designer/elsa-workflows-designer/src/modules/workflow-definitions/components/toolbox-activities.tsx, src/designer/elsa-workflows-designer/src/services/activity-walker.ts, src/modules/Elsa.Telnyx/Activities/Dial.cs, src/modules/Elsa.Telnyx/Activities/GetCallStatus.cs, src/modules/Elsa.Telnyx/Client/Models/Requests.cs, src/modules/Elsa.Workflows.Core/Activities/Switch.cs
This PR adds a new property called "RecordFormat" to the Dial activity.
While testing the Switch activity, I ran into a bug with the ports not being displayed in the designer. It was such a small change that I included it here with this PR.
=> Update Dial activity and fix Switch

src/designer/elsa-workflows-designer/src/modules/flowchart/graph-factory.ts
and which activity do you focus on when you paste multiple)
=> do not select just pasted activities (because property panel connected)

src/modules/Elsa.Http/Middleware/WorkflowsMiddleware.cs
The workflow fault check and handling were done before the workflow execution. It was adjusted to be done after the execution.
=> Handle workflow fault after workflow execution

src/modules/Elsa.Workflows.Runtime/Contracts/ITriggerIndexer.cs, src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs, src/modules/Elsa.Workflows.Runtime/HostedServices/PopulateRouteTable.cs, src/modules/Elsa.Workflows.Runtime/Services/TriggerIndexer.cs
update routetable on startup especially nescesary for routes with variables
=> V3 update routetable on startup

src/designer/elsa-workflows-designer/src/models/core.ts, src/designer/elsa-workflows-designer/src/modules/workflow-definitions/components/workflow-properties/variables-viewer.tsx, src/designer/elsa-workflows-designer/src/modules/workflow-instances/components/journal.tsx, src/designer/elsa-workflows-designer/src/modules/workflow-instances/models.ts, src/designer/elsa-workflows-designer/src/services/activity-walker.ts, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Runtime/20230313133115_Initial.Designer.cs, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Runtime/20230313133115_Initial.cs, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Runtime/RuntimeElsaDbContextModelSnapshot.cs, src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Runtime/20230313133144_Initial.Designer.cs, src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Runtime/20230313133144_Initial.cs, src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Runtime/RuntimeElsaDbContextModelSnapshot.cs, src/modules/Elsa.EntityFrameworkCore.Sqlite/Migrations/Runtime/20230313133130_Initial.Designer.cs, src/modules/Elsa.EntityFrameworkCore.Sqlite/Migrations/Runtime/20230313133130_Initial.cs, src/modules/Elsa.EntityFrameworkCore.Sqlite/Migrations/Runtime/RuntimeElsaDbContextModelSnapshot.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/Journal/List/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/Journal/List/Models.cs, src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs, src/modules/Elsa.Workflows.Core/Models/WorkflowExecutionLogEntry.cs, src/modules/Elsa.Workflows.Runtime/Entities/WorkflowExecutionLogRecord.cs, src/modules/Elsa.Workflows.Runtime/Middleware/PersistWorkflowExecutionLogMiddleware.cs
This PR fixes a bug with the Journal where it would not find certain activities. It refactors the way activities are uniquely identified by taking advantage of the NodeId property of an activity graph node.
=> Fixes for Journal

configureawait.props
Fixes https://github.com/elsa-workflows/elsa-core/issues/3820
=> Fix Nuget symbol package validation

src/activities/Elsa.Activities.Kafka/Activities/KafkaMessageReceived/KafkaMessageReceived.cs, src/activities/Elsa.Activities.Kafka/Bookmarks/MessageReceivedBookmark.cs, src/activities/Elsa.Activities.Kafka/Bookmarks/OverrideKafkaBookmarkProvider.cs, src/activities/Elsa.Activities.Kafka/Elsa.Activities.Kafka.csproj, src/activities/Elsa.Activities.Kafka/Extensions/ServiceCollectionExtensions.cs, src/activities/Elsa.Activities.Kafka/Models/KafkaMessageEvent.cs, src/activities/Elsa.Activities.Kafka/Models/MessageReceivedInput.cs, src/activities/Elsa.Activities.Kafka/SchemaRegistry/AvroSchemaResolver.cs, src/activities/Elsa.Activities.Kafka/SchemaRegistry/DefaultSchemaResolver.cs, src/activities/Elsa.Activities.Kafka/SchemaRegistry/ESchemaRegistryTypes.cs, src/activities/Elsa.Activities.Kafka/SchemaRegistry/ISchemaResolver.cs, src/activities/Elsa.Activities.Kafka/Services/Client.cs, src/activities/Elsa.Activities.Kafka/Services/Worker.cs
Feature added to only trigger KafkaMessageReceived triggers based on a SchemaRegistry schema.
This feature is very important and urgent for us! Would be awesome to get a feedback as soon as possible!
#3661
=> Feature/schema registry  Trigger KafkaMessageReceived based on schemas #3661 

src/activities/Elsa.Activities.Kafka/Activities/KafkaMessageReceived/KafkaMessageReceived.cs, src/activities/Elsa.Activities.Kafka/Bookmarks/MessageReceivedBookmark.cs, src/activities/Elsa.Activities.Kafka/Bookmarks/OverrideKafkaBookmarkProvider.cs, src/activities/Elsa.Activities.Kafka/Configuration/KafkaConfiguration.cs, src/activities/Elsa.Activities.Kafka/Services/Worker.cs, src/activities/Elsa.Activities.Kafka/Services/WorkerManager.cs
Added a flag to indicate that the header comparison should be ignored for this specific trigger.  #3823
=> Bugfix/kafka Workaround

src/scripting/Elsa.Scripting.JavaScript/Handlers/ConfigureJavaScriptEngine.cs, src/scripting/Elsa.Scripting.JavaScript/Handlers/RenderJavaScriptDateTimeTypeDefinitions.cs
Add new function to support adding new entrys in Journal from JS in activities
=> Add journal entry from JS

src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-definitions/components/toolbox-activities.tsx
=> feat(toolbar-activities.tsx): Added Search for activities in the designer toolbar

.github/workflows/npm-packages.yml
This PR aims to add the packaging and publishing of Angular and React Wrapper.
=> add pack/publish actions to GitHub Actions

.github/workflows/npm-packages.yml, src/designer/designer_packages/angular-workspace/projects/component-library/package.json, src/designer/designer_packages/react-workspace/react-wrapper/package.json
fix package path to create artefacts.
Change wrapper package version to be in sync with designer version.
=> update package path and wrapper version

src/designer/designer_packages/elsa-workflows-designer/src/modules/flowchart/flowchart.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-instances/components/viewer.scss, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-instances/components/viewer.tsx
Contains fixes for:
#3843
#3844
#3136
=> Fixed workflow instances layout issues. Fixed context menu position.

src/designer/designer_packages/elsa-workflows-designer/src/components.d.ts, src/designer/designer_packages/elsa-workflows-designer/src/components/toolbar/workflow-toolbar-menu/workflow-toolbar-menu.tsx, src/designer/designer_packages/elsa-workflows-designer/src/components/toolbar/workflow-toolbar/workflow-toolbar.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/notifications/models.ts, src/designer/designer_packages/elsa-workflows-designer/src/modules/notifications/notification-manager.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/notifications/notification-service.ts, src/designer/designer_packages/elsa-workflows-designer/src/modules/notifications/notification-template.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/notifications/toast-manager.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/notifications/toast-notification.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-definitions/plugins/workflow-definitions-plugin.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-instances/plugin.tsx
Restyled notifications. Notifications are now hidden when opening the menu.
=> Added error handling messages. 

src/modules/Elsa.Workflows.Runtime/Activities/RunTask.cs
=> Update RunTask XML Comment

src/modules/Elsa.MassTransit/Consumers/DispatchWorkflowRequestConsumer.cs, src/modules/Elsa.MassTransit/Implementations/MassTransitWorkflowDispatcher.cs, src/modules/Elsa.MassTransit/Messages/DispatchWorkflowDefinition.cs, src/modules/Elsa.Scheduling/Activities/Cron.cs, src/modules/Elsa.Scheduling/Contracts/IBookmarkScheduler.cs, src/modules/Elsa.Scheduling/Features/SchedulingFeature.cs, src/modules/Elsa.Scheduling/HostedServices/CreateSchedulesHostedService.cs, src/modules/Elsa.Scheduling/Services/DefaultBookmarkScheduler.cs, src/modules/Elsa.Scheduling/Services/DefaultTriggerScheduler.cs, src/modules/Elsa.Workflows.Runtime/Contracts/IBookmarkStore.cs, src/modules/Elsa.Workflows.Runtime/Contracts/ITriggerStore.cs, src/modules/Elsa.Workflows.Runtime/Extensions/StoredBookmarkExtensions.cs, src/samples/aspnet/Elsa.Samples.WorkflowContexts/Entities/Order.cs, src/samples/aspnet/Elsa.Samples.WorkflowContexts/Program.cs, src/samples/aspnet/Elsa.Samples.WorkflowContexts/Providers/OrderWorkflowContextProvider.cs, src/samples/aspnet/Elsa.Samples.WorkflowContexts/Workflows/CustomerCommunicationsWorkflow.cs
Fixes the issues reported via #3924
=> Fix timer issues

src/core/Elsa.Core/Activities/ControlFlow/Join/Join.cs
In case of multiple join activities in the same workflow, receiving inbound transitions from the same activity (a fork, for example), some Join activities are not notified of all transitions and get stuck in an unescapable state.
This patch writes the inbound transitions in all the Join nodes found in the workflow, not only the first one found.
=> Fix inbound transitions tracking in Join activity

src/modules/Elsa.Http/Parsers/JsonHttpContentParser.cs
remove polymorphicobjectconverter for httpendpoint
=> remove polymorphicobjectconverter for http serialization

src/bundles/Elsa.AllInOne.Web/Program.cs, src/bundles/Elsa.AllInOne.Web/appsettings.json
=> Configure CORS policy

src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/FlowSwitch.cs, src/modules/Elsa.Workflows.Core/Activities/Switch.cs, src/modules/Elsa.Workflows.Core/Models/SwitchMode.cs
Added modes: match first and match any
This implementation is the same as in Elsa 2
=> Added modes to the switch activities

src/designer/designer_packages/elsa-workflows-designer/src/components.d.ts, src/modules/Elsa.Dapper.Migrations/Elsa.Dapper.Migrations.csproj, src/modules/Elsa.Dapper.Migrations/FodyWeavers.xml, src/modules/Elsa.Dapper.Migrations/Identity/Initial.cs, src/modules/Elsa.Dapper.Migrations/Management/Initial.cs, src/modules/Elsa.Dapper.Migrations/Readme.md, src/modules/Elsa.Dapper.Migrations/Runtime/Initial.cs, src/modules/Elsa.Dapper/Abstractions/SqlDialectBase.cs, src/modules/Elsa.Dapper/Contracts/ISqlDialect.cs, src/modules/Elsa.Dapper/Elsa.Dapper.csproj, src/modules/Elsa.Dapper/Extensions/ParameterizedQueryBuilderExtensions.cs, src/modules/Elsa.Dapper/Modules/Identity/Extensions/IdentityFeatureExtensions.cs, src/modules/Elsa.Dapper/Modules/Identity/Features/Feature.cs, src/modules/Elsa.Dapper/Modules/Identity/Records/ApplicationRecord.cs, src/modules/Elsa.Dapper/Modules/Identity/Records/RoleRecord.cs, src/modules/Elsa.Dapper/Modules/Identity/Records/UserRecord.cs, src/modules/Elsa.Dapper/Modules/Identity/Services/ApplicationStore.cs, src/modules/Elsa.Dapper/Modules/Identity/Services/RoleStore.cs, src/modules/Elsa.Dapper/Modules/Identity/Services/UserStore.cs, src/modules/Elsa.Dapper/Modules/Management/Extensions/DapperWorkflowManagementFeatureExtensions.cs, src/modules/Elsa.Dapper/Modules/Runtime/Extensions/DapperWorkflowManagementFeatureExtensions.cs, src/modules/Elsa.Dapper/Services/Store.cs, src/samples/aspnet/Elsa.Samples.AspNet.DapperPersistence/Program.cs
This PR adds a Dapper persistence provider for the Identity module.
=> Implement Dapper for Identity

src/modules/secrets/Elsa.Secrets/Providers/SecretNamesOptionsProvider.cs
Use Name given by user input rather than system name.
=> Correct SecretNamesOptionsProvider display name

src/designer/designer_packages/elsa-workflows-designer/src/components/panel/panel.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/flowchart/flowchart.scss, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-definitions/components/editor.scss, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-instances/components/viewer.scss, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-instances/components/viewer.tsx
Changed arrow direction on expanded panels.
=> Fixed spacing issue and panel display issue on workflow instances.

src/modules/Elsa.Workflows.Runtime/Activities/PublishEvent.cs
Improvements:
- Complete activity after the event was created
- Send input body
=> Publish event improvements

src/designer/designer_packages/elsa-workflows-designer/src/components/toolbar/workflow-toolbar-menu/workflow-toolbar-menu.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-instances/components/journal.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-instances/models.ts, src/modules/Elsa.Http/Middleware/WorkflowsMiddleware.cs, src/modules/Elsa.Workflows.Core/Middleware/Activities/ExecutionLogMiddleware.cs
=> Show suspended activities in journal

src/core/Elsa.Core/Handlers/WriteWorkflowSuspendExecutionLog.cs
Previous PR caused this build error: 
```
/home/runner/work/elsa-core/elsa-core/src/core/Elsa.Core/Handlers/WriteWorkflowSuspendExecutionLog.cs(9,56): error CS0246: The type or namespace name 'CancellationToken' could not be found (are you missing a using directive or an assembly reference?) [/home/runner/work/elsa-core/elsa-core/src/core/Elsa.Core/Elsa.Core.csproj]
/home/runner/work/elsa-core/elsa-core/src/core/Elsa.Core/Handlers/WriteWorkflowSuspendExecutionLog.cs(9,12): error CS0246: The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?) [/home/runner/work/elsa-core/elsa-core/src/core/Elsa.Core/Elsa.Core.csproj]
/home/runner/work/elsa-core/elsa-core/src/core/Elsa.Core/Handlers/WriteWorkflowSuspendExecutionLog.cs(7,49): error …
```
=> Fixing build

src/designer/elsa-workflows-studio/src/components.d.ts, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-definitions-list/elsa-studio-workflow-definitions-list.tsx, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-definitions-list/localizations.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-list/elsa-workflow-definitions-screen/elsa-workflow-definitions-list-screen.tsx, src/designer/elsa-workflows-studio/src/index.html, src/designer/elsa-workflows-studio/src/services/elsa-client.ts, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Backup.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/List.cs, src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Restore.cs
Allows backing up and restoring entire workflow definitions list. Upon restoring determines if workflow definition already exists, publishing a new version if it does and is published or creating a new one if it does not.
=> New workflow definitions backup/restore

src/activities/Elsa.Activities.Temporal.Hangfire/Elsa.Activities.Temporal.Hangfire.csproj, src/samples/server/Elsa.Samples.Server.Host/Elsa.Samples.Server.Host.csproj, src/samples/worker/Elsa.Samples.Timers.Hangfire/CronTaskWorkflow.cs, src/samples/worker/Elsa.Samples.Timers.Hangfire/Elsa.Samples.Timers.Hangfire.csproj, src/server/Elsa.Server.Hangfire/Elsa.Server.Hangfire.csproj, test/integration/Elsa.Core.IntegrationTests/Elsa.Core.IntegrationTests.csproj
Update Elsa to use hangfire v1.8. Possible fixes #4276.
=> Update hangfire to 1.8

src/clients/Elsa.Api.Client/Resources/WorkflowDefinitions/Contracts/IWorkflowDefinitionsApi.cs, src/clients/Elsa.Api.Client/Resources/WorkflowDefinitions/Requests/DispatchWorkflowDefinitionRequest.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Dispatch/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Dispatch/Models.cs
Added the ability to specify VersionOptions to DispatchEndpoint similar to ExecuteEndpoint. And also added a Dispatch call method to IWorkflowDefinitionsApi
=> V3 improve dispatch endpoint

src/modules/Elsa.Workflows.Core/Extensions/ExpressionExecutionContextExtensions.cs
This PR addresses an issue where child activities attempting to create variables with names already present in a parent scope would encounter failures. 
- Introduction of new methods to the `ExpressionExecutionContext` class.
- Refactoring of existing methods for enhanced readability and the addition of validation checks.
- Methods for creating dictionaries based on specific contexts (`WorkflowExecutionContext` and `ActivityExecutionContext`).
- Methods for accessing specific contexts and current activity input and variable values.
- A method (`CreateVariable`) for creating a variable within the context.
- Ensure parameter validation for each method.
- Break down longer methods into more concise and comprehensible ones.
- Update method names for better clarity on their functions.
=> Allow variable shadowing in child activity scopes

src/modules/Elsa.EntityFrameworkCore.Sqlite/Extensions/DbContextOptionsBuilderExtensions.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowDefinitionStore.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowInstanceStore.cs, src/modules/Elsa.Workflows.Management/Models/WorkflowDefinitionSummary.cs, src/modules/Elsa.Workflows.Management/Models/WorkflowInstanceSummary.cs
This PR fixes issue #4350 - thanks @rolandgriesser for reporting and sharing the solution!
=> Use mapping expression for correct EF core projections

src/modules/Elsa.Workflows.Runtime/Elsa.Workflows.Runtime.csproj
Reslove https://github.com/elsa-workflows/elsa-core/issues/4392
Elsa.Workflow.Runtime Implicitly Installed packages quantity decreased from 62 to 8.
=> replace DistributedLock package with DistributedLock.FileSystem

src/activities/Elsa.Activities.Http/Consumers/UpdateRouteTable.cs, src/activities/Elsa.Activities.Http/Middleware/HttpEndpointMiddleware.cs
fix 404 issue after published workflow from designer. Close #4308
=> fix issue 4308

src/activities/Elsa.Activities.Http/Activities/HttpEndpoint/HttpEndpoint.cs, src/activities/Elsa.Activities.Http/Contracts/IRouteTable.cs, src/activities/Elsa.Activities.Http/Extensions/RouteTableExtensions.cs, src/activities/Elsa.Activities.Http/Services/RouteTable.cs
#4415 
Fix issues described in issue using proposed solution
=> fix issues with double slashes

src/modules/Elsa.Workflows.Core/Helpers/ActivityTypeNameHelper.cs
=> make type name helper aware of generics

src/designer/designer_packages/elsa-workflows-designer/src/modules/flowchart/shapes.ts
=> bugfix using editor as standalone

src/modules/Elsa.Workflows.Core/Activities/For.cs, src/samples/console/Elsa.Samples.ConsoleApp.LoopingWorkflows/Workflows/ForWorkflow.cs, test/integration/Elsa.IntegrationTests/Activities/Break/Workflows/BreakForWorkflow.cs
Implements fix for issue #4496.
=> Corrected behaviour of 'For' activity.

src/designer/elsa-workflows-studio/src/components/controls/elsa-pager/localizations.ts, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-dashboard/localizations.ts, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-definitions-list/localizations.ts, src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-workflow-instances-list/localizations.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-properties-panel/localizations.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-publish-button/localizations.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-list/elsa-workflow-definitions-screen/elsa-workflow-definitions-list-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-list/elsa-workflow-definitions-screen/localizations.ts, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-list/elsa-workflow-instance-list-screen/elsa-workflow-instance-list-screen.tsx, src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-list/elsa-workflow-instance-list-screen/localizations.ts, src/designer/elsa-workflows-studio/src/components/shared/elsa-confirm-dialog/localizations.ts
lenguages (es-ES and pt-PT)  for elsa dashbaord
=> lenguages (es-ES and pt-PT)  for elsa dashbaord

src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-definitions/services/api.ts
=> bugfix publish workflow results in 415 response

src/activities/Elsa.Activities.BlobStorage/Activities/BlobExists.cs, src/activities/Elsa.Activities.BlobStorage/Activities/DeleteBlob.cs, src/activities/Elsa.Activities.BlobStorage/Activities/ReadBlob.cs, src/activities/Elsa.Activities.BlobStorage/Activities/WriteBlob.cs, src/activities/Elsa.Activities.BlobStorage/Elsa.Activities.BlobStorage.csproj, src/activities/webhooks/Elsa.Activities.Webhooks/Elsa.Activities.Webhooks.csproj, src/clients/Elsa.Client/Elsa.Client.csproj, src/core/Elsa.Abstractions/Elsa.Abstractions.csproj, src/core/Elsa.Core/Elsa.Core.csproj, src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs, src/core/Elsa.Core/Providers/WorkflowStorage/BlobStorageWorkflowStorageProvider.cs, src/core/Elsa.Core/Providers/WorkflowStorage/BlobStorageWorkflowStorageProviderOptions.cs, src/core/Elsa.Core/Providers/Workflows/BlobStorageWorkflowProvider.cs, src/samples/aspnet/Elsa.Samples.SignalApi/Startup.cs, src/samples/console/Elsa.Samples.FileBasedWorkflow/Program.cs, src/server/Elsa.Server.Api/Elsa.Server.Api.csproj
#4429 Consolidated Newtonsoft.Json for build issues
Added Netbox extensions previously imported via Storage.net
=> Update deprecated Storage.Net to FluentStorage

src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-definitions/components/browser.tsx, src/designer/designer_packages/elsa-workflows-designer/src/modules/workflow-instances/components/browser.tsx
Fixes issue #4576 by changing css classes.
=> fix issue 4576 text alignment

src/activities/Elsa.Activities.Kafka/Elsa.Activities.Kafka.csproj, src/activities/Elsa.Activities.Kafka/Models/MessageReceivedInput.cs, src/activities/Elsa.Activities.Kafka/Services/Worker.cs
Added serialized message headers to MessageReceivedInput --> WorkflowInput
=> Kafka: Added Serialized Headers to WorkflowInput

src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/DbContext.cs
Fixes problems of incorrect type of column for Oracle
=> V3 - Support for Oracle DB in Runtime Module

src/core/Elsa.Core/StartupTasks/ContinueRunningWorkflows.cs
This is needed to resolve concurrency problems, where another Engine Instance has changed the state of the resuming workflowinstance.
The state of the workflowinstance is updated after the lock on the workflowinstance has been acquired.
See discussion: [https://github.com/elsa-workflows/elsa-core/discussions/4546](https://github.com/elsa-workflows/elsa-core/discussions/4546)
=> Update WorkflowInstance state before resuming

src/activities/Elsa.Activities.RabbitMq/Activities/RabbitMqMessageReceived/RabbitMqMessageReceived.cs, src/activities/Elsa.Activities.RabbitMq/Activities/SendRabbitMqMessage/SendRabbitMqMessage.cs, src/activities/Elsa.Activities.RabbitMq/Bookmarks/MessageReceivedBookmark.cs, src/activities/Elsa.Activities.RabbitMq/Configuration/RabbitMqBusConfiguration.cs, src/activities/Elsa.Activities.RabbitMq/Services/Client.cs, src/activities/Elsa.Activities.RabbitMq/Services/RabbitMqQueueStarter.cs, src/activities/Elsa.Activities.RabbitMq/Services/Worker.cs, src/activities/Elsa.Activities.RabbitMq/Testing/RabbitMqTestQueueManager.cs
=> Adding amqps support to rabbit activities

src/activities/Elsa.Activities.Temporal.Common/Consumers/ScheduleTriggerConsumer.cs, src/activities/Elsa.Activities.Temporal.Common/Handlers/ScheduleTimers.cs, src/activities/Elsa.Activities.Temporal.Common/Services/IWorkflowDefinitionScheduler.cs, src/activities/Elsa.Activities.Temporal.Hangfire/Elsa.Activities.Temporal.Hangfire.csproj, src/activities/Elsa.Activities.Temporal.Hangfire/Jobs/RunHangfireWorkflowDefinitionJob.cs, src/activities/Elsa.Activities.Temporal.Hangfire/Services/HangfireWorkflowDefinitionScheduler.cs, src/activities/Elsa.Activities.Temporal.Hangfire/Services/HangfireWorkflowInstanceScheduler.cs, src/activities/Elsa.Activities.Temporal.Quartz/Services/QuartzWorkflowDefinitionScheduler.cs, src/core/Elsa.Abstractions/Extensions/CompositeActivityBlueprintExtensions.cs, src/samples/server/Elsa.Samples.Server.Host/Elsa.Samples.Server.Host.csproj, src/samples/worker/Elsa.Samples.Timers.Hangfire/Elsa.Samples.Timers.Hangfire.csproj, src/server/Elsa.Server.Hangfire/Dispatch/HangfireWorkflowDispatcher.cs, src/server/Elsa.Server.Hangfire/Elsa.Server.Hangfire.csproj, src/server/Elsa.Server.Hangfire/Jobs/CorrelatedWorkflowDefinitionJob.cs, src/server/Elsa.Server.Hangfire/Jobs/WorkflowDefinitionJob.cs, src/server/Elsa.Server.Hangfire/Jobs/WorkflowInstanceJob.cs, test/integration/Elsa.Core.IntegrationTests/Elsa.Core.IntegrationTests.csproj
* Updated hangfire to latest version.
* Applied job names for hangfire jobs.
=> Hangfire job names

src/modules/Elsa.Identity/Endpoints/Login/RequestValidator.cs
#4598 
Fix endpoint throwing NullRef. Exception by adding request validation.
!! please note that this PR should not close the issue, since client side validation should be implemented as well (see issue) !!
=> Add Input Validation for Elsa.Identity Login Endpoint

src/samples/aspnet/Elsa.Samples.AspNet.WorkflowContexts/Program.cs
PR to add activity execution log and exception handling to pipeline
It can be confusing for people who rely on the example to enable workflow context.
=> V3 - Add to sample activity execution log pipeline and exception handler pipeline

src/activities/Elsa.Activities.Mqtt/Activities/MqttMessage.cs, src/activities/Elsa.Activities.Mqtt/Activities/MqttMessageReceived/MqttMessageReceived.cs, src/activities/Elsa.Activities.Mqtt/Options/MqttClientOptions.cs, src/activities/Elsa.Activities.Mqtt/Services/BusClientFactory.cs, src/activities/Elsa.Activities.Mqtt/Services/IMqttClientWrapper.cs, src/activities/Elsa.Activities.Mqtt/Services/MqttClientWrapper.cs, src/activities/Elsa.Activities.Mqtt/Services/MqttTopicsStarter.cs, src/activities/Elsa.Activities.Mqtt/Services/Worker.cs
Elsa.Activities.Mqtt.Activities.MqttMessage substitute MQTTnet.MqttApplicationMessage problem of serialization
some classes bcome sealed for better performance.
=>  substitute MQTTnet.MqttApplicationMessage problem of serialization

src/modules/Elsa.Http/Activities/HttpEndpoint.cs, src/modules/Elsa.Http/Features/HttpFeature.cs, src/modules/Elsa.Http/Parsers/FormHttpContentParser.cs
Add Parser for Form data 'application/x-www-form-urlencoded'
=> Add Parser for Form data 'application/x-www-form-urlencoded'

src/modules/Elsa.MassTransit/Activities/PublishMessage.cs, src/modules/Elsa.MassTransit/Implementations/MassTransitActivityTypeProvider.cs
Fixed the Message input descriptor for dynamically provided MassTransit PublishMessage activities.
=> Refactor MassTransitActivityTypeProvider

src/modules/Elsa.Dapper/Services/SqlServerDbConnectionProvider.cs
=> Use correct dialect for SqlServerDbConnectionProvider

src/modules/Elsa.Scheduling/Services/DefaultTriggerScheduler.cs
This PR is the Bugfix for this Issue : https://github.com/elsa-workflows/elsa-core/issues/4907
Catching the exception currently preventing the server from starting successfully and logging a warning when a incorrect cron expression was added to the cron activity
=> Fix elsa-workflows/elsa-core#4907

Directory.Packages.props, src/modules/Elsa.Quartz.EntityFrameworkCore.MySql/Elsa.Quartz.EntityFrameworkCore.MySql.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.MySql/MySqlQuartzExtensions.cs, src/modules/Elsa.Quartz.EntityFrameworkCore.PostgreSql/Elsa.Quartz.EntityFrameworkCore.PostgreSql.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.SqlServer/Elsa.Quartz.EntityFrameworkCore.SqlServer.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.SqlServer/SqlServerQuartzExtensions.cs, src/modules/Elsa.Quartz.EntityFrameworkCore.Sqlite/Elsa.Quartz.EntityFrameworkCore.Sqlite.csproj
=> Update AppAny package version and fix MySql and SqlServer Quartz persistence

.github/workflows/packages.yml, src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs, src/modules/Elsa.Workflows.Core/Services/WorkflowRunner.cs, src/modules/Elsa.Workflows.Core/Services/WorkflowStateExtractor.cs
=> Fixed setting updated and finished date on workflow instance

src/modules/Elsa.Elasticsearch/Modules/Management/WorkflowInstanceStore.cs
following the issue i have opend, this is my fix suggestion
=> #4963 - elastic store workflowinstance search fix

src/modules/Elsa.EntityFrameworkCore.Common/Extensions/QueryableExtensions.cs
Temporarily reverted the bulk implementation due to it not working correctly with shadow properties in PostgreSQL #5046
=> Reverted bulk implementation

src/modules/Elsa.Http/Features/HttpFeature.cs, src/modules/Elsa.Http/Parsers/PlainTextHttpContentParser.cs
=> Added missing text parser for HTTP responses

Elsa.sln, src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowDefinitionStorePopulator.cs, test/unit/Elsa.Workflows.Runtime.UnitTests/Elsa.Workflows.Runtime.UnitTests.csproj, test/unit/Elsa.Workflows.Runtime.UnitTests/Services/DefaultWorkflowDefinitionStorePopulatorTests.cs, test/unit/Elsa.Workflows.Runtime.UnitTests/Usings.cs
=> Prevented overwriting of existing workflows

src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
=> Add configuration value accessor in JintJavaScriptEvaluator

src/modules/Elsa.MassTransit.AzureServiceBus/Features/AzureServiceBusFeature.cs, src/modules/Elsa.MassTransit.RabbitMq/Features/RabbitMqServiceBusFeature.cs, src/modules/Elsa.MassTransit/Features/MassTransitFeature.cs
=> Prevented creation of default queues for temporary consumers

src/modules/Elsa.Workflows.Core/Services/ActivityRegistry.cs, src/modules/Elsa.Workflows.Runtime/Services/WorkflowCancellationService.cs
When MassTransit is enabled the delay with processing the distributed workflow definition messages could result in accessing the ActivityDescriptor dictionary while it is being updated.
=> Fix concurrency issues with distributed messages

Directory.Packages.props, src/modules/Elsa.Common/Elsa.Common.csproj, src/modules/Elsa.Telnyx/Elsa.Telnyx.csproj, src/modules/Elsa.Workflows.Core/Elsa.Workflows.Core.csproj
This change reduces the dependencies for the newer framework by now leveraging libraries provided as part of the framework.
Closes #5106
=> #5106 Cleanup packages to leverage framework

Directory.Packages.props, samples/aspnet/Elsa.Samples.AspNet.QuartzIntegration/Elsa.Samples.AspNet.QuartzIntegration.csproj, samples/drop-ins/SampleDropIn/SampleDropIn.csproj, src/Directory.Build.props
This PR marks the JetBrains.Annotations package with PrivateAssets=All.
Fixes #5108
=> Make JetBrains.Annotations Private

src/modules/Elsa.MassTransit.AzureServiceBus/Features/AzureServiceBusFeature.cs, src/modules/Elsa.MassTransit.RabbitMq/Features/RabbitMqServiceBusFeature.cs, src/modules/Elsa.MassTransit/Features/MassTransitFeature.cs, src/modules/Elsa.MassTransit/Features/MassTransitWorkflowDispatcherFeature.cs
- Configured MassTransitWorkflowCancellationDispatcher
- Fixed RabbitMQ endpoint configuration
- Fixed consumer configuration when running InMemory
Fixes #5153
=> Fixed per instance distributed messaging

src/bundles/Elsa.ServerAndStudio.Web/Program.cs, src/bundles/Elsa.ServerAndStudio.Web/appsettings.json, src/modules/Elsa.MassTransit.AzureServiceBus/Features/AzureServiceBusFeature.cs, src/modules/Elsa.MassTransit.RabbitMq/Features/RabbitMqServiceBusFeature.cs, src/modules/Elsa.MassTransit/Features/MassTransitFeature.cs, src/modules/Elsa.MassTransit/Options/MassTransitOptions.cs, src/modules/Elsa.MassTransit/Options/MassTransitWorkflowDispatcherOptions.cs
- Exposes MassTransit setting for increasing throughput
- Fix auto deletion of temporary queues and exchanges in Rabbit MQ
Fixes #5171
=> Add settings for MassTransit message handling

src/bundles/Elsa.ServerAndStudio.Web/Program.cs, src/modules/Elsa.MassTransit/Consumers/WorkflowDefinitionEventsConsumer.cs, src/modules/Elsa.Workflows.Management/Contracts/IActivityRegistryPopulator.cs, src/modules/Elsa.Workflows.Management/Handlers/RefreshActivityRegistryHandler.cs, src/modules/Elsa.Workflows.Management/Services/ActivityRegistryPopulator.cs
Instead of repopulation the entire ActivityRegistry, only add the new workflow definition.
=> Changed behaviour on publishing workflows

src/modules/Elsa.JavaScript/Features/JavaScriptFeature.cs, src/modules/Elsa.JavaScript/Options/JintOptions.cs, src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
This PR implements parsed JavaScript expressions for improved performance when executing workflows multiple times.
Fixes #5272
=> Cache JavaScript Expressions

src/modules/Elsa.Alterations/Activities/CompleteAlterationPlan.cs, src/modules/Elsa.Alterations/Activities/DispatchAlterationJobs.cs, src/modules/Elsa.Alterations/Activities/GenerateAlterationJobs.cs, src/modules/Elsa.Alterations/Constants/AlterationFaultCategories.cs, src/modules/Elsa.Alterations/Constants/AlterationFaultCodes.cs, src/modules/Elsa.Alterations/Elsa.Alterations.csproj.DotSettings, src/modules/Elsa.Http/Activities/WriteFileHttpResponse.cs, src/modules/Elsa.Http/Activities/WriteHttpResponse.cs, src/modules/Elsa.Http/Constants/HttpFaultCategories.cs, src/modules/Elsa.Http/Constants/HttpFaultCodes.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Dispatch/Endpoint.cs, src/modules/Elsa.Workflows.Core/Activities/Fault.cs, src/modules/Elsa.Workflows.Core/Constants/DefaultFaultKinds.cs, src/modules/Elsa.Workflows.Core/Constants/DefaultFaultTypes.cs, src/modules/Elsa.Workflows.Core/Elsa.Workflows.Core.csproj.DotSettings, src/modules/Elsa.Workflows.Core/Exceptions/FaultException.cs, src/modules/Elsa.Workflows.Runtime/Activities/BulkDispatchWorkflows.cs, src/modules/Elsa.Workflows.Runtime/Activities/DispatchWorkflow.cs, src/modules/Elsa.Workflows.Runtime/Constants/RuntimeFaultCategories.cs, src/modules/Elsa.Workflows.Runtime/Constants/RuntimeFaultCodes.cs, src/modules/Elsa.Workflows.Runtime/Elsa.Workflows.Runtime.csproj.DotSettings, src/modules/Elsa.Workflows.Runtime/Responses/DispatchWorkflowDefinitionResponse.cs, test/integration/Elsa.Workflows.IntegrationTests/Scenarios/Incidents/Workflows/FaultyWorkflow.cs
=> Add Fault Code, Category and Type

Directory.Packages.props
Updated Npgsql package to fix vulnerability
=> Update Npgsql versions

Directory.Packages.props, src/bundles/Elsa.Server.Web/Elsa.Server.Web.csproj, src/modules/Elsa.Dapper/Elsa.Dapper.csproj, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Elsa.EntityFrameworkCore.PostgreSql.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.PostgreSql/Elsa.Quartz.EntityFrameworkCore.PostgreSql.csproj
Override versions used of Npgsql to ensure usage of versions without known vulnerability
=> Update Npgsql package versions

src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowDefinitionStore.cs
The update involves optimizing the WorkflowDefinitionStore logic. The minor change is that it removed an unneeded space in the CountDistinctAsync method. More importantly, an upgrade issue with 'IsSystem' from older versions of Elsa to 3.2 has been rectified by adding checks and conditions to suit legacy versions. In the future, once all systems are updated, this check can be removed.
Fixes #5366 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5462)
=> Update and optimize WorkflowDefinitionStore logic

src/activities/Elsa.Activities.Mqtt/Activities/SendMqttMessage/SendMqttMessage.cs
This change enables end-users via the designer to send an MQTT message using JSON, or JavaScript or Liquid templating.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5461)
=> Support JavaScript and Liquid when sending MQTT messages

Directory.Packages.props, src/modules/Elsa.Workflows.Management/Services/WorkflowDefinitionPublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5598)
=> Extended check when to update dependent workflows

build/_build.csproj, src/modules/Elsa.Dapper/Elsa.Dapper.csproj, src/modules/Elsa.EntityFrameworkCore.SqlServer/Elsa.EntityFrameworkCore.SqlServer.csproj, src/modules/Elsa.MassTransit.AzureServiceBus/Elsa.MassTransit.AzureServiceBus.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.SqlServer/Elsa.Quartz.EntityFrameworkCore.SqlServer.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5605)
=> Forced package upgrade due to vulnerability

src/modules/Elsa.Quartz.EntityFrameworkCore.MySql/MySqlQuartzExtensions.cs, src/modules/Elsa.Quartz.EntityFrameworkCore.PostgreSql/PostgreSqlQuartzExtensions.cs, src/modules/Elsa.Quartz.EntityFrameworkCore.SqlServer/SqlServerQuartzExtensions.cs, src/modules/Elsa.Quartz.EntityFrameworkCore.Sqlite/SqliteQuartzExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5625)
=> Allow user to use DbContext pooling with Quartz

src/bundles/Elsa.ServerAndStudio.Web/Elsa.ServerAndStudio.Web.csproj, src/bundles/Elsa.ServerAndStudio.Web/Program.cs, src/bundles/Elsa.ServerAndStudio.Web/appsettings.json, src/modules/Elsa.EntityFrameworkCore.MySql/DbContextOptionsBuilder.cs, src/modules/Elsa.EntityFrameworkCore.MySql/Features.cs
fixes #5633 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5621)
=> Use auto detect of mySQL version

src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/TriggerStore.cs
As mentionned, a quick bugfix to add the missing "TenantAgnostic" flag in TriggerStore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5689)
=> fix(multitenancy): add missing TenantAgnostic flag to trigger store

src/modules/Elsa.Expressions/Options/ExpressionOptions.cs, src/modules/Elsa.Http/Features/HttpFeature.cs, test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JArrayIsland.json, test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JArrayWithoutType.json, test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JObjectIsland.json, test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JObjectWithoutType.json, test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JsonArrayIsland.json, test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JsonObjectIsland.json, test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JsonObjectWithoutType.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5743)
=> Added aliases for all missing types used in UI

src/bundles/Elsa.Server.Web/Enums/ApplicationRole.cs, src/clients/Elsa.Api.Client/Resources/WorkflowInstances/Contracts/IWorkflowInstancesApi.cs, src/clients/Elsa.Api.Client/Resources/WorkflowInstances/Models/HasJournalUpdateRequest.cs, src/common/Elsa.Api.Common/Extensions/WebApplicationExtensions.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/Journal/HasUpdates/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/Journal/HasUpdates/Models.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5751)
=> Added endpoint to poll for journal updates

Directory.Packages.props, src/bundles/Elsa.Server.Web/Elsa.Server.Web.csproj, src/bundles/Elsa.ServerAndStudio.Web/Elsa.ServerAndStudio.Web.csproj, src/bundles/Elsa.Studio.Web/Elsa.Studio.Web.csproj, src/clients/Elsa.Api.Client/Elsa.Api.Client.csproj, src/modules/Elsa.EntityFrameworkCore.Common/Elsa.EntityFrameworkCore.Common.csproj, src/modules/Elsa.EntityFrameworkCore.MySql/Elsa.EntityFrameworkCore.MySql.csproj, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Elsa.EntityFrameworkCore.PostgreSql.csproj, src/modules/Elsa.EntityFrameworkCore.SqlServer/Elsa.EntityFrameworkCore.SqlServer.csproj, src/modules/Elsa.EntityFrameworkCore.Sqlite/Elsa.EntityFrameworkCore.Sqlite.csproj, src/modules/Elsa.EntityFrameworkCore/Elsa.EntityFrameworkCore.csproj, src/modules/Elsa.FileStorage/Elsa.FileStorage.csproj, src/modules/Elsa.Http/Elsa.Http.csproj, src/modules/Elsa.MongoDb/Elsa.MongoDb.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.MySql/Elsa.Quartz.EntityFrameworkCore.MySql.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.PostgreSql/Elsa.Quartz.EntityFrameworkCore.PostgreSql.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.SqlServer/Elsa.Quartz.EntityFrameworkCore.SqlServer.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.Sqlite/Elsa.Quartz.EntityFrameworkCore.Sqlite.csproj, src/modules/Elsa.Telnyx/Elsa.Telnyx.csproj, src/modules/Elsa.WorkflowProviders.BlobStorage/Elsa.WorkflowProviders.BlobStorage.csproj, src/modules/Elsa.Workflows.Api/Elsa.Workflows.Api.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5777)
=> Overwritten System.Text.Json version due to vulnerability

src/clients/Elsa.Api.Client/Extensions/PropertyBagExtensions.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Post/Endpoint.cs, src/modules/Elsa.Workflows.Management/Services/WorkflowDefinitionImporter.cs
Those changes are required to fix handling in the studio. Studio also needs a fix to copy the property bag while sending the request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5778)
=> bugfixing issues related to new PropertyBag in workflow definition

src/modules/Elsa.WorkflowContexts/Extensions/ActivityExtensions.cs, src/modules/Elsa.WorkflowContexts/Extensions/WorkflowExtensions.cs, src/modules/Elsa.WorkflowContexts/Middleware/WorkflowContextWorkflowExecutionMiddleware.cs
PropertyBag changes caused few more issues which should be resolved with this PR.
I couldn't find a quick way to inject the type converter in the extension methods for activity and workflow. Please review and let me know if this approach is acceptable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5802)
=> fix workflow context execution middleware and script completion

src/modules/Elsa.MongoDb/Features/MongoDbFeature.cs
Ported MongoDB class map registration fix from #5870 to 3.2.x
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5877)
=> Change MongoDB classmap registration for SerializedKeyValuePair

src/modules/Elsa.EntityFrameworkCore.PostgreSql/Features.cs, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Handlers/DbExceptionTransformer.cs, src/modules/Elsa.EntityFrameworkCore/Handlers/RethrowDbExceptionHandler.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Alterations/Feature.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Identity/Feature.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Labels/Feature.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowDefinitionPersistenceFeature.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowInstancePersistenceFeature.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowManagementPersistenceFeature.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/WorkflowRuntimePersistenceFeature.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5894)
=> rename DbExceptionHandlers to better reflect their intent.

src/modules/Elsa.Http/Activities/SendHttpRequestBase.cs, src/modules/Elsa.Http/Parsers/FileHttpContentParser.cs
This pull request Address the Issue: [5928](https://github.com/elsa-workflows/elsa-core/issues/5928).
Looking forward for the review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5930)
=> Fix NullReferenceException when parsing the HttpResponse in the SendHttpRequestbase

src/modules/Elsa.Workflows.Runtime/Activities/Event.cs
Resolves issue #5933
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5934)
=> Set event payload when event bookmark resumes

src/bundles/Elsa.Server.Web/Activities/CompositeExample.cs, src/bundles/Elsa.Server.Web/Elsa.Server.Web.csproj, src/bundles/Elsa.Server.Web/Program.cs, src/bundles/Elsa.Server.Web/appsettings.json, src/modules/Elsa.AzureServiceBus/Features/AzureServiceBusFeature.cs, src/modules/Elsa.AzureServiceBus/HostedServices/CreateQueuesTopicsAndSubscriptions.cs, src/modules/Elsa.AzureServiceBus/HostedServices/StartWorkers.cs, src/modules/Elsa.AzureServiceBus/Services/Worker.cs, src/modules/Elsa.Workflows.Core/Activities/Composite.cs, src/modules/Elsa.Workflows.Core/Contracts/IComposite.cs, src/modules/Elsa.Workflows.Core/Services/ActivityFactory.cs
This PR fixes several DI issues that would occur when the module is enabled, which rendered the module completely broken. This is now fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5975)
=> Fix Azure Service Bus module DI issues 

src/clients/Elsa.Api.Client/Resources/ActivityExecutions/Contracts/IActivityExecutionsApi.cs, src/clients/Elsa.Api.Client/Resources/ActivityExecutions/Models/ActivityExecutionRecordSummary.cs, src/modules/Elsa.Workflows.Api/Endpoints/ActivityExecutionSummaries/ListSummaries/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/ActivityExecutionSummaries/ListSummaries/Models.cs, src/modules/Elsa.Workflows.Api/Endpoints/ActivityExecutions/Get/Endpoint.cs
Created new classes and endpoints to handle activity execution records and summaries retrieval. Added related models and updated relevant interfaces.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6018)
=> Add endpoints for activity execution records and summaries

src/modules/Elsa.MongoDb/Features/MongoDbFeature.cs
This PR changes the DI registration of `IMongoDatabase`. In the existing implementation, `IMongoDatabase` is registered as scoped, and the factory method creates a new instance of `MongoClient` each time `IMongoDatabase` is resolved.
According to the MongoDB documentation ([here](https://www.mongodb.com/docs/drivers/csharp/current/faq/#how-does-connection-pooling-work-in-the-.net-c--driver-) and [here](https://www.mongodb.com/community/forums/t/best-practice-for-singleton-vs-multiple-mongoclients-when-you-need-to-authenticate-with-different-users/125935/2)), the `MongoClient` is meant to be used as a singleton, because it maintains a pool of connections to the MongoDB server.
In this PR, I registered an instance of `IMongoClient` as singleton, and then resolved that instance from the …
=> Register MongoDb client as singleton

src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Export/Endpoint.cs, src/modules/Elsa.Workflows.Core/Serialization/Configurators/AdditionalConvertersConfigurator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6056)
=> Include $schema when exporting workflow definition

src/apps/Elsa.Server.Web/Program.cs, src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs, src/modules/Elsa.JavaScript/TypeDefinitions/Services/TypeDefinitionDocumentRenderer.cs, src/modules/Elsa.Secrets.Management/Notifications/SecretExpired.cs, src/modules/Elsa.Secrets.Management/Services/DefaultExpiredSecretsUpdater.cs, src/modules/Elsa.Secrets.Management/Services/DefaultSecretNameGenerator.cs, src/modules/Elsa.Secrets.Scripting/JavaScript/ConfigureEngineWithSecrets.cs, src/modules/Elsa.Secrets.Scripting/JavaScript/SecretsTypeDefinitionProvider.cs
This PR refactors accessing secrets via JS expressions by resolving the secret as-needed, which includes validating whether the secret is active or not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6070)
=> Refactor JS expressions for accessing secrets

src/modules/Elsa.Http/ContentWriters/FormUrlEncodedHttpContentFactory.cs
Updated the GetContentAsDictionary method to handle different types of content more gracefully. Changed the type from Dictionary to IDictionary to increase compatibility. Adjusted content serialization to accommodate varying input formats reliably.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6074)
=> Refactor FormUrlEncodedHttpContentFactory for better flexibility

src/modules/Elsa.MassTransit/Consumers/DispatchCancelWorkflowsRequestConsumer.cs, src/modules/Elsa.Workflows.Runtime/Contracts/IWorkflowCancellationService.cs, src/modules/Elsa.Workflows.Runtime/Notifications/WorkflowCancelled.cs, src/modules/Elsa.Workflows.Runtime/Notifications/WorkflowCancelling.cs, src/modules/Elsa.Workflows.Runtime/Services/WorkflowCanceler.cs, src/modules/Elsa.Workflows.Runtime/Services/WorkflowCancellationService.cs
Introduced WorkflowCancelled and WorkflowCancelling notification records. Changed cancellation service to return a boolean instead of an integer. Integrated mediator notifications in the workflow canceler service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6075)
=> Add workflow cancellation notifications

src/clients/Elsa.Api.Client/Resources/Tasks/Contracts/ITasksApi.cs, src/clients/Elsa.Api.Client/Resources/Tasks/Requests/ReportTaskCompletedRequest.cs
fixes refit contract for ITasksApi in Elsa.Api.Client
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6102)
=> fix: fix ITasksApi refit contract in Elsa.Api.Client

src/modules/Elsa.Workflows.Core/Builders/WorkflowBuilder.cs, src/modules/Elsa.Workflows.Core/Contracts/IWorkflowBuilder.cs, src/modules/Elsa.Workflows.Runtime/Activities/ExecuteWorkflow.cs, src/modules/Elsa.Workflows.Runtime/Models/ExecuteWorkflowResult.cs, test/component/Elsa.Workflows.ComponentTests/Scenarios/ExecuteWorkflows/ExecuteWorkflowsTests.cs, test/component/Elsa.Workflows.ComponentTests/Scenarios/ExecuteWorkflows/Workflows/MainWorkflow.cs, test/component/Elsa.Workflows.ComponentTests/Scenarios/ExecuteWorkflows/Workflows/SubroutineWorkflow.cs
Introduced a new `ExecuteWorkflow` activity that allows executing nested workflows. Added `ExecuteWorkflowResult` model to handle results and integrated component tests to verify nested workflow execution. Enhanced `IWorkflowBuilder` to support fluent methods for adding outputs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6137)
=> Add functionality to execute nested workflows

src/modules/Elsa.Http/Services/DefaultHttpEndpointBasePathProvider.cs, src/modules/Elsa.Http/UIHints/HttpEndpointPathUIHandler.cs
Updated the URL trimming logic to ensure consistent handling of base URLs and paths, removing trailing slashes where necessary. This change improves the consistency and reliability of URL generation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6141)
=> Refactor URL trimming logic in HTTP endpoint handlers

src/modules/Elsa.ProtoActor.Core/Constants.cs, src/modules/Elsa.ProtoActor.Core/Features/ProtoActorFeature.cs, src/modules/Elsa.ProtoActor.Core/HeaderNames.cs, src/modules/Elsa.ProtoActor.Core/Middleware/TenantScopeMiddleware.cs, src/modules/Elsa.Workflows.Runtime.ProtoActor/Services/ProtoActorWorkflowClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6142)
=> Fix Tenant ID propagation for Proto.Actor runtime

src/apps/Elsa.Server.Web/Program.cs, src/modules/Elsa.Workflows.Runtime/Activities/ExecuteWorkflow.cs, src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs, src/modules/Elsa.Workflows.Runtime/Handlers/ResumeExecuteWorkflowActivity.cs, src/modules/Elsa.Workflows.Runtime/Options/BookmarkQueuePurgeOptions.cs, src/modules/Elsa.Workflows.Runtime/Services/DefaultBookmarkQueuePurger.cs, src/modules/Elsa.Workflows.Runtime/Stimuli/ExecuteWorkflowStimulus.cs
Introduce BookmarkQueuePurgeOptions and ExecuteWorkflowStimulus classes for managing workflow queue purging and stimulus handling. Implement related handler and activity modifications to support waiting for child workflows and purging old bookmark queue entries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6153)
=> ExecuteWorkflow Activity: Add Wait For Completion option 

src/clients/Elsa.Api.Client/Shared/Enums/LogPersistenceEvaluationMode.cs, src/clients/Elsa.Api.Client/Shared/Models/LogPersistenceConfiguration.cs, src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithCommonTypes.cs, src/modules/Elsa.JavaScript/Providers/VariableTypeDefinitionProvider.cs, src/modules/Elsa.JavaScript/Services/TypeAliasRegistry.cs, src/modules/Elsa.JavaScript/TypeDefinitions/Services/TypeDefinitionDocumentRenderer.cs, src/modules/Elsa.JavaScript/TypeDefinitions/Services/TypeDescriber.cs, src/modules/Elsa.Workflows.Core/Extensions/DictionaryExtensions.cs, src/modules/Elsa.Workflows.Management/Features/WorkflowManagementFeature.cs, src/modules/Elsa.Workflows.Runtime/Elsa.Workflows.Runtime.csproj.DotSettings, src/modules/Elsa.Workflows.Runtime/Enums/LogPersistenceEvaluationMode.cs, src/modules/Elsa.Workflows.Runtime/Models/LogPersistenceConfiguration.cs, src/modules/Elsa.Workflows.Runtime/Services/DefaultActivityExecutionMapper.cs
This PR adds support for dynamic expression evaluation to determine the Log Persistence Mode for activity inputs and outputs. This enhancement allows greater flexibility by enabling the persistence mode to be evaluated dynamically based on runtime conditions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6159)
=> Implement Dynamic Expression Evaluation for Log Persistence Mode

src/modules/Elsa.Http/Middleware/HttpWorkflowsMiddleware.cs, src/modules/Elsa.Http/Services/RouteMatcher.cs, test/component/Elsa.Workflows.ComponentTests/Scenarios/HttpWorkflows/RouteDataTests.cs, test/component/Elsa.Workflows.ComponentTests/Scenarios/HttpWorkflows/Workflows/RouteDataWorkflow.cs
This PR fixes route data handling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6176)
=> Fix route data handling

src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithVariables.cs, test/component/Elsa.Workflows.ComponentTests/Elsa.Workflows.ComponentTests.csproj, test/component/Elsa.Workflows.ComponentTests/Scenarios/InputOutput/InputOutputTests.cs, test/component/Elsa.Workflows.ComponentTests/Scenarios/InputOutput/Workflows/consumer.json, test/component/Elsa.Workflows.ComponentTests/Scenarios/InputOutput/Workflows/provider.json
This fixes an issue where inputs would be declared as new variables, causing a "miss" when trying to read the input.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6178)
=> Add synthetic properties to JS engine for exclusion

.github/workflows/packages.yml, src/apps/Elsa.Server.Web/Program.cs, src/modules/Elsa.Workflows.Runtime.Distributed/Services/DistributedBookmarkQueueWorker.cs, src/modules/Elsa.Workflows.Runtime/Contracts/IBookmarkQueueSignaler.cs, src/modules/Elsa.Workflows.Runtime/Elsa.Workflows.Runtime.csproj, src/modules/Elsa.Workflows.Runtime/Extensions/RateLimitedFuncExtensions.cs, src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs, src/modules/Elsa.Workflows.Runtime/Handlers/SignalBookmarkQueueWorker.cs, src/modules/Elsa.Workflows.Runtime/Services/BookmarkQueueProcessor.cs, src/modules/Elsa.Workflows.Runtime/Services/BookmarkQueueSignaler.cs, src/modules/Elsa.Workflows.Runtime/Services/BookmarkQueueWorker.cs, src/modules/Elsa.Workflows.Runtime/Services/StoreBookmarkQueue.cs, src/modules/Elsa.Workflows.Runtime/Tasks/TriggerBookmarkQueueRecurringTask.cs
Introduce rate-limited function invocation for bookmark queue processing using ThrottleDebounce library to optimize performance. Update related classes and interfaces to support asynchronous and cancellation-aware operations, improving system responsiveness. Adjust logging to provide more detailed information during bookmark queue handling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6187)
=> Fix race condition and add rate limiting to bookmark queue processing

src/modules/Elsa.Workflows.Runtime/Services/BackgroundActivityInvoker.cs
Added a call to save workflow variables in the BackgroundActivityInvoker to ensure that any changes are persisted during background activity execution. This helps maintain consistency and state integrity across workflow invocations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6195)
=> Persist workflow variables during background execution.

src/modules/Elsa.CSharp/Services/CSharpEvaluator.cs
Compilation of the Script wasn't entirely thread safe, specifically, if the same script was being evaluated twice at the same time on an empty cache:
Thread 1: Puts Script<T> into cache, then starts compiling it
Thread 2: Finds not yet compiled Script<T> in cache, starts compiling it as well
Thread 1: Done compiling, Assembly.Load it for running
Thread 2: Done compiling, Assembly.Load it <--- Exception: Assembly with name XYZ already loaded
The Solution is to use CreateDelegate which compiles the script the moment it is being put into the cache and the cache then only serves precompiled delegates that are immediately runnable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflo …
=> Fix C# Script<T> race conditino

src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/Variables/List/Endpoint.cs, src/modules/Elsa.Workflows.Core/Contracts/IStorageDriver.cs, src/modules/Elsa.Workflows.Core/Contracts/IVariablePersistenceManager.cs, src/modules/Elsa.Workflows.Core/Contracts/IWorkflowInstanceVariableReader.cs, src/modules/Elsa.Workflows.Core/Enums/StorageDriverTag.cs, src/modules/Elsa.Workflows.Core/Services/DefaultWorkflowInstanceVariableReader.cs, src/modules/Elsa.Workflows.Core/Services/MemoryStorageDriver.cs, src/modules/Elsa.Workflows.Core/Services/VariablePersistenceManager.cs, src/modules/Elsa.Workflows.Core/VariableStorageDrivers/WorkflowInstanceStorageDriver.cs, src/modules/Elsa.Workflows.Core/VariableStorageDrivers/WorkflowStorageDriver.cs, src/modules/Elsa.Workflows.Management/Contracts/IWorkflowInstanceVariableManager.cs, src/modules/Elsa.Workflows.Management/Services/WorkflowInstanceVariableManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6201)
=> Introduce the possibility to exclude variable value retrieval for certain storage drivers

src/modules/Elsa.Workflows.Core/Services/VariablePersistenceManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6204)
=> Fixed variable value retrieval

src/modules/Elsa.Workflows.Runtime/Services/BackgroundActivityInvoker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6209)
=> Fixed issues where the outputs of a background activity will not be mapped

src/modules/Elsa.Expressions/Helpers/ObjectConverter.cs, src/modules/Elsa.Workflows.Core/Contexts/StorageDriverContext.cs, src/modules/Elsa.Workflows.Core/Services/VariablePersistenceManager.cs, src/modules/Elsa.Workflows.Core/VariableStorageDrivers/WorkflowInstanceStorageDriver.cs
Refactored `StorageDriverContext` to include `Variable` and updated its usage across relevant methods to ensure context accuracy. Enhanced `ObjectConverter` to support conditional deserialization of JSON objects. Adjusted `WorkflowInstanceStorageDriver` to utilize improved variable resolution with new conversion options.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6210)
=> Refactor variable handling in storage driver logic

src/modules/Elsa.Workflows.Core/Activities/Fork.cs, src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.Cancel.cs
Added logic to cancel child activities during activity cancellation. Removed redundant bookmark removal logic in the `Fork` activity for better clarity and efficiency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6213)
=> Refactor activity cancellation and bookmark handling.

src/common/Elsa.Testing.Shared.Component/Services/SignalManager.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/BulkDelete/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/BulkDeleteVersions/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/BulkPublish/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/BulkRetract/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Delete/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/DeleteVersion/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Import/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/ImportFiles/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Post/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Publish/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Retract/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/UpdateReferences/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Version/Delete.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Version/Revert.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6218)
=> Call async methods when in an async method

test/performance/Directory.Build.props, test/performance/Elsa.Workflows.PerformanceTests/Config.cs, test/performance/Elsa.Workflows.PerformanceTests/ConsoleActivitiesBenchmark.cs, test/performance/Elsa.Workflows.PerformanceTests/Elsa.Workflows.PerformanceTests.csproj, test/performance/Elsa.Workflows.PerformanceTests/Program.cs, test/performance/Elsa.Workflows.PerformanceTests/UnitTest1.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6244)
=> Added example of perfomance test

src/modules/Elsa.Expressions/Helpers/ObjectConverter.cs
This update enables deserialization of JSON nodes into ExpandoObject via ObjectConverter. It improves type handling and interoperability with dynamic structures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6248)
=> Add support for ExpandoObject deserialization in ObjectConverter

src/modules/Elsa.Workflows.Runtime/Services/LocalWorkflowClient.cs
Replaced synchronous `CreateWorkflowInstance` with `CreateAndCommitWorkflowInstanceAsync` to ensure instance creation is properly committed. Included support for cancellation tokens to improve process control and reliability.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6282)
=> Update workflow creation to use async commit method

.github/workflows/packages.yml, src/modules/Elsa.Workflows.Core/Contracts/IVariablePersistenceManager.cs, src/modules/Elsa.Workflows.Core/Services/VariablePersistenceManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6290)
=> Added DeleteVariablesAsync method for the workflow context

src/modules/Elsa.Workflows.Core/Contracts/IVariablePersistenceManager.cs, src/modules/Elsa.Workflows.Core/Services/VariablePersistenceManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6293)
=> Added DeleteVariablesAsync method for the workflow context - main

src/modules/Elsa.MassTransit/Activities/MessageReceived.cs, src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.cs, src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs, src/modules/Elsa.Workflows.Core/Extensions/WorkflowExecutionContextExtensions.cs, src/modules/Elsa.Workflows.Core/Models/Bookmark.cs, src/modules/Elsa.Workflows.Runtime/Services/StimulusSender.cs
Ensure type validation for incoming messages and clean up workflow input to prevent unintended data propagation. Added a dedicated ResumeAsync method to handle bookmark resumption logic consistently.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6302)
=> Refine message handling in MessageReceived activity

src/modules/Elsa.Dapper.Migrations/Runtime/V3_3.cs, src/modules/Elsa.EntityFrameworkCore.MySql/Migrations/Runtime/20250116192733_V3_3.Designer.cs, src/modules/Elsa.EntityFrameworkCore.MySql/Migrations/Runtime/20250116192733_V3_3.cs, src/modules/Elsa.EntityFrameworkCore.MySql/Migrations/Runtime/RuntimeElsaDbContextModelSnapshot.cs, src/modules/Elsa.EntityFrameworkCore.Oracle/Migrations/Runtime/20250116193207_V3_3.Designer.cs, src/modules/Elsa.EntityFrameworkCore.Oracle/Migrations/Runtime/20250116193207_V3_3.cs, src/modules/Elsa.EntityFrameworkCore.Oracle/Migrations/Runtime/RuntimeElsaDbContextModelSnapshot.cs, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Runtime/20250116192950_V3_3.Designer.cs, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Runtime/20250116192950_V3_3.cs, src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Runtime/RuntimeElsaDbContextModelSnapshot.cs, src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Runtime/20250116192837_V3_3.Designer.cs, src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Runtime/20250116192837_V3_3.cs, src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Runtime/RuntimeElsaDbContextModelSnapshot.cs, src/modules/Elsa.EntityFrameworkCore.Sqlite/Migrations/Runtime/20250116192907_V3_3.Designer.cs, src/modules/Elsa.EntityFrameworkCore.Sqlite/Migrations/Runtime/20250116192907_V3_3.cs, src/modules/Elsa.EntityFrameworkCore.Sqlite/Migrations/Runtime/RuntimeElsaDbContextModelSnapshot.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/Configurations.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6309)
=> Regenerate 3_3 Runtime module migrations

src/modules/Elsa.Workflows.Core/Middleware/Activities/ExceptionHandlingMiddleware.cs, src/modules/Elsa.Workflows.Runtime/Services/DefaultActivityExecutionMapper.cs
Refactored `ExceptionHandlingMiddleware` to improve readability and modularity by splitting responsibilities into smaller methods. Replaced `GetAggregateStatus` with direct use of `source.Status` for significant performance improvement when a large number of activity instances are involved. Updated null-checks for clarity and fixed inconsistent usage of default values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6317)
=> Refactor exception handling and activity status logic

src/modules/Elsa.Workflows.Management/Mappers/VariableDefinitionMapper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6328)
=> Fix variable default value serialization and array type parsing

src/modules/Elsa.MongoDb/Common/MongoDbStore.cs, src/modules/Elsa.MongoDb/Extensions/StringExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6329)
=> Refactor MongoDbStore to use EmptyToNull for TenantId assignments and add StringExtensions for null handling

docker/docker-compose.yml, src/modules/Elsa.Email/Activities/SendEmail.cs, src/modules/Elsa.Workflows.Management/Mappers/VariableDefinitionMapper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6332)
=> Add SMTP server configuration and refactor email activity for improved error handling and attachment processing

src/modules/Elsa.Workflows.Management/Mappers/VariableDefinitionMapper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6340)
=> Fix variable mapping and aliasing

.github/workflows/pr.yml, .nuke/build.schema.json, build/Build.CI.GitHubActions.cs, build/_build.csproj
Manual edits of workflow file don't help much when NUKE regenerates the file. Added customization to allow installation of custom NET versions to runner. Minor upgrade to NUKE too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6339)
=> Upgrade to NUKE 9.0.4 and fix automatic workflow generation

src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs
Reintroduced `GetAncestors` method and added new methods: `GetDescendants`, `GetActiveChildren`, and `GetChildren`. These methods enhance navigation through activity execution contexts by providing easy access to hierarchical relationships like ancestors, descendants, and children.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6341)
=> Restore methods for traversing activity execution context hierarchy

src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6353)
=> Back-port PolymorphicObjectConverter from 3.3

src/clients/Elsa.Api.Client/Resources/WorkflowInstances/Models/ActivityIncident.cs, src/clients/Elsa.Api.Client/Resources/WorkflowInstances/Models/WorkflowState.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6377)
=> Exposed incidents in the Elsa.Api.Client

.github/workflows/packages.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6378)
=> Updated deprecated artifact

.github/workflows/packages.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6379)
=> Updated deprecated artifacts

src/modules/Elsa.Common/Multitenancy/Implementations/DefaultTenantAccessor.cs, src/modules/Elsa.Hangfire/Jobs/ExecuteBackgroundActivityJob.cs, src/modules/Elsa.Hangfire/Jobs/ResumeWorkflowJob.cs, src/modules/Elsa.Hangfire/Jobs/RunWorkflowJob.cs, src/modules/Elsa.Hangfire/Services/HangfireBackgroundActivityScheduler.cs, src/modules/Elsa.Hangfire/Services/HangfireWorkflowScheduler.cs, src/modules/Elsa.Workflows.Runtime/Services/BackgroundActivityInvoker.cs
Refactored Hangfire-related services and jobs to include tenant context management using ITenantAccessor and ITenantFinder. Updated job constructors and method signatures to support tenant-specific execution. Improved exception-throwing syntax for better readability in BackgroundActivityInvoker.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6380)
=> Fix multitenancy support in Hangfire services and jobs

Directory.Packages.props, src/apps/Elsa.Server.Web/Elsa.Server.Web.csproj
Resolves the duplicate packages and corrects the formatting issue that prevents the project from building. The only intended change is to now contains the required packages for SQL activities.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6386)
=> ISSUE: Resolves Directory.Packages.props - Prevents Building

src/apps/Elsa.Server.Web/Elsa.Server.Web.csproj, src/apps/Elsa.Server.Web/Program.cs, src/apps/Elsa.Server.Web/appsettings.json, src/modules/Elsa.Webhooks/Extensions/ModuleExtensions.cs, src/modules/Elsa.Webhooks/Features/WebhooksFeature.cs
Simplified the configuration of sinks, sources, and HTTP clients by using direct actions instead of service-level options. Updated Apply method to finalize configurations and added notification handlers for better extensibility. Improved code readability and maintainability by consolidating logic and removing unnecessary dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6440)
=> Refactor WebhooksFeature to streamline configuration.

Directory.Packages.props, samples/aspnet/Elsa.Samples.AspNet.EntityFrameworkCore.PostgresSql/Elsa.Samples.AspNet.EntityFrameworkCore.PostgresSql.csproj, src/Directory.Build.props, src/bundles/Elsa.Server.LoadBalancer/Elsa.Server.LoadBalancer.csproj, src/bundles/Elsa.Server.Web/Elsa.Server.Web.csproj, src/bundles/Elsa.ServerAndStudio.Web/Elsa.ServerAndStudio.Web.csproj, src/bundles/Elsa.Studio.Web/Elsa.Studio.Web.csproj, src/bundles/ElsaStudioWebAssembly/ElsaStudioWebAssembly.csproj, src/modules/Elsa.Common/Elsa.Common.csproj, src/modules/Elsa.Dapper/Elsa.Dapper.csproj, src/modules/Elsa.Http/Activities/SendHttpRequestBase.cs, src/modules/Elsa.Http/Elsa.Http.csproj, src/modules/Elsa.Quartz.EntityFrameworkCore.PostgreSql/Elsa.Quartz.EntityFrameworkCore.PostgreSql.csproj, src/modules/Elsa.Quartz/Elsa.Quartz.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6447)
=> Add Resiliency to HTTP Request Activity

src/modules/Elsa.Http/Activities/SendHttpRequestBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6465)
=> Revise retry policy

src/modules/Elsa.CSharp/Activities/RunCSharp/RunCSharp.cs, src/modules/Elsa.JavaScript/Activities/RunJavaScript/RunJavaScript.cs, src/modules/Elsa.Python/Activities/RunPython/RunPython.cs, src/modules/Elsa.Sql/Activities/SqlCommand.cs, src/modules/Elsa.Sql/Activities/SqlQuery.cs, src/modules/Elsa.Sql/Activities/SqlSingleValue.cs
This PR is to accompany a Studio PR and closes elsa-workflows/elsa-studio#441
Details of this issue can be found here: https://github.com/elsa-workflows/elsa-studio/issues/441
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6481)
=> Bug - Update Scripting Activities To Resolve Auto Complete Issues

docker/docker-compose.yml, src/apps/Elsa.Server.Web/appsettings.json, src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.cs, src/modules/Elsa.Workflows.Core/Memory/Variable.cs
Replaced LINQ-based logic with a dictionary approach to merge variables. This ensures that variables are consistently merged by either name or ID when name is absent. It improves code clarity and handles edge cases more robustly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6493)
=> Refactor variable merging logic in ActivityExecutionContext

src/modules/Elsa.Workflows.Core/Contracts/IActivityRegistry.cs, src/modules/Elsa.Workflows.Core/Services/ActivityRegistry.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6497)
=> #6400 Add ClearProvider again to ActivityRegistry

src/common/Elsa.Mediator/Extensions/DependencyInjectionExtensions.cs, src/common/Elsa.Mediator/HostedServices/BackgroundCommandSenderHostedService.cs, src/common/Elsa.Mediator/HostedServices/BackgroundEventPublisherHostedService.cs, src/common/Elsa.Mediator/HostedServices/JobRunnerHostedService.cs, src/common/Elsa.Mediator/Options/MediatorOptions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6498)
=> Allow to configure JobRunner worker count

.github/workflows/packages.yml, Elsa.sln, src/modules/Elsa.Http/Activities/HttpEndpoint.cs, src/modules/Elsa.Http/Middleware/HttpWorkflowsMiddleware.cs, src/modules/Elsa.Workflows.Core/Contexts/TriggerIndexingContext.cs, src/modules/Elsa.Workflows.Runtime/Services/TriggerIndexer.cs
Refactored `TriggerIndexingContext` to enhance immutability and streamline trigger handling logic. Added support for generating trigger names dynamically and improved bookmark creation in HTTP workflows. Removed unused Docker Compose file and updated the base version in the build workflow to `3.5.0`.
Fixes #6512
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6516)
=> Refactor trigger indexing and update base version to 3.5.0.

src/modules/Elsa.Workflows.Core/Memory/Variable.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6514)
=> Fix incorrect Id assignment in Variable constructor

Directory.Build.props, Directory.Packages.props, src/apps/Elsa.Server.Web/Program.cs, src/modules/Elsa.EntityFrameworkCore.Common/ElsaDbContextBase.cs, src/modules/Elsa.EntityFrameworkCore.Common/PersistenceFeatureBase.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowManagementPersistenceFeature.cs
Fixed DbContext pooling support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6531)
=> Fix DbContext pooling

src/clients/Elsa.Api.Client/Resources/WorkflowInstances/Models/ActivityIncident.cs, src/modules/Elsa.Workflows.Core/Middleware/Activities/ExceptionHandlingMiddleware.cs, src/modules/Elsa.Workflows.Core/Middleware/Workflows/EngineExceptionHandlingMiddleware.cs, src/modules/Elsa.Workflows.Core/Middleware/Workflows/ExceptionHandlingMiddleware.cs, src/modules/Elsa.Workflows.Core/Models/ActivityIncident.cs, src/modules/Elsa.Workflows.Runtime.ProtoActor/Mappers/ActivityIncidentMapper.cs, src/modules/Elsa.Workflows.Runtime.ProtoActor/Proto/WorkflowInstance.Messages.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6572)
=> Extended the incidents data to include the activityNodeId (#6570)

src/modules/Elsa.Workflows.Core/Services/ActivityDescriber.cs
Fixes an incorrect type use: IContainer lives in System.ComponentModel and does not represent a container activity. The correct type to use is `Container`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6584)
=> Fix Container Type Evaluation

src/modules/Elsa.Workflows.Core/Features/WorkflowsFeature.cs, src/modules/Elsa.Workflows.Management/Mappers/VariableDefinitionMapper.cs
Introduced a new `GetStorageDriverType` method for cleaner and modular handling of storage driver type resolution. Added dependency on `IServiceScopeFactory` to manage backward compatibility with older type namespaces.
Fixes #6587
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6588)
=> Refactor variable storage driver mapping logic.

src/clients/Elsa.Api.Client/Extensions/JsonObjectExtensions.cs, src/clients/Elsa.Api.Client/Shared/Models/ActivityDesignerMetadata.cs, src/clients/Elsa.Api.Client/Shared/Models/Connection.cs, src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/Flowchart.cs, src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/Connection.cs, src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/Position.cs, src/modules/Elsa.Workflows.Core/Activities/Flowchart/Serialization/ConnectionJsonConverter.cs, src/modules/Elsa.Workflows.Core/Activities/Flowchart/Serialization/FlowchartJsonConverter.cs
Introduced a `Position` model to represent coordinates. Updated connection models, serializers, and related logic to include vertices, enabling richer flowchart connections. Simplified null initialization and improved collection handling across components.
Closes #4297
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6585)
=> Add support for connection vertices in flowcharts

src/modules/Elsa.Dapper/Modules/Runtime/Stores/DapperWorkflowExecutionLogStore.cs, src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/WorkflowExecutionLogStore.cs, src/modules/Elsa.Scheduling/Activities/Cron.cs, src/modules/Elsa.Workflows.Api/Models/ExecutionLogRecord.cs, src/modules/Elsa.Workflows.Core/Abstractions/Activity.cs, src/modules/Elsa.Workflows.Core/Behaviors/ScheduledChildCallbackBehavior.cs, src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.Cancel.cs, src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.Complete.cs, src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs, src/modules/Elsa.Workflows.Core/Handlers/EvaluateParentInputProperties.cs, src/modules/Elsa.Workflows.Core/Middleware/Activities/ExecutionLogMiddleware.cs, src/modules/Elsa.Workflows.Core/Notifications/InvokingActivityCallback.cs, src/modules/Elsa.Workflows.Runtime/Entities/WorkflowExecutionLogRecord.cs, src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs, src/modules/Elsa.Workflows.Runtime/LogPersistence/Extensions/ActivityExecutionContextExtensions.cs, src/modules/Elsa.Workflows.Runtime/LogPersistence/Handlers/EvaluateParentInputProperties.cs, src/modules/Elsa.Workflows.Runtime/Services/DefaultActivityExecutionMapper.cs, src/modules/Elsa.Workflows.Runtime/Services/WorkflowExecutionLogRecordExtractor.cs
Refactored activity input and log persistence property evaluation using improved notification handlers. Removed redundant `ActivityState` property and associated serialization logic, ensuring payloads are only serialized when necessary. All changes streamline workflow processing and enhance maintainability.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6603)
=> Remove obsolete properties and refactor activity evaluation

Directory.Build.props, Directory.Packages.props, src/modules/Elsa.MongoDb/Elsa.MongoDb.csproj
Updated package references to their latest versions in `Directory.Packages.props`, ensuring compatibility and access to the latest features. Enabled `MongoDB.Driver.Core.Extensions.DiagnosticSources` in `Elsa.MongoDb.csproj` and cleaned up unused ElsaStudio version property in `Directory.Build.props`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6635)
=> Update package versions

README.md
Corrected "Programmatic Workflows" to "Coding Workflows" for consistency with the content structure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6629)
=> Fix typo in README.md section title

src/modules/Elsa.Workflows.Runtime/Activities/BulkDispatchWorkflows.cs, src/modules/Elsa.Workflows.Runtime/Exceptions/WorkflowInstanceNotFoundException.cs, src/modules/Elsa.Workflows.Runtime/Handlers/SignalBookmarkQueueWorker.cs, src/modules/Elsa.Workflows.Runtime/Messages/RunWorkflowInstanceResponse.cs, src/modules/Elsa.Workflows.Runtime/Services/BookmarkQueueSignaler.cs, src/modules/Elsa.Workflows.Runtime/Services/BookmarkQueueWorker.cs, src/modules/Elsa.Workflows.Runtime/Services/BookmarkResumer.cs, src/modules/Elsa.Workflows.Runtime/Services/LocalWorkflowClient.cs, src/modules/Elsa.Workflows.Runtime/Services/StoreBookmarkQueue.cs
Improves the reliability and efficiency of the workflow runtime by:
- Refactors the `BookmarkQueueSignaler` to use channels for more robust signaling.
- Enhances the `BookmarkQueueWorker` to handle exceptions and continue processing.
- Adds a new `WorkflowInstanceNotFoundException` for clearer error handling when workflow instances are not found.
- Introduces a handler for `WorkflowInstanceSaved` to trigger bookmark queue processing upon workflow instance creation.
- Updates the BulkDispatchWorkflows activity to use null defaults.
- Clarifies comments related to bookmark and workflow instance checks during bookmark resumption.
Fixes #6642
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Enhances workflow runtime resilience and signaling

src/modules/Elsa.MassTransit/Features/MassTransitFeature.cs
- add configurable service bus callback
- invoke new bus configuration in AddMassTransit
Fixes #6651
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6658)
=> Add bus configurator hook to MassTransitFeature

Directory.Packages.props, Elsa.sln, src/modules/Elsa.Http/Elsa.Http.csproj, src/modules/Elsa.SasTokens/Contracts/DataProtectorTokenService.cs, src/modules/Elsa.SasTokens/Contracts/ITokenService.cs, src/modules/Elsa.SasTokens/Elsa.SasTokens.csproj, src/modules/Elsa.SasTokens/Extensions/ModuleExtensions.cs, src/modules/Elsa.SasTokens/Features/SasTokensFeature.cs, src/modules/Elsa.SasTokens/FodyWeavers.xml
This PR adds back SasToken project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6673)
=> Add back SasToken project.

src/clients/Elsa.Api.Client/Elsa.Api.Client.csproj, src/clients/Elsa.Api.Client/Shared/UIHints/RadioList/RadioList.cs, src/clients/Elsa.Api.Client/Shared/UIHints/RadioList/RadioListItem.cs, src/clients/Elsa.Api.Client/Shared/UIHints/RadioList/RadioListProps.cs
This PR creates the necessary Api Client Models for RadioList UIHint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6711)
=> Create Api Client Models for RadioList UIHint.

src/apps/Elsa.Server.Web/RadioListActivity.cs, src/modules/Elsa.Workflows.Core/Features/WorkflowsFeature.cs, src/modules/Elsa.Workflows.Core/UIHints/RadioList/RadioList.cs, src/modules/Elsa.Workflows.Core/UIHints/RadioList/RadioListItem.cs, src/modules/Elsa.Workflows.Core/UIHints/RadioList/RadioListOptionsProviderBase.cs, src/modules/Elsa.Workflows.Core/UIHints/RadioList/RadioListProps.cs, src/modules/Elsa.Workflows.Core/UIHints/RadioList/RadioListUIHintHandler.cs, src/modules/Elsa.Workflows.Core/UIHints/RadioList/StaticRadioListOptionsProvider.cs
This PR does the following:
- Renamed `CheckList` to `RadioList` in `RadioListProps`.
- Updated `WorkflowsFeature` to include `RadioListUIHintHandler` and `StaticRadioListOptionsProvider`.
- Introduced `TestRadioList` class for executing radio list functionality.
- Created `RadioList` and `RadioListItem` classes for managing radio list items.
- Added `RadioListOptionsProviderBase` for custom radio list data logic.
- Implemented `StaticRadioListOptionsProvider` for static radio list options.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6712)
=> Add RadioList support and related UI components

src/clients/Elsa.Api.Client/Extensions/DependencyInjectionExtensions.cs, src/clients/Elsa.Api.Client/Resources/Tests/ITestsApi.cs, src/clients/Elsa.Api.Client/Resources/Tests/TestActivityRequest.cs, src/clients/Elsa.Api.Client/Resources/Tests/TestActivityResponse.cs, src/clients/Elsa.Api.Client/Resources/WorkflowDefinitions/Models/ActivityHandle.cs, src/clients/Elsa.Api.Client/Resources/WorkflowDefinitions/Models/WorkflowDefinitionHandle.cs, src/modules/Elsa.Expressions.Liquid/Handlers/ConfigureLiquidEngine.cs, src/modules/Elsa.Workflows.Api/Endpoints/Activities/TestRun/Endpoint.cs, src/modules/Elsa.Workflows.Api/Endpoints/Tests/Activities/Endpoint.cs, src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.cs, src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs, src/modules/Elsa.Workflows.Core/Contracts/IActivityInvoker.cs, src/modules/Elsa.Workflows.Core/Contracts/IActivityTestRunner.cs, src/modules/Elsa.Workflows.Core/Contracts/IWorkflowRunner.cs, src/modules/Elsa.Workflows.Core/Features/WorkflowsFeature.cs, src/modules/Elsa.Workflows.Core/Middleware/Activities/DefaultActivityInvokerMiddleware.cs, src/modules/Elsa.Workflows.Core/Models/WorkflowDefinitionHandle.cs, src/modules/Elsa.Workflows.Core/Models/WorkflowGraph.cs, src/modules/Elsa.Workflows.Core/Services/ActivityInvoker.cs, src/modules/Elsa.Workflows.Core/Services/ActivityTestRunner.cs, src/modules/Elsa.Workflows.Management/Handlers/Notifications/EvictWorkflowDefinitionServiceCache.cs, src/modules/Elsa.Workflows.Management/Notifications/WorkflowDefinitionDraftSaved.cs, src/modules/Elsa.Workflows.Management/Notifications/WorkflowDefinitionDraftSaving.cs, src/modules/Elsa.Workflows.Management/Services/WorkflowDefinitionPublisher.cs
Adds an API endpoint for testing individual activities within a workflow definition.
- Introduces the `ActivityTestRunner` to execute activities in isolation.
- Provides API endpoints and client extensions for initiating tests.
- Includes ActivityState in response.
- Refactors code for improved organization and clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6719)
=> Implement Activity Testing API

src/common/Elsa.Mediator/Channels/NotificationsChannel.cs, src/common/Elsa.Mediator/CommandStrategies/DefaultStrategy.cs, src/common/Elsa.Mediator/Contexts/NotificationStrategyContext.cs, src/common/Elsa.Mediator/Contracts/INotificationsChannel.cs, src/common/Elsa.Mediator/Extensions/HandlerExtensions.cs, src/common/Elsa.Mediator/HostedServices/BackgroundCommandSenderHostedService.cs, src/common/Elsa.Mediator/HostedServices/BackgroundEventPublisherHostedService.cs, src/common/Elsa.Mediator/HostedServices/JobRunnerHostedService.cs, src/common/Elsa.Mediator/Middleware/Notification/Components/NotificationHandlerInvokerMiddleware.cs, src/common/Elsa.Mediator/PublishingStrategies/BackgroundProcessingStrategy.cs, src/common/Elsa.Mediator/PublishingStrategies/ParallelProcessingStrategy.cs, src/common/Elsa.Mediator/PublishingStrategies/SequentialProcessingStrategy.cs
Refactors the notification system to utilize a `NotificationContext` throughout channels and middleware.
- Introduces `NotificationContext` to encapsulate the notification along with relevant execution context.
- Modifies channels and middleware to operate on `NotificationContext` rather than directly on the notification.
- Ensures the `CancellationToken` is correctly passed to handlers through the `NotificationContext`.
Fixes #6449
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6821)
=> Refactors notification system for context

src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithVariableTypes.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6849)
=> Refine variable type registration by excluding `object` and optimizing collection processing.

src/clients/Elsa.Api.Client/Shared/Models/ActivityStatus.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6856)
=> Add missing `Pending` state to `ActivityStatus` enum

.github/workflows/packages.yml, src/modules/Elsa.Http/Activities/SendHttpRequestBase.cs, src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Execute/PostEndpoint.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6904)
=> Fixed content type check from execute endpoint

src/modules/Elsa.Workflows.Core/Extensions/ItemSourceActivityExecutionContextExtensions.cs
Closes #6896
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6897)
=> Add IAsyncEnumerable check to ItemSourceActivityExecutionContextExtensions.GetItemSource

src/modules/Elsa.Workflows.Core/Expressions/InputExpressionHandler.cs, src/modules/Elsa.Workflows.Core/Services/ActivityDescriber.cs, src/modules/Elsa.Workflows.Core/UIHints/InputUIHints.cs, src/modules/Elsa.Workflows.Management/Providers/DefaultExpressionDescriptorProvider.cs
Hello ! Following feature request #6903 and sfmskywalker's review in PR #6905 , here is the PR for `elsa-core`. The PR for `elsa-studio` is coming shortly after.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6910)
=> Workflow input as activity input

.github/workflows/elsa-server-and-studio.yml, .github/workflows/elsa-server.yml, .github/workflows/elsa-studio.yml, .github/workflows/packages.yml, src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/Flowchart.cs, test/integration/Elsa.Workflows.IntegrationTests/Scenarios/FlowchartNextActivity/Tests.cs
Refactors the Flowchart activity to enhance error handling and code clarity.
- Replaces `Exception` with `throw new()` for conciseness.
- Adds null check for connectionFollowed to avoid unnecessary processing.
- Improves test case coverage, especially around backward connections and dangling activities.
- Fixes potential issues with join activity execution in complex scenarios based on branch name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6938)
=> Improves Flowchart activity robustness
