elsa-workflows/elsa-core

- src/core/Elsa.Core/Results/HaltResult.cs
When continue on first pass is set, the workflow should resume instead of execute the halt task again.
> Updated Halt task to resume on first pass if set

- src/core/Elsa.Core/WorkflowBuilders/WorkflowBuilder.cs
To reproduce, run Sample12 after pulling in previous PR. You'll get a "sequence contains no elements" error.
> Fixed issue where named activities couldn't be used with Then()

- src/core/Elsa.Core/Services/ActivityResolver.cs
- src/samples/Sample12/Program.cs
To reproduce, run Sample12 on 1.1.1 branch and you'll get a duplicate key exception.
The registration was being performed twice, once by AddElsa() and again by AddUserTasks(). You could probably remove the AddUserTasks() extension method altogether.
> Fixed bug where multiple activity registrations of the same type would cause duplicate key exception

- src/core/Elsa.Core/Expressions/WorkflowExpressionEvaluator.cs
- src/scripting/Elsa.Scripting.JavaScript/Services/JavaScriptExpressionEvaluator.cs
- Checks if the target type is a string while the source type is an object, in which case the object is converted to its string representation instead of trying to be deserialized.
- Adds exception handling around expression evaluation.
> Improve expression evaluation

- src/core/Elsa.Core/Persistence/Memory/MemoryWorkflowInstanceStore.cs
- src/samples/Sample08/Messages/CreateOrder.cs
- src/samples/Sample08/Messages/OrderShipped.cs
- src/samples/Sample08/Workflows/CreateOrderWorkflow.cs
Looks like it is really important to correlate MassTransit messages to workflow instances. I have updated the demo to show this, as I ran a few in parallel and several errors were occurring.
> Message correlation

- src/core/Elsa.Abstractions/Models/Variables.cs
- src/core/Elsa.Abstractions/Models/WorkflowExecutionScope.cs
Changed Variables.cs to full IDictionary with ConcurrentDictionary<string, object> backing-store
This should be a 1:1 drop in and work even in resumed flows.
Now i get objects (the originals) and you get JTokens *CoughSweat*
BTW i think it may perform better because convert to jtoken is only done when needed. (Dont kill me if not)
This should even be a lit more thread-safe - (there should be some locks somewhere i think to be 100% safe....)
Lotsa shoulds... :-D Could you give it a look please? This would straighten the GetVariable mess in my flows and reduces converts a lot...
> Changed Variables.cs to full IDictionary with ConcurrentDictionary<string, object> backing-store

- src/activities/Elsa.Activities.MassTransit/Activities/ReceiveMassTransitMessage.cs
Was comparing against the variable object, not the variable value.
> Fix issue with receive MassTransit message input variable use

- .dockerignore
- Dockerfile
- Elsa.sln
- Samples.sln
- docker-compose.yaml
- src/activities/Elsa.Activities.Dropbox/Elsa.Activities.Dropbox.csproj
- src/activities/Elsa.Activities.Http/Elsa.Activities.Http.csproj
- src/activities/Elsa.Activities.Timers/Elsa.Activities.Timers.csproj
- src/core/Elsa.Abstractions/Elsa.Abstractions.csproj
- src/core/Elsa.Core/Elsa.Core.csproj
- src/dashboard/Elsa.Dashboard.Web/Elsa.Dashboard.Web.csproj
- src/dashboard/Elsa.Dashboard.Web/Program.cs
- src/dashboard/Elsa.Dashboard.Web/Properties/launchSettings.json
- src/dashboard/Elsa.Dashboard.Web/README.md
- src/dashboard/Elsa.Dashboard.Web/Startup.cs
- src/dashboard/Elsa.Dashboard.Web/appsettings.Development.json
- src/dashboard/Elsa.Dashboard.Web/appsettings.json
- src/dashboard/Elsa.Dashboard/Extensions/ActivityDefinitionListExtensions.cs
- src/dashboard/Elsa.WorkflowDesigner/Elsa.WorkflowDesigner.csproj
- src/persistence/Elsa.Persistence.DocumentDb/Elsa.Persistence.DocumentDb.csproj
- src/persistence/Elsa.Persistence.EntityFrameworkCore/Elsa.Persistence.EntityFrameworkCore.csproj
- src/persistence/Elsa.Persistence.MongoDb/Elsa.Persistence.MongoDb.csproj
- src/persistence/Elsa.Persistence.YesSql/Elsa.Persistence.YesSql.csproj
- src/samples/Sample05/Sample05.csproj
- src/samples/Sample14/Sample14.csproj
- src/samples/Sample18/Sample18.csproj
- src/utils/Elsa.AutoMapper.Extensions/Elsa.AutoMapper.Extensions.csproj
The Dockerfile builds a new project called Elsa.Dashboard.Web, which serves as both the dashboard and workflow server.
To build the Dockerfile:
`docker build --pull .`
To run the Dockerfile, make sure you have MongoDB and an SMTP host running.
If you don't have these installed, use the docker-compose file, which will run MongoDB and Smtp4Dev in containers.
> Add Dockerfile and docker-compose

- src/activities/Elsa.Activities.MassTransit/Activities/PublishMassTransitMessage.cs
- src/activities/Elsa.Activities.MassTransit/Activities/SendMassTransitMessage.cs
- src/activities/Elsa.Activities.MassTransit/Extensions/ServiceCollectionExtensions.cs
- src/samples/Sample08/Workflows/HandleOrderWorkflow.cs
I have also made a small change to try and maintain using the consume context which is available in the current scope when consuming a message from the bus. 
If this consume context is not available in the current scope, then the bus is used.
This allows for maintaining a continuous conversation ID if available.
> Add the ability to publish events via MassTransit

- src/core/Elsa/ElsaServiceCollectionExtensions.cs
- src/scripting/Elsa.Scripting.JavaScript/Extensions/JavaScriptServiceCollectionExtensions.cs
- src/scripting/Elsa.Scripting.JavaScript/Options/ScriptOptions.cs
- src/scripting/Elsa.Scripting.JavaScript/Services/JavaScriptExpressionEvaluator.cs
I've given this a crack using the options builder pattern, but I'm interested to know if you think there's a better/tidier way of doing it.
I tried adding another optional parameter to `AddElsa` extension method, but that didn't look great, as I then needed to provided the param name with both the existing param and the new one being optional:
`services.AddElsa(scriptOptions: options => options.Configure(x => x.AllowClr = false)`
What I've commited is a separate extension method. 
```
.AddElsa()
.WithJavaScriptOptions(x => x.Configure(o => o.AllowClr = false))
```
If it's not called, it will default to allowing CLR use as per the existing version.
> Add script options configuration (#179)

- README.md
The new url is https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Workflows/
> Fix link on Orchard Core doc

- src/scripting/Elsa.Scripting.JavaScript/Extensions/JavaScriptServiceCollectionExtensions.cs
Moved `WithJavaScriptOptions` into `Microsoft.Extensions.DependencyInjection` namespace so easier to discover. Existing AddJavaScriptExpressionEvaluator method also moved in. This should be safe as it shouldn't be called anyone directly, as it's called as part of AddElsa().
> Moved JavaScript DI extension method namespace (#179)

- src/persistence/Elsa.Persistence.YesSql/Extensions/StoreFactory.cs
- src/persistence/Elsa.Persistence.YesSql/Indexes/WorkflowInstanceIndex.cs
- src/persistence/Elsa.Persistence.YesSql/Serialization/YesSqlJsonSerializer.cs
- src/persistence/Elsa.Persistence.YesSql/Services/YesSqlWorkflowInstanceStore.cs
* WorkflowInstanceIndex now stores records correctly
* Saving a workflow instance now updates existing instance rather than creating a new document
* Fixed serialisation exception when saving existing instance containing NodaTime types
I had to create a new YesSql `IContentSerializer` (`YesSqlJsonSerializer`) because the YesSql version (`YesSql.Serialization.JsonContentSerializer`) has private settings, so I couldn't derive and add NodaTime support.
> YesSql instance storage fixes

- src/core/Elsa.Abstractions/Models/Variables.cs
* SetVariables no longer re-wraps variable in another variable
* GetVariable<T> now uses Convert.ChangeType
Fixes issue where saving an Int32, serialising and deserialising, then accessing with GetVariable<int>(...) no longer causes type cast exception.
The saved value is a JValue which treats Int32 as Int64. Convert.ChangeType has a better chance of performing conversion without error.
Also returns default of T if the variable isn't found - **is this safe to do?**
> Variable fixes

- src/activities/Elsa.Activities.Console/Activities/ReadLine.cs
- src/activities/Elsa.Activities.Http/Activities/ReceiveHttpRequest.cs
- src/activities/Elsa.Activities.MassTransit/Activities/ReceiveMassTransitMessage.cs
- src/activities/Elsa.Activities.Timers/Activities/CronEvent.cs
- src/activities/Elsa.Activities.Timers/Activities/InstantEvent.cs
- src/activities/Elsa.Activities.Timers/Activities/TimerEvent.cs
- src/activities/Elsa.Activities.Timers/HostedServices/TimersHostedService.cs
- src/activities/Elsa.Activities.UserTask/Activities/UserTask.cs
- src/activities/Elsa.Activities.Workflows/Activities/Correlate.cs
- src/activities/Elsa.Activities.Workflows/Activities/Signaled.cs
- src/core/Elsa.Abstractions/Services/Extensions/WorkflowInvokerExtensions.cs
- src/core/Elsa.Abstractions/Services/Models/WorkflowBlueprint.cs
- src/core/Elsa.Core/Expressions/VariableExpression.cs
- src/core/Elsa.Core/Expressions/VariableHandler.cs
- src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs
- src/core/Elsa.Core/Messages/Handlers/PersistenceWorkflowEventHandler.cs
- src/core/Elsa.Core/Persistence/Memory/MemoryWorkflowInstanceStore.cs
- src/core/Elsa.Core/Services/Activity.cs
- src/core/Elsa.Core/Services/WorkflowFactory.cs
- src/core/Elsa.Core/Services/WorkflowRunner.cs
- src/core/Elsa.Core/WorkflowBuilders/WorkflowBuilder.cs
- src/samples/Sample02/Program.cs
- src/samples/Sample05/RecurringWorkflow.cs
- src/samples/Sample08/Workflows/CreateOrderWorkflow.cs
- src/samples/Sample13/Program.cs
As a proof-of-concept, this PR adds a specialized `VariableExpression` that can be used for activities that need access to a variable, without the need to use a script expression. Similarly, additional workflow expression implementations could be added to simplify accessing workflow state from activities.
Fixes #71
> Added VariableExpression

- src/core/Elsa.Abstractions/Converters/TypeNameHandlingConverter.cs
- src/core/Elsa.Abstractions/Serialization/Handlers/DefaultValueHandler.cs
- src/core/Elsa.Abstractions/Serialization/Handlers/IValueHandler.cs
- src/core/Elsa.Abstractions/Serialization/Handlers/ObjectHandler.cs
- src/core/Elsa.Abstractions/Serialization/Handlers/PrimitiveValueHandler.cs
After commit: 80ad408 (Fix broken date/time/nodatime serialization (#214)), custom object type names weren't being serialised in the TypeName attribute.
I've registered `ObjectHandler` which was already in there. 
Also had to add `Type` param to `IValueHandler.Serialize` as was unable to get the underlying object type from `JObject`.
> Fixed Serialization for Objects

- src/persistence/Elsa.Persistence.EntityFrameworkCore/DbContexts/DesignTimeDbContextFactoryBase.cs
- src/persistence/Elsa.Persistence.EntityFrameworkCore/DbContexts/MySqlContextFactory.cs
- src/persistence/Elsa.Persistence.EntityFrameworkCore/DbContexts/PostgreSqlContextFactory.cs
- src/persistence/Elsa.Persistence.EntityFrameworkCore/DbContexts/SqlServerContextFactory.cs
- src/persistence/Elsa.Persistence.EntityFrameworkCore/DbContexts/SqliteContext.cs
- src/persistence/Elsa.Persistence.EntityFrameworkCore/DbContexts/SqliteContextFactory.cs
- src/persistence/Elsa.Persistence.EntityFrameworkCore/Elsa.Persistence.EntityFrameworkCore.csproj
- src/samples/Sample16/Sample16.csproj
- src/samples/Sample19/Sample19.csproj
- src/samples/Sample23/Sample23.csproj
Fix an issue where some DB Context factories use the base ElsaContext type instead of the derived type, causing a "Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[]' while attempting to activate" error.
> Fix an issue with some DB Context factories

- src/activities/Elsa.Activities.ControlFlow/Activities/ForEach.cs
When giving a generic list to foreach throw exception to casting object list. better to keeping just IList.
> Foreach generic list<T> bug

- src/core/Elsa.Abstractions/Models/WorkflowFault.cs
- src/core/Elsa.Abstractions/Services/Models/WorkflowExecutionContext.cs
- src/core/Elsa.Abstractions/Services/Models/WorkflowFault.cs
- src/core/Elsa.Core/Results/FaultWorkflowResult.cs
Expose the underlying System.Exception that caused the Workflow to return a fault. This will allow callers to execute error handling based on the runtime Exception (if present) instead of error text.
Right now, Exception can be null. If Nullable Reference Types will be enabled in this project in the future, perhaps we can change this implementation a little and initialize the Exception object when only an errorMessage is specified.
> Add Exception property to WorkflowFault

- src/activities/Elsa.Activities.ControlFlow/Activities/ForEach.cs
**Issue Summary**
The incorrect scope is ended (removed from the stack) when using the ForEach activity with an empty collection. This happens because the current scope is ended when the current index is equal to the count of items in the collection. In scenarios where the collection is empty, a new scope is **not** added, however, the previous scope is ended. This results in a faulted workflow when accessing variables from previous scopes and a 'System.InvalidOperationException' when accessing the default workflow scope.
**Steps to Reproduce**
Example workflow code
```csharp
public class ScopeTestWorkflow : IWorkflow
{
public void Build(IWorkflowBuilder builder)
{
builder
.StartWith<SetVariable>(x =>
{
x.VariableName = "scopeTest";
x.ValueExpression = new …
```
> Fix bug in ForEach activity when the collection is empty

- Samples.sln
- src/core/Elsa.Abstractions/Services/IWorkflowHost.cs
- src/core/Elsa.Core/Services/WorkflowHost.cs
- src/samples/Elsa.Samples.WorkflowDefinition/Elsa.Samples.WorkflowDefinition.csproj
- src/samples/Elsa.Samples.WorkflowDefinition/Program.cs
This PR will fix _Object reference not set to an instance of an object._ if user tries to run workflow definition without publish it.
**How To Test?**
To test this fix, I have added new sample project named `Elsa.Samples.WorkflowDefinition`. While creating WorkflowDefinition I have mentioned `IsPublished = true`, if you change it to `false`, it will log the error using Microsoft.Logging framework as fatal error and also it will throw Workflow exception as below -
> Fix#325:Elsa 2#RunWorkflowDefinitionAsync getting object reference null

- src/persistence/Elsa.Persistence.EntityFrameworkCore/DbContexts/ElsaContext.cs
There is a known issue in Newtonsoft.Json that it reverse the stack on deserialization and we have to manually reverse it. To resolve #334 
Reference: https://github.com/JamesNK/Newtonsoft.Json/issues/1596
> Reverse WorkflowInstanceEntity.Scopes on deserialization

- src/persistence/Elsa.Persistence.DocumentDb/DocumentDbStorage.cs
- src/persistence/Elsa.Persistence.DocumentDb/DocumentDbStorageOptions.cs
- src/persistence/Elsa.Persistence.DocumentDb/Documents/DocumentBase.cs
- src/persistence/Elsa.Persistence.DocumentDb/Documents/WorkflowDefinitionVersionDocument.cs
- src/persistence/Elsa.Persistence.DocumentDb/Documents/WorkflowInstanceDocument.cs
- src/persistence/Elsa.Persistence.DocumentDb/Extensions/ServiceConfigurationExtensions.cs
- src/persistence/Elsa.Persistence.DocumentDb/Helpers/ClientHelper.cs
- src/persistence/Elsa.Persistence.DocumentDb/Helpers/QueryHelper.cs
- src/persistence/Elsa.Persistence.DocumentDb/IDocumentDbStorage.cs
- src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowDefinitionStore.cs
- src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowInstanceStore.cs
Bug #311 : 
1. The class "DocumentDbStorage" has limitation in creating required collections for this application to run. 
2. The NodaTime serialization is not happening properly while sending/retrieving data to/from DB.  
3. The deletion of WorkflowDefinition throws exception
4. async/await is not used properly. Because of that application hanged while running in both IISExpress and IIS
Fixed all above issues. Also have done major refactoring in the following classes.
1. DocumentDbStorage.cs
3. ServiceConfigurationExtensions.cs
4. CosmosDbWorkflowInsanceStore.cs
5. CosmosDbWorkflowDefinitionStore.cs
6. ClientHelper.cs
> fixed IOC and async/await related issues in CosmosDB persistence library (#311)

- src/core/Elsa.Abstractions/Models/ActivityDefinition.cs
- src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/WorkflowDefinitionEditor.cshtml
Bug #341: the issue is generated by the ContainsKey() that adds the Name propery (uppercase) even if there is already name (lowercase) added by the activity definition. Fixed with a "ToLower()" on get and set methods of ActivityDefinition
Layout problem: the "Import" and "Settings gear" goes to a new line. Fixed by setting the style of Title+Descrition and toolbar as col instead of col-8 and col-4 to allow the browser to autosize the column
> fix for bug #341 and fix designer toolbar alignment

- src/core/Elsa.Abstractions/Models/ActivityDefinition.cs
Since the State property is serialized JSON the getter and setter needs to look for the key lowercased. This allows the property to be set with the name and have the Name property persisted in the datastore (i.e. EF). This fixes the problem so the outputs of the activity may be retrieved by name
> Fixed getter and setter for Name property

- src/activities/Elsa.Activities.Console/Activities/ReadLine/ReadLine.cs
- src/activities/Elsa.Activities.Dropbox/Extensions/ServiceCollectionExtensions.cs
- src/activities/Elsa.Activities.Email/Activities/SendEmail/SendEmail.cs
- src/activities/Elsa.Activities.Email/Activities/SendEmail/SendEmailBuilderExtensions.cs
- src/activities/Elsa.Activities.Email/Activities/SendEmail/SendEmailExtensions.cs
- src/activities/Elsa.Activities.Email/Extensions/ServiceCollectionExtensions.cs
- src/activities/Elsa.Activities.Http/Activities/Redirect/Redirect.cs
- src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequest.cs
- src/activities/Elsa.Activities.Http/Activities/WriteHttpResponse/WriteHttpResponse.cs
- src/activities/Elsa.Activities.Http/Models/HttpResponseModel.cs
- src/activities/Elsa.Activities.MassTransit/Activities/MassTransitBusActivity.cs
- src/activities/Elsa.Activities.Timers/Activities/CronEvent/CronEvent.cs
- src/activities/Elsa.Activities.Timers/Activities/CronEvent/CronEventBuilderExtensions.cs
- src/activities/Elsa.Activities.Timers/Activities/InstantEvent/InstantEventBuilderExtensions.cs
- src/activities/Elsa.Activities.Timers/Activities/TimerEvent/TimerEventBuilderExtensions.cs
- src/activities/Elsa.Activities.Timers/Extensions/ServiceCollectionExtensions.cs
- src/activities/Elsa.Activities.Timers/HostedServices/TimersHostedService.cs
- src/core/Elsa.YesSql.Provider.Sqlite.InMemory/SingletonDbConnectionFactory.cs
- src/scripting/Elsa.Scripting.JavaScript/Converters/TruncatingNumberJsonConverter.cs
- src/scripting/Elsa.Scripting.Liquid/Services/LiquidExpressionHandler.cs
I am opening this PR according to https://github.com/elsa-workflows/elsa-core/pull/413#pullrequestreview-513985910
It also does not contain changes for the projects in the `core` folder so as not to make this PR huge.
--------------------
Did you get rid of it Reflection Activity btw? I liked it and even had a plan to improve it.
--------------------
I also want to ask a question (probably it's not the best place, but anyway).
What is the benefit of taking `Action<OptionsBuilder<TOptions>>`?  like
```
public static IServiceCollection AddHttpServices(this IServiceCollection services, Action<OptionsBuilder<HttpActivityOptions>> options)
{
options.Invoke(services.AddOptions<HttpActivityOptions>());
// other stuff
}
```
and a caller should do
```
services.AddHttpActivities(options => …
```
> Minor cleanup of elsa 2.0

- src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/UserMenuItems.cshtml
- src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/_ViewImports.cshtml
- src/dashboard/Elsa.Dashboard/Elsa.Dashboard.csproj
There is a security Vulnerability with Microsoft.AspNetCore.Mvc version 1.0.0.
Since Gravatar does not appear to be used at all, remove the dependency to improve security.
> Remove gravatar dependency

- src/core/Elsa.Abstractions/Models/BlockingActivity.cs
ListByBlockingActivityAsync() builds following query to retrieve blocked activities. 
SELECT VALUE root FROM root JOIN (SELECT VALUE EXISTS(SELECT VALUE y0 FROM root JOIN y0 IN root["blockingActivities"] WHERE (y0["**ActivityType**"] = "ReceiveMassTransitMessage") ) ) AS v0 WHERE (((root["status"] = 1) AND (root["correlationId"] = "c02bc6fe-3730-4805-82f0-85741172aef7")) AND v0) ORDER BY root["createdAt"] DESC "}}
Due to the serialization issue, **ActivityType** is not serialized into **activityType** in the query. The fix helps to correct the same. After the fix, the query will be built like below
SELECT VALUE root FROM root JOIN (SELECT VALUE EXISTS(SELECT VALUE y0 FROM root JOIN y0 IN root["blockingActivities"] WHERE (y0["**activityType**"] = "ReceiveMassTransitMessage") ) ) AS v0 …
> Fix : ListByBlockingActivityAsync() in documentDB persistence layer is not retrieving the blocked activities

- src/core/Elsa.Core/Serialization/Converters/ExceptionConverter.cs
- src/persistence/Elsa.Persistence.DocumentDb/DocumentDbStorage.cs
The **JsonSerializerSettings** which is attached with **DocumentClient** do not have proper converters for **Exception** that leads to the JSON serialization error.
The changes to fix the issue available as part of the PR. Please have a look and approve the same.
> DocumentDB persistence layer unable to deserialize the Exception class instances

- Samples.sln
- Samples.sln.DotSettings
- src/core/Elsa.Abstractions/ActivityProviders/ActivityType.cs
- src/core/Elsa.Abstractions/Extensions/ActivityActivatorExtensions.cs
- src/core/Elsa.Abstractions/Services/IActivityActivator.cs
- src/core/Elsa.Abstractions/Services/IWorkflowInterruptor.cs
- src/core/Elsa.Core/ActivityTypeProviders/TypeBasedActivityProvider.cs
- src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs
- src/core/Elsa.Core/Extensions/WorkflowDefinitionManagerExtensions.cs
- src/core/Elsa.Core/HostedServices/StartWorkflow.cs
- src/core/Elsa.Core/Indexes/WorkflowInstanceIndex.cs
- src/core/Elsa.Core/Services/ActivityActivator.cs
- src/core/Elsa.Core/Services/WorkflowInterruptor.cs
- src/samples/aspnet/Elsa.Samples.CustomActivityTypeProviders/Activities/Sleep.cs
- src/samples/aspnet/Elsa.Samples.CustomActivityTypeProviders/Elsa.Samples.CustomActivityTypeProviders.csproj
- src/samples/aspnet/Elsa.Samples.CustomActivityTypeProviders/Endpoints/WakeUp.cs
- src/samples/aspnet/Elsa.Samples.CustomActivityTypeProviders/Program.cs
- src/samples/aspnet/Elsa.Samples.CustomActivityTypeProviders/Properties/launchSettings.json
- src/samples/aspnet/Elsa.Samples.CustomActivityTypeProviders/Startup.cs
- src/samples/aspnet/Elsa.Samples.CustomActivityTypeProviders/Workflows/InterruptableWorkflow.cs
- src/samples/aspnet/Elsa.Samples.CustomActivityTypeProviders/appsettings.json
- src/samples/aspnet/Elsa.Samples.CustomActivityTypeProviders/interrupt.http
- src/samples/aspnet/Elsa.Samples.HelloWorldHttp/Startup.cs
The Workflow Interruptor is essentially an API to trigger any workflow that is blocked on any type of activity, manually, by providing an easy to use API.
A sample use case scenario might be where your application hosts certain workflows of which you know can be blocked on a given activity type, but some event occurs that requires your app to simply unblock these workflows.
> Add Workflow Interruptor API

- src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowInstanceStore.cs
The delete API is not using the correct documentUri to delete the document. The fix uses the correct URI for the same.
> Workflow instance delete API is not deleting the document

- src/persistence/Elsa.Persistence.DocumentDb/DocumentDbCollectionInfo.cs
- src/persistence/Elsa.Persistence.DocumentDb/DocumentDbStorage.cs
- src/persistence/Elsa.Persistence.DocumentDb/DocumentDbStorageOptions.cs
- src/persistence/Elsa.Persistence.DocumentDb/Documents/WorkflowDefinitionVersionDocument.cs
- src/persistence/Elsa.Persistence.DocumentDb/Documents/WorkflowInstanceDocument.cs
- src/persistence/Elsa.Persistence.DocumentDb/Helpers/ClientHelper.cs
- src/persistence/Elsa.Persistence.DocumentDb/Helpers/QueryHelper.cs
- src/persistence/Elsa.Persistence.DocumentDb/IDocumentDbStorage.cs
- src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowDefinitionStore.cs
- src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowInstanceStore.cs
Since dashboard get crashed or hanged for longtime due to cross partition queries. I just add a partition key to resolve the same.
After adding the partition key, I tested the changes with CosmoDB. Now I am not seeing any crash or hang. Dashboard loads without delay. 
Without the fix, I have to wait for longtime for dashboard to load. Most of time, it will crash or hang. Now it is loading quickly without much delay.
> Added partition key for heavy read queries and also to avoid cross partition queries 

- src/core/Elsa.Abstractions/Attributes/ContextTypeNameAttribute.cs
- src/core/Elsa.Abstractions/Extensions/TypeExtensions.cs
- src/core/Elsa.Abstractions/Models/WorkflowDefinition.cs
- src/core/Elsa.Abstractions/Models/WorkflowInstance.cs
- src/core/Elsa.Core/Persistence/Specifications/SpecificationExtensions.cs
- src/core/Elsa.Core/Persistence/Specifications/WorkflowDefinitionSpecificationExtensions.cs
- src/core/Elsa.Core/Persistence/Specifications/WorkflowInstancSpecificationExtensions.cs
- src/core/Elsa.Core/Persistence/Specifications/WorkflowInstanceContextIdMatchSpecification.cs
- src/core/Elsa.Core/Persistence/Specifications/WorkflowInstanceContextMatchSpecification.cs
- src/core/Elsa.Core/Services/WorkflowFactory.cs
- src/persistence/Elsa.Persistence.YesSql/Documents/WorkflowInstanceDocument.cs
- src/persistence/Elsa.Persistence.YesSql/Indexes/WorkflowInstanceIndex.cs
Issue: #514 
The data type `Type` was not serialized correctly, which made a comparison from `ContextType` impossible. Therefore I decided to use string. I find it more convenient this way than writing a separate serializer for each database.
`ContextType` in `WorkflowContextOptions` could also be stored as `string` later.
After PR #536 and this PR. `WorkflowContextProvider` could also be stored in `ElsaOptions`. When registering a `WorkflowContextProvider`, the `ContextType` is also registered. This way all available `ContextTypes` for the designer are automatically available.
> Add ContextType to WorkflowInstance

- Elsa.sln
- src/activities/Elsa.Activities.Rebus/Triggers/MessageReceivedTrigger.cs
- src/core/Elsa.Abstractions/ElsaOptions.cs
- src/core/Elsa.Abstractions/Extensions/AssemblyExtensions.cs
- src/core/Elsa.Abstractions/Extensions/ServiceCollectionExtensions.cs
- src/core/Elsa.Abstractions/Models/TypeList.cs
- src/core/Elsa.Core/ActivityTypeProviders/TypeBasedActivityProvider.cs
- src/core/Elsa.Core/ElsaConfiguration.cs
- src/core/Elsa.Core/ElsaConfigurationsOptions.cs
- src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs
- src/core/Elsa.Core/Extensions/ServiceCollectionExtensions.cs
- src/core/Elsa.Core/Services/ServiceBusFactory.cs
- src/core/Elsa.Core/WorkflowProviders/ProgrammaticWorkflowProvider.cs
- src/core/Elsa/ElsaServiceCollectionExtensions.cs
- src/locking/Elsa.DistributedLocking.AzureBlob/ElsaOptionsExtensions.cs
- src/locking/Elsa.DistributedLocking.Redis/ElsaOptionsExtensions.cs
- src/locking/Elsa.DistributedLocking.SqlServer/ElsaOptionsExtensions.cs
- src/persistence/Elsa.Persistence.MongoDb/Extensions/ServiceCollectionExtensions.cs
- src/persistence/Elsa.Persistence.YesSql/Extensions/ServiceCollectionExtensions.cs
- src/servicebus/Elsa.Rebus.AzureServiceBus/Extensions/ElsaOptionsExtensions.cs
- src/servicebus/Elsa.Rebus.RabbitMq/Extensions/ElsaOptionsExtensions.cs
I took a point from the list #468.
Activities are now stored in `ElsaOptions`. I renamed the old class `ElsaOptions` to `ElsaConfigurationsOptions`. Among other things because `public IServiceCollection Services { get; }` is not needed at runtime.
Also, activities and workflows can be added via Assembly. It is no longer necessary to add each activity and workflow individually.
> Redesign activities and workflows management

- src/persistence/Elsa.Persistence.DocumentDb/DocumentDbStorage.cs
- src/persistence/Elsa.Persistence.DocumentDb/Documents/DocumentBase.cs
- src/persistence/Elsa.Persistence.DocumentDb/Documents/WorkflowDefinitionVersionDocument.cs
- src/persistence/Elsa.Persistence.DocumentDb/Documents/WorkflowInstanceDocument.cs
- src/persistence/Elsa.Persistence.DocumentDb/Elsa.Persistence.DocumentDb.csproj
- src/persistence/Elsa.Persistence.DocumentDb/Extensions/DateTimeExtensions.cs
- src/persistence/Elsa.Persistence.DocumentDb/Extensions/DocumentClientExtensions.cs
- src/persistence/Elsa.Persistence.DocumentDb/Extensions/DocumentQueryExtensions.cs
- src/persistence/Elsa.Persistence.DocumentDb/Extensions/QueryableExtensions.cs
- src/persistence/Elsa.Persistence.DocumentDb/Extensions/ServiceConfigurationExtensions.cs
- src/persistence/Elsa.Persistence.DocumentDb/Extensions/TypeExtensions.cs
- src/persistence/Elsa.Persistence.DocumentDb/Helpers/CosmosDbStoreHelper.cs
- src/persistence/Elsa.Persistence.DocumentDb/Helpers/ICosmosDbStoreHelper.cs
- src/persistence/Elsa.Persistence.DocumentDb/IDocumentDbStorage.cs
- src/persistence/Elsa.Persistence.DocumentDb/ITenantProvider.cs
- src/persistence/Elsa.Persistence.DocumentDb/Mapping/DocumentProfile.cs
- src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowDefinitionStore.cs
- src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowInstanceStore.cs
- src/persistence/Elsa.Persistence.DocumentDb/Services/CosmosDbWorkflowStoreBase.cs
- src/persistence/Elsa.Persistence.DocumentDb/TenantProvider.cs
1. Cleaned up the duplicate code
2. Enhanced the cosmos DB persistence assembly to inject the custom logic for handling tenants
3. Enhanced to inject the custom logic in Cosmos DB CURD operations
> Cosmos DB persistence layer refactoring

- src/dashboard/Elsa.Dashboard/Conventions/ElsaConvention.cs
RouteValues dictionary will not have area as a key all the time if in-case we have controllers without areas
> Added null checks in ControllerModelConvention

- src/core/Elsa.Abstractions/Services/Models/WorkflowExecutionContext.cs
- src/core/Elsa.Core/Activities/ControlFlow/Finish/Finish.cs
- src/core/Elsa.Core/Activities/ControlFlow/Join/Join.cs
- src/core/Elsa.Core/Handlers/RescheduleBranchingActivitiesAndContainers.cs
- src/core/Elsa.Core/Services/WorkflowRunner.cs
The changes in this PR improve the behavior of the Finish activity so that:
* It can be used within composite activities to exit early while also cleaning up any blocking activities + contained scopes
* It can be used within the workflow itself (root composite activity) to complete the workflow directly while cleaning up any blocking activities.
> Improve Finish activity

- .gitignore
- .vscode/tasks.json
- Elsa.code-workspace
- Elsa.sln
- src/core/Elsa.Abstractions/Models/Variables.cs
- src/core/Elsa.Abstractions/Services/Models/ActivityExecutionContext.cs
- src/core/Elsa.Abstractions/Services/Models/WorkflowExecutionContext.cs
- test/shared/Elsa.Testing.Shared/AutoFixture/Attributes/AutofixtureServiceProviderAttribute.cs
- test/shared/Elsa.Testing.Shared/AutoFixture/Attributes/OmitOnRecursionAttribute.cs
- test/shared/Elsa.Testing.Shared/AutoFixture/SpecimenBuilders/AutofixtureServiceProviderSpecimenBuilder.cs
- test/shared/Elsa.Testing.Shared/Elsa.Testing.Shared.csproj
- test/unit/Elsa.UnitTests/AutoMoqDataAttribute.cs
- test/unit/Elsa.UnitTests/Elsa.UnitTests.csproj
- test/unit/Elsa.UnitTests/Models/VariablesTests.cs
- test/unit/Elsa.UnitTests/Services/Models/ActivityExecutionContextTests.cs
- test/unit/Elsa.UnitTests/Services/Models/WorkflowExecutionContextTests.cs
Both `ActivityExecutionContext` and `WorkflowExecutionContext` have a new method `PurgeVariables()` which clears all variables from the current workflow instance.
Further details in commit messages.
> Resolves #485 - Add PurgeVariables functionality

- appveyor.yml
- test/unit/Elsa.UnitTests/Activities/Signaling/SignalReceivedTests.cs
It actually turns out that no change is required to the `SignalReceived`
activity in order to achieve this.  As these unit tests prove & document,
that is already the current behaviour.
The only risks I see is that I have either:
* Misunderstood how an `OutputResult` is used when part of a `CombinedResult` - it certainly seems that this is the endorsed way of communicating "Activity output"
* Misunderstood the intended meaning of `Signal.Input` - presumably this is the expected manner in which "Input" will be provided when triggering a signal
> Resolve #486 - Signal input is emitted as output

- src/samples/Sample25/DataProcessingWorkflow.cs
The activity I removed would never have been executed, because it is
not connected from either of the IfElse branches.
Since this is Elsa 1.x, I've fixed it using the cheapest/quickest possible
solution which is to just remove the misleading part of the sample.
> Resolve #548 - improperly connected activity

- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Configuration/BookmarkConfiguration.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Configuration/WorkflowDefinitionConfiguration.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Configuration/WorkflowInstanceConfiguration.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Migrations/20210308174917_AddIndicies.Designer.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Migrations/20210308174917_AddIndicies.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/20210308175249_AddIndicies.Designer.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/20210308175249_AddIndicies.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Sqlite/Migrations/20210308201030_AddIndicies.Designer.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Sqlite/Migrations/20210308201030_AddIndicies.cs
- src/samples/persistence/Elsa.Samples.Persistence.EntityFramework/Elsa.Samples.Persistence.EntityFramework.csproj
- src/samples/persistence/Elsa.Samples.Persistence.EntityFramework/HelloWorld.cs
- src/samples/persistence/Elsa.Samples.Persistence.EntityFramework/Program.cs
#709 
Added a number of indices to the EF context configuration.    
* multi-column: I tried to target the calls that the background services make
* single-column: these will help UIs filter/sort by the various fields
I've deployed/migrated all three providers and ran the sample app.
Note that the nvarchar SQL Server columns affected by this PR have been changed from `nvarchar(max)` to `nvarchar(450)` because:
A) SQL Server cannot index `varchar(max)` fields
B) Older verions have a 900 byte size limit to indices
> Indicis for EF Providers

- test/integration/Elsa.Core.IntegrationTests/Autofixture/HostBuilderWithDuplicateActivitiesWorkflowAttributes.cs
- test/integration/Elsa.Core.IntegrationTests/Elsa.Core.IntegrationTests.csproj
- test/integration/Elsa.Core.IntegrationTests/Persistence/WorkflowMayContainDuplicateActivitiesIntegrationTests.cs
- test/integration/Elsa.Core.IntegrationTests/Workflows/DuplicateActivitiesWorkflow.cs
As noted in the discussion for #683 - the issue is no longer relevant as-reported.  There might be some further consideration to be had as to _whether or not we truly wish to permit duplicate activity IDs_, but that is a conversation which does not necessarily need to happen right now.
> Resolve #683 - Tests to prove no exception

- Elsa.sln
- src/activities/Elsa.Activities.Http/Activities/HttpEndpoint/HttpEndpoint.cs
- src/activities/Elsa.Activities.Telnyx/Activities/AnswerCall.cs
- src/activities/Elsa.Activities.Telnyx/Activities/GatherUsingAudio.cs
- src/activities/Elsa.Activities.Telnyx/Activities/HangupCall.cs
- src/activities/Elsa.Activities.Telnyx/Activities/TransferCall.cs
- src/clients/Elsa.Client/Models/ActivityPropertyDescriptor.cs
- src/core/Elsa.Abstractions/Attributes/ActivityPropertyAttribute.cs
- src/core/Elsa.Abstractions/Design/PropertyCategories.cs
- src/core/Elsa.Abstractions/Metadata/ActivityPropertyDescriptor.cs
- src/core/Elsa.Core/Metadata/TypedActivityTypeDescriber.cs
- src/dashboards/blazor/ElsaDashboard.Shared/Surrogates/ActivityPropertyDescriptorSurrogate.cs
- src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx
- src/designer/elsa-workflows-studio/src/components/editors/monaco/elsa-monaco/elsa-monaco.tsx
- src/designer/elsa-workflows-studio/src/components/editors/workflow-editor/elsa-activity-editor-modal/elsa-activity-editor-modal.tsx
- src/designer/elsa-workflows-studio/src/index.html
- src/designer/elsa-workflows-studio/src/models/domain.ts
- src/designer/elsa-workflows-studio/src/plugins/if-plugin.tsx
- src/designer/elsa-workflows-studio/src/plugins/run-javascript-plugin.tsx
This PR adds the ability to group activities properties together by annotating them with a category. The workflow designer can take advantage of this information to display grouped properties under a separate tab. For example, the `HttpEndpoint` activity has a property called `TargetType` which is considered to be an "advanced" setting. Its property now looks like this in code:
```csharp
[ActivityProperty(Category = PropertyCategories.Advanced)]
public Type? TargetType { get; set; }
```
Notice that it now has a category of "Advanced".
The activity editor uses that information to display a separate tab called "Advanced":
When no category is specified, the property appears under the default "Properties" tab.
As an activity developer, you are free to use any string value for activity …
> Activity Property Categories

- src/activities/Elsa.Activities.Http/Models/StringValuesModel.cs
- test/unit/Elsa.UnitTests/Activities/Http/StringValuesModelTests.cs
Mostly this is non-controversial (details in the commit message but it's going to be real boring stuff).
_The only thing I wanted to flag up_ is that implementing `IConvertible` makes this class [non-CLS-compliant].  Right now, the assembly is not marked with the `CLSCompliantAttribute` and so we are not claiming to be CLS-compliant.  I am not sure how important CLS-compliance is to us though, generally speaking CLS-compliant libraries are more reusable across a wider variety of platforms.
* If we don't care about CLS compliance then _"nothing to see here, move along"_
* If we think we might care about CLS compliance then when we add `[assembly: CLSCompliant(true)]`, we need to add `[CLSCompliant(false)]` to this class
[non-CLS-compliant]: …
> Resolve #785 - improve API for StringValuesModel

- .gitignore
- src/core/Elsa.Abstractions/Exceptions/CannotSetActivityPropertyValueException.cs
- src/core/Elsa.Abstractions/Services/ActivityPropertyProviders.cs
- src/core/Elsa.Core/Activities/ControlFlow/ForEach/ForEachBuilderExtensions.cs
It seems that some work done in these commits, for the
file `ForEachBuilderExtensions` was responsible:
* 4807ace13c54f7395e322cd81e7395163e9f2b9c
* dfbba1e1762c870da1b6c258daed8a7cfc5e5423
A couple of the extension methods were missing out a `ToList()`
which later caused an `ArgumentException` when setting a property
value via reflection.
I also added an extra exception for the set-value logic.  This way,
if/when there is a problem, the exception will indicate which property
it was trying to set at the time.
> Fix build failure: ForEachWorkflowTests

- appveyor.yml
It looks like the docker credentials are incorrect, because
builds are failing with an auth problem.  For example build 2.0.0-preview7.1704:
https://ci.appveyor.com/project/sfmskywalker/elsa/builds/38438996#L6715
This can be re-enabled once the auth issue is fixed.  There should be
no real harm in disabling it, since it's not working at the moment anyway.
> Temporarily disable docker deployment

- .gitignore
- appveyor.yml
- src/core/Elsa.Abstractions/Exceptions/CannotSetActivityPropertyValueException.cs
- src/core/Elsa.Abstractions/Services/ActivityPropertyProviders.cs
- src/core/Elsa.Core/Activities/ControlFlow/ForEach/ForEachBuilderExtensions.cs
- src/core/Elsa.Core/ElsaOptions.cs
- src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs
As discussed in https://github.com/elsa-workflows/elsa-core/discussions/802 added method to options called `NoCoreActivities()` , this enables user of Elsa to easily control which of the core activities will be available. 
For example, to have only SetVariable activity:
`
services
.AddElsa(options => options
.NoCoreActivities()
.UseEntityFrameworkPersistence(ef => ef.UseSqlite())
.AddActivity<Elsa.Activities.Primitives.SetVariable>()
);
`
> Method to skip adding core activites automatically.

- src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequest.cs
This adds another content type to Send HTTP Requests activity to enable form posting as described in https://github.com/elsa-workflows/elsa-core/issues/811.
In addition it resolves Send HTTP Requests activity  Url bug described in https://github.com/elsa-workflows/elsa-core/issues/812.
> SendHttpRequest enhancement for form post as well as URL bug resolution

- appveyor.yml
- src/persistence/Elsa.Persistence.YesSql/Elsa.Persistence.YesSql.csproj
- src/persistence/Elsa.Persistence.YesSql/Migrations.cs
- src/persistence/Elsa.Persistence.YesSql/Services/DataMigrationManager.cs
- src/persistence/Elsa.Persistence.YesSql/Services/DatabaseInitializer.cs
- test/integration/Elsa.Core.IntegrationTests/Autofixture/WithPostgresYesSqlAttribute.cs
- test/integration/Elsa.Core.IntegrationTests/Elsa.Core.IntegrationTests.csproj
- test/integration/Elsa.Core.IntegrationTests/Persistence/YesSql/PostgresSqlYesSqlIntegrationTests.cs
From this point onwards, in order to run all of the tests, you must now have postgresql installed and running on your dev environment.  The credentials/config is:
* Database name: elsa-yessql
* Username: postgres (this is the default anyway)
* Password: Password12! (this matches AppVeyor's postgres password)
* Port: 5432 (this is the default anyway)
> Resolve #751 - Crash when using PostgreSql with YesSQL

- src/scripting/Elsa.Scripting.JavaScript/Services/PlainObjectResultConverter.cs
Add capability to handle "it was already the right type"
> Fix plain object result converter for same object type

- src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx
- src/designer/elsa-workflows-studio/src/models/domain.ts
This is my attempt on solving first part of the problem described in https://github.com/elsa-workflows/elsa-core/issues/781.
Sorting child activities based on output order should prevent lines from crossing left to right and vice versa.
However second part of the problem remains so https://github.com/elsa-workflows/elsa-core/issues/781 should remain open.
> Sort Child Activities Based On Output Order

- src/activities/Elsa.Activities.MassTransit/Activities/ReceiveMassTransitMessage/ReceiveMassTransitMessage.cs
- src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Controllers/TriggerMessageController.cs
- src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Messages/FirstMessage.cs
- src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Messages/IInterfaceMessage.cs
- src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Messages/SecondMessage.cs
- src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Startup.cs
- src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Workflows/InterfaceTestWorkflow.cs
With this PR, I will address this issues:
**Use interfaces as messages**
MassTransit strongly suggest to use interfaces as messages (see https://masstransit-project.com/usage/messages.html#messages).
Now, interfaces will implemented using GreenPipes and the given message type will never be the same as the originally defined interface.
I updated the MessageType check, using IsAssignableFrom rather than Equals.
**Updated Test-Project**
Additionally I added another Test-Endpoint and a Test-Workflow in the MassTransit example project to test this behaviour.
**Small typo in test-project**
Finally, I found a typo in the Test-Project classes and fixed this also.
If there are any codestyle issues or anything else, please let me know.
Hope this helps :)
> Fix to support Interfaces as MassTransit messages

- src/designer/elsa-workflows-studio/src/components/editors/properties/elsa-multi-text-property/elsa-multi-text-property.tsx
My change from https://github.com/elsa-workflows/elsa-core/pull/907 combined with some of the changes that were done in parallel made MultiText without Options not render at all.
This is small fix for that.
> Fix MultiText without options

- src/core/Elsa.Core/Serialization/Converters/ExceptionConverter.cs
Serialization Error. Case of a "Fault" Outcome using a single message string without "Exception". This serializer fails when a null value is received breakin the Designer. Now it's fixed.
Steps to reproduce this:
- Create a new Workflow in Elsa Designer 1
- Add a ReceiveHttpRequest with a path "/test1"
- Add a WriteHttpResponse
- Add another WriteHttpResponse
- Execute the workflow with "/test1"
WriteHttpResponse creates this fault that breaks the system:
return Fault("Response has already started");
> Serialization Error. Case of a "Fault" Outcome using a single message string.

- src/core/Elsa.Abstractions/Design/RuntimeSelectListItemsProviderSettings.cs
- src/designer/elsa-workflows-studio/src/components.d.ts
- src/designer/elsa-workflows-studio/src/components/controls/elsa-input-tags/elsa-input-tags-dropdown.tsx
- src/designer/elsa-workflows-studio/src/components/editors/properties/elsa-check-list-property/elsa-check-list-property.tsx
- src/designer/elsa-workflows-studio/src/components/editors/properties/elsa-dropdown-property/elsa-dropdown-property.tsx
- src/designer/elsa-workflows-studio/src/components/editors/properties/elsa-multi-text-property/elsa-multi-text-property.tsx
- src/designer/elsa-workflows-studio/src/models/domain.ts
- src/designer/elsa-workflows-studio/src/services/elsa-client.ts
- src/designer/elsa-workflows-studio/src/utils/select-list-items.ts
- src/samples/server/Elsa.Samples.Server.Host/Activities/VehicleActivity.cs
- src/server/Elsa.Server.Api/Endpoints/Designer/RuntimeSelectListItems/Get.cs
This PR adds the ability for developers to provide list option values to dropdown list controls used in the designer at runtime.
To provide values at runtime, implement `IActivityPropertyOptionsProvider` that returns an object of `RuntimeSelectListItemsProviderSettings`, which itself needs to return the class type that will provide the options. This provider needs to implement `IRuntimeSelectListItemsProvider`.
An example can be found in https://github.com/elsa-workflows/elsa-core/tree/feature/elsa-2.0/src/samples/server/Elsa.Samples.Server.Host by looking at the `VehicleActivity` that implements the necessary interfaces.
> Runtime List Options

- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Extensions/ServiceCollectionExtensions.cs
Migrations should auto-run by default if the user chose pooled Db Contexts.  They must not auto-run if they chose non-pooled contexts.
> Resolve #930 - EF migrations now auto-run again

- src/server/Elsa.Server.Api/ElsaApiOptions.cs
- src/server/Elsa.Server.Api/Extensions/ServiceCollectionExtensions.cs
- src/server/Elsa.Server.Api/RouteConstraints/CompatibilityApiVersionConstraint.cs
This PR is a result of a conversation on Discord where several users pointed out that their existing APIs didn't show up anymore in Swagger. It looks like this is being caused by Elsa adding API versioning services, which requires controllers to use `ApiControllerAttribute` - but some projects don't use this (yet).
With this change, the user can now customize API versioning configuration or disable it altogether.
> Introduce API options to customize or disable Api Versioning

- src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/Startup.cs
Moving `app.UseCors()` to the top of the Http Pipeline config fixes some CORS problems I found (closes #1039)
> Fix CORS issue in Dashboard Monolith sample project

- src/activities/Elsa.Activities.AzureServiceBus/Bookmarks/QueueMessageReceivedBookmark.cs
- src/activities/Elsa.Activities.AzureServiceBus/Bookmarks/TopicMessageReceivedBookmark.cs
- src/activities/Elsa.Activities.AzureServiceBus/Services/ServiceBusQueuesStarter.cs
- src/activities/Elsa.Activities.AzureServiceBus/Services/ServiceBusTopicsStarter.cs
- src/activities/Elsa.Activities.Entity/Bookmarks/EntityChangedBookmark.cs
- src/activities/Elsa.Activities.Http/Bookmarks/HttpEndpointBookmark.cs
- src/activities/Elsa.Activities.Http/Middleware/HttpEndpointMiddleware.cs
- src/activities/Elsa.Activities.MassTransit/Bookmarks/MessageReceivedBookmark.cs
- src/activities/Elsa.Activities.Rebus/Bookmarks/MessageReceivedBookmark.cs
- src/activities/Elsa.Activities.Temporal.Common/Bookmarks/CronBookmark.cs
- src/activities/Elsa.Activities.Temporal.Common/Bookmarks/StartAtBookmark.cs
- src/activities/Elsa.Activities.Temporal.Common/Bookmarks/TimerBookmark.cs
- src/core/Elsa.Abstractions/Bookmarks/BookmarkProviderContext.cs
- src/core/Elsa.Abstractions/Services/ActivityPropertyProviders.cs
- src/core/Elsa.Abstractions/Services/Models/ActivityBlueprintWrapper.cs
- src/core/Elsa.Abstractions/Services/Models/IActivityBlueprintWrapper.cs
- src/core/Elsa.Abstractions/Services/NullActivityPropertyValueProvider.cs
- src/core/Elsa.Core/Activities/Signaling/Activities/SignalReceived/SignalReceivedBookmark.cs
- src/core/Elsa.Core/Activities/Workflows/RunWorkflow/Bookmarks/RunWorkflowBookmark.cs
- src/core/Elsa.Core/Bookmarks/BookmarkIndexer.cs
- src/server/Elsa.Server.Api/Services/WorkflowBlueprintMapper.cs
Update activity property evaluation to store computed value as part of workflow instance state
This allows bookmarking to be optimized and fixes the issue when the system needs to access an activity's property from a workflow instance without having to re-evaluate the property value provider which may be impossible to do since there is no context.
A potential downside is increased workflow instance size, but this needs to be resolved as part of #898
> Update activity property evaluation to store computed value

- src/core/Elsa.Abstractions/Attributes/ActivityAttribute.cs
- src/core/Elsa.Abstractions/Metadata/ActivityDescriberExtensions.cs
- src/core/Elsa.Abstractions/Metadata/IDescribesActivityType.cs
- src/core/Elsa.Abstractions/Metadata/IOutcomesProvider.cs
- src/core/Elsa.Abstractions/Metadata/OutcomesProvider.cs
- src/core/Elsa.Core/ActivityTypeProviders/TypeBasedActivityProvider.cs
- src/core/Elsa.Core/Metadata/TypedActivityTypeDescriber.cs
This PR allows you to either provide a `string[]` value for an `ActivityDefinition`'s `Outcomes` property as normal, like so:
```csharp
[ActivityDefinition(Outcomes = new[] {"Done", "Cancelled", "Etc..."})]
```
And now also like so:
```csharp
[ActivityDefinition(Outcomes = typeof(MyOutcomesProvider))]
```
Where `MyOutcomesProvider` implements `IOutcomesProvider` or inherits from `OutcomesProvider`, like so:
```csharp
public class MyOutcomesProvider : OutcomesProvider
{
protected override IEnumerable<string> GetOutcomes() => new[] { "Dynamic Outcome 1", "Dynamic Outcome 2" };
}
```
Fixes #873
> Add support for dynamic outcome provider

- src/activities/Elsa.Activities.AzureServiceBus/Activities/SendAzureServiceBusMessage/AzureServiceBusSendActivity.cs
- src/activities/Elsa.Activities.AzureServiceBus/Activities/SendAzureServiceBusMessage/SendAzureServiceBusQueueMessage.cs
- src/activities/Elsa.Activities.AzureServiceBus/Activities/SendAzureServiceBusMessage/SendAzureServiceBusTopicMessage.cs
- src/activities/Elsa.Activities.AzureServiceBus/Extensions/MessageBodyExtensions.cs
This PR give the ability for the user to specify a MessageModel object as the input of the Activity.
This allow the user to customize a lot of property of the Brocker Service Message like SystemProps and User Props.
Today this can be use in Code and we can think about new Activity like CreateServiceBusMessage to have UI to create this kind of object using the Designer
> add capability to use MessageModel as the input of the Azure Service Bus Sender

- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.MySql/DbContextOptionsBuilderExtensions.cs
TargetFramework: net5.0
MySql: 10.4.8-MariaDB
```c#
services
.AddElsa(elsa => elsa
.UseEntityFrameworkPersistence(ef => ef.UseMySql("Server=*;port=*;UserId=*;Password=*;Database=elsa;"))
.AddConsoleActivities()
.AddHttpActivities(opt => opt.BaseUrl = new Uri(appSettings.BaseUrl))
.AddQuartzTemporalActivities()
.AddActivitiesFrom<Startup>()
.AddWorkflowsFrom<Startup>()
);
```
System.InvalidOperationException:
“A schema "Elsa" has been set for an object of type "CreateTableOperation" with the name of "__EFMigrationsHistory". MySQL does not support the EF Core concept of schemas. Any schema property of any "MigrationOperation" must be null. This behavior can be changed by setting the `SchemaBehavior` option in the `UseMySql` call.”
ignore the schema, see …
> Fix MySql does not support the EF Core concept of schemas

- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Extensions/MySqlDatabaseFacadeExtensions.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Extensions/QueryableBulkExtensions.cs
TargetFramework: net5.0
MySql: 10.4.8-MariaDB
handle an incoming HTTP request:
```
ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
string.Substring(int startIndex, int length)
EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlServerDialect.GetBatchSqlReformatTableAliasAndTopStatement(string sqlQuery)
EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, bool isUpdate)
EFCore.BulkExtensions.BatchUtil.GetSqlDelete(IQueryable query, DbContext context)
EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchDeleteArguments(IQueryable query)
EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync(IQueryable query, CancellationToken cancellationToken)
Elsa.Persistence.EntityFramework.Core.Extensions.QueryableBulkExtensions.Batch …
```
> Fix EFCore.BulkExtensions does not support MySQL

- src/activities/Elsa.Activities.Conductor/Elsa.Activities.Conductor.csproj
- src/activities/Elsa.Activities.Http/Elsa.Activities.Http.csproj
- src/activities/Elsa.Activities.Http/Parsers/JsonHttpResponseBodyParser.cs
- src/activities/Elsa.Activities.Webhooks/Elsa.Activities.Webhooks.csproj
- src/dashboards/ElsaDashboard/ElsaDashboard.Web.csproj
- src/designer/bindings/aspnet/Elsa.Designer.Components.Web/Elsa.Designer.Components.Web.csproj
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.MySql/Elsa.Persistence.EntityFramework.MySql.csproj
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Elsa.Persistence.EntityFramework.PostgreSql.csproj
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Elsa.Persistence.EntityFramework.SqlServer.csproj
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Sqlite/Elsa.Persistence.EntityFramework.Sqlite.csproj
- src/server/Elsa.Server.Api/Elsa.Server.Api.csproj
- src/server/Elsa.Server.Orleans/Elsa.Server.Orleans.csproj
Hi,
I created this pull request as an attempt to support multi targeting both .NET Core 3.1 and .NET 5 for Elsa 2.
I have not included any multi targeting on samples or tests right now.
I have tested by running monolith sample while targeting .NET Core 3.1 instead of .NET 5.
> Multi targeting for .NET Core 3.1 and .NET 5

- src/core/Elsa.Abstractions/Builders/ISetupActivity.cs
- src/core/Elsa.Core/Builders/SetupActivity.cs
This solves #1146.
I needed to leave existing methods in ISetupActivity and SetupActivity because when I tried to move them to SetupActivityExtensions it started complaining that `propertyAccessor.GetProperty()` is not accessible/defined.
So I'll leave that to someone more clever than I am :)......
> Enabling directly named properties used using SetupActivity (not just through C# property name)

- src/core/Elsa.Abstractions/Extensions/StateDictionaryExtensions.cs
Which allows for normal usage of Dictionaries inside state....
This relates to problem described in #1145.
I wasn't sure when `state` could be `null` so I left it to behave as before (returning temporary object/default value).
> State sets default value if get doesn't find it

- src/core/Elsa.Core/Services/Workflows/WorkflowPublisher.cs
When an unpublished workflow is published, IsLatest is not set to false because the PublishAsync method was only looking for published workflows.
> fix: Reset IsLatest also for not published workflows on PublishAsync

- src/activities/Elsa.Activities.AzureServiceBus/Extensions/ServiceCollectionExtensions.cs
- src/activities/Elsa.Activities.Conductor/Extensions/ElsaOptionsBuilderExtensions.cs
- src/core/Elsa.Core/ElsaOptions.cs
- src/core/Elsa.Core/ElsaOptionsBuilder.cs
- src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs
- src/core/Elsa.Core/Services/Messaging/ServiceBusFactory.cs
- src/core/Elsa.Core/StartupTasks/CreateSubscriptions.cs
This PR allows Rebus message types to be read from and sent to the same queue, decreasing the number of queues necessary.
> Reuse certain queues for certain event types

- src/core/Elsa.Core/Services/Workflows/WorkflowStarter.cs
I forgot to pass `TenantId` at `InstantiateAsync`
> Pass TenantId as parameter (Fix: #1307)

- src/core/Elsa.Abstractions/Models/WorkflowPersistenceBehavior.cs
- src/core/Elsa.Abstractions/Services/Workflows/IWorkflowExecutionLog.cs
- src/core/Elsa.Core/Handlers/FlushWorkflowExecutionLog.cs
- src/core/Elsa.Core/Handlers/PersistWorkflow.cs
- src/core/Elsa.Core/Services/Workflows/WorkflowExecutionLog.cs
- src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-settings-modal/elsa-workflow-settings-modal.tsx
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkStore.cs
- src/scripting/Elsa.Scripting.JavaScript/Handlers/ConfigureJavaScriptEngine.cs
- test/integration/Elsa.Core.IntegrationTests/Persistence/InMemory/InMemoryStoreIntegrationTests.cs
- test/integration/Elsa.Core.IntegrationTests/Workflows/ForkJoinWorkflowTests.cs
- test/integration/Elsa.Core.IntegrationTests/Workflows/PersistableWorkflow.cs
- test/shared/Elsa.Testing.Shared/Unit/WorkflowsUnitTestBase.cs
This PR reduces the number of database commits that happen during the execution of a workflow in the following ways:
- Activity execution log records are now only committed at the same time the workflow instance is persisted (as opposed to writing execution log records as soon as they are created).
- The `PersistWorkflow` handler now handles less notifications to achieve a more sane number of times the workflow instance is being written.
Closed #1410
> Flush activity execution log

- Elsa.sln
- src/core/Elsa.Core/Persistence/Specifications/WorkflowInstances/WorkflowCreatedBeforeSpecification.cs
- src/core/Elsa.Core/Persistence/Specifications/WorkflowInstances/WorkflowStatusSpecification.cs
- src/modules/Elsa.Retention/Elsa.Retention.csproj
- src/modules/Elsa.Retention/Extensions/ServiceCollectionExtensions.cs
- src/modules/Elsa.Retention/HostedServices/CleanupService.cs
- src/modules/Elsa.Retention/Jobs/CleanupJob.cs
- src/modules/Elsa.Retention/Options/CleanupOptions.cs
- src/samples/server/Elsa.Samples.Server.Host/Elsa.Samples.Server.Host.csproj
- src/samples/server/Elsa.Samples.Server.Host/Startup.cs
- src/samples/server/Elsa.Samples.Server.Host/appsettings.json
This PR adds a background service that periodically removes workflow instances and related records.
It allows you to configure:
- Sweep interval (how often the database is queried for outdated records).
- Time to live: how long workflow instances are allowed to exist.
- Page size: how many records to delete at a given time. This prevents huge amounts of records to be loaded in memory in one go. Instead, the job will load pages of data and keep deleting them until no results are left.
> Implement retention service

- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx
When there are no selected activities (.selectedActivities is undefined) it is defaulted  to empty object
> #1598: Context Menu not disasppearing issue fixed

- src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-journal/elsa-workflow-instance-journal.tsx
This adds a Variables Tab to the workflow instance viewer as discussed in https://github.com/elsa-workflows/elsa-core/issues/2413
> add variables tab to instance view

- src/designer/elsa-workflows-studio/src/components/controls/elsa-monaco/elsa-monaco.tsx
Removing allowJs option does not seem to be having any negative sides and it fixes the issue when properties form already entered expression always appear in intellisense (e.g. for "return test.prop." intellisense will suggest both "test" and "prop" as valid options even when they are not).
> Fixes #2417

- src/activities/Elsa.Activities.AzureServiceBus/Services/BusClientFactory.cs
Moved return statement inside try block, otherwise finally block which releases semaphore could sometimes not be executed, causing semaphore to hold lock indefinitely.
> Fix for semaphore issue in AzureServiceBus activities

- src/core/Elsa.Core/Elsa.Core.csproj
- src/core/Elsa.Core/Services/Workflows/WorkflowRunner.cs
Like discussed on discord - reuse the workflowexecution scope - and do not create a new one
> do not create a new Scope - reuse workflowExecutionContext's scope

- src/clients/Elsa.Client/ElsaClient.cs
- src/clients/Elsa.Client/Extensions/ServiceCollectionExtensions.cs
- src/clients/Elsa.Client/IElsaClient.cs
- src/clients/Elsa.Client/Services/IScriptingApi.cs
Exposes `/v1/scripting/javascript/type-definitions` endpoint through the client to allow consumers to easily access definition files.
> Add scripting api to elsa client

- test/integration/Elsa.Core.IntegrationTests/Workflows/TimerWorkflow.cs
- test/integration/Elsa.Core.IntegrationTests/Workflows/TimerWorkflowTests.cs
- test/shared/Elsa.Testing.Shared/Unit/WorkflowsUnitTestBase.cs
I was investigating how to test workflows with Timers and realized that it would be much simpler to do if you had the ability to inject elsa options into WorkflowsUnitTestBase. I also added a test for a workflow with a timer to demonstrate how to use it
> Testing workflows with Timers

- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx
This fixes the exception when importing an definition and no history is available!
https://github.com/elsa-workflows/elsa-core/issues/2595
> fixes an exception is no history is available

- src/clients/Elsa.Client/Models/GetTypeScriptDefinitionFileRequest.cs
- src/clients/Elsa.Client/Services/IScriptingApi.cs
Small fix to keep up to date with recent changes.
9f36d668 updated the JavaScript TypeDefinitions endpoint `Elsa.Server.Api/Endpoints/Scripting/JavaScript/TypeDefinitions/Get.cs` to use POST instead of GET.
> Update scripting client to use POST endpoint method

- src/core/Elsa.Core/Providers/ActivityTypes/TypeBasedActivityProvider.cs
Allow Composite Activity or other subclass to not explicitly defined [Browsable(true)] if base class define [Browsable(false)]
refer to #2651
> Do not force Browsable of SubActivity to false if not defined.

- src/activities/Elsa.Activities.AzureServiceBus/Activities/SendAzureServiceBusMessage/AzureServiceBusSendActivity.cs
- src/activities/Elsa.Activities.AzureServiceBus/ActivityExecutionResults/ServiceBusActionResult.cs
- src/core/Elsa.Abstractions/ActivityResults/SuspendResult.cs
- src/core/Elsa.Core/Handlers/ExecuteWorkflowsPostSuspensionTasks.cs
- test/integration/Elsa.Core.IntegrationTests/Elsa.Core.IntegrationTests.csproj
- test/integration/Elsa.Core.IntegrationTests/Workflows/ServiceBusWorkflowTest.cs
This PR is a the first of Azure Service Bus Enhancement #753  , that allow to use Fire and Forget for the Topic Sender.
This allow to wait before sending the Message to the Service Bus. 
With this, we can wait for the next suspend and use a Service Bus Received Activity to receive the response. If not setting FireAndForget to false, we can have side effect and receive the message using the Topic Worker before the BookMark with Correlation Id was correctly set.
The default value is True to avoid breaking change (sent directly)
> Azure Service Bus Enhancement - Add Fire And Forget Option

- src/scripting/Elsa.Scripting.Liquid/Handlers/ConfigureLiquidEngine.cs
This fixes the issue where ExpandoObjects (sourced eg. from JSON content posted to the workflow) would be interpreted by Fluid as a Dictionary, rather than an Object.
This caused unexpected results, for exmaple when converting the object to JSON.
> Update Liquid engine to treat ExpandoObject as ObjectValue rather than a dictionary type.

- src/clients/Elsa.Client/Models/SaveWorkflowDefinitionRequest.cs
- src/clients/Elsa.Client/Models/WorkflowDefinition.cs
Updates client workflow definition models to match the API.
`SaveWorkflowDefinitionRequest.cs`: 
- Adds Tag and Channel properties
- Changes Variables to be a string
`WorkflowDefinition.cs`:
- Adds CustomAttributes
- Changes Variables to be a string as this is the actual return type after the `VariablesConverter` is ran
> Update Elsa.Client workflow definition models to match Elsa.Server

- src/activities/Elsa.Activities.Rebus/Extensions/PublishRebusMessageExtensions.cs
- src/activities/Elsa.Activities.Rebus/Extensions/RebusMessageReceivedExtensions.cs
- src/activities/Elsa.Activities.Rebus/Extensions/SendRebusMessageExtensions.cs
This pull request is to add convenience Extension Methods for setting properties on Rebus Activities, following the 'with*' naming convention. The Extension methods included are:
- `WithMessage` & `WithHeaders` (for _SendRebusMessage_ & _PublishRebusMessage_ Activites)
- `WithMessageType` (_RebusMessageReceived_ Activity)
> Extension Methods for Rebus Activities

- src/persistence/Elsa.Persistence.MongoDb/Extensions/ServiceCollectionExtensions.cs
Added missing .AddSingleton(sp => sp.GetRequiredService<TDbContext>().Triggers);
> Mongo dependency registration missing for Triggers

- src/core/Elsa.Core/Activities/ControlFlow/ForEach/ForEach.cs
This PR optimizes the ForEach Items property - to use IEnumerable type - this way any collection can be assigned - and there is no need that the EnumerableResultConverter needs to Serialize and Deserialize the collection - since desiredType.IsAssignableFrom(enumerable.GetType() gives True - and returns the enumarable as is.
> Optimize ForEach activity

- src/activities/Elsa.Activities.File/Activities/DeleteFile/DeleteFile.cs
Copy ActivityInput attribute fields from ReadFile.Path to DeleteFile.Path to enable programmatically filling the Path property from Elsa Dashboard.
Confirmed working in Elsa Dashboard Monolith sample.
> Make DeleteFile.Path attributes match ReadFile.Path

- src/designer/elsa-workflows-studio/src/services/elsa-client.ts
In the `createHttpClient` function, assigning the `HttpClient` singleton after awaiting other operations allows a quick succession of calls to `#createHttpClient` to instantiate multiple `HttpClient` instances and overwrite the singleton instance.
Performing creation and assignment of the `HttpClient` before any asynchronous operations ensures that sequential invocations of `#createHttpClient` operate on the same `HttpClient` instance.
The sequence of operations is _roughly_ as follows:
Currently, creation of the `HttpClient` instance takes place in step `A1` and `A2`. Assignment take place in steps `B1` and `B2`.
This causes the `HttpClient` singleton to be overwritten when `createElsaClient` is invoked before a previous execution has completed.
Moving assignment of the `HttpClient` …
> Ensure the front-end HttpClient is only created once

- src/activities/Elsa.Activities.Email/Activities/SendEmail/SendEmail.cs
Hi @sfmskywalker - it currently happens that in the SendEmail activity - when you enter something in the attachment field (default or javascript) - and then delete the whole string in der designer - that the Attachment property contains an empty string ( "" ) - which then leads to an error because it tries to attach an file - where the string is empty.
i added 2 checks where for the string case!
> Optimize string checking for Attachment

- src/designer/elsa-workflows-studio/src/components/designers/tree/elsa-designer-tree/elsa-designer-tree.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-test-panel/elsa-workflow-test-panel.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-test-panel/localizations.ts
- src/designer/elsa-workflows-studio/src/services/elsa-client.ts
- src/modules/workflowtesting/Elsa.WorkflowTesting.Api/Endpoints/Execute.cs
- src/modules/workflowtesting/Elsa.WorkflowTesting.Api/Models/WorkflowTestExecuteResponse.cs
Currently, when workflow is executed from test panel and there is already an instance of this workflow running (typical scenario - execute workflow with blocking activity and refresh the page) - there is no feedback telling user what exactly is going on. Developer tools will display 404 error, but that tells very little as well.
I've added confirmation modal for this scenario, that is asking if user wants to stop current instance and start a new one.
> Workflow Testing UI Improvement

- src/designer/elsa-workflows-studio/src/components/editors/properties/elsa-dropdown-property/elsa-dropdown-property.tsx
This is a quick fix for issue https://github.com/elsa-workflows/elsa-core/issues/2604
I tested with Join activity.
By default the designer UI has Mode set to undefined until change event is triggered. The activity still works because enum type takes first value as default.
> Fix dropdown default value from select list

- src/activities/webhooks/Elsa.Webhooks.Persistence.YesSql/Elsa.Webhooks.Persistence.YesSql.csproj
- src/core/Elsa.Core/Elsa.Core.csproj
- src/core/Elsa.Core/Extensions/PrimitiveExtensions.cs
This PR updates Elsa to use Automapper Version 11 as the latest supported version
> Bump Automapper Version to 11

- src/activities/Elsa.Activities.AzureServiceBus/Services/Worker.cs
As the worker is created under WorkerManager.cs as per
```
worker = ActivatorUtilities.CreateInstance<Worker>(_serviceProvider, queueOrTopic, subscription ?? "", RemoveWorkerAsync);
```
The case of
```
subscription == null 
```
will never be fired and it will try to process a subscription with a empty name. This causes the Error event handler to be called which then disposes of the _processor early resulting in the following error.
System.ObjectDisposedException: The message processor is unable to continue and will stop processing; the host application has closed the connection to the Service Bus service. Object name: 'ServiceBusConnection'.
This pull request fixes this scenario where a queue is used, and not a topic/subscription model.
> Fixing the Azure Worker Processor

- src/activities/Elsa.Activities.Http/Middleware/HttpEndpointMiddleware.cs
- src/server/Elsa.Server.Api/Endpoints/WorkflowDefinitions/Models.cs
- src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/List.cs
- src/server/Elsa.Server.Api/Swagger/Examples/WorkflowDefinitionSummaryModelExample.cs
This solves #2989 ([11bfcfd](https://github.com/elsa-workflows/elsa-core/pull/2992/commits/11bfcfdae66a4c22165f5f172150d6884885a8e8)) and #2994 ([44ae915](https://github.com/elsa-workflows/elsa-core/pull/2992/commits/44ae9158fe1d318c33c9bbb75e944be1a5466a4a)) and #2861 ([8f5cde7](https://github.com/elsa-workflows/elsa-core/pull/2992/commits/8f5cde76aab4feaa62a6f2c58adeef0b6de7d08a)).
> Various ITenantAccessor/Multitenancy fixes

- src/designer/elsa-workflows-designer/src/components.d.ts
- src/designer/elsa-workflows-designer/src/components/activities/flowchart/flowchart.tsx
- src/designer/elsa-workflows-designer/src/components/designer/canvas/canvas.tsx
- src/designer/elsa-workflows-designer/src/components/designer/workflow-editor/workflow-editor.tsx
- src/designer/elsa-workflows-designer/src/components/shell/studio/studio.tsx
- src/designer/elsa-workflows-designer/src/index.html
- src/designer/elsa-workflows-designer/src/index.ts
- src/designer/elsa-workflows-designer/src/services/activity-name-formatter.ts
- src/designer/elsa-workflows-designer/src/services/index.ts
- src/designer/elsa-workflows-designer/src/utils/utils.ts
This PR adds a designer feature that will autogenerate activity names. Example:
The default naming strategy is *camel case**, but there are other ones available. This is the list out of the box:
- PascalCaseStrategy
- CamelCaseStrategy
- SnakeCaseStrategy
- KebabCaseStrategy
Additionally, custom strategies can be configured.
Here's an example demonstrating how to configure a strategy from the HTML page hosting the designer:
```html
<script type="module">
// Import publicly exposed plugins, services and models to use in vanilla JavaScript.
import {Container, ActivityNameFormatter} from "/build/index.esm.js"; // Use NPM package once released.
// Get a reference to the ActivityNameFormatter.
const activityNameFormatter = Container.get(ActivityNameFormatter); // Using service locator to get a …
```
> Auto name activity

- src/activities/Elsa.Activities.BlobStorage/Elsa.Activities.BlobStorage.csproj
- src/activities/Elsa.Activities.File/Elsa.Activities.File.csproj
- src/core/Elsa.Abstractions/Elsa.Abstractions.csproj
As discussed in #3018.
Remove dependency from a preview version of a dependency: `System.ComponentModel.Annotations Version=6.0.0-preview.4.21253.7` and use the latest stable version `5.0.0`.
Remove from _Elsa.Abstractions_ project the dependency on `System.ComponentModel.Annotations` as it's own code does not depend on it.
Add `System.ComponentModel.Annotations Version=5.0.0` to the correct projects that depend on this package: _Elsa.Activities.File_ and _Elsa.Activities.BlobStorage_.
> Refactor System.ComponentModel.Annotations dependencies.

- src/activities/Elsa.Activities.File/Services/FileSystemWatchersStarter.cs
- src/core/Elsa.Abstractions/Services/Triggers/ITriggerRemover.cs
- src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs
- src/core/Elsa.Core/Services/Triggers/TriggerRemover.cs
**Original Issue**
A malformed path would crash the program on startup because the `Directory.CreateDirectory` method would throw an unhandled exception. This is a bigger issue if the workflow is persistent since the trigger will get created but there isn't a way to remove it if something goes wrong. Meaning that if you use a `WatchDirectory` activity with an invalid path the project will fail to start until you change or remove the trigger in your database.
**How to create the original error**
I used the project `ElsaDashboard.Samples.AspNetCore.Monolith` in the samples directory for testing since it already has Elsa server setup with SQLite as the persistence provider.
I added file activities using `AddFileActivities()` in the Startup file and  I started up the project. I created a new …
> Remove triggers that have a malformed path

- src/activities/Elsa.Activities.Http/Activities/HttpEndpoint/HttpEndpoint.cs
- src/activities/Elsa.Activities.Http/Activities/HttpEndpoint/HttpEndpointBuilderExtensions.cs
- src/activities/Elsa.Activities.Http/Activities/HttpEndpoint/HttpEndpointExtensions.cs
- src/activities/Elsa.Activities.Http/Activities/Redirect/Redirect.cs
- src/activities/Elsa.Activities.Http/Activities/Redirect/RedirectBuilderExtensions.cs
- src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequest.cs
- src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequestBuilderExtensions.cs
- src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequestExtensions.cs
- src/activities/Elsa.Activities.Http/Activities/WriteHttpResponse/WriteHttpResponseBuilderExtensions.cs
- src/activities/Elsa.Activities.Http/Activities/WriteHttpResponse/WriteHttpResponseExtensions.cs
- src/core/Elsa.Abstractions/Builders/IBuilder.cs
- src/core/Elsa.Core/Builders/BuilderExtensions.cs
When I create workflows using the Elsa I use the Builder API.
There is a sparse amount of XML code comments on the methods and properties so the learning curve to using the Builder API is pretty steep.
So, this is a venture to add XML code comments to Elsa. Hopefully making it easier for new users to pick it up. This PR focuses on the HTTP activities.
---
A large majority of the builder extensions are exactly the same with some of the parameter types changed around so `inheritdoc` is used quite a bit. This also means that if the maintainers of elsa-core don't think that a comment is accurate a whole swath of them can be changed rather easily.
> Add XML Code Comments For The HTTP Activities

- src/core/Elsa.Core/Providers/WorkflowStorage/BlobStorageWorkflowStorageProvider.cs
Adding `await _blobStorage.SetBlobAsync(blob, cancellationToken);` to persist changes to the metadata so binary data is correctly delt with when read back.
#3115
> Persist blob metadata changes

- src/core/Elsa.Abstractions/Attributes/ActivityInputObjectAttribute.cs
- src/core/Elsa.Abstractions/Services/Workflows/ActivityPropertyProviders.cs
- src/core/Elsa.Core/Metadata/TypedActivityTypeDescriber.cs
- src/core/Elsa.Core/Services/Workflows/ActivityActivator.cs
Expanding ActivtyInput functionality to allow classes to be used for re-usable input properties across activities.
The ActivityInputObjectAttribute identifies a class to extract ActivityInputs from.
A category can be provided on the ActivityInputObjectAttribute that will be added to all of the properties in that class that don't provide their own category.
```` csharp
[ActivityInputObject(Category ="Example Category")]
public ExtraProperties Example { get; set; }
````
The properties will appear in the designer form as if they were added directly to the activity.
```` csharp
public class ExtraProperties
{
[ActivityInput(Hint = "The base URL.",
UIHint = ActivityInputUIHints.SingleLine,
SupportedSyntaxes = new[] { SyntaxNames.Literal, SyntaxNames.Liquid, SyntaxNames.JavaScript })]
public …
```
> Define inputs in reusable objects

- src/core/Elsa.Abstractions/Models/ActivityDefinition.cs
This change will fix an issue where PropertyStorageProviders on ActivityDefinition isn't be read or written in MongoDB
https://github.com/elsa-workflows/elsa-core/blob/6daa8e456e8a3ab2b20da20d214626f259881b1f/src/core/Elsa.Abstractions/Models/ActivityDefinition.cs#L16
As discussed in #3103, mongo by default ignores read only properties so the PropertyStorageProviders selected in the designer is never persisted.
Adding the setter allows mongo to read and write and doesn't appear cause any issues elsewhere.
> Mongo db can't write to read only properties

- src/activities/Elsa.Activities.Email/Activities/SendEmail/SendEmail.cs
If attachments object is empty string, ignore and return from method.
Fixes #3162
> Check if attachments object is empty string

- src/persistence/Elsa.Persistence.MongoDb/Services/DatabaseRegister.cs
Correcting issue #2998.
Adding try catch around the registration instead of if (BsonSerializer.LookupSerializer<JObjectSerializer>() == null).
As mentioned in the issue, BsonSerializer.LookupSerializer is not being used for the correct purpose here.
https://github.com/elsa-workflows/elsa-core/blob/f2fa88f42f30e9db4f68d948ca02b9f8d28889b1/src/persistence/Elsa.Persistence.MongoDb/Services/DatabaseRegister.cs#L63-L64
It will try and find a serializer for VariablesSerializer (MongoDB.Bson.Serialization.BsonClassMapSerializer<Elsa.Persistence.MongoDb.Serializers.VariablesSerializer>) if it doesn't find one then it will create one and return that.
This means those serializers never get registered.
I believe this issue is also the cause of https://github.com/elsa-workflows/elsa-core/issues/3008
> Mongo serializer registration

- src/core/Elsa.Core/Activities/ControlFlow/Join/Join.cs
- test/integration/Elsa.Core.IntegrationTests/Workflows/ForkEagerJoinWorkflow.cs
- test/integration/Elsa.Core.IntegrationTests/Workflows/ForkJoinWorkflowTests.cs
- test/unit/Elsa.UnitTests/Models/SimpleStackTests.cs
Another aspect of the recently added eager join option is that of branch order. You will get a little bit different behavior dependent on in which branch the block activity is. If the blocking activity is executed before the joining branch it will be cleared, but if the blocking activity is executed after the joining branch it will be blocking after the execution, because it was not blocking at the time of the join, it was scheduled.
With this PR a join of an EagerJoin will also clear all scheduled activities inside the fork, effectively stopping all execution.
If you don't think that this should be the behavior of EagerJoin, perhaps this could be added as another option to the Join?
> If eager join is set, clear scheduled activities on join

- src/activities/Elsa.Activities.Http/Services/DefaultHttpEndpointWorkflowFaultHandler.cs
- src/core/Elsa.Abstractions/Models/WorkflowInstance.cs
- src/core/Elsa.Abstractions/Services/Models/WorkflowExecutionContext.cs
- src/core/Elsa.Core/Activities/ControlFlow/Join/Join.cs
- src/core/Elsa.Core/Activities/Workflows/RunWorkflow/Helper/HashHelper.cs
- src/core/Elsa.Core/Activities/Workflows/RunWorkflow/RunWorkflow.cs
- src/core/Elsa.Core/Handlers/CompensateWorkflow.cs
- src/core/Elsa.Core/Services/Workflows/WorkflowReviver.cs
- src/designer/elsa-workflows-studio/src/components/editors/properties/elsa-dropdown-property/elsa-dropdown-property.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-journal/elsa-workflow-instance-journal.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-viewer-screen/elsa-workflow-instance-viewer-screen.tsx
- src/designer/elsa-workflows-studio/src/models/domain.ts
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Configuration/WorkflowInstanceConfiguration.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkWorkflowInstanceStore.cs
- src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/Retry.cs
- test/integration/Elsa.Core.IntegrationTests/Scripting/JavaScript/JavaScriptExpressionsIntegrationTests.cs
**This PR has breaking changes**
Hi, I will try to set up my needs to explain what is this PR about. We are migrating our app core from custom Hangfire jobs to Elsa workflows with custom activities to enrich our app and also to have the ability to modify the workflows without making changes on the code. So, the first thing I did was to copy my hangfire flow to custom activities on Elsa. Everything was OK and the workflow was being executing with the same results. Then, I started do dig more, so, I purpossely failed some activities (custom and fault activity) to try the retry functionality and it wasn't working. Already opened an [issue with the problem ](https://github.com/elsa-workflows/elsa-core/issues/3180). If I couldn't retry my failed activities, I would need to give up elsa, so I …
> Fault array, fix retry, new parameter in Join activity

- src/designer/elsa-workflows-studio/src/components/editors/elsa-multi-expression-editor/elsa-multi-expression-editor.tsx
Found an Issue when removing data from an input box, or changing it from Default to JavaScript/Liquid would add the value to the Array i.e `{ JavaScript: "" }` . Just wrapped an if to check the value before it does this. Means empty string values would get passed through if you clear the value of an expression or if you just switched Default -> JavaScript without entering anything.
> Adding Statements to Catch if expression has no value. 

- src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-viewer-screen/elsa-workflow-instance-viewer-screen.tsx
Fixes issue in [#2845](https://github.com/elsa-workflows/elsa-core/issues/2845)
We use MongoDB to store data, ActivityLifecycle properties are getting parsed into the MongoDB as Uppercase. Therefore as described in the Issue, the status UI doesn't show so no green border for successful activities or green icon. 
This just adds a check if the default value (lowercase) is null then it will try the uppercase property.
> Workflow Instance UI Display Fix

- src/designer/elsa-workflows-studio/src/components/editors/properties/elsa-dropdown-property/elsa-dropdown-property.tsx
@sfmskywalker trying to reapply the fix for dropdown as in #2857.
Simply I'm trying to reassign the value at the end of `componentWillLoad()` to force the default value.
```js
if (this.currentValue != undefined) {
this.propertyModel.expressions[defaultSyntax] = this.currentValue;
}
```
This needs to be validated with the cascading dropdown feature from @jdevillard
> #2857 attempt to reapply fix for dropdown

- src/activities/Elsa.Activities.Http/Extensions/ServiceCollectionExtensions.cs
- src/activities/Elsa.Activities.Http/Middleware/HttpEndpointMiddleware.cs
- src/activities/Elsa.Activities.Http/Parsers/Request/XmlHttpRequestBodyParser.cs
In #3245 I've added simple XML support to SendHTTPRequest activity.
Adding similar support for HTTPEndpoint activity.
> HTTP Endpoint activity Xml support

- src/bundles/Elsa.WorkflowServer.Web/Program.cs
- src/modules/Elsa.ProtoActor/Implementations/ProtoActorWorkflowRuntime.cs
- src/modules/Elsa.ProtoActor/Protos/Messages.proto
- src/modules/Elsa.Workflows.Api/Endpoints/Events/Trigger/Endpoint.cs
- src/modules/Elsa.Workflows.Core/Activities/Composite.cs
- src/modules/Elsa.Workflows.Core/ActivityNodeResolvers/OutboundActivityPortResolver.cs
- src/modules/Elsa.Workflows.Core/Implementations/WorkflowRunner.cs
- src/modules/Elsa.Workflows.Core/Models/Bookmark.cs
- src/modules/Elsa.Workflows.Core/Models/Workflow.cs
- src/modules/Elsa.Workflows.Runtime/Implementations/BookmarkManager.cs
- src/modules/Elsa.Workflows.Runtime/Implementations/DefaultWorkflowRuntime.cs
- src/modules/Elsa.Workflows.Runtime/Services/IBookmarkManager.cs
- src/modules/Elsa.Workflows.Runtime/Services/IWorkflowRuntime.cs
This PR adds a default implemention of `IWorkflowRuntime` as a default alternative to the Proto Actor runtime.
The default runtime behaves more like the "classical" V2 implementation where workflow instances are stored directly in the database through the `IWorkflowInstanceStore` abstraction.
> V3 default runtime

- src/core/Elsa.Abstractions/Persistence/IStore.cs
- src/core/Elsa.Abstractions/Persistence/IWorkflowInstanceStore.cs
- src/core/Elsa.Core/Persistence/Decorators/EventPublishingWorkflowInstanceStore.cs
- src/core/Elsa.Core/Persistence/Decorators/InitializingWorkflowDefinitionStore.cs
- src/core/Elsa.Core/Persistence/InMemory/InMemoryStore.cs
- src/modules/retention/Elsa.Retention/Contracts/IRetentionSpecificationFilter.cs
- src/modules/retention/Elsa.Retention/HostedServices/CleanupHostedService.cs
- src/modules/retention/Elsa.Retention/Jobs/CleanupJob.cs
- src/modules/retention/Elsa.Retention/Options/CleanupOptions.cs
- src/modules/retention/Elsa.Retention/Services/RetentionSpecificationFilter.cs
- src/modules/retention/Elsa.Retention/Specifications/CompletedWorkflowFilterSpecification.cs
- src/modules/retention/Elsa.Retention/Specifications/WorkflowStatusFilterSpecification.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkStore.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkWorkflowInstanceStore.cs
- src/persistence/Elsa.Persistence.MongoDb/Stores/MongoDbStore.cs
- src/persistence/Elsa.Persistence.YesSql/Stores/YesSqlStore.cs
- src/samples/server/Elsa.Samples.Server.Host/Startup.cs
this PR aims to replace the last proposal : #3278  to solve issue of timeout in retention module (#3253)
Indeed, in the current store implementation, when a delete is realize, some select are done which get All the data of the DB. This could be very huge (when considering Data column) even for one record.
The idea is to :
- query the Store and getting only Id and then delete the record.
- filter data as much as we can on server side (using specification)
- lower the memory consumption of this module.
with this change, the time spent to delete is taken moslty in the BatchDeleteWithWorkAroundAsync() (and not in the multiple previous findMany )
> Retention module improvement v2 #3253

- Elsa.sln.DotSettings
- src/bundles/Elsa.WorkflowServer.Web/Program.cs
- src/designer/elsa-workflows-designer/src/components/icons/activities/flow-join.tsx
- src/designer/elsa-workflows-designer/src/services/activity-icon-registry.tsx
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/FlowJoin.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/Flowchart.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Contracts/IJoinNode.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Extensions/ConnectionsExtensions.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/ActivityFlowState.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/FlowScope.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/JoinMode.cs
- src/modules/Elsa.Workflows.Core/Implementations/ActivityInvoker.cs
- src/modules/Elsa.Workflows.Core/Implementations/WorkflowStateSerializer.cs
- src/modules/Elsa.Workflows.Core/Models/ActivityBase.cs
- src/modules/Elsa.Workflows.Core/Models/ActivityExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Models/ActivityNode.cs
- src/modules/Elsa.Workflows.Core/Models/WorkflowExecutionContext.cs
- src/modules/Elsa.Workflows.Management/Implementations/ActivityDescriber.cs
- src/modules/Elsa.Workflows.Management/Implementations/PropertyOptionsResolver.cs
This PR enhances the Flowchart activity by supporting implicit forks & joins.
By default, implicit joins always employ a "wait all" strategy.
If you need a "wait any" join mode, use the explicit "Flow Join" activity and configure its mode with "Wait Any".
The following screenshots displays what's now possible:
It showcases two implicit forks, one implicit join and one explicit join.
When running this workflow, the output will look like this:
```shell
Start
Line 2
Line 2a
Line 1
<after 5 seconds...>
Will happen
End
```
> Implicit fork & join

- src/modules/Elsa.Workflows.Core/Extensions/WorkflowExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Implementations/ActivitySchedulerFactory.cs
- src/modules/Elsa.Workflows.Core/Implementations/QueueBasedActivityScheduler.cs
- src/modules/Elsa.Workflows.Core/Implementations/StackBasedActivityScheduler.cs
- src/modules/Elsa.Workflows.Core/Pipelines/WorkflowExecution/Components/ActivitySchedulerMiddleware.cs
- src/modules/Elsa.Workflows.Core/Services/IActivityScheduler.cs
- src/modules/Elsa.Workflows.Runtime/Implementations/WorkflowHost.cs
This PR introduces a queue-based implementation that replaces the original Elsa 1 & 2 stack-based scheduler.
The queue-based scheduler will execute activities in a first-in-first-out manner, effectively achieving a breadth-first execution of workflows that branch out into multiple paths.
This prevents issues such as branch-exhaustion, where one branch that is scheduled could take a long time, preventing other branches from executing.
This does not parallelize branches. For that, we need activities themselves to execute in the background (subject of a separate PR).
To demonstrate the difference in behavior, take a look at the following workflow:
With the stack-based scheduler, each individual branch will execute one by one. In other words, branch 1 first executes until it reaches its end, …
> Queue-based activity scheduler

- src/core/Elsa.Core/Options/ElsaOptions.cs
- src/core/Elsa.Core/Options/ElsaOptionsBuilder.cs
These changes allow the user to enable the TenantSignaler in a more convenient way. #3336
> adding UseTenantSignaler to ElsaOptionsBuilder

- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/ElsaContext.cs
Regarding the Pomelo [documentation](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options) :
`MySQL does not support the EF Core concept of schemas`
Schema are more or less the same thing as the Db Name (in the connectionstring).
To allow GetSchemaQualifiedTableName() to be use, we need to remove the Schema information for Mysql. The dbContext take care during the call of the Db to use. Without this we can't use a connection string like : 
`"MySql": "Server=localhost;Database=mycustomdb;Uid=root;Pwd=my-secret-pw;"`   because Database must be equal to Elsa (and it seems to be case sensitive...)
> MySql - Set schemaName to Empty to allow using GetSchemaQualifiedTableName()

- src/core/Elsa.Core/Services/Workflows/WorkflowRunner.cs
Updating the workflow runner to throw if a FaultResult is returned by the Activity.
As highlighted in #2723 if you return a FaultResult from an activity, the execution log doesn't get the fault added to it so it won't be displayed in the designer.
To correct this i've checked to see if the result of the activity is a faultResult and throw an exception so sends a ActivityFaulted event.
We could also expand the ActivityFaulted to accept a message as well as the exception so it matches FaultResult and in the handler resolve whether it's to use the Message or the Exception rather than having to create/thow an exception.
> Check the result and throw if it's a fault

- src/activities/Elsa.Activities.Telnyx/TelnyxWebhookLogScope.cs
- src/activities/Elsa.Activities.Telnyx/Webhooks/Services/WebhookHandler.cs
- src/activities/Elsa.Activities.Temporal.Quartz/Jobs/RunQuartzWorkflowInstanceJob.cs
- src/activities/Elsa.Activities.Temporal.Quartz/Services/QuartzWorkflowInstanceScheduler.cs
- src/activities/Elsa.Activities.Temporal.Quartz/WorkflowInstanceLogScope.cs
- src/core/Elsa.Core/Services/Dispatch/QueuingWorkflowDispatcher.cs
- src/core/Elsa.Core/Services/Workflows/WorkflowRunner.cs
- src/core/Elsa.Core/WorkflowInstanceLogScope.cs
For loggers such as the console logger just write the result of `ToString()` method (see [here](https://github.com/dotnet/runtime/blob/0589ce6c3022f4b9b7571268be5f97f45a003ad7/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatter.cs#L207)).
Which results in it writing something like:
```
=> SpanId:f126fcaa1f140d25, TraceId:0bd70f4174cd963684d8fd55e4dc2ecb, ParentId:0000000000000000 => ConnectionId:0HMM16A1C5J1U => RequestPath:/test-path RequestId:0HMM16A1C5J1U:00000009 => System.Collections.Generic.Dictionary`2[System.String,System.Object]
```
Of note is the `System.Collections.Generic.Dictionary`2[System.String,System.Object]` part.
This just replaces those dictionaries with some concrete types (based on [aspnetcore/ConnectionLogScope.cs](https://github.com/dotnet/ …
> Use log scopes with a better `ToString()` implementation.

- src/core/Elsa.Core/Persistence/Specifications/WorkflowDefinitions/WorkflowDefinitionNameSpecification.cs
- src/scripting/Elsa.Scripting.Liquid/Filters/WorkflowDefinitionIdFilter.cs
This PR enhances the core liquid filter WorkflowDefinitionIdFilter with another optional parameter. The parameter can take an (optional) workflow definition Id from which the tenant id will be used to find the workflow definition in the right tenant.
This can be used to call a subworkflow from a tenant specific workflow. Without this adapter liquid filter the workflow definition will always be searched in the default tenant.
The new syntax (following liquid syntax would be):
`{{ \"<name of the workflow>\" | workflow_definition_id:\"name\",WorkflowInstanceId }}`
or by tag
`{{ \"<tag of the workflow>\" | workflow_definition_id:\"tag\",WorkflowInstanceId }}`
> Enhance WorkflowDefinition id liquid filter

- appveyor.yml
The symbol packages don't seem to be available from nuget.org.
I can't verify that this fixes the issue as it requires actually pushing the packages but based on [How to publish NuGet symbol packages using the new symbol package format '.snupkg' | Microsoft Learn](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#publishing-a-symbol-package) it looks like this _might_ resolve the issue.
> Publish symbol packages to the v3 NuGet API.

- src/core/Elsa.Core/Activities/Workflows/RunWorkflow/RunWorkflow.cs
The goal would be to extend the "RunWorkflow" activity next to Blocking and FireAndForget by the option "DispatchAndForget" to send the WorkflowRequest via the WorkflowDispatcher into the ServiceBus and to make it possible to process the WorkflowRequest on a separate node.
closes #3451
> Dispatch and forget

- src/scripting/Elsa.Scripting.JavaScript/Typings/EnumerableTypeDefinitionProvider.cs
- test/unit/Elsa.UnitTests/Scripting/JavaScript/Typings/EnumerableTypeDefinitionProviderTests.cs
This should fix #3477 
I'm quite new with xUnit, if the test could be better, please provide me some guidance.
Imho I found the design of the TypeDefinitionProvider a bit confusing: if I've understood it correctly, I would have preferred to split the responsibility of collecting types (`CollectTypes`) from that of returning the Typescript definition types (`SupportsType/GetTypeDefinition`); because they are not even cohesive responsibilities.
In fact, up to date, I don't see any providers that do both.
> fix EnumerableTypeDefinitionProvider #3477

- src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequest.cs
This is a continuation of the topic started with the previous PR, which I closed:
https://github.com/elsa-workflows/elsa-core/pull/3473
The picture below is the gist of it:
It turns out, that by using javascript in the content field, we can take the output of the previous SendHttpRequest, and put it into the body. However, since the Content field currently is a string, the file data will get corrupt in the middle of the conversion, even if we use something like `String.fromCharCode.apply(null, activities.PictureGet.ResponseContent())` to turn the bytes into string.
But this is issue is easily solved, by turning Content into object, and then check by type whether to send as string or as byte array.
> Allow handling SendHttpRequest content as bytes

- src/designer/bindings/aspnet/Elsa.Designer.Components.Web/Elsa.Designer.Components.Web.csproj
- src/designer/elsa-workflows-studio/src/components.d.ts
- src/designer/elsa-workflows-studio/src/components/designers/x6-designer/graph-factory.ts
- src/designer/elsa-workflows-studio/src/components/designers/x6-designer/x6-designer.css
- src/designer/elsa-workflows-studio/src/components/designers/x6-designer/x6-designer.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/localizations.ts
- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-publish-button/elsa-workflow-publish-button.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-instance-viewer/elsa-workflow-instance-viewer-screen/elsa-workflow-instance-viewer-screen.tsx
- src/designer/elsa-workflows-studio/src/globals/tailwind.css
- src/designer/elsa-workflows-studio/stencil.config.dist.ts
- src/designer/elsa-workflows-studio/stencil.config.prod.ts
- src/designer/elsa-workflows-studio/stencil.config.ts
1. Improve graph connection generation by calculating `step` value to the edge routing depending on the layout of the target nodes
2. Update connection views, when moving one node, so nodes won't hide the connections underneath them
3. Allow pasting of nodes to cursor position (useful when pasting to another workflow)
4. Fix showing the node selection style in all environments (updated the stencil configs - purge css safelist)
5. Make auto-layout use batch update, so the whole operation can be undone with ctrl+z
6. Improve the per-activity test result window positioning, so it wouldn't appear outside the screen and also make it scrollable
> Make improvements related to x6 graphs

- src/server/Elsa.Server.Api/Extensions/SchemaFilters/XEnumNamesSchemaFilter.cs
- src/server/Elsa.Server.Api/Extensions/ServiceCollectionExtensions.cs
Currently, the OpenAPI file on /swagger/v1/swagger.json does not include information on enums.
Example: 
```json
"WorkflowPersistenceBehavior": {
"enum": [
0,
1,
2
],
"type": "integer",
"format": "int32"
},
```
With this fix the output is now: 
```json
"WorkflowPersistenceBehavior": {
"enum": [
0,
1,
2
],
"type": "integer",
"format": "int32",
"x-enumNames": [
"Suspended",
"WorkflowBurst",
"ActivityExecuted"
]
},
```
This means that tools like NSwag can now generate HttpClients with the correct enums.
> Allow Swagger OpenAPI file to include name of enums

- src/persistence/Elsa.Persistence.MongoDb/Extensions/ServiceCollectionExtensions.cs
- src/persistence/Elsa.Persistence.MongoDb/Options/ElsaMongoDbOptions.cs
- src/persistence/Elsa.Persistence.MongoDb/Serializers/TypeSerializer.cs
- src/persistence/Elsa.Persistence.MongoDb/Services/DatabaseRegister.cs
- test/integration/Elsa.Core.IntegrationTests/Autofixture/WithMongoDbAttribute.cs
In this commit there is some cleanup of MongoDb persistence provider initialization, as well as the option to opt out the automatic registration of VariablesSerializer, to use default BsonSerializer or custom version of BsonSerializer.
The option is opt-out, so previous code is unaffected.
Added also option to specify test mongodb connection string from environment variable.
Related to #3538
> MongoDb Persistence: Cleanup and optout Serialzier for Variables object

- src/scripting/Elsa.Scripting.JavaScript/Activities/RunJavaScript/RunJavaScript.cs
https://github.com/elsa-workflows/elsa-core/issues/3555
casting to `<IEnumerable<string>>` causes an exception. Changing the datatype to `string[]` removes the need for the cast. I tested this successfully using the workflow in the attached issue.
> Different Datype for JS function setOutcomes

- src/designer/elsa-workflows-studio/src/components/designers/x6-designer/x6-designer.tsx
Found issue while using WorkflowEditor blazor component in dynamically changing workflow definition ids. Api calls were successful, model setup correctly by elsaStudio but x6 designer weren't re-rendering. This PR fixes that issue.
> Fix for dynamic model changes are not triggering re-rendering x6 designer

- src/activities/Elsa.Activities.Kafka/Elsa.Activities.Kafka.csproj
- src/scripting/Elsa.Scripting.JavaScript/Typings/EnumerableTypeDefinitionProvider.cs
Fix #3614 by reintroducing check whether `elementType` is `null`.
Fix Kafka project and main branch build.
> Fix for EnumerableTypeDefinitionProvider #3614 and fix Kafka project build

- src/scripting/Elsa.Scripting.JavaScript/Handlers/RenderJavaScriptDateTimeTypeDefinitions.cs
The return type for the `instantFromLocalDate` javascript function is `Instant`, actually, but the type definition provider reports `LocalDate` to the client.
> Fix return type in `instantFromLocalDate` type def

- src/activities/Elsa.Activities.Kafka/Services/Worker.cs
There is no need to log every incoming KafkaMessage as a warning. This just fills up logs with unnessecary warnings.
> Activities Kafka: Changed LogLevel to Information

- src/activities/Elsa.Activities.AzureServiceBus/Extensions/ServiceCollectionExtensions.cs
- src/activities/Elsa.Activities.AzureServiceBus/Services/DefaultAzureServiceBusTenantIdResolver.cs
- src/activities/Elsa.Activities.AzureServiceBus/Services/IAzureServiceBusTenantIdResolver.cs
- src/activities/Elsa.Activities.AzureServiceBus/Services/Worker.cs
- test/integration/Elsa.Core.IntegrationTests/Workflows/ServiceBusWorkflowTest.cs
This PR is in response to #3667 Feature: Azure Service Bus Tenant Id Resolver.
Introduces a new interface `IAzureServiceBusTenantIdResolver` with a single method `ResolveAsync`  this method will pass all the relevant details from the Worker to the Resolver.
By Default Elsa will ship with a "NoOp" resolver called `DefaultAzureServiceBusTenantIdResolver` which returns a null string.
This will be added to dependency injection as a singleton (resolved from the root scope when workers are created).
Applications may override this behavior by registering a custom instance of the `IAzureServiceBusTenantIdResolver` **after** the call to `AddAzureServiceBusActivities(...)`.
Such as the code snippet below.
```
services.AddElsa(c =>
{
// ...omitted
c.AddAzureServiceBusActivities(az => …
```
> feat: 🎸 AzureServiceBus - TenantIdResolver

- src/core/Elsa.Core/Providers/Workflows/BlobStorageWorkflowProvider.cs
- src/core/Elsa.Core/Providers/Workflows/DatabaseWorkflowProvider.cs
- src/designer/elsa-workflows-studio/tailwind.config.js
This PR attempts to address two issues my team is facing:
1. Some missing tenant id filters
2. Elsa's css files conflict with many of our website's styles because they aren't limited to `elsa-studio-root` and below
> fix: add missing tenant id specifiers; limit tailwind css to elsa-studio-root

- src/activities/Elsa.Activities.RabbitMq/Elsa.Activities.RabbitMq.csproj
- src/core/Elsa.Abstractions/Elsa.Abstractions.csproj
- src/core/Elsa.Core/Elsa.Core.csproj
- src/samples/worker/Elsa.Samples.RebusErrorWorker/Elsa.Samples.RebusErrorWorker.csproj
- src/samples/worker/Elsa.Samples.RebusWorker/Elsa.Samples.RebusWorker.csproj
- src/servicebus/Elsa.Rebus.AzureServiceBus/Elsa.Rebus.AzureServiceBus.csproj
- src/servicebus/Elsa.Rebus.RabbitMq/Elsa.Rebus.RabbitMq.csproj
When using .NET 6 / 7 we were getting warnings in rebus due to version mismatches:
```
warning NU1608: Detected package version outside of dependency constraint: 
Rebus.Microsoft.Extensions.Logging 3.0.0 requires microsoft.extensions.logging (>= 6.0.0 && < 7.0.0) 
but version Microsoft.Extensions.Logging 7.0.0 was resolved. [TargetFramework=net6.0]
```
```
warning NU1608: Detected package version outside of dependency constraint: 
Rebus.Microsoft.Extensions.Logging 3.0.0 requires microsoft.extensions.logging (>= 6.0.0 && < 7.0.0) 
but version Microsoft.Extensions.Logging 7.0.0 was resolved. [TargetFramework=net7.0]
```
This PR resolves these issues:
https://github.com/rebus-org/Rebus.Microsoft.Extensions.Logging/pull/11
The other warnings were resolved in other PRs:
```
warning NU1608: …
```
> Upgraded Rebus to remove warnings

- appveyor.yml
- src/activities/Elsa.Activities.Email/Services/ISmtpService.cs
- src/activities/Elsa.Activities.Email/Services/MailKitSmtpService.cs
- src/activities/Elsa.Activities.Telnyx/Activities/BridgeCalls.cs
- src/activities/Elsa.Activities.Telnyx/Activities/Dial.cs
- src/activities/Elsa.Activities.Telnyx/Client/Models/Requests.cs
- src/activities/Elsa.Activities.Telnyx/Client/Models/Responses.cs
- src/activities/Elsa.Activities.Telnyx/Client/Services/ICallsApi.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeAnswerCall.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeBridgeCalls.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeDial.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeGatherUsingAudio.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeGatherUsingSpeak.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumePlayAudio.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeSpeakText.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeStartRecording.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeStopAudioPlayback.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeTransferCall.cs
- src/activities/Elsa.Activities.Telnyx/Handlers/ResumeWebhookDrivenActivity.cs
- src/activities/Elsa.Activities.Telnyx/OutcomeNames.cs
- src/activities/Elsa.Activities.Telnyx/Providers/Bookmarks/DialBookmark.cs
- src/core/Elsa.Core/Handlers/InfiniteLoopDetectionHandler.cs
- src/core/Elsa.Core/Services/Workflows/WorkflowRunner.cs
- src/designer/elsa-workflows-studio/package.json
This PR fixes an issue where execution scopes are cleared prematurely in the event of a faulting workflow. 
As seen in issue #3669, this leads to an unintended behavior.
> Fix premature cleaning of scopes after retrying faulted workflow

- src/modules/Elsa.Jobs.Activities/Handlers/JobExecutedHandler.cs
- src/modules/Elsa.MassTransit/Consumers/DispatchWorkflowRequestConsumer.cs
- src/modules/Elsa.ProtoActor/Implementations/ProtoActorWorkflowRuntime.cs
- src/modules/Elsa.Telnyx/Handlers/TriggerWebhookDrivenActivities.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/Flowchart.cs
- src/modules/Elsa.Workflows.Core/Middleware/Activities/LoggingMiddleware.cs
- src/modules/Elsa.Workflows.Core/Models/WorkflowExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Pipelines/ActivityExecution/ActivityExecutionPipeline.cs
- src/modules/Elsa.Workflows.Runtime/Handlers/DispatchWorkflowRequestHandler.cs
- src/modules/Elsa.Workflows.Runtime/Handlers/ResumeDispatchWorkflowActivityHandler.cs
- src/modules/Elsa.Workflows.Runtime/Implementations/DefaultWorkflowRuntime.cs
- src/modules/Elsa.Workflows.Runtime/Services/IWorkflowRuntime.cs
This PR fixes two issues:
1. Deadlock: the workflow runtime would always deadlock when triggering workflows (because of `ResumeDispatchWorkflowActivityHandler`).
2. Having multiple triggers on a flowchart would not schedule the triggered activity, but the first activity always.
Fixes #3713
> Fix deadlock + multiple trigger support

- src/designer/elsa-workflows-designer/package.json
- src/designer/elsa-workflows-designer/src/components.d.ts
- src/designer/elsa-workflows-designer/src/components/inputs/output-picker.tsx
- src/designer/elsa-workflows-designer/src/components/inputs/variable-picker.tsx
- src/designer/elsa-workflows-designer/src/modules/workflow-definitions/components/properties/input-output-settings.tsx
- src/designer/elsa-workflows-designer/src/modules/workflow-definitions/components/properties/properties.tsx
- src/designer/elsa-workflows-designer/src/services/input-control-registry.tsx
- src/modules/Elsa.JavaScript/Activities/RunJavaScript.cs
- src/modules/Elsa.Workflows.Designer/package-lock.json
- src/modules/Elsa.Workflows.Designer/package.json
- src/modules/Elsa.Workflows.Management/Activities/SetWorkflowOutput.cs
- src/modules/Elsa.Workflows.Management/Models/InputUIHints.cs
This PR adds an output picker control for the SetWorkflowOutput activity, which is fed from the output definitions of the current workflow definition. This replaces the free form text field that was used originally.
> Add output picker for SetWorkflowOutput activity

- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Extensions/QueryableBulkExtensions.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkWorkflowInstanceStore.cs
BatchDeleteWithWorkAroundAsync was referencing an issue that looks to be resolved, I tested it and it works on a postgres database, I was however not able to test it on a mysql db, so I didn't change the mysql implementation.
DeleteMany generated sql that couldn't be executed with psql (WorkflowInstanceId would need to be within quotation marks) but the batch delete looked like it generated performant sql.
> DeleteMany fixes

- src/modules/Elsa.EntityFrameworkCore/Common/EntityStore.cs
- src/modules/Elsa.EntityFrameworkCore/Common/PersistenceFeatureBase.cs
- src/modules/Elsa.EntityFrameworkCore/Common/Store.cs
- src/modules/Elsa.EntityFrameworkCore/Extensions/ExpressionExtensions.cs
- src/modules/Elsa.EntityFrameworkCore/Extensions/QueryableExtensions.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Labels/Feature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Labels/LabelStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Labels/WorkflowDefinitionLabelStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/EFCoreWorkflowManagementPersistenceFeature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowDefinitionPersistenceFeature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowDefinitionStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowInstancePersistenceFeature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowInstanceStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/DefaultRuntimePersistenceFeature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/ExecutionLogRecordPersistenceFeature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/TriggerStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/WorkflowExecutionLogStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/WorkflowStateStore.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Post/Endpoint.cs
This PR synchronizes access to the API endpoint that handles saving of workflow definitions from the designer. This prevents potential race conditions leaving the workflow definition metadata in a corrupted state.
> Sycnrhonize access to publish / save workflow definition endpoint

- src/designer/elsa-workflows-studio/src/modules/credential-manager/elsa-secret-editor-modal/elsa-secret-editor-modal.tsx
- src/designer/elsa-workflows-studio/src/modules/credential-manager/pages/credential-manager-items-list.tsx
Fixes two issues:
1. Fix the `elsa-credential-manager-items-list` failing to open from the Elsa dashboard due to the `monacoLibPath` not being injected from the tunnel.
2. Fixes the `elsa-secret-editor-modal` throwing errors for secrets that don't have any of the following properties:
1. `GrantType`
2. `AuthorizationUrl`
3. `AccessTokenUrl`
4. `ClientId`
5. `ClientSecret`
> Fix credential manager in designer.

- src/modules/retention/Elsa.Retention/Specifications/CompletedWorkflowFilterSpecification.cs
- src/modules/retention/Elsa.Retention/Specifications/WorkflowStatusFilterSpecification.cs
I couldn't get the current default retention to work. The default specification generated a query that was looking for a workflow with the status running AND finished, which could never be true. This PR adjusted that to be OR instead.
I might misunderstand something but to me it feels like only finished workflows should be removed by default so I removed the running from the list
> Retention specification fixes

- src/modules/Elsa.Workflows.Management/Serialization/Converters/InputJsonConverter.cs
Currently, when you try to execute a workflow that has a HttpEndpoint activity, it throws the following error:
InvalidOperationException: Operation is not valid due to the current state of the object.
The issue is caused by the undefined value of Policy on HttpEndpoint. This PR fixes it by excluding the Inputs thas have no value from the activity.
> Undefined json element value fix

- src/core/Elsa.Abstractions/Elsa.Abstractions.csproj
- src/core/Elsa.Core/Elsa.Core.csproj
- src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs
- src/core/Elsa.Core/Extensions/MessageHandlerServiceCollectionExtensions.cs
- src/indexing/Elsa.Indexing.Abstractions/Extensions/ElsaIndexingOptionsExtensions.cs
- src/samples/aspnet/Elsa.Samples.InProcessBackgroundMediator/Elsa.Samples.InProcessBackgroundMediator.csproj
- src/samples/aspnet/Elsa.Samples.InProcessBackgroundMediator/Program.cs
MediatR.Extensions.Microsoft.DependencyInjection is also replaced with the main MediatR package since it is deprecated.
> Upgrade MediatR to 12.0.1 fixing issue #3775

- src/core/Elsa.Core/Activities/Workflows/RunWorkflow/Extensions/RunWorkflowExtensions.cs
I'd like to propose an extension to the RunWorkflow activity which allows to run a workflow by its name. Currently it will throw an exception if the name is incorrect but I'm open to suggestions about a better solution.
> Add WithNamedWorkflow extension to RunWorkflow activity

- src/activities/Elsa.Activities.Kafka/Bookmarks/OverrideKafkaBookmarkProvider.cs
OverrideKafkaBookmarkProvider provided a second bookmark for default kafka trigger. #3832
> Fixed double wf execution #3832

- src/modules/Elsa.Workflows.Management/Activities/WorkflowDefinitionActivity/WorkflowDefinitionActivity.cs
- src/modules/Elsa.Workflows.Management/Serialization/Converters/ActivityJsonConverter.cs
- src/modules/Elsa.Workflows.Management/Serialization/SerializationOptionsConfigurator.cs
This PR improves the handling of activity descriptors that were initially missing, and then later restored. Think of importing consuming workflows of composite activities not yet added to the system. Before this change, not specifying a version number would take version 1 of the dependency workflow, even if there is a newer version available.
Now, it will always take the latest version of no explicit version number was provided.
> Take latest version if none specified

- src/common/Elsa.Testing.Shared/ServiceProviderExtensions.cs
- src/modules/Elsa.Http/Contracts/IHttpBookmarkProcessor.cs
- src/modules/Elsa.Http/Handlers/DefaultHttpEndpointWorkflowFaultHandler.cs
- src/modules/Elsa.Http/Middleware/WorkflowsMiddleware.cs
- src/modules/Elsa.Http/Models/HttpEndpointFaultedWorkflowContext.cs
- src/modules/Elsa.Http/Services/HttpBookmarkProcessor.cs
- src/modules/Elsa.ProtoActor/Extensions/ProtoStringExtensions.cs
- src/modules/Elsa.ProtoActor/Features/ProtoActorFeature.cs
- src/modules/Elsa.ProtoActor/Grains/WorkflowGrain.cs
- src/modules/Elsa.ProtoActor/Mappers/BookmarkMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/ExceptionMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/WorkflowExecutionResultMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/WorkflowFaultStateMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/WorkflowStatusMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/WorkflowSubStatusMapper.cs
- src/modules/Elsa.ProtoActor/Protos/Grains.proto
- src/modules/Elsa.ProtoActor/Protos/Messages.proto
- src/modules/Elsa.ProtoActor/Services/ProtoActorWorkflowRuntime.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Execute/Endpoint.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IWorkflowRuntime.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowRuntime.cs
This PR updates the way HTTP responses are sent in case of a faulting workflow.
Before this change, HTTP responses would respond with HTTP OK. After this change, HTTP responses will now include error details and a 500 status code.
Fixes #3936
> Send HTTP error when workflow faults

- src/modules/Elsa.Email/Activities/SendEmail.cs
- src/modules/Elsa.Expressions/Helpers/ObjectConverter.cs
This PR refactors the input types for the `To`, `Cc` and `Bcc` fields.
Before this change, these inputs accepted `object` types and had the activity figure out if the value was a list of strings or a single string. This logic missed arrays of objects, which is the materialized type when the designer creates the inputs.
Instead of changing that logic, I chose to instead revert the input type to be a collection of strings, which is easier to reason about also from the point of view of programmatic workflows.
From the designer's point of view, we can still provide a singular string value instead of an array, which is more user friendly. 
To make that work, I updated the ObjectConverter to make a small leap by assuming that if the source value is a string and the target type to convert into …
> Refactor SendEmail inputs to support list of strings and single string

- src/bundles/Elsa.WorkflowServer.Web/Program.cs
- src/modules/Elsa.Http/Contracts/IHttpEndpointAuthorizationHandler.cs
- src/modules/Elsa.Http/Features/HttpFeature.cs
- src/modules/Elsa.Http/Handlers/AllowAnonymousHttpEndpointAuthorizationHandler.cs
- src/modules/Elsa.Http/Handlers/AuthenticationBasedHttpEndpointAuthorizationHandler.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/TypeJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Services/BookmarkHasher.cs
- src/modules/Elsa.Workflows.Runtime/Comparers/WorkflowTriggerEqualityComparer.cs
- src/modules/Elsa.Workflows.Runtime/Comparers/WorkflowTriggerHashEqualityComparer.cs
- src/modules/Elsa.Workflows.Runtime/Services/TriggerIndexer.cs
This PR fixes an issue where triggers would not be updated under certain conditions.
In the case of HTTP Endpoint, the issue was that the `Authorize` field is excluded from the Hash computation (as it should) - but because trigger comparison relied on this hash, changing only the Authorize value would not change the hash, and therefore the trigger would not be replaced.
> Fix HTTP triggers not being updated

- src/activities/webhooks/Elsa.Webhooks.Persistence.MongoDb/Services/ElsaMongoDbContext.cs
- src/modules/secrets/Elsa.Secrets.Persistence.MongoDb/Elsa.Secrets.Persistence.MongoDb.csproj
- src/modules/secrets/Elsa.Secrets.Persistence.MongoDb/Services/ElsaMongoDbContext.cs
- src/modules/workflowsettings/Elsa.WorkflowSettings.Persistence.MongoDb/Elsa.WorkflowSettings.Persistence.MongoDb.csproj
- src/modules/workflowsettings/Elsa.WorkflowSettings.Persistence.MongoDb/Services/ElsaMongoDbContext.cs
- src/persistence/Elsa.Persistence.MongoDb/Elsa.Persistence.MongoDb.csproj
- src/persistence/Elsa.Persistence.MongoDb/Options/ElsaMongoDbOptions.cs
- src/persistence/Elsa.Persistence.MongoDb/Services/ElsaMongoDbContext.cs
- src/persistence/Elsa.Persistence.MongoDb/Services/ElsaMongoDbDriverHelpers.cs
Added an option to allow the user to opt-in for LINQ3 provider that actually causes regressions. See #4000
> MongoDb Provider - Switch to LINQ2

- src/core/Elsa.Core/Services/Bookmarks/BookmarkIndexer.cs
- src/core/Elsa.Core/Services/Triggers/TriggersForActivityBlueprintAndWorkflowProvider.cs
- src/core/Elsa.Core/Services/Workflows/ActivityTypeService.cs
If an ActivityType provider generates an exception it will cause the /activities endpoint to fail and the missing triggers will cause the runtime to stop.
This attempts to handle those exceptions that may be caused by external dependencies and improve the engine robustness.
> Handle exceptions generated from ActivityTypeProviders

- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Dispatch/Endpoint.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Dispatch/Models.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Execute/Endpoint.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Execute/Models.cs
Allow the user to select which activity should start with from the ones marked with 'Can start workflow'. This is useful when calling the workflow through the /execute or /dispatch endpoint.
> Allow the user to select the start activty when calling through the api

- Elsa.sln
- src/designer/designer_packages/elsa-workflows-designer/src/utils/utils.ts
- src/modules/Elsa.JavaScript/Extensions/WorkflowExecutionContextExtensions.cs
- src/modules/Elsa.JavaScript/Features/JavaScriptFeature.cs
- src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
- src/modules/Elsa.JavaScript/TypeDefinitions/Providers/ActivityOutputFunctionsDefinitionProvider.cs
- src/modules/Elsa.JavaScript/TypeDefinitions/Providers/CommonFunctionsDefinitionProvider.cs
- src/modules/Elsa.Liquid/Handlers/ConfigureLiquidEngine.cs
- src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Extensions/ActivityExtensions.cs
- src/modules/Elsa.Workflows.Core/Models/ActivityExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Models/ActivityOutputRegister.cs
- src/modules/Elsa.Workflows.Core/Models/WorkflowExecutionContext.cs
- src/samples/console/Elsa.Samples.ConsoleApp.ActivityOutput/Elsa.Samples.ConsoleApp.ActivityOutput.csproj
- src/samples/console/Elsa.Samples.ConsoleApp.ActivityOutput/Program.cs
- src/samples/console/Elsa.Samples.ConsoleApp.ActivityOutput/Workflows/LastResultWorkflow.cs
- src/samples/console/Elsa.Samples.ConsoleApp.ActivityOutput/Workflows/TargetActivityOutputWorkflow.cs
This PR adds a couple of APIs to access a given activity's output as well as the last result.
A console sample project was added to demonstrate how to do this for programmatic workflows.
When using the designer, we use JS expressions.
For example:
```javascript
// Generic form:
getOutputFrom("SomeActivityId");
// Generic form accepting a second argument in case an activity provides output named other than "Result":
getOutputFrom("SomeActivityId", "SomeOutputName");
// Typed form:
getResultFromHttpEndpoint1();
getSomeOutputNameFromSomeActivityId();
```
One improvement to be made is to generate a typescript definition that takes into account the output types.
> Implement direct access to activity output and last result

- src/clients/Elsa.Api.Client/Shared/Models/Activity.cs
- src/clients/Elsa.Api.Client/Shared/Models/Container.cs
- src/clients/Elsa.Api.Client/Shared/Models/Trigger.cs
- src/designer/designer_packages/elsa-workflows-designer/src/modules/flowchart/flowchart.tsx
- src/designer/designer_packages/elsa-workflows-designer/src/modules/flowchart/graph-factory.ts
- src/designer/designer_packages/elsa-workflows-designer/src/modules/flowchart/models.ts
- src/designer/designer_packages/elsa-workflows-designer/src/utils/graph.ts
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/Flowchart.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Extensions/ConnectionsExtensions.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/Connection.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/Endpoint.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/ObsoleteConnection.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Serialization/ConnectionJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Serialization/FlowchartJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Serialization/ObsoleteConnectionJsonConverter.cs
- test/integration/Elsa.IntegrationTests/Scenarios/ImplicitJoins/Workflows/ImplicitLoopWorkflow.cs
This PR refactors the structure of the `Connection` model used by the `Flowchart` activity, as follows:
**Original**
```
Connection
{
IActivity Source;
IActivity Target;
string SourcePort;
string TargetPort;
}
```
**New**
```
Connection
{
Endpoint Source;
Endpoint Target;
}
Endpoint
{
IActivity Activity;
string Port;
}
```
The Flowchart JSON converter is updated to be backwards-compatible, meaning that it will still understand the original structure. When serialising, however, it will write out the new structure.
> Refactor connection model

- src/modules/Elsa.Scheduling/Services/DefaultTriggerScheduler.cs
The Cron triggers were not unscheduled, this resulted in multiple executions upon the publishing and unpublishing of workflows.
> UnscheduleCron triggers

- src/modules/Elsa.Scheduling/Services/DefaultBookmarkScheduler.cs
- src/modules/Elsa.Scheduling/Services/DefaultTriggerScheduler.cs
As discussed in pull request #4149 The ToList and list variable are unnecessary.
So this pull request cleans up both DefaultTriggerScheduler and DefaultBookmarkScheduler by removing both the variable and the ToList actions.
> Cleanup schedulers

- src/persistence/Elsa.Persistence.MongoDb/Options/ElsaMongoDbOptions.cs
- src/persistence/Elsa.Persistence.MongoDb/Services/ElsaMongoDbDriverHelpers.cs
Best practice for usage of MongoClient is creating a **single instance** for the entire process. (or a single instance for each different connection string). 
Actual code create a new MongoClient and uses a local cache to limit the number of client, but with this commit we allow the caller to redefine the function to create MongoClient and use an external cache (or use decorators, etc).
> Added ability to externalize MongoClient creation

- src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
- src/modules/Elsa.Workflows.Core/Extensions/ActivityExtensions.cs
- src/modules/Elsa.Workflows.Core/Models/ActivityOutputRecord.cs
- src/modules/Elsa.Workflows.Core/Models/ActivityOutputRegister.cs
- test/unit/Elsa.Workflows.Core.UnitTests/ExpressionExecutionContextExtensionsTests.cs
Summary:
This Pull Request contains various refactoring and modification changes to the codebase, including changing the signature of GetConfiguredEngine(), adding logic to filter the output of output records based on container IDs, removing unused code from CreateVariableAccessors(), changing the signature of the GetVariableInScope() method, changing the logic to find an output value by ActivityInstanceId, and making the SetVariable method create a variable when it does not exist. 
List of Changes:
- Changed the signature of GetConfiguredEngine() to return an object instead of Engine
- Added logic in GetConfiguredEngine() to filter the output of output records based on container IDs
- Changed the signature of GetVariableInScope() to return an object instead of the original IEnumerable or …
> Update output selector with support for activity instances

- src/activities/Elsa.Activities.Http/Activities/HttpEndpoint/HttpEndpoint.cs
- src/activities/Elsa.Activities.Http/Activities/HttpEndpoint/HttpEndpointExtensions.cs
- src/activities/Elsa.Activities.Http/Middleware/HttpEndpointMiddleware.cs
- src/activities/Elsa.Activities.Http/Services/CustomHeaderAuthorizationHandler.cs
- src/samples/aspnet/Elsa.Samples.HttpEndpointSecurity/Workflows/SecureHelloWorkflow.cs
For HttpEndpoint activity we have to have the previous authorization work in parallel with the now new check for plain header (ApiKey or something like that). I feel like there could be a better solution, so I am open to suggestions.
> Add option to check custom header when receiving http endpoint request

- src/clients/Elsa.Api.Client/Extensions/DependencyInjectionExtensions.cs
- src/clients/Elsa.Api.Client/Options/ElsaClientOptions.cs
Sometimes, when configuring the HttpClient, it may be necessary to access the ServiceProvider.
For example, for authentication, I use BearerToken and to get it I need to access other services:
```
services.AddElsaClient(options =>
{
options.BaseAddress = new Uri(elsaServerUrl + "elsa/api");
options.ConfigureHttpClient = (provider, client) =>
{
IClientAccessTokenCache? clientAccessTokenCache = provider.GetService<IClientAccessTokenCache>();
ClientAccessToken? clientToken = clientAccessTokenCache?
.GetAsync("m2m", new ClientAccessTokenParameters())
.GetAwaiter()
.GetResult();
client.SetBearerToken(clientToken?.AccessToken);
};
});
```
> V3 Add to ConfigureHttpClient access to the service provider

- src/modules/Elsa.Http/Activities/WriteHttpResponse.cs
- src/modules/Elsa.Workflows.Core/Extensions/InputExtensions.cs
List of changes:
- Added logic to use `StatusCode` input as HTTP response status
- Added logic to omit content writing when status code is set to `HttpStatusCode.NoContent`
- Created extension methods for `ActivityExecutionContext` and `ExpressionExecutionContext` to get input values, with additional overloads to support retrieving a default value when not present.
Aiming to reduce complexity by consolidating duplicated code from existing methods.
> Fix WriteHttpResponse when NoContent

- src/bundles/Elsa.WorkflowServer.Web/Program.cs
- src/modules/Elsa.Dapper/Modules/Runtime/Stores/DapperActivityExecutionRecordStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/ActivityExecutionLogStore.cs
- src/modules/Elsa.MongoDb/Modules/Runtime/ActivityExecutionLogStore.cs
- src/modules/Elsa.Scheduling/Handlers/DeleteSchedules.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IActivityExecutionStore.cs
- src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs
- src/modules/Elsa.Workflows.Runtime/Filters/ActivityExecutionRecordFilter.cs
- src/modules/Elsa.Workflows.Runtime/Handlers/DeleteActivityExecutionLogRecords.cs
- src/modules/Elsa.Workflows.Runtime/Stores/MemoryActivityExecutionStore.cs
- src/modules/Elsa.Workflows.Runtime/Stores/NoopActivityExecutionStore.cs
Summary:
- Added useHangfire constant and updated Program.cs to use Hangfire scheduler
- Refactored DapperActivityExecutionRecordStore, EntityFrameworkCore ActivityExecutionLogStore, and MongoDb ActivityExecutionLogStore to add the DeleteManyAsync method
- Added new notification handler for deleting activity execution log records when handling WorkflowInstancesDeleting notification
- Added new filter for ActivityExecutionRecord called ActivityExecutionRecordFilter, to allow multiple workflow instance ids to be specified
- Added new method to IActivityExecutionStore called DeleteManyAsync which deletes all activity execution records matching the specified filter
- Added new implementation of DeleteManyAsync in MemoryActivityExecutionStore which filters the IQueryable, and deletes all …
> Delete ActivityExecutionRecords when deleting workflow instances

- src/common/Elsa.Features/Services/IFeature.cs
- src/modules/Elsa.Http/Abstractions/HttpCorrelationIdSelectorBase.cs
- src/modules/Elsa.Http/Abstractions/HttpWorkflowInstanceIdSelectorBase.cs
- src/modules/Elsa.Http/Contracts/IHttpCorrelationIdSelector.cs
- src/modules/Elsa.Http/Contracts/IHttpWorkflowInstanceIdSelector.cs
- src/modules/Elsa.Http/Elsa.Http.csproj
- src/modules/Elsa.Http/Extensions/ServiceCollectionExtensions.cs
- src/modules/Elsa.Http/Features/HttpFeature.cs
- src/modules/Elsa.Http/Middleware/WorkflowsMiddleware.cs
- src/modules/Elsa.Http/Selectors/HeaderHttpCorrelationIdSelector.cs
- src/modules/Elsa.Http/Selectors/HeaderHttpWorkflowInstanceIdSelector.cs
- src/modules/Elsa.Http/Selectors/QueryStringHttpCorrelationIdSelector.cs
- src/modules/Elsa.Http/Selectors/QueryStringHttpWorkflowInstanceIdSelector.cs
This PR introduces enhancements to the Elsa HTTP module:
1. **Correlation ID Selectors**: A new abstraction, `IHttpCorrelationIdSelector`, has been added to allow for the extraction of correlation IDs from HTTP requests.
2. **Workflow Instance ID Selectors**: The `IHttpWorkflowInstanceIdSelector` interface provides a mechanism to extract workflow instance IDs from HTTP requests. This aids in associating specific workflow instances with incoming HTTP requests.
3. **Base Classes for Selectors**: To simplify the implementation of the above selectors, base classes `HttpCorrelationIdSelectorBase` and `HttpWorkflowInstanceIdSelectorBase` have been provided. These offer common functionalities and can be extended as needed.
> Implement HTTP correlation ID selectors

- src/activities/Elsa.Activities.Conductor/Activities/RunTask.cs
The `Payload` property of the `Elsa.Activities.Conductor.RunTask` is annotated as an `ActivityOutput`. This seems to be wrong as it is used in the `OnExecuteAsync` method, where it is always set to `null` with this annotation. Annotating it to be an `ActivityInput` solves that problem.
> Change RunTask Payload from ActivityOutput to ActivityInput

- src/modules/Elsa.EntityFrameworkCore.MySql/Modules/Management/Extensions.cs
- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Modules/Management/Extensions.cs
- src/modules/Elsa.EntityFrameworkCore.SqlServer/Modules/Management/Extensions.cs
- src/modules/Elsa.EntityFrameworkCore.Sqlite/Modules/Management/Extensions.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/Extensions.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowManagementPersistenceFeature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/ActivityExecutionLogStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/WorkflowExecutionLogStore.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/SafeDictionaryConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/SafeDictionaryConverterFactory.cs
- src/modules/Elsa.Workflows.Core/Serialization/Providers/BasicSerializationProvider.cs
Summary:
This pull request updates the logic for setting up persistence for the EF Core database provider. It also adds a new class `SafeDictionaryConverter` and updates the `BasicSerializationProvider` class.
List of changes:
- Updated `OnSaveAsync()` and `OnLoadAsync()` to use the IActivityStateSerializer interface and JsonSerializer, respectively.
- Added a new class `SafeDictionaryConverter` that safely serializes a dictionary of objects, even if some of the objects are not serializable.
- Added a new class `SafeDictionaryConverterFactory` that creates instances of `SafeDictionaryConverter`. 
- Updated `BasicSerializationProvider` to add the SafeDictionaryConverterFactory to the list of converters, and to enable reference handling. 
- Changed the EF Core workflow instance and …
> Support serialization of non(de)serializable values

- src/clients/Elsa.Api.Client/Contracts/IElsaClient.cs
- src/clients/Elsa.Api.Client/Extensions/DependencyInjectionExtensions.cs
- src/clients/Elsa.Api.Client/Resources/Scripting/Contracts/IJavaScriptApi.cs
- src/clients/Elsa.Api.Client/Resources/Scripting/Requests/GetWorkflowJavascriptDefinitionRequest.cs
- src/clients/Elsa.Api.Client/Resources/WorkflowDefinitions/Contracts/IWorkflowDefinitionsApi.cs
- src/clients/Elsa.Api.Client/Resources/WorkflowDefinitions/Requests/GetTypeDefinitionsRequest.cs
- src/clients/Elsa.Api.Client/Services/ElsaClient.cs
Add the Refit request to retrieve type definitions.
I am not sure if it's okay to have this request in the WorkflowDefinitions interface.
If not please let me know where you want it and i'll refactor.
> V3 get type definitions request

- src/modules/Elsa.Workflows.Runtime/Elsa.Workflows.Runtime.csproj
`System.Drawing.Common v5.0.0` nupkg has one critical vulnerability. `System.Drawing.Common v5.0.0` package is being indirectly referenced by `DistributedLock v2.3.2`. `DistributedLock v2.3.3` now references `System.Drawing.Common v6.0.0`.
Related discussion: #4359
> Package DistributedLock upgraded to V2.3.3

- src/bundles/Elsa.WorkflowServer.Web/Elsa.WorkflowServer.Web.csproj
- src/bundles/Elsa.WorkflowServer.Web/Program.cs
- src/modules/Elsa.EntityFrameworkCore.SqlServer/Modules/Runtime/Extensions.cs
- src/modules/Elsa.EntityFrameworkCore.Sqlite/Modules/Runtime/Extensions.cs
- src/modules/Elsa.ProtoActor/Elsa.ProtoActor.csproj
- src/modules/Elsa.ProtoActor/Extensions/ClusterExtensions.cs
- src/modules/Elsa.ProtoActor/Extensions/ProtoInputExtensions.cs
- src/modules/Elsa.ProtoActor/Features/ProtoActorFeature.cs
- src/modules/Elsa.ProtoActor/Grains/RunningWorkflows.cs
- src/modules/Elsa.ProtoActor/Grains/WorkflowInstance.cs
- src/modules/Elsa.ProtoActor/Handlers/StopRunningWorkflows.cs
- src/modules/Elsa.ProtoActor/Handlers/UpdateRunningWorkflows.cs
- src/modules/Elsa.ProtoActor/Mappers/BookmarkMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/ExceptionMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/WorkflowExecutionResultMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/WorkflowFaultStateMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/WorkflowStatusMapper.cs
- src/modules/Elsa.ProtoActor/Mappers/WorkflowSubStatusMapper.cs
- src/modules/Elsa.ProtoActor/Models/RunningWorkflowInstanceEntry.cs
- src/modules/Elsa.ProtoActor/Proto/RunningWorkflows.Messages.proto
- src/modules/Elsa.ProtoActor/Proto/RunningWorkflows.proto
- src/modules/Elsa.ProtoActor/Proto/Shared.proto
- src/modules/Elsa.ProtoActor/Proto/WorkflowInstance.Messages.proto
- src/modules/Elsa.ProtoActor/Proto/WorkflowInstance.proto
- src/modules/Elsa.ProtoActor/Services/ProtoActorWorkflowRuntime.cs
- src/modules/Elsa.ProtoActor/Snapshots.cs
- src/samples/aspnet/Elsa.Samples.AspNet.ProtoActorRuntime.AzureContainerApps/Program.cs
This PR fixes an issue with the Running Workflows grain by implementing snapshot recovery.
Summary: 
This Pull Request updates imports and references for ProtoActor. It adds ExportState() and ImportState() RPCs to WorkflowInstance and renames WorkflowGrain to WorkflowInstance. It also adds several new messages, records, and handlers to allow for managing existing workflow instances. 
List of changes: 
- Imported google/protobuf/empty.proto and google/protobuf/wrappers.proto packages
- Moved Json message and Input message from Elsa.ProtoActor.Protos to Shared.proto
- Modified option csharp_namespace to Elsa.ProtoActor.ProtoBuf
- Added ExportState() and ImportState() RPCs to WorkflowInstance service
- Renamed WorkflowGrain service to WorkflowInstance
- Renamed WorkflowRegistrySnapshot to …
> Refactor proto files and fix snapshot loading of running workflows grain

- src/modules/Elsa.Dapper/Modules/Management/Services/DapperWorkflowDefinitionStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowDefinitionStore.cs
- src/modules/Elsa.MongoDb/Modules/Management/WorkflowDefinitionStore.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/IsNameUnique/Endpoint.cs
IWorkflowDefinitionStore GetIsNameUnique only inverted the result in the InMemoryStore, and it was inverted again in the endpoint. 
I changed the GetIsNameUnique to return false when the name already exists, and removed the invert in the endpoint. 
This should fix the issue seen in elsa-workflows/elsa-studio#29
> Fixed IsNameUnique for InMemory WorkflowDefinition store

- src/bundles/Elsa.WorkflowServer.Web/Program.cs
- src/modules/Elsa.Liquid/Features/LiquidFeature.cs
- src/modules/Elsa.Liquid/Options/FluidOptions.cs
- src/modules/Elsa.Liquid/Services/LiquidParser.cs
- src/modules/Elsa.Liquid/Services/LiquidTemplateManager.cs
Fixes #4380
This PR also changes from HtmlEncoder to NullEncoder by default.
To configure the default encoder, do this from Program.cs:
```csharp
services.AddElsa(elsa => elsa.UseLiquid(liquid => liquid.FluidOptions => options => options.Encoder = HtmlEncoder.Default));
```
Summary:
This pull request refactors the existing LiquidFeature and LiquidTemplateManager classes, adds a new LiquidOptions class, and adds relevant using statements.
List of Changes:
-Added using statements for System.Text, System.Text.Encodings.Web, and Fluid to the Program.cs file. 
-Added a new option to the LiquidFeature class to configure the Fluid options. 
-Added a new options class LiquidOptions which includes a dictionary of Fluid filter registrations, parser configurations, and a flag for allowing access to …
> Make Liquid TextEncoder configurable

- src/server/Elsa.Server.Api/Attributes/NewtonsoftJsonFormatterAttribute.cs
- src/server/Elsa.Server.Api/Extensions/ElsaNewtonsoftJsonConvention.cs
- src/server/Elsa.Server.Api/Extensions/ServiceCollectionExtensions.cs
The idea is instead of using AddNewtonsoftJson to all controllers,make an attribute to use Newtensoft as Object result's formatter, and apply this attribute to all controllers that in Elsa.Server.Api namespace.
> make NewtonsoftJson and System.Text.Json works side by side.

- src/modules/Elsa.Http/Activities/WriteFileHttpResponse.cs
- src/modules/Elsa.Http/DownloadableProviders/UrlDownloadableProvider.cs
- Support for large zip files by using temp files.
- Buffered response via FileStreamResult
- FileStreamResult supports byte range download resumption
Summary
This pull request addresses a variety of refactoring changes, such as moving `SendFileStream` out of the `WriteFileHttpResponse` class and into a helper class as well as abstracting common code between `SendSingleFileAsync` and `SendMultipleFileAsync` into a new method. Additional modifications to the `CreateContentDisposition`, `WriteResponseAsync`, and `SendMultipleFilesAsync` methods are also included. 
- Added a private method called `GetContentType` that takes parameters `ActivityExecutionContext` and `string filename` and returns a string. 
- Modified existing `CreateContentDisposition` method to account for the new …
> WriteFileHttpResponse updates

- src/clients/Elsa.Api.Client/Resources/ActivityDescriptors/Models/ActivityDescriptor.cs
- src/modules/Elsa.Workflows.Core/Activities/Break.cs
- src/modules/Elsa.Workflows.Core/Activities/Complete.cs
- src/modules/Elsa.Workflows.Core/Activities/End.cs
- src/modules/Elsa.Workflows.Core/Activities/Finish.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/FlowJoin.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/Flowchart.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Contracts/ITerminalNode.cs
- src/modules/Elsa.Workflows.Core/Activities/Sequence.cs
- src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Contracts/ITerminalNode.cs
- src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Models/ActivityDescriptor.cs
- src/modules/Elsa.Workflows.Core/Services/ActivityDescriber.cs
- src/modules/Elsa.Workflows.Core/Services/WorkflowStateExtractor.cs
Provides the ITerminalNode abstraction to allow activities to act as terminal nodes in a diagram, such as End, Break, Finish and Complete.
Terminal nodes will complete their parent Flowchart and Sequence activity immediately and do not have a Done outcome.
This PR also fixes an issue with the Finish activity not completing.
Summary: 
This pull request introduces changes to the ActivityDescriptor model, adds the ITerminalNode interface, updates the display name of the FlowJoin activity, and modifies global logging language to better reflect terminal activities.
List of Changes: 
- Added a new property to the `ActivityDescriptor` model named `IsTerminal`, which is intended to store whether this activity type is a terminal activity. 
- The `Break`, `Complete`, `End`, and `Finish` activity …
> Terminal Activities

- src/modules/Elsa.Http/Activities/WriteFileHttpResponse.cs
- src/modules/Elsa.Http/Features/HttpFeature.cs
- src/modules/Elsa.Http/Options/HttpFileCacheOptions.cs
- src/modules/Elsa.Http/Services/ZipManager.cs
This PR contains the following improvements for the File HTTP Response activity:
1. Control location of temp folder
2. Compute e-tag based on file hash instead of modified date to ensure uniqueness
Summary:
This pull request introduces a number of changes to improve the `WriteFileHttpResponse`, `HttpFeature` and `ZipManager` classes. The changes include using `MD5.Create()` to calculate etag header value in `WriteFileHttpResponse`, switching to `IOptions<HttpFileCacheOptions>` to configure the `IFileCacheStorageProvider` in `HttpFeature`, and adding a new `HttpFileCacheOptions` class for default `LocalCacheDirectory` configuration. The `ZipManager` has also been changed to use `GetTempFilePath` for zip blobs.
List of Changes: 
- Changed `WriteFileHttpResponse` to use `MD5.Create()` to …
> HTTP File Response Improvements

- src/modules/Elsa.AzureServiceBus/Activities/MessageReceived.cs
- src/modules/Elsa.Http/Activities/HttpEndpoint.cs
- src/modules/Elsa.MassTransit/Activities/MessageReceived.cs
- src/modules/Elsa.Scheduling/Activities/StartAt.cs
- src/modules/Elsa.Telnyx/Activities/AnswerCallBase.cs
- src/modules/Elsa.Telnyx/Activities/BridgeCallsBase.cs
- src/modules/Elsa.Telnyx/Activities/CallAnswered.cs
- src/modules/Elsa.Telnyx/Activities/CallHangup.cs
- src/modules/Elsa.Telnyx/Activities/DialAndWait.cs
- src/modules/Elsa.Telnyx/Activities/GatherUsingAudio.cs
- src/modules/Elsa.Telnyx/Activities/GatherUsingSpeak.cs
- src/modules/Elsa.Telnyx/Activities/IncomingCall.cs
- src/modules/Elsa.Telnyx/Activities/StartRecordingBase.cs
- src/modules/Elsa.Telnyx/Activities/TransferCall.cs
- src/modules/Elsa.Telnyx/Activities/WebhookEvent.cs
- src/modules/Elsa.Workflows.Core/Abstractions/Activity.cs
- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Contracts/IActivity.cs
- src/modules/Elsa.Workflows.Core/Enums/ActivityStatus.cs
- src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Extensions/ExpressionExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Middleware/Activities/DefaultActivityInvokerMiddleware.cs
- src/modules/Elsa.Workflows.Runtime/Activities/RunTask.cs
- test/integration/Elsa.IntegrationTests/Scenarios/CanExecute/Activities/CustomActivity.cs
- test/integration/Elsa.IntegrationTests/Scenarios/CanExecute/Tests.cs
- test/integration/Elsa.IntegrationTests/Scenarios/CanExecute/Workflows/MagicWorkflow.cs
- test/integration/Elsa.IntegrationTests/Scenarios/FlowchartNextActivity/Activities/CustomActivity.cs
This PR adda a new `CanExecuteAsync` method to `IActivity`. allowing custom activities to perform custom logic to determine if the activity should be executed or not.
Issue #4477 
Summary:
This pull request adds a new test class, adds a new class for building workflow sequence, and updates the CustomActivity class with a new code activity.
List of Changes:
- Added a test class called CanExecuteTests containing a Theory called 'Activities are executed only when they report that they can execute'
- Added a class called MagicWorkflow with code to build a workflow sequence
- Updated CustomActivity class to include a new code Activity.
Refactoring Target:
- Use more descriptive names for variables and parameters in the MagicWorkflow class
- Consolidate multiple code blocks in the MagicWorkflow …
> Activity Preconditions

- src/core/Elsa.Abstractions/Models/WorkflowPersistenceBehavior.cs
- src/core/Elsa.Core/Handlers/PersistWorkflow.cs
In Elsa.Abstractions there is enum for serialization of existing workflows in blob storage. WorkflowPassCompleted is missing there.
> Missing WorkflowPassCompleted enum element in WorkflowPersistenceBehavior.cs

- src/bundles/Elsa.WorkflowServer.Web/Program.cs
- src/common/Elsa.Api.Common/Extensions/SwaggerExtensions.cs
This adds the Swagger documentation generation and Swagger UI middleware as a pair of extension methods (Issue #4299)
Once these are added to the application, you can view the API documentation by visiting: /swagger
At the moment I've hard-coded the version number at "3.0" - is there a better means of getting the version number of the API? The Elsa.Api.Common project's version number doesn't appear to be set.
Just submitting this PR at this stage to make sure this is heading in the right direction... I'll be adding some actual documentation to the API endpoints and updating this PR for further feedback / review.
Thanks!
> Adds Swagger documentation generation and UI.

- src/core/Elsa.Core/Serialization/DefaultContentSerializer.cs
Switch from `CamelCasePropertyNamesContractResolver` to `DefaultContractResolver`. `CamelCasePropertyNamesContractResolver` has a shared cache for contracts between instances. If any Dictionary<string, string> is previously serialized with settings to process dictionary keys, `ActivityDefinitionProperty.Expressions` will also be serialized with dictionary key processing. It's better to use DefaultContractResolver, which has a cache for each instance.
> 3537 Switch to DefaultContractResolver

- src/activities/Elsa.Activities.Kafka/Activities/SendKafkaMessage/SendKafkaMessage.cs
- src/activities/Elsa.Activities.Kafka/Configuration/KafkaOptions.cs
- src/activities/Elsa.Activities.Kafka/Services/Client.cs
- src/activities/Elsa.Activities.Kafka/Services/WorkerManager.cs
Added possibility to add DefaultConnectionString if connection string in trigger/activity is empty
> [Kafka] Added possibility to add DefaultConnectionString

- src/modules/Elsa.Workflows.Core/Extensions/ActivityPropertyExtensions.cs
- src/modules/Elsa.Workflows.Management/Serialization/Converters/ActivityJsonConverter.cs
This PR ensures that the "Not Found" text is always displayed, instead of any custom display texts.
Summary:
This pull request updates the ActivityPropertyExtensions class to allow for the flagging of an activity to execute synchronously or asynchronously, and adds methods to get and set the display text and description of the activity.
List of Changes:
- Added flag to allow for the flagging of an activity to execute either synchronously or asynchronously
- Added method to get and set the display text and description of the activity 
Refactoring Target:
- Introduce an enum type for ActivityKind to help clarify behavior at the call site
- Use better descriptive strings in the method documentation to make the code easier to reason about
> Update NotFoundActivity display text + description

- src/bundles/Elsa.WorkflowServer.Web/Program.cs
- src/bundles/Elsa.WorkflowServer.Web/WorkflowContexts/CustomerContext.cs
- src/bundles/Elsa.WorkflowServer.Web/WorkflowContexts/OrderWorkflowContextProvider.cs
- src/clients/Elsa.Api.Client/Extensions/DependencyInjectionExtensions.cs
- src/clients/Elsa.Api.Client/Extensions/DictionaryExtensions.cs
- src/clients/Elsa.Api.Client/Resources/Features/Contracts/IFeaturesApi.cs
- src/clients/Elsa.Api.Client/Resources/WorkflowExecutionContexts/Contracts/IWorkflowContextProviderDescriptorsApi.cs
- src/clients/Elsa.Api.Client/Resources/WorkflowExecutionContexts/Models/WorkflowContextProviderDescriptor.cs
- src/modules/Elsa.WorkflowContexts/Endpoints/ProviderTypes/List/Endpoint.cs
- src/modules/Elsa.WorkflowContexts/Extensions/ModuleExtensions.cs
- src/modules/Elsa.Workflows.Api/Endpoints/Features/List/Endpoint.cs
This PR adds a client API for accessing workflow contexts from the server, which is used by the new [WorkflowContext module for Elsa Studio](https://github.com/elsa-workflows/elsa-studio/issues/41).
> Add WorkflowContext client API

- Elsa.sln
- src/bundles/Elsa.WorkflowServer.Web/Elsa.WorkflowServer.Web.csproj
- src/bundles/Elsa.WorkflowServer.Web/Program.cs
- src/bundles/Elsa.WorkflowServer.Web/appsettings.json
- src/modules/Elsa.FileStorage/Activities/OpenFile.cs
- src/modules/Elsa.FileStorage/Activities/SaveFile.cs
- src/modules/Elsa.FileStorage/Contracts/IStorageProvider.cs
- src/modules/Elsa.FileStorage/Elsa.FileStorage.csproj
- src/modules/Elsa.FileStorage/Extensions/ModuleExtensions.cs
- src/modules/Elsa.FileStorage/Features/BlobStorageFeature.cs
- src/modules/Elsa.FileStorage/FodyWeavers.xml
- src/modules/Elsa.FileStorage/Services/BlobStorageProvider.cs
- src/modules/Elsa.Http/Activities/WriteFileHttpResponse.cs
This PR adds an initial version of a new module called Storage.
For now, it comes with SaveFile and OpenFile, and leverages the FluentStorage package.
With FluentStorage, these activities support not just local file system access, but any storage provider that is supported by FluentStorage, such as Azure Blob Storage, AWS, FTP, and many more.
Summary: 
This pull request adds the necessary implementation in order to add a new project for "Elsa.FileStorage" and adds the importation of packages "FluentStorage.Azure.Blobs" and "Elastic.Clients.Elasticsearch.IndexManagement". 
List of Changes: 
- Removed the Quartz configuration section from the appsettings.json file 
- Added OpenFile.cs and SaveFile.cs files under Elsa.FileStorage.Activities namespace
- Added IBlobStorageProvider.cs file …
> Storage module

- src/clients/Elsa.Api.Client/Contracts/IElsaClient.cs
- src/clients/Elsa.Api.Client/Extensions/DependencyInjectionExtensions.cs
- src/clients/Elsa.Api.Client/Resources/ActivityDescriptorOptions/Contracts/IActivityDescriptorOptionsApi.cs
- src/clients/Elsa.Api.Client/Resources/ActivityDescriptorOptions/Requests/GetActivityDescriptorOptionsRequest.cs
- src/clients/Elsa.Api.Client/Resources/ActivityDescriptorOptions/Responses/GetActivityDescriptorOptionsResponse.cs
- src/clients/Elsa.Api.Client/Services/ElsaClient.cs
- src/modules/Elsa.CSharp/Activities/RunCSharp/RunCSharpOptionsProvider.cs
- src/modules/Elsa.Http/ActivityOptionProviders/HttpContentTypeOptionsProvider.cs
- src/modules/Elsa.JavaScript/Activities/RunJavaScript/RunJavaScriptOptionsProvider.cs
- src/modules/Elsa.Python/Activities/RunPython/RunPythonOptionsProvider.cs
- src/modules/Elsa.Workflows.Api/Endpoints/ActivityDescriptorOptions/Get/Endpoint.cs
- src/modules/Elsa.Workflows.Api/Endpoints/ActivityDescriptorOptions/Get/Models.cs
- src/modules/Elsa.Workflows.Core/Contracts/IActivityPropertyOptionsProvider.cs
- src/modules/Elsa.Workflows.Core/Contracts/IPropertyOptionsResolver.cs
- src/modules/Elsa.Workflows.Core/Services/PropertyOptionsResolver.cs
This PR is the first about the #4491 
It's necessary for issue on dashboard project : 
- elsa-workflows/elsa-studio#67
- and elsa-workflows/elsa-studio#51
This PR add :
- Endpoint to get Provider Options
- Api Client interface which could be use by the Studio
- Context Object to pass custom information to the provider from the client (for elsa-workflows/elsa-studio#67)
> Enhancement/runtime options provider#4491

- src/clients/Elsa.Api.Client/Resources/ActivityDescriptorOptions/Contracts/IActivityDescriptorOptionsApi.cs
- src/modules/Elsa.Workflows.Api/Endpoints/ActivityDescriptorOptions/Get/Endpoint.cs
Summary: Changes to '/descriptors/activities/{activityTypeName}/options/{propertyName}' Endpoint
List of Changes: 
- Changed HTTP verb from GET to POST
- Added permission configure
Refactoring Target:
- Create a separate permission configure method to avoid code duplication
- Consider using a more specific permission configure to this endpoint instead of generic permissions
> Change endpoint to Post

- src/designer/elsa-workflows-studio/src/components.d.ts
- src/designer/elsa-workflows-studio/src/components/editors/elsa-multi-expression-editor/elsa-multi-expression-editor.tsx
- src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx
- src/designer/elsa-workflows-studio/src/components/shared/elsa-modal-dialog/elsa-modal-dialog.tsx
Adding the Dialog to the other Expression editors. Is difficult to read when using more complex functions in JavaScript
Original change done in [This PR](https://github.com/elsa-workflows/elsa-core/pull/3510/files#diff-d4f7d49b703578c4114106866ef63b11a77e704ac24ae02e44f4797642d4e351)
Here is a gif demonstrating the changes to the height and width for the dialog/editor.
> Adding dialog to Multi Expression Editor

- src/modules/Elsa.Workflows.Core/Activities/ParallelForEachT.cs
This PR fix the ParallelForEach when the Items list of ParallelForEach activity is empty.
Actually the activity keeps suspended.
Fix #4608
> V3 - Fix ParallelForEach Behaviour when empty items

- src/modules/Elsa.EntityFrameworkCore.Common/Contracts/IElsaDbContextSchema.cs
- src/modules/Elsa.EntityFrameworkCore.Common/DbSchemaAwareMigrationAssembly.cs
- src/modules/Elsa.EntityFrameworkCore.Common/ElsaDbContextBase.cs
- src/modules/Elsa.EntityFrameworkCore.Common/ElsaDbContextOptionsExtension.cs
- src/modules/Elsa.EntityFrameworkCore.Common/ElsaDbContextOptionsExtensions.cs
- src/modules/Elsa.EntityFrameworkCore.MySql/Migrations/Alterations/20231015122151_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.MySql/Migrations/Identity/20231015122238_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.MySql/Migrations/Labels/20231015122253_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.MySql/Migrations/Management/20231015122223_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.MySql/Migrations/Runtime/20231024160940_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Alterations/20231015122203_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Identity/20231015122250_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Labels/20231015122304_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Management/20231015122234_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Migrations/Runtime/20231024160952_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Alterations/20231015122155_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Identity/20231015122242_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Labels/20231015122257_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Management/20231015122227_Initial.cs
- src/modules/Elsa.EntityFrameworkCore.SqlServer/Migrations/Runtime/20231024160944_Initial.cs
This PR allow you to define a custom Schema Name for the `DbContext` **And** take this information into account in Migration.
for example : 
```csharp
elsa.UseWorkflowManagement(management => { management.UseEntityFrameworkCore(ef =>
ef.UseSqlServer("Server=(localdb)\\MSSQLLocalDb;Initial Catalog=Elsav3CustomSchema;Integrated Security=True;",
new ElsaDbContextOptions()
{
SchemaName = "CustomSchemaName",
}));
});
```
If not defined, the default Schema Name will be `Elsa`
This change is available for the following provider : 
- SqlServer
- Mysql
- PostgreSql
Sqlite does'nt seems to take into account any schema name.
Summary:
This pull request changes the hardcoded schema "Elsa" to "_schema.Schema" in CreateIndex(), CreateTable() and DropTable() methods, as well as adding a constructor to …
> Features : Allow Customization of DbContext  Schema

- src/locking/Elsa.DistributedLocking.AzureBlob/DistributedLockingOptionsExtensions.cs
This PR overloads the `UseAzureBlobLockProvider` method to receive a connection string - container name pair for convenience.
> Overload UseAzureBlobLockProvider with connection string/container name

- src/core/Elsa.Core/Options/ElsaOptions.cs
- src/core/Elsa.Core/StartupTasks/ContinueRunningWorkflows.cs
Currently in a multi node environment, a running Workflow on one node can block the ResumeWorkflow Startup on another node.
This PR adds an additional configuration setting to be able to have a custom timeout for acquiring the DistributedLock  in the ContinueRunningWorkflows Startup, which resumes all `running` or `idling`  Workflows.
With this setting i can define a short Timeout like 5-10s before i stop acquiring the lock.
If i can not acquire the lock in a short timespan, i assume that the other node is running this workflow, and i can skip resuming this workflow. 
This design would potentially leave 2 edgecases unhandled:
- the lock acquisistion is very slow for different reasons (network problems, unresponsive DB or similar)
- Potentially: another instance hasn't correctly disposed …
> Make the timeout configurable for acquiring the DistributedLock in ContinueRunningWorkflows

- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/CustomDbContextOptionsExtensionInfo.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/DbSchemaAwareMigrationAssembly.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Elsa.Persistence.EntityFramework.Core.csproj
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/ElsaContext.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/ElsaDbContextOptions.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/ElsaDbContextOptionsExtension.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/ElsaDbContextOptionsExtensions.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/IElsaDbContextSchema.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.MySql/DbContextOptionsBuilderExtensions.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/DbContextOptionsBuilderExtensions.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/Migrations/20211215111405_Initial.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/Migrations/20220120170132_Update241.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/Migrations/20220120204210_Update25.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/Migrations/20220512203705_Update28.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/DbContextOptionsBuilderExtensions.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Migrations/20210523093439_Initial.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Migrations/20210611200035_Update21.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Migrations/20210923112216_Update23.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Migrations/20211215100208_Update24.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Migrations/20220120170155_Update241.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Migrations/20220120204155_Update25.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.PostgreSql/Migrations/20220512203651_Update28.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/DbContextOptionsBuilderExtensions.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/20210523093504_Initial.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/20210611200049_Update21.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/20210923112224_Update23.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/20211215100215_Update24.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/20220120170305_Update241.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/20220120204205_Update25.cs
- src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.SqlServer/Migrations/20220512203701_Update28.cs
This PR allows you to define a custom DB Schema in V2. This basically merges this https://github.com/elsa-workflows/elsa-core/pull/4638 in V2.
Defining a custom Schema:
```
elsa.UseWorkflowManagement(management => { management.UseEntityFrameworkCore(ef =>
ef.UseSqlServer("Server=(localdb)\\MSSQLLocalDb;Initial Catalog=Elsav3CustomSchema;Integrated Security=True;",
new ElsaDbContextOptions()
{
SchemaName = "CustomSchemaName",
}));
});
```
If no Custom-Schema is defined, `Elsa` will be used.
This change applies to
- SqlServer
- PostgreSql
- Oracle
- MySql
> Custom Db Schema for SqlServer, PostgreSql and Oracle

- src/modules/Elsa.Http/Activities/SendHttpRequestBase.cs
This PR allow the user to choose to validate or not the Authorization Header when adding to the request.
__Motivation__
User can be in situation where the Authorization Header is not strictly following the HTTP Standard.
For example, it seems that for example, the AWS Signature is not accepted by the C# implementation.
_sigv4-auth-using-authorization-header_ 
```
Authorization: AWS4-HMAC-SHA256 
Credential=AKIAIOSFODNN7EXAMPLE/20130524/us-east-1/s3/aws4_request, 
SignedHeaders=host;range;x-amz-date,
Signature=fe5f80f77d5fa3beca038a248ff027d0445342fe2855ddc963176630326f1024
```
for example, the semicolon `;` in the SignedHeaders part seems to not be compatible. I don't know who is not respecting the RFC.
So instead of force the user to create a new HTTP activity, I propose to add this …
> Feature HTTP Activity : Allow adding Authorization Header without validation

- src/clients/Elsa.Api.Client/Extensions/DependencyInjectionExtensions.cs
- src/clients/Elsa.Api.Client/Options/ElsaClientBuilderOptions.cs
Add a new option to control the number of automatic retries for transient failures.
Currently when a workflow is triggered from Elsa Studio, it will retry for 3 times automatically if failed, and each time it will start from the the beginning. This means some activities may be run for up to 4 times (for example, when the workflow has two activities, and the first one activity always gets success and the second one is always failed, the first one will be run for 4 times successfully).
Fixes elsa-workflows/elsa-studio#108
> New options to control retry logic for transient failures

- src/common/Elsa.Api.Common/Elsa.Api.Common.csproj
Use the latest release version, instead of the beta version.
> Update FastEndpoints* nuget packages to 5.21.2 version

- Directory.Build.props
Use the new [NET 8 SDK artifacts output layout](https://learn.microsoft.com/en-us/dotnet/core/sdk/artifacts-output) feature which consolidates `bin` and `obj` folders under root level `artifacts` directory. Need to have `Directory.Build.props` to root level for proper configuration (you might want to consider such standard way over common.props too). For a solution with large amount of projects this can help both with I/O performance and cleanup (deleting `obj` and `bin` folders as they are in single place).
To remove old cruft, might be good idea to run locally in solution root directory:
```powershell
Get-ChildItem .\ -include bin,obj -Recurse | foreach ($_) { remove-item $_.fullname -Force -Recurse }
```
> Use NET 8 SDK artifacts output

- src/bundles/Elsa.Server.Web/Program.cs
- src/modules/Elsa.Workflows.Core/Extensions/ExpressionExecutionContextExtensions.cs
This PR addresses #4789 by allowing the JS function `setVariable` to dynamically create a new variable if the specified variable doesn't already exist in the current scope.
This change however, does not create a workflow variable definition, which means it will currently not be visible from the Variables panel when looking at the workflow instance viewer. This might be part of an improvement in a later iteration.
> Allow creation of variables dynamically via `setVariable`

- src/modules/Elsa.Workflows.Core/Services/VariablePersistenceManager.cs
Fixes #4807 
In the LoadVariablesAsync function, it already has "ToList()", fix this in SaveVariablesAsync and DeleteVariablesAsync functions.
> Fix InvalidOperation Exception for SaveVariablesAsync and DeleteVariablesAsync functions

- src/modules/secrets/Elsa.Secrets.Persistence.EntityFramework.SqlServer/Elsa.Secrets.Persistence.EntityFramework.SqlServer.csproj
- src/persistence/Elsa.Persistence.MongoDb/Elsa.Persistence.MongoDb.csproj
- src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/ElsaDashboard.Samples.AspNetCore.Monolith.csproj
- src/samples/server/Elsa.Samples.Server.Host/Elsa.Samples.Server.Host.csproj
Missed to upgrade the dependency of the ElsaDashboard.Samples.AspNetCore.Monolith project which lead to following build error:
`/home/runner/work/elsa-core/elsa-core/src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/ElsaDashboard.Samples.AspNetCore.Monolith.csproj : error NU1605: Warning As Error: Detected package downgrade: Microsoft.Identity.Client from 4.56.0 to 4.54.1. Reference the package directly from the project to select a different version.  [/home/runner/work/elsa-core/elsa-core/Elsa.sln]
/home/runner/work/elsa-core/elsa-core/src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/ElsaDashboard.Samples.AspNetCore.Monolith.csproj : error NU1605:  ElsaDashboard.Samples.AspNetCore.Monolith -> Elsa.Rebus.AzureServiceBus -> …
> 2.x .NET 8 Build fix

- src/modules/Elsa.Workflows.Core/Services/WorkflowStateExtractor.cs
A new method ApplyInput has been added to prevent overwriting any existing input in the WorkflowExecutionContext. Now, input items are added to the workflow execution context only if they don't exist there already. The Apply method has been updated as well to add workflow state inputs appropriately.
Fixes #4705
> Add input application to workflow state extractor

- src/bundles/Elsa.Server.Web/Program.cs
- src/modules/Elsa.JavaScript/Contracts/IJavaScriptEvaluator.cs
- src/modules/Elsa.JavaScript/Helpers/StringObjectDictionaryConverter.cs
- src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
- src/modules/Elsa.Workflows.Core/Extensions/ExpressionExecutionContextExtensions.cs
- test/integration/Elsa.IntegrationTests/Scenarios/JavaScriptListsAndArrays/Tests.cs
A `StringObjectDictionaryConverter` has been added, which converts all `IList` fields of an object to array fields. This enhances the interaction of JS expressions with list types, allowing common Array methods to be applied directly. Furthermore, defaults have been added to the `ExpressionEvaluatorOptions` parameters to improve usability. Lastly, adjustments were made to ensure variables are correctly set while evaluating expressions.
Closes #4849
> Add support for list/array conversion in JavaScript evaluator

- src/modules/Elsa.EntityFrameworkCore.Common/Elsa.EntityFrameworkCore.Common.csproj
It is unused and brings in EF6
> Drop LinqKit dependency

- Elsa.sln.DotSettings
- src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
- src/modules/Elsa.Quartz/Services/QuartzWorkflowScheduler.cs
- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.Cancel.cs
- src/modules/Elsa.Workflows.Core/Extensions/ExpressionExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Services/WorkflowStateExtractor.cs
- test/integration/Elsa.IntegrationTests/Scenarios/JavaScriptListsAndArrays/Tests.cs
This PR introduces an optimization to the workflow instance storage by eliminating the need to persist completed activity execution contexts. This change leverages the previously introduced `ActivityExecutionRecord` storage, which has made the persistence of these contexts redundant. The primary reason for retaining completed activity execution contexts was to facilitate direct access to activity outputs. However, this requirement is now addressed through a recommended workaround that involves capturing activity outputs using variables.
The benefits of this optimization include:
- A significant reduction in the storage size of workflow instances, leading to improved performance in workflow instance viewing.
- Enhanced efficiency in serializing and deserializing workflow instances during …
> Remove Persistence of Completed Activity Execution Contexts

- samples/console/Elsa.Samples.ConsoleApp.HelloWorld/Program.cs
- src/modules/Elsa.ProtoActor/Services/ProtoActorWorkflowRuntime.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IWorkflowRuntime.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowRuntime.cs
The methods in the workflow runtime now accept nullable runtime options. Providing workflow options is now optional - if no options are provided, default values are used. Changes have been applied across all relevant methods in IWorkflowRuntime, ProtoActorWorkflowRuntime and DefaultWorkflowRuntime classes, thus ensuring consistent behavior and null safety across the workflow runtime.
> Make workflow runtime methods accept nullable options

- src/modules/Elsa.MongoDb/Features/MongoDbFeature.cs
Hello,
See issue: 
https://github.com/elsa-workflows/elsa-core/issues/4885
Based on the context provided, it appears that we are encountering a serialization registration issue when running integration tests with Elsa and MongoDB. The error message indicates that a serializer for the Object type is being registered multiple times, which is not allowed by the MongoDB driver.
The code snippet provided suggests a solution to use BsonSerializer.TryRegisterSerializer instead of BsonSerializer.RegisterSerializer.
```csharp
private static void RegisterSerializers()
{
BsonSerializer.TryRegisterSerializer(typeof(object), new PolymorphicSerializer());
BsonSerializer.TryRegisterSerializer(typeof(Type), new TypeSerializer());
BsonSerializer.TryRegisterSerializer(typeof(Variable), new …
```
> issues(4885)

- Elsa.sln.DotSettings
- src/modules/Elsa.Workflows.Core/Serialization/Converters/ActivityJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/ActivityJsonConverterFactory.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/InputJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/InputJsonConverterFactory.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/JsonIgnoreCompositeRootConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/OutputJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/OutputJsonConverterFactory.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/JsonActivitySerializer.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/SerializationOptionsConfigurator.cs
- src/modules/Elsa.Workflows.Management/Features/WorkflowManagementFeature.cs
- test/integration/Elsa.IntegrationTests/Serialization/ProgrammaticWorkflowsAndDelegates/Tests.cs
- test/integration/Elsa.IntegrationTests/Serialization/ProgrammaticWorkflowsAndDelegates/Workflows.cs
This PR fixes an issue when using C# delegates inside of programmatic classes when they are serialized.
Also added new integration tests for serialization of programmatic workflows. 
Additionally, major refactoring was performed on the serialization classes. This involved moving the classes to new namespaces and enhancing their functionalities to correctly handle null inputs and to support the serialization of activities and expressions. Also, updated Elsa.sln.DotSettings and JsonActivitySerializer to handle new serializers.
> Fix serialization of delegate expressions

- src/common/Elsa.Testing.Shared/ServiceProviderExtensions.cs
- src/modules/Elsa.Workflows.Management/Services/WorkflowDefinitionManager.cs
- src/modules/Elsa.Workflows.Management/Services/WorkflowDefinitionPublisher.cs
- test/integration/Elsa.IntegrationTests/Elsa.IntegrationTests.csproj
- test/integration/Elsa.IntegrationTests/Scenarios/DependencyWorkflowsPublishing/Tests.cs
- test/integration/Elsa.IntegrationTests/Scenarios/DependencyWorkflowsPublishing/Workflows/child.json
- test/integration/Elsa.IntegrationTests/Scenarios/DependencyWorkflowsPublishing/Workflows/parent.json
> Update both published and draft consuming workflows upon child workflow definition update

- src/modules/Elsa.EntityFrameworkCore.Common/Extensions/ExpressionExtensions.cs
Converted the result of the Select() operation to a list, within the BuildContainsExpression method. This prevents multiple enumerations of the 'entities' variable, improving the performance of the method by reducing the number of iterations.
Fixes #4884
> Fix memory leak when using EF Core

- src/bundles/Elsa.Server.Web/Program.cs
- src/modules/Elsa.Workflows.Runtime/Activities/Event.cs
- src/modules/Elsa.Workflows.Runtime/Activities/PublishEvent.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IEventPublisher.cs
- src/modules/Elsa.Workflows.Runtime/Services/EventPublisher.cs
The 'input' parameter in 'PublishAsync', 'DispatchAsync' and related methods across multiple classes has been replaced with 'payload'. The renaming of 'input' to 'payload' provides a more intuitive understanding of the parameter as the actual content or data of the event being published or dispatched. It also includes changes in 'PublishInternalAsync' where the workflow input dictionary is now being populated with the payload.
This is a breaking change due to the renaming of the `Input` property to `Payload` on the `PublishEvent` activity.
Although we could (still) consider to deprecate the `Input` property in favor of the new `Payload` property, I think we don't need to given the fact that passing around input from PublishEvent to Event has never worked before this PR, so I doubt that …
> Fix consumption of event payload

- src/modules/Elsa.Workflows.Core/Activities/While.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/InputJsonConverter.cs
> Fix serialization of Boolean activity input

- src/modules/Elsa.MongoDb/Modules/Identity/CreateIndices.cs
- src/modules/Elsa.MongoDb/Modules/Labels/CreateIndices.cs
- src/modules/Elsa.MongoDb/Modules/Management/CreateIndices.cs
- src/modules/Elsa.MongoDb/Modules/Runtime/CreateIndices.cs
Releated to this issues: https://github.com/elsa-workflows/elsa-core/issues/4918
> issues(4918): fix resolve scoped service for Elsa.MongoDb.Modules

- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/List/Endpoint.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/List/Models.cs
- src/modules/Elsa.Workflows.Management/Filters/WorkflowInstanceFilter.cs
Issue: https://github.com/elsa-workflows/elsa-core/issues/4937
Need:
Current: 
At the endpoint **elsa/api/workflow-instances** currently return all workflow instances even we have millions of instances !!
Target:
Add two properties to filters, FromCreatedAt and ToCreatedAt to help us to get instances between 2 date times.
> feature: Add created date time to filter

- src/modules/Elsa.Http/Elsa.Http.csproj
Related to: [https://github.com/elsa-workflows/elsa-core/issues/4951](https://github.com/elsa-workflows/elsa-core/issues/4951)
Removed references to multiple packages that are not used within the project and some (Microsoft.AspNetCore.X) packages were deprecated and should not be used.
Please ensure that the changes does not break anything unforeseen.
> Removed references to packages that are not used

- Directory.Packages.props
- NuGet.Config
- src/clients/Elsa.Api.Client/Resources/WorkflowInstances/Contracts/IWorkflowInstancesApi.cs
- src/clients/Elsa.Api.Client/Resources/WorkflowInstances/Requests/ListWorkflowInstancesRequest.cs
- src/clients/Elsa.Api.Client/Shared/Enums/TimestampFilterOperator.cs
- src/clients/Elsa.Api.Client/Shared/Models/TimestampFilter.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/List/Endpoint.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/List/Models.cs
- src/modules/Elsa.Workflows.Management/Elsa.Workflows.Management.csproj
- src/modules/Elsa.Workflows.Management/Enums/TimestampFilterOperator.cs
- src/modules/Elsa.Workflows.Management/Filters/WorkflowInstanceFilter.cs
- src/modules/Elsa.Workflows.Management/Models/TimestampFilter.cs
- src/modules/Elsa.Workflows.Management/RequiredMembers.cs
This PR enhances the ability to filter workflow instance search results. I includes the following filters:
- Has Incidents
- ID, Correlation ID, Definition ID, Name
- Date ranges: Created, Updated, Finished
The following filters already existed:
- Status
- Sub Status
- Workflow Definitions
> Enhanced Workflow Instance Filters

- Directory.Packages.props
- src/bundles/Elsa.Server.Web/Program.cs
- src/modules/Elsa.EntityFrameworkCore.Common/Elsa.EntityFrameworkCore.Common.csproj
- src/modules/Elsa.EntityFrameworkCore.Common/Extensions/QueryableExtensions.cs
This PR replaces the custom, potentially buggy, bulk upsert implementation by leveraging the battle-tested EFCore.BulkExtensions.MIT package.
Hopefully fixes #4982
> Update BulkUpsertAsync extension method with EFCore.BulkExtensions package

- src/modules/Elsa.Dapper/Services/Store.cs
- src/modules/Elsa.Http/Middleware/WorkflowsMiddleware.cs
> Respond with 500 in case of Incidents

- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowDefinitionStorePopulator.cs
Since we are unable to find the exact scenario in which issue #5033 occurs, logging has been added to get more information.
> Added logging to pinpoint issue #5033

- src/modules/Elsa.Common/Models/VersionOptions.cs
`VersionOptions.LatestAndPublished` was incorrectly setting the `LatestOrPublished` property to true rather than the `LatestAndPublished` property.
> Update VersionOptions.LatestAndPublished to set correct property

- src/modules/Elsa.Common/Serialization/ConfigurableSerializer.cs
- src/modules/Elsa.Expressions/Helpers/ObjectConverter.cs
- src/modules/Elsa.Http/ContentWriters/JsonContentFactory.cs
The update enriches the serializers with Unicode encoding to handle a wider range of characters. Classes such as ConfigurableSerializer, ObjectConverter, and JsonContentFactory have been modified to use JavaScriptEncoder with UnicodeRanges.All, supporting serialization and deserialization of all Unicode characters. Furthermore, any unreferenced code now carries a note for JSON serializer stating that it's incompatible with .NET's trimming feature.
Fixes #5048
> Add Unicode encoding support to serializers

- samples/aspnet/Elsa.Samples.AspNet.BatchProcessing/Workflows/OrderBatchProcessor.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/List/Endpoint.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/List/Models.cs
- src/modules/Elsa.Workflows.Core/Activities/ParallelForEachT.cs
Refactor the endpoint for listing workflow instances to use a more robust enum parsing method and improve validation. Update models to accept string collections for statuses and sub-statuses, which enables validating and parsing these enums directly within the endpoint.
> Refactor workflow instance listing and enum parsing

- Elsa.sln
- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowDefinitionStorePopulator.cs
- test/unit/Elsa.Workflows.Runtime.UnitTests/Elsa.Workflows.Runtime.UnitTests.csproj
- test/unit/Elsa.Workflows.Runtime.UnitTests/Services/DefaultWorkflowDefinitionStorePopulatorTests.cs
- test/unit/Elsa.Workflows.Runtime.UnitTests/Usings.cs
- test/unit/Elsa.Workflows.Runtime.UnitTests1/Services/DefaultWorkflowDefinitionStorePopulatorTests.cs
Fixes #5033 and other issues with importing workflow definitions through background processes.
- Prevents trying to add multiple versions with the Id
- Prevents multiple definitions with status IsLatest
- Makes most recent workflow (based on version) leading
- Fixes version comparison that caused issues in earlier attempts of this fix (Version from Identity compared to Version from root)
> Made loading workflows more robust

- src/modules/Elsa.MongoDb/Modules/Management/CreateIndices.cs
The previous implementation used the generic MongoCollectionBase service to retrieve workflow definition and instance collections. Now, the code has been updated to use IMongoCollection specifically designed for WorkflowDefinition and WorkflowInstance. This change ensures better typing and possibly performance improvements.
This tackles issue #4658
in addition, the indexes documented in CreateIndices.cs were never created until this change was made.
> Update MongoDb collection service retrieval

- src/modules/Elsa.Alterations/Services/DefaultAlterationPlanScheduler.cs
Refactor the ID generation for Alteration Plans to ensure the `planParams.Id` is always set directly before creating a DispatchWorkflowDefinitionRequest. This avoids the unnecessary extra variable and ensures the ID property is consistently used throughout the method.
Fixes 5093
> Fix ID assignment logic in Scheduler

- src/modules/Elsa.Alterations.Core/Contracts/IAlterationPlanManager.cs
- src/modules/Elsa.Alterations.Core/Notifications/AlterationPlanCompleted.cs
- src/modules/Elsa.Alterations.MassTransit/Features/AlterationsMassTransitFeature.cs
- src/modules/Elsa.Alterations/Activities/CompleteAlterationPlan.cs
- src/modules/Elsa.Alterations/Activities/DispatchAlterationJobs.cs
- src/modules/Elsa.Alterations/Activities/GenerateAlterationJobs.cs
- src/modules/Elsa.Alterations/Features/AlterationsFeature.cs
- src/modules/Elsa.Alterations/Handlers/AlterationJobCompletedHandler.cs
- src/modules/Elsa.Alterations/Handlers/AlterationPlanCompletedHandler.cs
- src/modules/Elsa.Alterations/Services/AlterationPlanManager.cs
- src/modules/Elsa.Alterations/Services/DefaultAlterationJobRunner.cs
- src/modules/Elsa.Alterations/Services/DefaultAlterationRunner.cs
- src/modules/Elsa.Alterations/Workflows/ExecuteAlterationPlanWorkflow.cs
Implement notification publishing for completed alteration plans and add related handlers and management logic to coordinate alterations workflow triggering and completion status updates.
Fixes #5096
> Add alteration notifications and management

- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/ActivityExecutionLogStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/WorkflowExecutionLogStore.cs
- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.cs
- src/modules/Elsa.Workflows.Runtime/Extensions/LogExtensions.cs
- src/modules/Elsa.Workflows.Runtime/Extensions/LogStringExtensions.cs
The new LogStringExtensions class provides methods to sanitize log messages, ensuring that null characters are replaced with "\0". These changes prevent issues with PostgreSQL's inability to store null characters in strings, improving log data compatibility with the database.
Fixes #5102
> Add log message sanitization for PostgreSQL

- src/modules/Elsa.Alterations.Core/Contracts/IWorkflowInstanceFinder.cs
- src/modules/Elsa.Alterations.Core/Extensions/ServiceCollectionExtensions.cs
- src/modules/Elsa.Alterations.Core/Models/ActivityFilter.cs
- src/modules/Elsa.Alterations.Core/Models/AlterationWorkflowInstanceFilter.cs
- src/modules/Elsa.Alterations.Core/Services/AlteredWorkflowDispatcher.cs
- src/modules/Elsa.Alterations.Core/Services/WorkflowInstanceFinder.cs
- src/modules/Elsa.Alterations/Activities/GenerateAlterationJobs.cs
- src/modules/Elsa.Alterations/Endpoints/Alterations/DryRun/Endpoint.cs
- src/modules/Elsa.Alterations/Endpoints/Alterations/DryRun/Response.cs
- src/modules/Elsa.Workflows.Management/Filters/WorkflowInstanceFilter.cs
Added a new DryRun endpoint for executing alteration plans and implemented the IWorkflowInstanceFinder interface to search for workflow instances. Refactored existing code to use new workflow instance finder service, resulting in cleaner activity implementation.
Fixes #5109
> Add DryRun endpoint and workflow instance finder

- src/modules/Elsa.Workflows.Runtime/Activities/BulkDispatchWorkflows.cs
The terminology for the task completion status has been changed in the BulkDispatchWorkflows class. This includes renaming 'Finished' to 'Complete' in the FlowNode attribute, and when calling CompleteActivityWithOutcomesAsync method. This change makes the status names more consistent across the application.
Closes #4946
> Update FlowNode status terminology in BulkDispatchWorkflows

- .github/workflows/packages.yml
- docker/docker-compose.yml
- src/bundles/Elsa.Server.Web/Elsa.Server.Web.csproj
- src/common/Elsa.Features/Implementations/Module.cs
- src/common/Elsa.Features/Services/IModule.cs
- src/modules/Elsa.EntityFrameworkCore.Common/PersistenceFeatureBase.cs
- src/modules/Elsa.MassTransit.RabbitMq/Features/RabbitMqServiceBusFeature.cs
- src/modules/Elsa.MassTransit/Features/MassTransitFeature.cs
- src/modules/Elsa.MassTransit/Features/MassTransitWorkflowDispatcherFeature.cs
- src/modules/Elsa.MongoDb/Common/MongoDbStore.cs
- src/modules/Elsa.Workflows.Api/Features/WorkflowsApiFeature.cs
- src/modules/Elsa.Workflows.Core/Activities/DynamicActivity.cs
- src/modules/Elsa.Workflows.Core/Contexts/ActivityCompletedContext.cs
- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.Cancel.cs
- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.Complete.cs
- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Extensions/ActivityExtensions.cs
- src/modules/Elsa.Workflows.Core/Models/CreateBookmarkArgs.cs
- src/modules/Elsa.Workflows.Core/Services/BookmarkHasher.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowRuntime.cs
This PR introduces several minor improvements and bug fixes identified following the release of version 3.1, enhancing stability and functionality:
- Resolved a MongoDB exception triggered by attempting to bulk-write an empty document set: `System.ArgumentException: Must contain at least 1 request`.
- Addressed an EF Core Migrations exception: `System.MissingMethodException: Cannot dynamically create an instance of type V3_1`.
- Corrected an issue with RabbitMQ usage without MT Dispatcher, leading to a missing consumer type error.
- Solved a problem when using MassTransit without dispatcher features, resulting in a missing `IEndpointChannelFormatter` in the DI container.
- Refined code organization by moving specific ActivityExecutionContext extensions to a partial class, part of a …
> Minor improvements and bug fixes following the 3.1 release

- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.Complete.cs
- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Extensions/DictionaryExtensions.cs
- src/modules/Elsa.Workflows.Runtime/Activities/BulkDispatchWorkflows.cs
This PR introduces significant improvements to the BulkDispatchWorkflows activity by enabling the support for multiple input keys. Specifically, it allows users to provide a list of items, with each item being a dictionary. This change permits each dictionary key to act as the input name for the dispatched workflow, providing users with precise control over the inputs of the child workflow.
Furthermore, this update includes the flexibility to configure a different key for the workflow input, moving beyond the previously hardcoded "Item" key. This enhancement ensures backward compatibility for users who prefer not to adopt the "list of dictionaries" method, maintaining the activity's utility in existing workflows without requiring any modifications.
Sample Items JS expression: …
> Enhance BulkDispatchWorkflows Activity with Support for Multiple Input Keys and Customizable Input Key

- src/modules/Elsa.Workflows.Runtime/Activities/BulkDispatchWorkflows.cs
The method call used to complete an activity in the BulkDispatchWorkflows has been changed. Previously, the CompleteActivityAsync method was used, but it was replaced with the CompleteActivityWithOutcomesAsync method providing "Done" as the outcome.
Fixes #5184
> Update method call in BulkDispatchWorkflows

- src/modules/secrets/Elsa.Secrets/Encryption/AesSecretEncryptor.cs
- src/modules/secrets/Elsa.Secrets/Encryption/ISecretEncryptor.cs
- src/modules/secrets/Elsa.Secrets/Extensions/SecretsOptionsBuilderExtensions.cs
- src/modules/secrets/Elsa.Secrets/Manager/SecretsManager.cs
- src/modules/secrets/Elsa.Secrets/Providers/SecretsProvider.cs
I added new interface for encryptor so it is easy to change encryption method in server configuration. However I have few questions about `SecretsConfigOptions` that was added recently. It has 2 properties: `Enabled` and `EncryptionEnabled`. Before my changes for encryption `Enabled` property was used and `EncryptionEnabled` was unused at all. 
Should I return using of `Enabled` property and remove `EncryptionEnabled`?
Also options have `ConnectionStringIdentifier` and `ConnectionString` that are not used from options class at all. Should we keep it in options class?
> Allow to change encryption algorithm for secret properties

- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/FlowFork.cs
In the FlowFork.cs file of the Elsa.Workflows.Core module, the method ScheduleOutcomesAsync has been replaced with CompleteActivityWithOutcomesAsync. This fixes the issue of the activity not completing.
Fixes #5204
> Replace ScheduleOutcomesAsync with CompleteActivityWithOutcomesAsync

- src/bundles/Elsa.Server.Web/Program.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultActivityExecutionMapper.cs
> Fix LogPersistenceMode default mapping logic

- src/modules/Elsa.Workflows.Runtime/Activities/BulkDispatchWorkflows.cs
- Fixed "Item" use in correlation Id function. Previously the Item property was not accesible.
- Fixed "An item with the same key has already been added. Key: Error". This happened when both workflows that we were trying to dispatch failed during dispatching and they both tried to add the "Error" key in the journal.
- Fixed 'Suspended' bulk dispatch activity bug: If dispatching fails the workflow still waits for the children to complete. The behavior was changed to wait only after the ones for which dispatching succeeded.
> Bulk BulkDispatchWorkflows fixes

- src/modules/Elsa.Workflows.Runtime/Services/DefaultActivityExecutionMapper.cs
The code changes involve updating the activity execution mapper in Elsa.Workflows.Runtime. The updated logic now consider the closest ancestor in the workflow hierarchy when determining the workflow persistence property. This provides a more accurate representation of the workflow's state, rather than relying solely on the workflow execution context.
Fixes #5252
> Update activity execution mapping in workflow runtime

- src/modules/Elsa.Alterations.Core/Serialization/AlterationSerializer.cs
- src/modules/Elsa.Common/Contracts/IJsonSerializer.cs
- src/modules/Elsa.Common/Extensions/JsonSerializerOptionsExtensions.cs
- src/modules/Elsa.Common/Serialization/ConfigurableSerializer.cs
- src/modules/Elsa.Common/Serialization/JsonSerializer.cs
- src/modules/Elsa.Expressions/Helpers/ObjectConverter.cs
- src/modules/Elsa.Workflows.Core/Expressions/ObjectExpressionHandler.cs
- src/modules/Elsa.Workflows.Core/Extensions/ExpressionExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Extensions/VariableExtensions.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/ActivityJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/ExcludeFromHashConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/JsonIgnoreCompositeRootConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/SafeValueConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/VariableConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/ApiSerializer.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/JsonActivitySerializer.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/JsonWorkflowStateSerializer.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/SafeSerializer.cs
- src/modules/Elsa.Workflows.Management/Services/WorkflowSerializer.cs
This update refactors multiple classes dealing with JSON serialization. The usage of serializer options now includes a caching mechanism to avoid unnecessary recomputation. 'CreateOptions' method is replaced by a 'GetOptions' method that considers cached options. Classes are adjusted to clone options when necessary, ensuring a fresh and accurate context each time.
Closes #5144
> Refactor serializer options usage and enhance caching in workflow serialization

- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.Complete.cs
relative to #5262
This PR remove the SerializedOutput Value from the Journal Data , This avoid duplication of information in the `WorkflowExecutionLogRecords` table.
> Remove SerializedOutputValue from JournalData

- Directory.Packages.props
- samples/aspnet/Elsa.Samples.AspNet.EntityFrameworkCore.PostgresSql/Elsa.Samples.AspNet.EntityFrameworkCore.PostgresSql.csproj
- src/common/Elsa.Api.Common/Abstractions/Endpoints.cs
- src/modules/Elsa.Quartz/Elsa.Quartz.csproj
Bumped versions of packages and explicity specifed versions of packages to ensure the correct/latest versions was used by the dependency chain.
> bumped versions to fix dependency vulnerabilities

- src/bundles/Elsa.Server.Web/Program.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/Features/AzureServiceBusFeature.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/FlowJoin.cs
- test/component/Elsa.Workflows.ComponentTests/Helpers/Fixtures/Infrastructure.cs
- test/component/Elsa.Workflows.ComponentTests/Helpers/Fixtures/WorkflowServer.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/Activities/FlowJoins/Tests.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/Activities/FlowJoins/Workflows.cs
This PR fixes #5348
The relevant changes for the fix are found in FlowJoin.cs. All other changes were made to cater to the component test running successfully, regardless of the configured service bus broker in the "program under test".
> Fix FlowJoin Activity NRE Bug

- src/modules/Elsa.MassTransit/Services/MassTransitWorkflowDispatcher.cs
This commit introduces a distributed lock to the MassTransitWorkflowDispatcher to prevent concurrent updates to the workflow instance. The lock is acquired before any interaction with the workflow instance and is released after the update operation is complete.
Fixes #5417
> Add distributed locking to MassTransitWorkflowDispatcher

- src/modules/Elsa.MassTransit/Services/MassTransitWorkflowDispatcher.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/BulkDispatchWorkflows/BulkDispatchWorkflowsTests.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/BulkDispatchWorkflows/Workflows/EmployeeGreetingWorkflow.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/BulkDispatchWorkflows/Workflows/GreetEmployeesWorkflow.cs
This PR fixes a concurrency issue when sending concurrent workflow execution requests to the same workflow instance with different inputs.
Originally, this change was made to add support for sending large inputs from a parent workflow to a dispatched child workflow via a service bus.
However, that doesn't work when sending multiple messages concurrently, which we are seeing when using BulkDispatchWorkflow where multiple child workflows complete close to one another, overriding the "global" input state associated with the workflow input.
This PR attempts to only store the input with the workflow instance upon instance creation, while sending input alongside the dispatch message when resuming existing ones. The assumption here being that those messages include smaller input payloads.
The …
> Revert sending input as global state instead of parameter

- src/modules/Elsa.Http/Features/HttpFeature.cs
- src/modules/Elsa.Http/Parsers/TextHtmlHttpContentParser.cs
First iteration of a text/html http content parser, this parser handle the request as string but this allow to accept the request.(instead of reject it or set a null value because parser doesn't exist)
fix #5115
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5460)
> add text/html content parser as string content

- src/modules/Elsa.Scheduling/Activities/StartAt.cs
- src/modules/Elsa.Scheduling/Services/DefaultTriggerScheduler.cs
The `DefaultTriggerScheduler` received a significant refactoring, with the injection of the `ISystemClock` service and a modification of several method calls. Additionally, a check is included to avoid scheduling `StartAt` triggers if their execution time is in the past. For these triggers, an information message is logged and scheduling is skipped.
Fixes #5454
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5463)
> Refactor `DefaultTriggerScheduler` and handle past `StartAt` triggers

- samples/aspnet/Elsa.Samples.AspNet.WorkflowServer/Elsa.Samples.AspNet.WorkflowServer.csproj
- samples/aspnet/Elsa.Samples.AspNet.WorkflowServer/Program.cs
- samples/aspnet/Elsa.Samples.AspNet.WorkflowServer/Workflows/MysteriousPondWorkflow.cs
- samples/aspnet/Elsa.Samples.AspNet.WorkflowServer/mysterious_pond.http
- src/bundles/Elsa.Server.Web/Elsa.Server.Web.csproj
- src/modules/Elsa.Expressions/Extensions/JsonElementExtensions.cs
- src/modules/Elsa.Expressions/Models/ExpressionDescriptor.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/ActivityJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/ExpressionJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/ExpressionJsonConverterFactory.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/InputJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/JsonActivitySerializer.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/SafeSerializer.cs
- src/modules/Elsa.Workflows.Management/Providers/DefaultExpressionDescriptorProvider.cs
- src/modules/Elsa.Workflows.Runtime/Providers/ClrWorkflowProvider.cs
Extended the expression serialization. Added new classes ExpressionJsonConverter and ExpressionJsonConverterFactory implementing serialization of expression objects. Also, made respective changes in different serializers and related files for seamless integration.
Fixes #4781 #5474
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5490)
> Add JSON Serialization for Elsa expression

- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Activities/Flowchart.cs
- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/FlowScope.cs
This update prevents the creation of multiple flow activities by checking if the activity is already set to be created while the activity context has not yet been created.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5544)
> Add activity existence check in Flowchart

- src/bundles/Elsa.Server.Web/Program.cs
- src/modules/Elsa.MongoDb/Elsa.MongoDb.csproj
- src/modules/Elsa.MongoDb/Modules/Alterations/AlterationJobStore.cs
- src/modules/Elsa.MongoDb/Modules/Alterations/AlterationPlanStore.cs
- src/modules/Elsa.MongoDb/Modules/Alterations/CreateIndices.cs
- src/modules/Elsa.MongoDb/Modules/Alterations/Documents/AlterationPlanDocument.cs
- src/modules/Elsa.MongoDb/Modules/Alterations/Extensions.cs
- src/modules/Elsa.MongoDb/Modules/Alterations/Feature.cs
This PR provides a MongoDB implementation for interfaces `IAlterationJobStore` and `IAlterationPlanStore`, using the existing `MongoDbStore` class.
This solves issue #5554.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5555)
> Added MongoDB implementation for alteration storage

- src/modules/Elsa.MongoDb/Modules/Alterations/Feature.cs
Fixes DI issue related to `MongoAlterationPlanStore` introduced in #5555.
`MongoDbStore<AlterationPlanDocument>` and `IMongoCollection<AlterationPlanDocument>` weren't actually registered in the DI container, so trying to resolve them from `IServiceProvider` failed.
This was caused by me not committing all changes when I refactored how they were resolved in `MongoAlterationPlanStore`'s constructor: initially I was instantiating them using `IMongoDatabase`, but when I refactored the constructor to resolve them from the DI container I actually forgot to commit and push all the changes I made before opening a PR.
I re-tested everything and it works as expected now. Sorry!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fixed DI registration for MongoAlterationPlanStore

- src/bundles/Elsa.Server.Web/Enums/ApplicationRole.cs
- src/bundles/Elsa.Server.Web/Program.cs
- src/bundles/Elsa.Server.Web/appsettings.json
- src/modules/Elsa.MassTransit.AzureServiceBus/Features/AzureServiceBusFeature.cs
- src/modules/Elsa.MassTransit.RabbitMq/Features/RabbitMqServiceBusFeature.cs
- src/modules/Elsa.MassTransit/Features/MassTransitFeature.cs
A new enum ApplicationRole has been added for distinguishing among different roles (Hybrid, Api, Worker) an application can take. In the configuration of MassTransit, it is now possible to disable the consumers based on application role, which can help optimize the usage of resources and increase application efficiency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5561)
> Add application roles and configure them in MassTransit

- src/bundles/Elsa.Server.Web/Elsa.Server.Web.csproj
- src/modules/Elsa.Caching.Distributed.MassTransit/Features/MassTransitDistributedCacheFeature.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/Features/AzureServiceBusFeature.cs
- src/modules/Elsa.MassTransit.RabbitMq/Features/RabbitMqServiceBusFeature.cs
- src/modules/Elsa.MassTransit/Extensions/MassTransitFeatureExtensions.cs
- src/modules/Elsa.MassTransit/Extensions/ModuleExtensions.cs
- src/modules/Elsa.MassTransit/Features/MassTransitFeature.cs
- src/modules/Elsa.MassTransit/Features/MassTransitWorkflowManagementFeature.cs
- src/modules/Elsa.MassTransit/Models/ConsumerTypeDefinition.cs
- src/modules/Elsa.Workflows.Management/Services/WorkflowDefinitionActivityRegistryUpdater.cs
This PR fixes two issues:
1. Consumers related to background work such as invoking dispatch workflows were still active when using the Azure Service Bus transport.
2. Consumers related to pub/sub in order to invalidate caches and similar constructs were also disabled. They are now excluded from being disabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5578)
> Fix MT consumer registration when DisableConsumers is set

- Directory.Packages.props
- NuGet.Config
- src/modules/Elsa.Http/Activities/DownloadHttpFile.cs
- src/modules/Elsa.Http/Activities/HttpEndpoint.cs
- src/modules/Elsa.Http/Contexts/HttpResponseParserContext.cs
- src/modules/Elsa.Http/Contracts/IHttpContentParser.cs
- src/modules/Elsa.Http/DownloadableContentHandlers/HttpFileDownloadableContentHandler.cs
- src/modules/Elsa.Http/DownloadableContentHandlers/MultiDownloadableContentHandler.cs
- src/modules/Elsa.Http/Extensions/HeadersExtensions.cs
- src/modules/Elsa.Http/Extensions/HttpActivityExecutionContextExtensions.cs
- src/modules/Elsa.Http/Features/HttpFeature.cs
- src/modules/Elsa.Http/Models/HttpFile.cs
- src/modules/Elsa.Http/Models/HttpHeaders.cs
- src/modules/Elsa.Http/Parsers/FileHttpContentParser.cs
- src/modules/Elsa.Http/Parsers/JsonHttpContentParser.cs
- src/modules/Elsa.Http/Parsers/PlainTextHttpContentParser.cs
- src/modules/Elsa.Http/Parsers/TextHtmlHttpContentParser.cs
- src/modules/Elsa.Http/Parsers/XmlHttpContentParser.cs
- src/modules/Elsa.Http/Services/DefaultDownloadableManager.cs
- src/modules/Elsa.JavaScript/ObjectConverters/ByteArrayConverter.cs
- src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
- src/modules/Elsa.JavaScript/Services/TypeAliasRegistry.cs
- src/modules/Elsa.Workflows.Core/Extensions/OutputExtensions.cs
This commit adds a new activity, DownloadHttpFile, which provides the capability to download a file from a specified URL. It introduces supporting classes like HttpFile, FileHttpContentParser, and several extensions methods related to handling HTTP headers and file content. It also contains necessary updates in existing classes to accommodate the new file-download feature.
Closes #5601
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5608)
> Add HTTP file download activity and supporting classes

- src/bundles/Elsa.ServerAndStudio.Web/Program.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/Commands/CleanupSubscriptions.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/Features/AzureServiceBusFeature.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/Handlers/CleanupSubscriptions.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/Handlers/RemoveOrphanedSubscriptions.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/HostedServices/CleanSubscriptionsWithoutQueues.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/Notifications/CleanupSubscriptions.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/Options/SubscriptionCleanupOptions.cs
This fixes being able to remove temporary queues and subscriptions from the service bus namespace based on missing heartbeats.
This service will use all topics which name start with `elsa` to clean up all
- Topics without any subscriptions
- Subscriptions for which the forwarding queue can not be found in the same namespace.
#fixes 5635
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5636)
> Implement automated cleanup for Azure Service Bus subscriptions

- Directory.Packages.props
- src/modules/Elsa.MassTransit/Consumers/WorkflowDefinitionEventsConsumer.cs
- src/modules/Elsa.MassTransit/Contracts/IDistributedWorkflowDefinitionEventsDispatcher.cs
- src/modules/Elsa.MassTransit/Handlers/DistributedWorkflowDefinitionNotificationsHandler.cs
- src/modules/Elsa.MassTransit/Messages/WorkflowDefinitionVersionRetracted.cs
- src/modules/Elsa.MassTransit/Services/MassTransitDistributedEventsDispatcher.cs
- src/modules/Elsa.Workflows.Management/Handlers/RefreshActivityRegistry.cs
- src/modules/Elsa.Workflows.Management/Notifications/WorkflowDefinitionVersionRetracted.cs
- src/modules/Elsa.Workflows.Management/Services/WorkflowDefinitionPublisher.cs
This update enhances the handling of workflow definition retraction across multiple files and includes new notifications for workflow definition version retraction. The logic for updating the workflow definition registry has been adapted to keep published workflows in the registry unless they are no longer marked as an activity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5650)
> Update workflow definition registry and retraction handling

- src/modules/Elsa.MassTransit.AzureServiceBus/Handlers/RemoveOrphanedSubscriptions.cs
Fixed name matching which prevented subscriptions from being deleted
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5658)
> Fix subscription name matching in RemoveOrphanedSubscriptions

- src/modules/Elsa.Scheduling/Features/SchedulingFeature.cs
Scoped scheduler can't detect start duplicates because it's called from different scopes and doesn't have shared registry for tasks. (#5499)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5687)
> Register scheduler as singleton to avoid multiple starts of same task

- src/modules/Elsa.Dapper/Modules/Runtime/Records/ActivityExecutionRecord.cs
- src/modules/Elsa.Dapper/Modules/Runtime/Stores/DapperActivityExecutionRecordStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/ActivityExecutionLogStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/WorkflowExecutionLogStore.cs
- src/modules/Elsa.Expressions/Options/ExpressionOptions.cs
- src/modules/Elsa.Workflows.Core/Features/FlowchartFeature.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicDictionaryConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverterFactory.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/JsonWorkflowStateSerializer.cs
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JArrayIsland.json
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JArrayWithoutType.json
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JObjectIsland.json
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JObjectWithoutType.json
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JsonArrayIsland.json
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JsonObjectIsland.json
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/JsonObjectWithoutType.json
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/Polymorphism/Tests.cs
Updated JSON conversion to be able to use type aliases when saving serialized data to the DB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5682)
> Update serialization and conversion functions

- src/modules/Elsa.Workflows.Runtime/Activities/BulkDispatchWorkflows.cs
- src/modules/Elsa.Workflows.Runtime/Activities/DispatchWorkflow.cs
- src/modules/Elsa.Workflows.Runtime/Bookmarks/EventBookmarkPayload.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IWorkflowExecutionLogSink.cs
- src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs
- src/modules/Elsa.Workflows.Runtime/Middleware/Workflows/PersistWorkflowExecutionLogMiddleware.cs
- src/modules/Elsa.Workflows.Runtime/Services/StoreWorkflowExecutionLogSink.cs
Introduced an interface `IWorkflowExecutionLogSink` for storing workflow execution log records and implemented it as `StoreWorkflowExecutionLogSink`. This centralizes and streamlines the handling of persisting execution logs into the workflow's runtime, thus making the process more modular and maintainable. The `PersistWorkflowExecutionLogMiddleware` has also been refactored to use this sink, replacing the direct usage of the workflow execution log store.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5708)
> Add sink for persisting workflows execution log records

- src/clients/Elsa.Api.Client/Resources/WorkflowInstances/Requests/JournalFilter.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/Journal/FilteredList/Endpoint.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowInstances/Journal/FilteredList/Models.cs
This commit introduces the ActivityNodeIds filter to the journal request models. This enhancement allows filtering logs based on specific activity node IDs, providing more granular control over workflow instance logs. Additionally, unnecessary summary comments have been removed for clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5741)
> Add ActivityNodeIds filter to journal requests

- src/modules/Elsa.Workflows.Runtime/Contracts/IWorkflowExecutionLogRecordExtractor.cs
- src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs
- src/modules/Elsa.Workflows.Runtime/Services/StoreWorkflowExecutionLogSink.cs
- src/modules/Elsa.Workflows.Runtime/Services/WorkflowExecutionContext.cs
Introduced a new service, WorkflowExecutionLogRecordExtractor, to abstract the logic for extracting workflow execution logs records from the WorkflowExecutionContext. Updated StoreWorkflowExecutionLogSink to use this new service, which simplifies the execution log persistence method. This modification enhances code readability and enables potential reuse of the extraction logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5728)
> Add WorkflowExecutionLogRecordExtractor

- src/modules/Elsa.Http/Handlers/InvalidateHttpWorkflowsCache.cs
- src/modules/Elsa.MassTransit/Consumers/WorkflowDefinitionEventsConsumer.cs
- src/modules/Elsa.MassTransit/Handlers/DistributedWorkflowDefinitionNotificationsHandler.cs
- src/modules/Elsa.MassTransit/Messages/WorkflowDefinitionsReloaded.cs
- src/modules/Elsa.MassTransit/Services/AmbientConsumerScope.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Refresh/Endpoint.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Refresh/Models.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Reload/Endpoint.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IWorkflowDefinitionStorePopulator.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IWorkflowDefinitionsReloader.cs
- src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs
- src/modules/Elsa.Workflows.Runtime/Handlers/InvalidateHttpWorkflowCache.cs
- src/modules/Elsa.Workflows.Runtime/Handlers/InvalidateTriggersCache.cs
- src/modules/Elsa.Workflows.Runtime/Handlers/InvalidateWorkflowsCache.cs
- src/modules/Elsa.Workflows.Runtime/Notifications/WorkflowDefinitionsReloaded.cs
- src/modules/Elsa.Workflows.Runtime/Responses/RefreshWorkflowDefinitionsResponse.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowDefinitionStorePopulator.cs
- src/modules/Elsa.Workflows.Runtime/Services/WorkflowDefinitionRefresher.cs
- src/modules/Elsa.Workflows.Runtime/Services/WorkflowDefinitionsReloader.cs
- test/component/Elsa.Workflows.ComponentTests/Elsa.Workflows.ComponentTests.csproj
- test/component/Elsa.Workflows.ComponentTests/Scenarios/WorkflowDefinitionRefresh/DynamicEndpointTests.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/WorkflowDefinitionReload/RemoveReloadWorkflowTests.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/WorkflowDefinitionReload/http-workflow.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5732)
Also includes improvements suggested in the refresh PR (https://github.com/elsa-workflows/elsa-core/pull/5713) and during testing.
> Implemented workflows reload endpoint

- src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Middleware/Workflows/EngineExceptionHandlingMiddleware.cs
- src/modules/Elsa.Workflows.Runtime/Elsa.Workflows.Runtime.csproj.DotSettings
- src/modules/Elsa.Workflows.Runtime/Extensions/WorkflowExecutionPipelineBuilderExtensions.cs
Integrate new EngineExceptionHandlingMiddleware into the workflow execution pipeline to catch and log exceptions outside of running workflow activity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5860)
> Add engine exception handling middleware

- src/modules/Elsa.EntityFrameworkCore.Common/Contracts/IDbExceptionHandler.cs
- src/modules/Elsa.EntityFrameworkCore.Common/EntityStore.cs
- src/modules/Elsa.EntityFrameworkCore.Common/Store.cs
- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Features.cs
- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Handlers/DbExceptionHandler.cs
- src/modules/Elsa.EntityFrameworkCore/Handlers/NoopDbExceptionHandler.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Alterations/Feature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Identity/Feature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Labels/Feature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowDefinitionPersistenceFeature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowInstancePersistenceFeature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowManagementPersistenceFeature.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/WorkflowRuntimePersistenceFeature.cs
- src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Exceptions/DataProcessingException.cs
Introduced customizable database exception handlers across various modules, enabling specific error handling strategies for different DbContexts. Implemented a generic interface for exception handling and provided specific implementations for PostgreSQL and a No-op handler. Updated the code to utilize these handlers in various persistence features, enhancing error management and modularity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5869)
> Add customizable DB exception handlers

- src/modules/Elsa.Expressions/Helpers/ObjectConverter.cs
- src/modules/Elsa.Scheduling/Activities/Delay.cs
Switched to dictionary index access for "ResumeAt" in Delay.cs to ensure more efficient updating. Added handling for byte[] in ObjectConverter.cs to correctly deserialize from base64 strings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5878)
> Refactor journal data access and improve byte[] handling

- samples/aspnet/Elsa.Samples.AspNet.OrchardCoreIntegration/appsettings.json
- src/modules/Elsa.Agents.Activities/ActivityProviders/AgentActivityProvider.cs
- src/modules/Elsa.Workflows.Core/Contracts/ICommitStateHandler.cs
- src/modules/Elsa.Workflows.Core/Services/NoopCommitStateHandler.cs
- src/modules/Elsa.Workflows.Core/Services/WorkflowRunner.cs
- src/modules/Elsa.Workflows.Runtime.Distributed/Features/DistributedRuntimeFeature.cs
- src/modules/Elsa.Workflows.Runtime.Distributed/Services/DistributedWorkflowClient.cs
- src/modules/Elsa.Workflows.Runtime.Distributed/Services/DistributedWorkflowRuntime.cs
- src/modules/Elsa.Workflows.Runtime/Services/BookmarkPersister.cs
- src/modules/Elsa.Workflows.Runtime/Services/BookmarkResumer.cs
- src/modules/Elsa.Workflows.Runtime/Services/BookmarkUpdater.cs
- src/modules/Elsa.Workflows.Runtime/Services/StoreBookmarkQueue.cs
- src/modules/Elsa.Workflows.Runtime/Services/StoreCommitStateHandler.cs
Fixed background activity completion by fixing a bug in the bookmark updater.
The bookmark updater was deleting too many bookmarks, preventing background activities from being resumed & completed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5882)
> Fix background activity completion

- .github/workflows/packages.yml
- src/clients/Elsa.Api.Client/Resources/ActivityDescriptors/Requests/ListActivityDescriptorsRequest.cs
- src/modules/Elsa.Workflows.Api/Endpoints/ActivityDescriptors/List/Endpoint.cs
- src/modules/Elsa.Workflows.Core/Contracts/IActivityRegistry.cs
- src/modules/Elsa.Workflows.Core/Services/ActivityRegistry.cs
- src/modules/Elsa.Workflows.Core/Services/ActivityRegistryLookupService.cs
- src/modules/Elsa.Workflows.Management/Handlers/RefreshActivityRegistry.cs
- src/modules/Elsa.Workflows.Management/Services/ActivityRegistryPopulator.cs
Renamed several `RefreshDescriptors` methods to `RefreshDescriptorsAsync` to reflect their asynchronous nature consistently. Added an optional refresh parameter in the `ListActivityDescriptorsRequest` class and updated related endpoints to handle this parameter, triggering a registry refresh if necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5876)
> Add optional refresh parameter

- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Handlers/DbExceptionTransformer.cs
- src/modules/Elsa.Workflows.Core/Exceptions/DataProcessingException.cs
- src/modules/Elsa.Workflows.Core/Exceptions/UniqueKeyConstraintViolationException.cs
Refactor DataProcessingException to remove unique key logic and create a dedicated UniqueKeyConstraintViolationException. Update DbExceptionTransformer to use the new exception for unique key violations, improving code clarity and separation of concerns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5917)
> Introduce UniqueKeyConstraintViolationException

- src/modules/Elsa.Alterations.Core/Contexts/AlterationHandlerContext.cs
- src/modules/Elsa.Alterations.Core/Models/AlterationLog.cs
- src/modules/Elsa.Alterations.Core/Models/AlterationLogEntry.cs
- src/modules/Elsa.Alterations/Middleware/Workflows/RunAlterationsMiddleware.cs
- src/modules/Elsa.MongoDb/Common/MongoDbStore.cs
This PR addresses issue #5897. The implemented changes are:
- Add check in `MongoDbStore.AddManyAsync(IEnumerable<TDocument> documents, CancellationToken cancellationToken)` to verify that the `documents` collection has elements before trying to save them.
- Add the `EventName` property to class `AlterationLogEntry`. Made it nullable for backwards compatibility, and because it's not applicable in some scenarios.
- Add the alteration logs into the workflow execution context logs in `RunAlterationsMiddleware`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5911)
> Add alteration logs to workflow execution logs (#5897)

- src/apps/ElsaStudioWebAssembly/Program.cs
After updating solution to use Elsa.Studio packages to version 3.3.0-preview.524, one project doesn't compile du to signature change (`AddRemoteBackend`).
This PR fix the call to the method with the right parameters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5945)
> Fix : Change to parameter after update to Elsa.Studio packages to version 3.3.0-preview.524

- samples/drop-ins/SampleDropIn/DropIn.cs
- src/common/Elsa.DropIns.Core/IDropIn.cs
- src/common/Elsa.DropIns/Contexts/NuGetPackageAssemblyLoadContext.cs
- src/common/Elsa.DropIns/Elsa.DropIns.csproj
- src/common/Elsa.DropIns/Helpers/AssemblyLoader.cs
- src/common/Elsa.DropIns/HostedServices/DropInDirectoryMonitorHostedService.cs
- src/common/Elsa.DropIns/Models/DropInDescriptor.cs
New feature and code improvement.
Introduces an `Unconfigure` method for drop-ins and improves assembly loading to avoid file locking issues.
- `DropIn.cs` and `IDropIn.cs`: Added `Unconfigure` method for drop-ins.
- `NuGetPackageAssemblyLoadContext.cs`: Disposed `packageReader` to close `.nupkg` file.
- `AssemblyLoader.cs`: Modified to load assemblies from a memory stream.
- `DropInDirectoryMonitorHostedService.cs`: Added debounced unloader, async loading, and handling of file deletion events.
- `DropInDescriptor.cs`: Changed to class with `DynamicallyAccessedMembers` attribute to suppress IL2072 warning.
Fixes #5943
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-c …
> Enh/5943 DropIns - Prevention of File Locks and Unloading

- .github/workflows/packages.yml
After update of download-artifact by dependabot (#5941), we need to update the upload-artifact to the same major version (v4) to avoid issue : 
`Unable to download artifact(s): Artifact not found for name: elsa-nuget-packages
Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5947)
> [chore] Update upload-artifact major version for CI 

- Directory.Packages.props
- src/modules/Elsa.MassTransit/Elsa.MassTransit.csproj
After updating to Masstransit 8, ```MassTransit.Extensions.DependencyInjection``` has become obsolete and is recommended for removal. It is not used in the code, but adds incompatibility with Masstransit 8.
https://masstransit.io/support/upgrade#version-8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/5955)
> Remove obsolete package MassTransit.Extensions.DependencyInjection

- src/modules/Elsa.MongoDb/Modules/Management/WorkflowDefinitionStore.cs
- src/modules/Elsa.MongoDb/Modules/Runtime/BookmarkStore.cs
- src/modules/Elsa.MongoDb/Modules/Runtime/TriggerStore.cs
- This PR fixes the missing passing for tenantAgnostic to MongoStore in WorkflowDefinitionStore, BookmarkStore, TriggerStore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6002)
> Fix: missing tenantAgnostic parameter passing

- Directory.Build.props
- Directory.Packages.props
- src/bundles/Elsa.Server.Web/Elsa.Server.Web.csproj
- src/bundles/Elsa.ServerAndStudio.Web/Elsa.ServerAndStudio.Web.csproj
- src/bundles/Elsa.Studio.Web/Elsa.Studio.Web.csproj
- src/clients/Elsa.Api.Client/Elsa.Api.Client.csproj
- src/modules/Elsa.EntityFrameworkCore.Common/Elsa.EntityFrameworkCore.Common.csproj
- src/modules/Elsa.EntityFrameworkCore.MySql/Elsa.EntityFrameworkCore.MySql.csproj
- src/modules/Elsa.EntityFrameworkCore.PostgreSql/Elsa.EntityFrameworkCore.PostgreSql.csproj
- src/modules/Elsa.EntityFrameworkCore.SqlServer/Elsa.EntityFrameworkCore.SqlServer.csproj
- src/modules/Elsa.EntityFrameworkCore.Sqlite/Elsa.EntityFrameworkCore.Sqlite.csproj
- src/modules/Elsa.EntityFrameworkCore/Elsa.EntityFrameworkCore.csproj
- src/modules/Elsa.FileStorage/Elsa.FileStorage.csproj
- src/modules/Elsa.Http/Elsa.Http.csproj
- src/modules/Elsa.MongoDb/Elsa.MongoDb.csproj
- src/modules/Elsa.Quartz.EntityFrameworkCore.MySql/Elsa.Quartz.EntityFrameworkCore.MySql.csproj
- src/modules/Elsa.Quartz.EntityFrameworkCore.PostgreSql/Elsa.Quartz.EntityFrameworkCore.PostgreSql.csproj
- src/modules/Elsa.Quartz.EntityFrameworkCore.SqlServer/Elsa.Quartz.EntityFrameworkCore.SqlServer.csproj
- src/modules/Elsa.Quartz.EntityFrameworkCore.Sqlite/Elsa.Quartz.EntityFrameworkCore.Sqlite.csproj
- src/modules/Elsa.Telnyx/Elsa.Telnyx.csproj
- src/modules/Elsa.WorkflowProviders.BlobStorage/Elsa.WorkflowProviders.BlobStorage.csproj
- src/modules/Elsa.Workflows.Api/Elsa.Workflows.Api.csproj
Replaced hardcoded System.Text.Json version 8.0.4 with a variable $(SystemTextJsonVersion) across multiple project files. This improves maintainability and consistency when updating the package version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6019)
> Update System.Text.Json version reference

- src/modules/Elsa.MongoDb/Common/PersistenceFeatureBase.cs
- src/modules/Elsa.MongoDb/Contracts/ICollectionNamingStrategy.cs
- src/modules/Elsa.MongoDb/Features/MongoDbFeature.cs
- src/modules/Elsa.MongoDb/NamingStrategies/DefaultNamingStrategy.cs
Hello! This PR addresses issue #6004.
I created a `ICollectionNamingStrategy` interface, to allow customizing the names of the MongoDB collections created by Elsa Workflows. By creating their own implementation for this interface, users would be able to add a prefix etc. to the names of the collections. I used DI for resolving the `ICollectionNamingStrategy` implementation to allow users to inject `IConfiguration` or `IOptions<T>` in their implementations, in case for instance they want to get their prefix from a config file.
The scenario that inspired this PR was multiple services that use Elsa Workflows using the same MongoDB database. So they needed a way to differentiate between each service's Elsa collections. Also, I noticed the EF Core and Elasticsearch implementations already …
> Add MongoDB collection naming strategy

- src/modules/Elsa.MongoDb/Features/MongoDbFeature.cs
This PR resolves the issue proposed in https://github.com/elsa-workflows/elsa-core/issues/6001. It manually registers SerializedKeyValuePair.Key to BsonClassMap to prevent index creation failure.
Given that the SerializedKeyValuePair class is used by other persistence implementations, I believe manually registering its SerializedKeyValuePair.Key to BsonClassMap in the Mongo feature is a more appropriate solution. This approach avoids modifying the definition of SerializedKeyValuePair, which could potentially impact other persistence implementations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6036)
> Manually register SerializedKeyValuePair.Key to BsonClassMap to prevent index creation failure

- src/clients/Elsa.Api.Client/Shared/UIHints/SingleLine/SingleLineProps.cs
- src/modules/Elsa.Http/UIHints/HttpEndpointPathUIHandler.cs
- src/modules/Elsa.Workflows.Core/UIHints/SingleLine/SingleLineProps.cs
This PR introduces a "copy full path" feature for the `httpendpoint` activity in Elsa [#133](https://github.com/elsa-workflows/elsa-studio/issues/133) , utilizing the `MudExtension` component to enable start and end adornments. This feature has been integrated into the `SingleLineComponent`, allowing it to be toggled on or off through a flag in elsa-core. Currently, the Blazor text field has a limitation where both start and end adornments cannot be added to the same component, an issue acknowledged in the MudBlazor repository ([Issue #8945](https://github.com/MudBlazor/MudBlazor/issues/8945)).
1. Leverages `MudExtension` to support both start and end adornments.
2. Adds a copy icon as an end adornment, with the flexibility to support more adornments in the future.
3. Integrates the …
> Add Functionality to Copy Entire Path from HTTP Endpoint Activity #133

- src/modules/Elsa.MongoDb/Features/MongoDbFeature.cs
- src/modules/Elsa.MongoDb/Serializers/JsonNodeBsonSerializer.cs
Introduce JsonNodeBsonConverter for BSON serialization of JsonNode objects. Update MongoDbFeature to register the new serializer, enhancing JSON handling within MongoDB serialization context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6043)
> Add JsonNode BSON serializer

- src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverter.cs
Add null checks for `referenceResolver` in cases where `RefPropertyName` and `IdPropertyName` are being processed. This prevents potential null reference exceptions and ensures safer deserialization of objects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6051)
> Enhance error handling in `PolymorphicObjectConverter`

- src/apps/Elsa.Server.Web/Program.cs
- src/modules/Elsa.Dapper/Modules/Runtime/Stores/DapperBookmarkQueueStore.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/BookmarkQueueStore.cs
- src/modules/Elsa.MongoDb/Modules/Runtime/BookmarkQueueStore.cs
- src/modules/Elsa.Secrets.Management/Features/SecretManagementFeature.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IBookmarkQueuePurger.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IBookmarkQueueStore.cs
- src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs
- src/modules/Elsa.Workflows.Runtime/Filters/BookmarkQueueFilter.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultBookmarkQueuePurger.cs
- src/modules/Elsa.Workflows.Runtime/Stores/MemoryBookmarkQueueStore.cs
- src/modules/Elsa.Workflows.Runtime/Tasks/PurgeBookmarkQueueRecurringTask.cs
Introduce a new class `DefaultBookmarkQueuePurger` to purge old bookmark queue items. This includes an interface `IBookmarkQueuePurger` and a recurring task `PurgeBookmarkQueueRecurringTask`, with necessary updates to `IBookmarkQueueStore` implementations and application configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6080)
> Add bookmark queue purger functionality

- src/apps/Elsa.Server.Web/Program.cs
- src/modules/Elsa.CSharp/Extensions/VariableNameExtensions.cs
- src/modules/Elsa.CSharp/Handlers/GenerateArgumentAccessors.cs
- src/modules/Elsa.CSharp/Handlers/GenerateWorkflowInputAccessors.cs
- src/modules/Elsa.CSharp/Handlers/GenerateWorkflowVariableAccessors.cs
- src/modules/Elsa.CSharp/Options/CSharpOptions.cs
- src/modules/Elsa.JavaScript/Elsa.JavaScript.csproj
- src/modules/Elsa.JavaScript/Extensions/VariableNameExtensions.cs
- src/modules/Elsa.JavaScript/Features/JavaScriptFeature.cs
- src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithVariables.cs
- src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithVariablesAndInputOutputAccessors.cs
- src/modules/Elsa.JavaScript/Helpers/VariableNameValidator.cs
- src/modules/Elsa.JavaScript/Options/JintOptions.cs
- src/modules/Elsa.JavaScript/Providers/ActivityOutputFunctionsDefinitionProvider.cs
- src/modules/Elsa.JavaScript/Providers/CommonFunctionsDefinitionProvider.cs
- src/modules/Elsa.JavaScript/Providers/CommonTypesDefinitionProvider.cs
- src/modules/Elsa.JavaScript/Providers/InputFunctionsDefinitionProvider.cs
- src/modules/Elsa.JavaScript/Providers/VariableTypeDefinitionProvider.cs
- src/modules/Elsa.JavaScript/Providers/WorkflowVariablesTypeDefinitionProvider.cs
- src/modules/Elsa.JavaScript/Providers/WorkflowVariablesVariableProvider.cs
This PR adds an option to disable the automatic wrapper generation of C# and JavaScript functions for workflow variables.  
- **C# Syntax:**  
When opting out, `Variables.MyVariable` will no longer be available. Variables can only be accessed using:  
- `Variables.Get("MyVariable")`  
- `Variables.Get<T>("MyVariable")`  
- **JavaScript Syntax:**  
When opting out, `variables.MyVariable` and `getMyVariable()` will no longer be available. Variables can only be accessed using:  
- `getVariable("MyVariable")`  
This feature is helpful for applications requiring the use of variable names that are invalid in JavaScript or C#.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa …
> Add Variable Name Validation and Wrapper Control  

- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Extensions/ConnectionsExtensions.cs
Replaced visitedActivities with visitedConnections to ensure accuracy and clarity in tracking visited connections rather than activities. This change fixes #5865
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6138)
> Refactor connection traversal to use visitedConnections set

- src/modules/Elsa.Common/Multitenancy/Models/TenantScope.cs
- src/modules/Elsa.MassTransit/Consumers/WorkflowMessageConsumer.cs
- src/modules/Elsa.MassTransit/Middleware/TenantConsumeMiddleware.cs
Fixes #6133
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6144)
> Fix Tenant ID propagation for MassTransit

- src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/TypeJsonConverter.cs
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/Tests.cs
#5682 broke serialization in several ways:
- When a generic type was being serialized, such as ``List`1``, the `` ` `` was being escaped by `JsonSerializer.Serialize` to `"\u0060"`. The PolymorphicObjectConverter would then `.Trim('"')` without unescaping the `` ` ``, causing `"\\u0060"` to be written into the final json.
- When the type is generic with one type parameter, e.g. `List<T>`, and also `IEnumerable<T>`, as `List<T>` is, then it would append `[]` at the end of the type name, resulting in: `"System.Collections.Generic.List\\u00601[[Elsa.Workflows.IntegrationTests.Serialization.JsonSerialization.WorkflowAction, Elsa.Workflows.IntegrationTests]], System.Private.CoreLib[]"` which is very invalid. It may only do that, if the typename was simplified because the `elementType` is in …
> Fix Serialization of generic types including collections

- src/modules/Elsa.ProtoActor/Extensions/ProtoOutputExtensions.cs
- src/modules/Elsa.ProtoActor/Mappers/WorkflowExecutionResultMapper.cs
- src/modules/Elsa.ProtoActor/Proto/Shared.proto
- src/modules/Elsa.ProtoActor/Proto/WorkflowInstance.Messages.proto
- src/modules/Elsa.Workflows.Runtime/Activities/ExecuteWorkflow.cs
- src/modules/Elsa.Workflows.Runtime/Results/WorkflowExecutionResult.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowRuntime.cs
Introduced `Output` message and related data serialization/deserialization methods in `ProtoOutputExtensions`. Updated `WorkflowExecutionResult` and impacted methods to include `Output` handling. Enhanced workflow runtime logic to manage and integrate output data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6152)
> Add output serialization and deserialization support

- src/apps/Elsa.ServerAndStudio.Web/Program.cs
This PR addresses the Python.Runtime.BadPythonDllException error encountered in the Elsa.ServerAndStudio.Web solution. The error occurs because Runtime.PythonDLL path was not set
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6151)
> Fix: Resolve Python.Runtime.BadPythonDllException in Elsa.ServerAndStudio.Web

- src/modules/Elsa.Common/Converters/BigIntegerJsonConverter.cs
- src/modules/Elsa.Common/Serialization/ConfigurableSerializer.cs
- test/integration/Elsa.JavaScript.IntegrationTests/JsonConverterTest.cs
#6163
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6164)
> fix JavaScript BigInt mapping to BigInteger serialization incorrect

- src/modules/Elsa.JavaScript/Extensions/EngineExtensions.cs
- src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithCommonFunctions.cs
- src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithVariables.cs
- src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithVariablesAndInputOutputAccessors.cs
- src/modules/Elsa.JavaScript/Helpers/ObjectConverterHelper.cs
- src/modules/Elsa.Tenants/Features/TenantsFeature.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/JavaScriptVariables/JavaScriptVariablesWorkflow1.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/JavaScriptVariables/JavaScriptVariablesWorkflow2.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/JavaScriptVariables/JavaScriptVariablesWorkflow3.cs
- test/component/Elsa.Workflows.ComponentTests/Scenarios/JavaScriptVariables/JavaScriptVariablesWorkflowTests.cs
This PR addresses a bug where variables set using the `set{VariableName}` JavaScript syntax were being overridden during the workflow variable synchronization process. The issue occurred because the `variables` object, which serves as a copy of the workflow variables, was empty and incorrectly copied back, overwriting the manually set values.
- Added logic to check if copied variables have been modified.  
- Only modified variables are copied back into the workflow variables.  
- Retains values set using `set{VariableName}` syntax, ensuring expected behavior.
This ensures that user-defined variable values persist without interference from the synchronization logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fix JS Variable Setting Bug in Workflow Variable Sync Logic  

- .github/workflows/packages.yml
- Directory.Packages.props
- src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
Some systems require invalid syntax that is no longer supported by Jint 4. This downgrade is a temporary measure for those systems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6180)
> Downgrade to Jint 3.x for compatibility

- src/common/Elsa.Mediator/Contracts/IJobQueue.cs
- src/common/Elsa.Mediator/Services/JobQueue.cs
- src/modules/Elsa.Hangfire/Services/HangfireBackgroundActivityScheduler.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IBackgroundActivityScheduler.cs
- src/modules/Elsa.Workflows.Runtime/Handlers/CancelBackgroundActivities.cs
- src/modules/Elsa.Workflows.Runtime/Services/LocalBackgroundActivityScheduler.cs
Add a new method `UnscheduledAsync` to unschedule jobs across various components, including the job queue, background activity scheduler, and Hangfire integration. This enhancement provides a more robust way to remove jobs from scheduling, complementing the existing cancellation functionality.
This fixes an issue where a background activity execution job that resumed a workflow, which in turn would remove any associated bookmarks, which in turn would cancel the background job while that job is still executing and has to e.g. persist changes made to the DB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6183)
> Introduce job unscheduling functionality

- src/modules/Elsa.Webhooks/Handlers/RunTaskHandler.cs
- src/modules/Elsa.Webhooks/Models/RunTaskWebhookPayload.cs
Incorporated the TenantId field into the RunTaskWebhookPayload model and updated the RunTaskHandler to pass this information. This change enables multi-tenant support by including the tenant identifier in webhook payloads.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6191)
> Add TenantId to RunTaskWebhookPayload

- src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverter.cs
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/JsonSerialization/Tests.cs
This was broken by both #5871 and #5682:
1. When a `List<Guid>` was serialized, it was recognized as a primitive collection and thus plainly written to the JSON without any type information: `["d4d8404c-4357-47ff-a343-649a116539f5"]`
2. When this JSON was deserialized, due to lack of type info, it was deserialized as `List<object>`, containing `string`s. This is already not good.
3. When this `List<object>` gets serialized again (e.g. due to multiple workflow suspends causing `WorkflowState` serialization), this time it fails the primitive collection recognition, because `object` is not a primitive type. It now gets serialized as `{"_items": ["d4d8404c-4357-47ff-a343-649a116539f5"], "_type": "Object[]"}`
4. When that JSON gets deserialized, it tries to `ReadType(...)` but `ReadType` fails …
> Fix Primitive Collection serialization

- src/modules/Elsa.OpenTelemetry/Middleware/OpenTelemetryTracingActivityExecutionMiddleware.cs
- src/modules/Elsa.OpenTelemetry/Middleware/OpenTelemetryTracingWorkflowExecutionMiddleware.cs
This PR add the `TenantId` property to the span for :
- Workflow Span
- Activity Span
The aim is to facilitate the querying in the end analysis tools
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6083)
> [Feat: OTEL + Tenants] : Add TenantId Property to Span 

- src/modules/Elsa.Identity/Features/IdentityFeature.cs
- src/modules/Elsa.Quartz/Contracts/IJobKeyProvider.cs
- src/modules/Elsa.Quartz/Features/QuartzSchedulerFeature.cs
- src/modules/Elsa.Quartz/Services/JobKeyProvider.cs
- src/modules/Elsa.Quartz/Services/QuartzWorkflowScheduler.cs
- src/modules/Elsa.Quartz/Tasks/RegisterJobsTask.cs
This PR fixes an issue where jobs would scheduled only once because their key would already exist. Instead, jobs are now stored durably and we check to see if a trigger already exists, rather than a job.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6200)
> Fix Quartz scheduler implementation

- src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.InputEvaluation.cs
Commented out state filtering logic to address issues with log sanitization. The raw value is now directly stored in the activity state until a redesigned solution is implemented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6202)
> Disable activity state filtering temporarily.

- src/modules/Elsa.Common/Multitenancy/Implementations/DefaultTenantService.cs
- src/modules/Elsa.Tenants.AspNetCore/Extensions/ModuleExtensions.cs
- Introduced `SemaphoreSlim` to ensure thread safety for initialization and refresh operations in `DefaultTenantService`.  
- These changes address race conditions and enhance reliability during tenant operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6205)
> Add concurrency locks to DefaultTenantService operations

- src/modules/Elsa.Workflows.Core/Extensions/VariableExtensions.cs
- src/modules/Elsa.Workflows.Core/Services/VariablePersistenceManager.cs
Added `TryParseValue` method to handle parse errors gracefully and prevent crashes. Updated `VariablePersistenceManager` to log warnings when variable parsing fails, providing better debugging support and resilience during workflow execution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6207)
> Improve variable parsing with error handling and logging

- src/modules/Elsa.Retention/Feature/RetentionFeature.cs
Allow users to define their own sweep interval of the cleanup job in the Retention module
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6208)
> Retention: Add sweep interval to feature configuration

- src/modules/Elsa.Retention/CleanupStrategies/DeleteWorkflowInstanceStrategy.cs
- src/modules/Elsa.Retention/Feature/RetentionFeature.cs
- src/modules/Elsa.Retention/Jobs/CleanupJob.cs
Currently, we always delete `WorkflowInstance` entities after executing the `CleanupStrategy` of the related entities. 
https://github.com/elsa-workflows/elsa-core/blob/08f7c2bf782e867c327cc91863b63befceb804a2/src/modules/Elsa.Retention/Jobs/CleanupJob.cs#L75-L78
This might not be wanted if a stategy is implemented that archives the workflows while still retaining them in the orginal database. The introduced change allows us to define `CleanupStrategy` for the `WorkflowInstance` just like any other related entity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6211)
> Retention: Allow to define cleanup strategy for workflow instances

- src/modules/Elsa.Workflows.Core/Contexts/StorageDriverContext.cs
- src/modules/Elsa.Workflows.Core/Services/VariablePersistenceManager.cs
- src/modules/Elsa.Workflows.Runtime/Activities/ExecuteWorkflow.cs
- src/modules/Elsa.Workflows.Runtime/Bookmarks/ExecuteWorkflowPayload.cs
- src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs
- src/modules/Elsa.Workflows.Runtime/Handlers/ResumeExecuteWorkflowActivity.cs
This update introduces the ability to optionally wait for child workflows to complete before finishing the ExecuteWorkflow activity. A bookmark mechanism is used to resume the activity when the child workflow completes. Additionally, a new handler was added to manage the resumption of these workflows upon completion events.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6226)
> Add support for waiting for child workflows in ExecuteWorkflow

- src/modules/Elsa.Workflows.Core/Services/PropertyUIHandlerResolver.cs
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/UIHintSerializiation/ActivityUIHintDescriberTests.cs
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/UIHintSerializiation/TestActivity.cs
- test/integration/Elsa.Workflows.IntegrationTests/Serialization/UIHintSerializiation/TestEnumType.cs
This fixes #6082 and possibly other complaints about dropdowns not populating in the Elsa dashboard UI
The change includes two unit tests: the first test (checking for the dropdown uihint) passes without my changes, the second test (checking if the activity describer includes the UI specification for the dropdown) fails without my changes, but passes with my changes. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6217)
> Fix for #6082 - dropdowns are not populated for inputs without UIHints

- Directory.Packages.props
- src/Directory.Build.props
- src/modules/Elsa.Agents.Persistence.EntityFrameworkCore.MySql/Elsa.Agents.Persistence.EntityFrameworkCore.MySql.csproj
- src/modules/Elsa.Common/Elsa.Common.csproj
- src/modules/Elsa.EntityFrameworkCore.MySql/Elsa.EntityFrameworkCore.MySql.csproj
- src/modules/Elsa.Quartz.EntityFrameworkCore.MySql/Elsa.Quartz.EntityFrameworkCore.MySql.csproj
- src/modules/Elsa.Quartz/Elsa.Quartz.csproj
This PR removes support for .NET 6.0 from the project. Updates include:  
- Adjusted project files to target only supported .NET versions.  
- Updated documentation and CI/CD pipelines to reflect the removal of .NET 6.0.  
- Removed any .NET 6.0-specific code or dependencies.  
This change simplifies maintenance and focuses development on currently supported .NET versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6233)
> Drop .NET 6 Support

- src/modules/Elsa.Expressions/Helpers/ObjectConverter.cs
- src/modules/Elsa.Workflows.Core/Services/VariablePersistenceManager.cs
Added try-catch block to log failures when reading variables from storage, ensuring robust error handling. Also refined type checking for `ExpandoObject` deserialization in `ObjectConverter` to prevent invalid operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6256)
> Handle exceptions in variable loading and fix type checking.

- src/apps/Directory.Build.props
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/ImportFiles/Endpoint.cs
- src/modules/Elsa.Workflows.Core/Serialization/ReferenceHandlers/CrossScopedReferenceHandler.cs
- src/modules/Elsa.Workflows.Core/Serialization/Serializers/JsonWorkflowStateSerializer.cs
- src/modules/Elsa.Workflows.Management/Services/WorkflowDefinitionImporter.cs
- **Improves performance:** The converters and static properties are pre-configured when the class is initialized. Only the `ReferenceHandler` is refreshed per call, avoiding repeated configuration of common options like converters.
- **Thread-safe:** Since `_cachedOptions` is immutable, it can safely be reused across threads.
**Tradeoffs:** Still a performance cost during cloning, but much faster than fully recreating options each time as was done before the PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6272)
> Refactor JsonWorkflowStateSerializer to improve performance

- src/modules/Elsa.Workflows.Core/Serialization/Converters/TypeJsonConverter.cs
- src/modules/Elsa.Workflows.Management/Mappers/VariableDefinitionMapper.cs
Updated the logic to use `MakeArrayType` for array handling instead of generic collection types, ensuring consistency and better alignment with expected type structures. Adjustments were made in both the `VariableDefinitionMapper` and the `TypeJsonConverter`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6283)
> Refactor array type handling in variable and JSON converters

- Directory.Packages.props
- src/apps/Elsa.Server.Web/Elsa.Server.Web.csproj
- src/apps/Elsa.Server.Web/Program.cs
- src/apps/Elsa.Server.Web/appsettings.json
- src/modules/Elsa.Hangfire/Elsa.Hangfire.csproj
- src/modules/Elsa.Hangfire/Extensions/ModuleExtensions.cs
- src/modules/Elsa.Hangfire/Features/HangfireFeature.cs
- src/modules/Elsa.Hangfire/Features/HangfireSqlServerStorageFeature.cs
- src/modules/Elsa.Hangfire/Features/HangfireSqliteStorageFeature.cs
- src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs
Added support for configuring Hangfire job storage per database provider, including PostgreSql, SQLite, and SQL Server. Introduced new methods for flexible Hangfire setup, while marking older APIs and storage configuration extensions as obsolete. Refactored related configurations for streamlined and centralized job scheduling logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6284)
> Enable customizable Hangfire job storage and deprecate obsolete APIs.

- src/modules/Elsa.Http/Activities/HttpEndpoint.cs
- src/modules/Elsa.Http/Extensions/RouteExtensions.cs
- src/modules/Elsa.Http/Middleware/HttpWorkflowsMiddleware.cs
- src/modules/Elsa.Http/Services/RouteMatcher.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Post/Endpoint.cs
- src/modules/Elsa.Workflows.Api/Serialization/ArgumentJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/TypeJsonConverter.cs
- src/modules/Elsa.Workflows.Core/Services/VariableMapper.cs
- Previously, the code incorrectly used `MakeCollectionType` for arrays. This has been corrected to use `MakeArrayType`, ensuring proper deserialization of array arguments.
- Improved `TypeJsonConverter` to handle list type aliases more explicitly, replacing ambiguous syntax with clearer format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6301)
> Fix array type handling

- src/modules/Elsa.Common/Features/MultitenancyFeature.cs
Ensure `RunStartupTasks` is added before background and recurring tasks as order is critical for correct startup and tenant activation behavior. This prevents potential misalignment in task execution during tenant lifecycle events.
Fixes #6269
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6303)
> Reorder tenant services initialization for proper execution.

- src/apps/Elsa.Server.Web/Program.cs
- src/modules/Elsa.JavaScript/Extensions/EngineExtensions.cs
- src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithVariables.cs
- src/modules/Elsa.JavaScript/Options/JintOptions.cs
- src/modules/Elsa.Workflows.Core/Extensions/ExpressionExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Models/ActivityOutputRegister.cs
- src/modules/Elsa.Workflows.Core/Models/PropertyDescriptor.cs
Introduce a `DisableVariableCopying` option to improve performance by preventing workflow variables from being copied into the Jint engine or back into the workflow context. Updated related logic to honor this setting and ensure compatibility with existing behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6320)
> Add option to disable variable copying in Jint engine

- src/modules/Elsa.Email/Activities/SendEmail.cs
This update enables handling ExpandoObject as email attachments by extracting relevant properties like FileName, ContentType, and Content. It ensures proper parsing of the content and supports both byte arrays and streams for attachment data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6351)
> Add support for ExpandoObject attachments in email sending

- src/apps/Elsa.Server.Web/Elsa.Server.Web.csproj
- src/apps/Elsa.Server.Web/Program.cs
- src/modules/Elsa.EntityFrameworkCore.Common/Abstractions/DesignTimeDbContextFactoryBase.cs
Replaced Activator.CreateInstance with ActivatorUtilities.CreateInstance to streamline the DbContext instantiation. This improves dependency injection support and ensures better compatibility with service provider configurations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6354)
> Simplify DbContext creation with ActivatorUtilities.

- src/modules/Elsa.Workflows.Core/Models/ActivityOutputRegister.cs
- test/integration/Elsa.Workflows.IntegrationTests/Scenarios/ActivityOutputs/LoopingWorkflow.cs
- test/integration/Elsa.Workflows.IntegrationTests/Scenarios/ActivityOutputs/Tests.cs
Updated `ActivityOutputRegister` to always return the last output value. Added new integration test to validate the functionality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6358)
> Fix activity output

- src/modules/Elsa.Workflows.Api/Serialization/ArgumentJsonConverter.cs
This PR fixes a parsing issue of input and output definitions at the workflow definition level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6373)
> Fix output and input definition typing

- src/modules/Elsa.Hangfire/Jobs/ExecuteBackgroundActivityJob.cs
- src/modules/Elsa.Hangfire/Jobs/ResumeWorkflowJob.cs
- src/modules/Elsa.Hangfire/Jobs/RunWorkflowJob.cs
Introduce `[Obsolete]` ExecuteAsync overloads in job classes to support legacy calls while encouraging migration to preferred methods. `[UsedImplicitly]` annotations ensure these methods are retained for compatibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6388)
> Add obsolete ExecuteAsync overloads for job classes

- Elsa.sln
- src/apps/Elsa.Server.Web/Program.cs
- src/modules/Elsa.Tenants.AspNetCore/Features/MultitenantHttpRoutingFeature.cs
- src/modules/Elsa.Tenants.AspNetCore/Options/MultitenancyHttpOptions.cs
- src/modules/Elsa.Tenants.AspNetCore/Resolvers/HeaderTenantResolver.cs
Introduced `MultitenancyHttpOptions` to configure the tenant header name used for HTTP routing. Updated `HeaderTenantResolver` to utilize this option and modified the server setup to allow overriding the default header name. This enables more flexible multitenancy configurations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6395)
> Add customizable tenant header support for HTTP routing

- Elsa.sln
- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowStarter.cs
Added support for `Properties` and `ParentId` when creating workflow instances. This fixes an issue where the Properties were not propagated to the workflow instance being created.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6394)
> Add missing request properties when starting workflow

- .github/workflows/packages.yml
- src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs
Introduced methods to enable or disable the WorkflowInboxCleanupJob. Updated service configuration logic to conditionally register WorkflowInboxCleanupHostedService based on the toggle. This adds flexibility to control cleanup job behavior programmatically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6418)
> Add toggle for WorkflowInboxCleanupJob in WorkflowRuntimeFeature

- .github/workflows/packages.yml
- src/modules/Elsa.Dapper/Modules/Runtime/Stores/DapperActivityExecutionRecordStore.cs
- src/modules/Elsa.EntityFrameworkCore.Common/Extensions/BulkUpsertExtensions.cs
- src/modules/Elsa.EntityFrameworkCore.Common/Extensions/QueryableExtensions.cs
- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/ActivityExecutionLogStore.cs
- src/modules/Elsa.MongoDb/Modules/Runtime/ActivityExecutionLogStore.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/ILogRecordStore.cs
- src/modules/Elsa.Workflows.Runtime/Stores/MemoryActivityExecutionStore.cs
- src/modules/Elsa.Workflows.Runtime/Stores/NoopActivityExecutionStore.cs
Introduced a new AddManyAsync method across multiple activity execution stores to add collections of log records. This enhancement ensures consistency in handling bulk additions and aligns with existing store interfaces.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6416)
> Add AddManyAsync method to activity execution stores

- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs
I updated ActivityExecutionContext to set the parent context to use the ParentActivityExecutionContext setter, which populates the parent's Children set. I also updated a few places to use the Children set instead of searching through all of the workflow's activity contexts.
See https://github.com/elsa-workflows/elsa-core/issues/6421 for more details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6423)
> ActivityExecutionContext Children property not populated

- src/apps/Elsa.Server.Web/Program.cs
- src/modules/Elsa.MassTransit.AzureServiceBus/Features/AzureServiceBusFeature.cs
- src/modules/Elsa.MassTransit.RabbitMq/Features/RabbitMqServiceBusFeature.cs
- src/modules/Elsa.MassTransit/Features/MassTransitFeature.cs
This PR updates MassTransit configuration for Azure Service Bus and RabbitMQ. Previously, the IBusRegistrationContext was not included in the configuration action and prevents configuration of additional MassTransit components that require the context being passed in.
- `Program.cs`: Replaces `ConfigureServiceBus` with `ConfigureTransportBus` as the old action is now obsolete.
- `AzureServiceBusFeature.cs` and `RabbitMqServiceBusFeature.cs`: Marks `ConfigureServiceBus` as obsolete, introduces `ConfigureTransportBus`. Added XML documentation to bring awareness to the alternative action and some clarification that this action runs in addition to Elsa's standard configuration.
- `MassTransitFeature.cs`: Updates `ConfigureInMemoryTransport` method documentation and updates `AddMassTransit` …
> Add IBusRegistrationContext to Transport Configuration Actions

- src/modules/Elsa.Workflows.Runtime/Models/NewBookmarkQueueItem.cs
- src/modules/Elsa.Workflows.Runtime/Services/StimulusSender.cs
- src/modules/Elsa.Workflows.Runtime/Services/StoreBookmarkQueue.cs
Added CorrelationId for the NewBookmarkQueueItems.cs class. This makes sure that unrelated workflows are not randomly executing when working in a correlated environment.
For a better description of the issue see #6409 
I didn't see any tests associated to this so I didn't write any, not sure if there is a policy to create those
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6412)
> Add CorrelationId to NewBookmarkQueueItem

- src/modules/Elsa.Workflows.Runtime/Features/WorkflowRuntimeFeature.cs
- src/modules/Elsa.Workflows.Runtime/HostedServices/WorkflowInboxCleanupHostedService.cs
- src/modules/Elsa.Workflows.Runtime/Options/WorkflowInboxCleanupOptions.cs
Introduced an `IsEnabled` property in `WorkflowInboxCleanupOptions` to allow enabling or disabling the cleanup service. Updated related logic to respect this configuration, removing the redundant `_enableWorkflowInboxCleanupJob` field. Ensures easier management of the inbox cleanup feature via configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6429)
> Enable configurable toggle for workflow inbox cleanup job

- src/core/Elsa.Abstractions/Elsa.Abstractions.csproj
- src/core/Elsa.Core/Elsa.Core.csproj
- src/samples/aspnet/Elsa.Samples.InProcessBackgroundMediator/Elsa.Samples.InProcessBackgroundMediator.csproj
This PR upgrades the MediatR package from v12.0.1 to v12.4.1. The update was required because the
`AddMediatRClasses` method in `MediatR.Registration.ServiceRegistrar` now includes an optional
`CancellationToken` parameter. Without this upgrade, solutions using the latest MediatR version would
encounter a `MissingMethodException` due to the absence of the old method signature.
- Updated the MediatR package reference to v12.4.1.
- Ensured compatibility across the project.
The introduction of the CancellationToken parameter in the AddMediatRClasses method by MediatR means
that maintaining compatibility with the latest version is crucial. This change prevents runtime errors
and ensures that the project remains up-to-date with its dependencies.
All unit tests have been executed and passed …
> Upgrade MediatR to v12.4.1 to support updated AddMediatRClasses signature

- src/modules/Elsa.Webhooks/Extensions/ModuleExtensions.cs
- src/modules/Elsa.Webhooks/Features/WebhooksFeature.cs
Simplified the configuration of sinks, sources, and HTTP clients by using direct actions instead of service-level options. Updated Apply method to finalize configurations and added notification handlers for better extensibility. Improved code readability and maintainability by consolidating logic and removing unnecessary dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6441)
> Refactor WebhooksFeature to streamline configuration.

- Directory.Packages.props
- src/bundles/Elsa.Server.Web/Program.cs
- src/modules/Elsa.OpenTelemetry/Abstractions/ErrorSpanHandlerBase.cs
- src/modules/Elsa.OpenTelemetry/Contracts/IErrorSpanHandler.cs
- src/modules/Elsa.OpenTelemetry/Extensions/ModuleExtensions.cs
- src/modules/Elsa.OpenTelemetry/Features/OpenTelemetryFeature.cs
- src/modules/Elsa.OpenTelemetry/Handlers/DefaultErrorSpanHandler.cs
- src/modules/Elsa.OpenTelemetry/Handlers/FaultExceptionErrorSpanHandler.cs
- src/modules/Elsa.OpenTelemetry/Middleware/OpenTelemetryTracingActivityExecutionMiddleware.cs
- src/modules/Elsa.OpenTelemetry/Models/ErrorSpanContext.cs
Introduce infrastructure for handling error spans with OpenTelemetry, including `DefaultErrorSpanHandler` and `FaultExceptionErrorSpanHandler`. Define core abstractions (`ErrorSpanHandlerBase`, `IErrorSpanHandler`) and utilities for customizing OpenTelemetry integration. This enables improved error tracing and categorization in workflows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6428)
> Add OpenTelemetry error span handling infrastructure

- src/modules/Elsa.Workflows.Runtime/Services/DefaultBookmarkQueuePurger.cs
Based on default scheduling, DefaultBookmarkQueuePurger logs two low value information log entries every 10 seconds. I could filter all of the logging out with logging config, but that would also filter out this seemingly useful log entry too
`logger.LogInformation("Purged {Count} bookmark queue items.", items.Count);`
This is how our logs looked before this change
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6452)
> Stop DefaultBookmarkQueuePurger log spamming

- src/apps/Elsa.ServerAndStudio.Web/Properties/launchSettings.json
In the appSettings for the ServerAndStudio.Web project the baseUrl is configured as 8080.
This PR will align the launchSettings to be inline with that configuration so that it does not throw errors on startup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6467)
> Harmonized launchSettings to be inline with appSettings

- .github/workflows/packages.yml
- src/modules/Elsa.Quartz/Jobs/RunWorkflowJob.cs
- src/modules/Elsa.Scheduling/Requests/ScheduleNewWorkflowInstanceRequest.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Execute/EndpointBase.cs
- src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Execute/Models.cs
- src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Extensions/WorkflowExecutionContextExtensions.cs
- src/modules/Elsa.Workflows.Core/Options/RunWorkflowOptions.cs
- src/modules/Elsa.Workflows.Core/Services/WorkflowRunner.cs
- src/modules/Elsa.Workflows.Management/Services/WorkflowInstanceFactory.cs
- src/modules/Elsa.Workflows.Runtime/Messages/CreateAndRunWorkflowInstanceRequest.cs
- src/modules/Elsa.Workflows.Runtime/Messages/RunWorkflowInstanceRequest.cs
- src/modules/Elsa.Workflows.Runtime/Requests/InvokeTriggerRequest.cs
- src/modules/Elsa.Workflows.Runtime/Requests/StartWorkflowRequest.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowStarter.cs
- src/modules/Elsa.Workflows.Runtime/Services/LocalWorkflowClient.cs
- src/modules/Elsa.Workflows.Runtime/Services/TriggerInvoker.cs
Introduce the ability to pass (dynamic) variables into workflow invocations. 
Example passing dynamic variable (i.e. a variable that is not defined on the workflow) when starting a workflow:
```csharp
var variables = new Dictionary<string, object>
{
["MyDynamicVariable"] = "Hello dynamic variable!"
};
var startRequest = new StartWorkflowRequest
{
WorkflowDefinitionHandle = WorkflowDefinitionHandle.ByDefinitionId(workflowDefinitionId, VersionOptions.Published),
Variables = variables
};
await workflowStarter.StartWorkflowAsync(startRequest, cancellationToken);
```
The workflow being started can now access this variable even if the variable wasn't predefined on the workflow definition. For example, the following JS expression will return the variable value:
```javascript
return …
```
> Add support for passing initial variables

- scripts/docker/docker-compose.yml
- src/apps/Elsa.Server.Web/Program.cs
- src/modules/Elsa.Workflows.Core/Serialization/Converters/ActivityJsonConverter.cs
- src/modules/Elsa.Workflows.Management/Activities/WorkflowDefinitionActivity/WorkflowDefinitionActivityProvider.cs
Fixes that composite activities' Root property (by means of the `JsonIgnoreCompositeRootConverterFactory`) does not get serialized, just like the `WorkflowDefinitionActivity`.
Composite activities added to a workflow should not include their children when being serialized.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6478)
> Fix serialization of composite activities

- src/modules/Elsa.Workflows.Core/Activities/Flowchart/Models/FlowScope.cs
- test/integration/Elsa.Workflows.IntegrationTests/Scenarios/FlowchartNextActivity/Tests.cs
This fixes an issue where activities are executed more times than expected. See https://github.com/elsa-workflows/elsa-core/issues/6479 for more details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6480)
> Fixes issue with FlowJoin(WaitAny) where activities can be executed multiple times

- src/modules/Elsa.Workflows.Core/UIHints/InputUIHints.cs
This PR helps close https://github.com/elsa-workflows/elsa-studio/issues/455
This adds the supporting `InputUIHint.DateTimePicker` for this new component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6494)
> DateTimePicker UI Hint Missing

- src/modules/Elsa.Workflows.Core/Contexts/ActivityExecutionContext.cs
- src/modules/Elsa.Workflows.Core/Middleware/Activities/DefaultActivityInvokerMiddleware.cs
- src/modules/Elsa.Workflows.Core/Models/WorkflowExecutionState.cs
This fixes an issue where the `IsExecuting` flag would remain set to `true` when an exception occurs during execution, which in turn would lead the workflow recovery service to attempt to retry the workflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6501)
> Refactor activity execution state handling with IDisposable

- src/modules/Elsa.MassTransit/ConsumerDefinitions/DispatchWorkflowRequestConsumerDefinition.cs
Updated the retry policy for DispatchWorkflowRequestConsumer to not retry. Retrying this consumer could lead to duplicate executions of the same workflow instance, which is not desirable. Workflow retries should be handled explicitly to avoid unintended side effects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6505)
> Disable Retry Policy for DispatchWorkflowRequestConsumer to Prevent Duplicate Executions

- src/modules/Elsa.Sql.MySql/MySqlClient.cs
- src/modules/Elsa.Sql.PostgreSql/PostgreSqlClient.cs
- src/modules/Elsa.Sql.SqlServer/SqlServerClient.cs
- src/modules/Elsa.Sql.Sqlite/SqliteClient.cs
- src/modules/Elsa.Sql/Client/BaseSqlClient.cs
- src/modules/Elsa.Sql/Client/ISqlClient.cs
- src/modules/Elsa.Sql/Contracts/ISqlEvaluator.cs
- src/modules/Elsa.Sql/Elsa.Sql.csproj
- src/modules/Elsa.Sql/Models/EvaluatedQuery.cs
- src/modules/Elsa.Sql/Services/SqlEvaluator.cs
As raised by #6500, variables could originate from outside the Studio (from an external source) and therefore could expose the SQL queries to SQL Injection. To address this, the following has been implemented & changed:
- Variables are now inserted via `{{ }}` rather than `@`. I.e. `{{Variables.SomeVariable}}` or `{{Input.SomeInput}}`. This simplifies the SqlEvaluator logic and removes the issue with `@` being used within the query itself.
- Inserted variables/inputs/etc are automatically parameterised to prevent SQL Injection. No front end user code required.
- The parameter string format used in parameterising can be overridden in the base classes should another client need access to this, i.e. potentially oracle. Default configuration is `@p0`.
- Simplified client implementations to …
> FEAT - Automatic SQL Expression Parameterization

- src/modules/Elsa.MassTransit/ConsumerDefinitions/DispatchWorkflowRequestConsumerDefinition.cs
This ensures a workflow is not executed multiple times in case of an unhandled exception.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6506)
> Remove message retry configuration in DispatchWorkflowRequestConsumer

- src/modules/Elsa.Expressions/Helpers/ObjectConverter.cs
- test/unit/Elsa.Workflows.Core.UnitTests/ObjectConversion/Tests.cs
Added functionality to convert enumerables to arrays when the target type is an array. The implementation ensures each item is properly cast to the target array's element type and then added to the resulting array.
Fixes #6330
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6508)
> Handle conversion of enumerables to arrays in ObjectConverter

- src/modules/Elsa.JavaScript/ObjectConverters/EnumToStringConverter.cs
- src/modules/Elsa.JavaScript/ObjectConverters/JsonElementConverter.cs
- src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
Introduce `EnumToStringConverter` and `JsonElementConverter` to support conversion of enums and JSON elements in the JavaScript evaluation process. Update `JintJavaScriptEvaluator` to include these converters in the object conversion pipeline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6515)
> Add object converters for Enum and JsonElement handling

- src/modules/Elsa.Workflows.Runtime.Distributed/Services/DistributedWorkflowClient.cs
- src/modules/Elsa.Workflows.Runtime/Services/LocalWorkflowClient.cs
Updated `CreateAndRunInstanceAsync` to separate instance creation and execution with locking to handle nested workflow scenarios. Made `RunInstanceAsync` public to facilitate reuse in the distributed workflow client.
Fixes #6577
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6586)
> Fix Dispatch Workflow Resumption

- src/modules/Elsa.JavaScript/Handlers/ConfigureEngineWithVariablesAndInputOutputAccessors.cs
- src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
Previously, input variable names were case-sensitive when added to the dictionary, which could lead to potential issues with naming mismatches. This change ensures that input names are now treated as case-insensitive by using `StringComparer.OrdinalIgnoreCase`, improving consistency and usability.
Fixes #6598
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6590)
> Make input variable names case-insensitive in dictionary

- src/modules/Elsa.OpenTelemetry/Features/OpenTelemetryFeature.cs
- src/modules/Elsa.OpenTelemetry/Middleware/OpenTelemetryTracingWorkflowExecutionMiddleware.cs
- src/modules/Elsa.OpenTelemetry/Options/OpenTelemetryOptions.cs
Adds an option to use a dummy activity as a hack to prevent other middleware of reinstating the parent activity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6606)
> Start a new workflow trace when triggered from UI

- .github/workflows/packages.yml
- src/modules/Elsa.Http/Activities/HttpEndpoint.cs
- src/modules/Elsa.Http/Activities/HttpEndpointBase.cs
- src/modules/Elsa.Http/Extensions/HttpEndpointActivityExecutionContextExtensions.cs
- await HTTP resume callbacks to avoid losing async continuations
- make `WaitForHttpRequest` async and update callers
- `dotnet test --no-build` *(fails: `dotnet` not found)*
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6660)
> Fix async callback awaiting in HTTP endpoint

- src/common/Elsa.Mediator/HostedServices/BackgroundCommandSenderHostedService.cs
- src/common/Elsa.Mediator/HostedServices/BackgroundEventPublisherHostedService.cs
- fix typo "occured" -> "occurred" in hosted services
- `git status --short`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6654)
> Fix spelling in hosted service LogError messages

- test/unit/Elsa.Workflows.Core.UnitTests/ExpressionExecutionContextExtensionsTests.cs
- fix test to use `context.SetVariable` when checking variable creation
- `bash build.sh --target test` *(fails: `dotnet` not found)*
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6656)
> Fix SetVariable test

- src/modules/Elsa.Workflows.Runtime.Distributed/Services/DistributedWorkflowClient.cs
- src/modules/Elsa.Workflows.Runtime.ProtoActor/Actors/WorkflowInstance.cs
- src/modules/Elsa.Workflows.Runtime.ProtoActor/Extensions/ProtoOutputExtensions.cs
- src/modules/Elsa.Workflows.Runtime.ProtoActor/Mappers/CreateAndRunWorkflowInstanceRequestMapper.cs
- src/modules/Elsa.Workflows.Runtime.ProtoActor/Mappers/RunWorkflowInstanceRequestMapper.cs
- src/modules/Elsa.Workflows.Runtime.ProtoActor/Mappers/RunWorkflowInstanceResponseMapper.cs
- src/modules/Elsa.Workflows.Runtime.ProtoActor/Proto/Shared.proto
- src/modules/Elsa.Workflows.Runtime.ProtoActor/Proto/WorkflowInstance.Messages.proto
- src/modules/Elsa.Workflows.Runtime/Messages/CreateAndRunWorkflowInstanceRequest.cs
- src/modules/Elsa.Workflows.Runtime/Messages/RunWorkflowInstanceRequest.cs
- src/modules/Elsa.Workflows.Runtime/Messages/RunWorkflowInstanceResponse.cs
- src/modules/Elsa.Workflows.Runtime/Services/LocalWorkflowClient.cs
- add `IncludeWorkflowOutput` option to workflow run request messages
- return workflow output when flag is enabled
- propagate setting through local, distributed and ProtoActor clients
- extend ProtoActor protocol and mappers
- `dotnet test` *(fails: `dotnet` command not found)*
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6659)
> Add optional workflow output flag

- src/modules/Elsa.Workflows.Core/Services/ActivityRegistry.cs
@sfmskywalker 
This bug fix addresses the inconsistency in loading workflows marked as "Usable As Activity" in the Activity Panel.
Previously, when a user loaded a main workflow that included a sub-workflow with multiple versions (e.g., the third version), the system was sometimes unable to locate it in the activity descriptors. This issue was caused by a Distinct filter that excluded the intended version.
The fix resolves both the loading inconsistency and the version-mismatch problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6648)
> fix: code fixed to allow loading all the descriptors in the UI

- src/apps/Elsa.Server.Web/appsettings.json
- src/modules/Elsa.Alterations/Services/DefaultAlterationRunner.cs
Commits the workflow state during alteration execution to persist changes made during the alteration process.
This ensures that the workflow state is consistently saved, even during alterations, preventing data loss and enabling reliable workflow execution.
A potential optimization to avoid redundant database saves is identified and noted as a TODO.
Fixes #6735
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6736)
> Commits workflow state during alteration

- src/modules/Elsa.Workflows.Management/Mappers/WorkflowStateMapper.cs
- Introduced constant `WorkflowInstanceNameKey` to handle legacy workflow instance name properties.
- Updated `MapWorkflowStateToWorkflowInstance` method to set `Name` property for older instances.
Fixes #6748
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6767)
> Add backward compatibility for `WorkflowInstance.Name` mapping in `WorkflowStateMapper`

- src/modules/Elsa.IO.Compression/Activities/CreateZipArchive.cs
- src/modules/Elsa.IO/Extensions/ContentTypeExtensions.cs
This pull request introduces enhancements to the `CreateZipArchive` activity for handling duplicate entry names, updates the logic for validating Base64 strings, and refines code behavior to improve reliability and maintainability.
* Refined the `IsBase64String` method to validate padding positions and count, ensuring padding is correctly placed at the end and all trailing characters after the first '=' are also '='.
* Added checks to prevent false positives for short strings that consist only of lowercase letters and digits, improving the robustness of Base64 validation.
* Changed the `ZipArchiveMode` from `Create` to `Update` in `CreateZipStreamFromEntries`, allowing read operations inside the entries besides just creating them.
* Added logic to generate unique entry names in …
> Implementing better base64 evaluation + appropriate zip entry naming

- src/modules/Elsa.Http/ContentWriters/JsonContentFactory.cs
Modified the instantiation of `RawStringContent` to use a new `UTF8Encoding` instance with `encoderShouldEmitUTF8Identifier` set to `false`, affecting the handling of the UTF-8 byte order mark (BOM) in serialized JSON content. Fixes a bug with content length being different than expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6786)
> Update RawStringContent encoding in JsonContentFactory

- src/modules/Elsa.EntityFrameworkCore/Modules/Runtime/ActivityExecutionLogStore.cs
- src/modules/Elsa.Workflows.Core/Middleware/Activities/DefaultActivityInvokerMiddleware.cs
- src/modules/Elsa.Workflows.Runtime/Contracts/IActivityExecutonMapper.cs
- src/modules/Elsa.Workflows.Runtime/Entities/ActivityExecutionRecord.cs
- src/modules/Elsa.Workflows.Runtime/Extensions/ActivityExecutionContextEventExtensions.cs
- src/modules/Elsa.Workflows.Runtime/Extensions/ActivityExecutionContextRecordExtensions.cs
- src/modules/Elsa.Workflows.Runtime/Extensions/PipelineWorkflowsFeatureExtensions.cs
- src/modules/Elsa.Workflows.Runtime/LogPersistence/Extensions/ActivityExecutionPipelineBuilderExtensions.cs
- src/modules/Elsa.Workflows.Runtime/Middleware/Activities/CaptureActivityExecutionRecordMiddleware.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultActivityExecutionMapper.cs
- src/modules/Elsa.Workflows.Runtime/Services/StoreActivityExecutionLogSink.cs
- Added middleware for capturing activity execution records during workflow execution.
- Introduced async mapping in `DefaultActivityExecutionMapper` with additional serialization support.
- Enhanced `ActivityExecutionRecord` with new serialized properties for efficient storage.
- Updated extensions to include `UseActivityExecutionLogCapturing`.
- Simplified logging persistence by leveraging pre-serialized values in `ActivityExecutionLogStore`.
Fixes #6799
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6800)
> Introduce activity execution record capturing and serialization improvements

- src/modules/Elsa.IO.Compression/Services/Strategies/ZipEntryContentStrategy.cs
This pull request includes a minor update to the `ResolveAsync` method in the `ZipEntryContentStrategy` class. The change ensures that the `EntryName` property is only appended with the `innerContentExtension` if it does not already have an extension.
* [`src/modules/Elsa.IO.Compression/Services/Strategies/ZipEntryContentStrategy.cs`](diffhunk://#diff-ee222784b0956d06954564b8a2d4ebccb8e4ab3d1aae7be5ab9f71de6a0ed7eaL39-R39): Updated the logic in `ResolveAsync` to check if `zipEntry.EntryName` has an extension before appending `innerContentExtension`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6806)
> Fixed wrong naming in resulting entries when file is inputted from http

- src/modules/Elsa.Workflows.Core/Extensions/ActivityExecutionContextExtensions.cs
This pull request refactors the way extension metadata is handled in `ActivityExecutionContextExtensions.cs`, focusing on improving null handling and dictionary initialization. The changes streamline the logic for retrieving and setting extension metadata.
Improvements to extension metadata handling:
* Simplified dictionary initialization in `SetExtensionsMetadata` by using the null-coalescing operator to ensure a dictionary is always available.
* Improved null safety in `GetExtensionsMetadata` by using `TryGetValue` instead of direct casting, which makes the code more robust and less error-prone.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6891)
> Fixing unit tests

- src/modules/Elsa.WorkflowProviders.BlobStorage/Extensions/ModuleExtensions.cs
- src/modules/Elsa.Workflows.Core/Builders/WorkflowBuilder.cs
- src/modules/Elsa.Workflows.Core/Contracts/IWorkflowBuilder.cs
- src/modules/Elsa.Workflows.Runtime/Activities/Event.cs
- src/modules/Elsa.Workflows.Runtime/Extensions/DependencyInjectionExtensions.cs
- src/modules/Elsa.Workflows.Runtime/Models/MaterializedWorkflow.cs
- src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowDefinitionStorePopulator.cs
- src/modules/Elsa.Workflows.Runtime/Services/EventPublisher.cs
- test/integration/Elsa.Workflows.IntegrationTests/Scenarios/WorkflowDefinitionStorePopulation/InMemoryWorkflowMaterializer.cs
- test/integration/Elsa.Workflows.IntegrationTests/Scenarios/WorkflowDefinitionStorePopulation/InMemoryWorkflowProvider.cs
- test/integration/Elsa.Workflows.IntegrationTests/Scenarios/WorkflowDefinitionStorePopulation/Tests.cs
Addresses an issue where workflow identity conflicts arise during reloads, ensuring triggers consistently target the correct workflow definition version.
- Introduces an in-memory workflows provider and materializer for integration tests.
- Changes default parameter value from `default` to `null` in `UseFluentStorageProvider` method signature.
- Refactors `IndexTriggersAsync` to use `WorkflowDefinition` and update null assignment for serialization logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elsa-workflows/elsa-core/6909)
> Addresses workflow identity reload conflict
